### ISSUE TITLE
An error is reported when vlcj is deployed to centos7.2, and the video of *. MP, *. Avi types cannot be loaded

### ISSUE THREAD

**Issue by liuchuang1234** [caprica/vlcj#1001]
[root@centos opt]# java -jar vlcj-player-vlcj-3.x_fat.jar 
2020-09-15 12:50:16 INFO                            Info:78   - vlcj: 3.12.0
2020-09-15 12:50:16 INFO                            Info:79   - java: 1.8.0_221 Oracle Corporation
2020-09-15 12:50:16 INFO                            Info:80   - java home: /usr/java/jdk1.8.0_221/jre
2020-09-15 12:50:16 INFO                            Info:81   - os: Linux 3.10.0-123.el7.x86_64 amd64
2020-09-15 12:50:16 INFO                            Info:83   - LD_LIBRARY_PATH: null
2020-09-15 12:50:16 INFO                 NativeDiscovery:121  - Discovery found libvlc at '/usr/lib64'
JarClassLoader: Warning: Unable to load native library: java.lang.NullPointerException
2020-09-15 12:50:17 INFO                   LibVlcFactory:171  - vlc: 3.0.11.1 Vetinari, changeset 3.0.11.1-0-g52483f3ca2
2020-09-15 12:50:17 INFO                   LibVlcFactory:172  - libvlc: /usr/lib64/libvlc.so.5.6.0
[00007fd6444eb7a0] vlcpulse audio output error: PulseAudio server connection failure: 拒绝连接
^C

**Comment by caprica** [comment]
I don't understand what JarClassLoader is doing here.

**Comment by liuchuang1234** [comment]
> 我不明白JarClassLoader在这里做什么。

Have you ever deployed vlcj on centos7 before?

**Comment by caprica** [comment]
I don't use CentOS, but I don't see why it would be any different from any other Linux distribution.

You have a NullPointerException from JarClassLoader, start there.

Are you trying to bundle all the native libraries for LibVLC in your fat jar?

**Comment by liuchuang1234** [comment]
yes




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Mark Lee"<notifications@github.com&gt;; 
发送时间: 2020年9月15日(星期二) 下午2:52
收件人: "caprica/vlcj"<vlcj@noreply.github.com&gt;; 
抄送: "刘闯"<389142946@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [caprica/vlcj] An error is reported when vlcj is deployed to centos7.2, and the video of *. MP, *. Avi types cannot be loaded (#1001)





 
I don't use CentOS, but I don't see why it would be any different from any other Linux distribution.
 
You have a NullPointerException from JarClassLoader, start there.
 
Are you trying to bundle all the native libraries for LibVLC in your fat jar?

**Comment by caprica** [comment]
You can't load native DLLs from jar files. You must unpack them to the local filesystem first.

**Comment by liuchuang1234** [comment]
I still don't understand. Can DLL files run on Linux?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Mark Lee"<notifications@github.com&gt;; 
发送时间: 2020年9月15日(星期二) 下午3:18
收件人: "caprica/vlcj"<vlcj@noreply.github.com&gt;; 
抄送: "刘闯"<389142946@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [caprica/vlcj] An error is reported when vlcj is deployed to centos7.2, and the video of *. MP, *. Avi types cannot be loaded (#1001)





 
You can't load native DLLs from jar files. You must unpack them to the local filesystem first.

**Comment by caprica** [comment]
No.

On Linux they are "shared objects" not dlls, so files ending with ".so".

They are not portable though, so just because you build them one one Linux distribution does not mean they can just be copied onto some other distribution. The paths for shared objects on Linux are "baked in". You can google for "rpath" for some background.

There are solutions, but it's not easy.

Any in any case, you can not load a shared object (or DLL) from inside a jar file.

**Comment by caprica** [comment]
Similar to #623

**Comment by liuchuang1234** [comment]
Thank you very much. Although it can't be used on centos7, it can be deployed on Ubuntu 20.04.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Mark Lee"<notifications@github.com&gt;; 
发送时间: 2020年9月15日(星期二) 下午4:49
收件人: "caprica/vlcj"<vlcj@noreply.github.com&gt;; 
抄送: "刘闯"<389142946@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [caprica/vlcj] An error is reported when vlcj is deployed to centos7.2, and the video of *. MP, *. Avi types cannot be loaded (#1001)





 
Similar to #623

**Comment by caprica** [comment]
The main issue here is that copying shared object files built on one distribution to some other different distribution is just the wrong way to go about it.

The answer is, among many suggestions I suppose:

1. rely on OS package manager to install dependencies (like VLC) for you (easy)
2. build a Snap package (or something similar, AppImage, Flatpak) that bundles a JVM, VLC and your app in a portable way (hard)
3. etc...

But naively copying shared objects around is just not going to work generally.
