### ISSUE TITLE
Example of reading media file metadata

### ISSUE THREAD

**Issue by Tvaroh** [caprica/vlcj#1005]
Hey, is there an API to read flac/mp3/etc file tags from a local file?

**Comment by Tvaroh** [comment]
Nm, found https://github.com/caprica/vlcj-examples/blob/master/src/main/java/uk/co/caprica/vlcj/test/meta/SearchMetaTest.java

Great library!

**Comment by caprica** [comment]
Honestly, I prefer using other libraries to deal with metadata.

There's vlcj-info which is a small wrapper around the MediaInfo native library, which gives a lot more metadata.

But if all you need are the simple tags for mp3 etc, then the example you found is fine.

**Comment by Tvaroh** [comment]
@caprica thank you, probably I need more, like compilation tags, etc. But it's good as starting point. Thanks for suggestion!
