### ISSUE TITLE
Getting an exception every time release() is called

### ISSUE THREAD

**Issue by drstevendejong** [caprica/vlcj#1009]
I've tried everything, but calling

`embeddedMediaPlayer.media().prepare(myVideo);`

twice ALWAYS gives me an exception (in the native code) because of `release()` being called.

**Comment by caprica** [comment]
Posting the exception would be helpful.

**Comment by caprica** [comment]
Or are you saying there's no Java exception, only a native fatal crash?

**Comment by caprica** [comment]
Unable to reproduce this, post a self-contained example, whatever stack-traces or hotspot crash logs you have and which versions you are using if you want any more help.

**Comment by caprica** [comment]
If you can post the requested information please do so, otherwise I'll close this in the next day or so.
