### ISSUE TITLE
Accessing Media-Information

### ISSUE THREAD

**Issue by ThePatiento** [caprica/vlcj#1021]
Hi,
Are questions about theusage of VLCJ allowed here or is there maybe a better forum/community? (I already asked the question [here ](https://forum.videolan.org/viewtopic.php?f=32&t=155347)- no reply yet)

My question:
I am using libVLC (with VLCJ wrapper) to read out media information (like length, resolution, codec and so on). My problem is: What is the best way to access these information? I didn't really found a way in VLCJ do get these information directly. My current approach is, to start playing the video and grab these media information (like mediaPlayer.media().info().videoTracks());). It looks like these media finfos get loaded sometie during the playback. My problem is: How do I know when these informations are available?
```
mediaPlayer.events().addMediaPlayerEventListener(new MediaPlayerEventAdapter() {
                @Override
                public void mediaPlayerReady(MediaPlayer mediaPlayer) {
                    if (isMediaInfoReady())
                    {
                        System.out.println("mediaPlayerReady");
                        MediaUtil.showMediaInfo(mediaPlayer);
                        readMediaInfo();
                    }
                }

                @Override
                public void playing(MediaPlayer mediaPlayer) {
                    if (isMediaInfoReady())
                    {
                        System.out.println("playing");
                        MediaUtil.showMediaInfo(mediaPlayer);
                        readMediaInfo();
                    }
                }

                @Override
                public void positionChanged(MediaPlayer mediaPlayer, float newPosition) {
                    if (isMediaInfoReady())
                    {
                        System.out.println("positionChanged");
                        MediaUtil.showMediaInfo(mediaPlayer);
                        readMediaInfo();
                    }
                }
                 @Override
                public void videoOutput(MediaPlayer mediaPlayer, int newCount) {
                    if (isMediaInfoReady())
                    {
                        System.out.println("videoOutput");
                        MediaUtil.showMediaInfo(mediaPlayer);
                        readMediaInfo();
                    }
                }

                private boolean isMediaInfoReady() {
                    if (mediaPlayer.media().info().videoTracks().size()==1) {
                        if (mediaPlayer.media().info().videoTracks().get(0).width()>0) {
                            return true;
                        }
                    }
                    return false;
                }

            });
            mediaPlayer.media().start(mediaTitle.getMedium().getPath());
```
At the moment I am asking like brute force on several media player events if the resolution information is loaded. This feels really clumsy, error-prone and cumbersome. Anyone knows a better approach?
Top

**Comment by caprica** [comment]
Of course this is the right place to ask such questions...

**Comment by caprica** [comment]
There are a number of things to consider here:

1. Simplest case: parse the media first, wait for the parse completed event, then query the information.
2. Unfortunately some information is not available, even if the media has been parsed, until playback has actually started - for this you can use the various "elementary stream" events - IIRC you can either us the "added" or "updated" event and see if your track info is ready. But this means you have to actually play the media.
3. What I recommend, and what I do myself, is to use the separate "vcj-info" project - this is a Java wrapper with a decent API around the native "Mediainfo" tool. This is the most useful approach since that mediainfo tool can return EVERYTHING without playing the media. The downside is that you need yet another piece of native software installed. The format of the data returned by mediainfo is also a bit unstructured, but it is certainly usable.

**Comment by ThePatiento** [comment]
thanks for the info!
unfortunatly Mediainfo does not provide all the structure/chapter/menu information which VLC is doing fine. So i will stick with VLC and take a look on the "elementary stream" events (ypu have maybe an exampl or can oyu point me to some documation?)

**Comment by caprica** [comment]
For chapter information, did you try parsing first?

For documentation, well, you have the Javadoc, and you have a lot of examples in the GitHub projects. There isn't anything else.
