### ISSUE TITLE
Videos in vertical format are not played correctly

### ISSUE THREAD

**Issue by lsiem** [caprica/vlcj#1022]
I have a 90 degree rotated screen and would like to play videos in portrait format. However, the videos are only played a little more than halfway. Means almost 1/2 of the screen is black. I have already set the aspect ratio of the player to "9:16". This did not change anything. 
Pictures are not affected.
I'm sorry if this is not a bug but a mistake on my part.

Here is my current code: https://controlc.com/51cee847

**Comment by caprica** [comment]
Usually VLC will detect the correct orientation and set it automatically. So you must be be doing something out of the ordinary here.

Probably the only thing you can do is pass "--rotate-angle=90" via the media player factory or maybe as media options when you invoke play().

"--transform-type=90" should also work. or 270 or whatever.
