### ISSUE TITLE
Use vlcj play video in minecraft window error

### ISSUE THREAD

**Issue by GceCold** [caprica/vlcj#1031]
I have made a forge mod to play video in game window. If use the [vlcj-lwjgl-demo](https://github.com/caprica/vlcj-lwjgl-demo) directly,it can play.But the game window will display the last frame and can't redisplay the game when the video is finished.I try to correct it,but i failed.

```
[0000027500571ac0] main video output error: video output display creation failed
[h264 @ 000002750043c880] get_buffer() failed
[h264 @ 000002750043c880] thread_get_buffer() failed
[h264 @ 000002750043c880] decode_slice_header error
[h264 @ 000002750043c880] no frame!
[000002750032eb10] gl gl error: glBindTexture symbol not found, bailing out
[000002750032e180] gl gl error: glBindTexture symbol not found, bailing out
```

My mod repository:https://github.com/GceCold/IceVideo/blob/master/src/main/java/ltd/icecold/icevideo/Video.java

Use the demo: ![use the demo](https://user-images.githubusercontent.com/16684508/102636836-1ba7a600-4190-11eb-80fa-828828024d9f.gif)

**Comment by caprica** [comment]
These are native error messages coming from VLC, not Java/vlcj errors:
```
[000002750032eb10] gl gl error: glBindTexture symbol not found, bailing out
```
So maybe some incompatibility between VLC and Minecraft's use of OpenGL, I don't know.

But I do know there's nothing can be changed in vlcj to resolve this.

**Comment by GceCold** [comment]
I try to correct the code in the rendering part
