### ISSUE TITLE
LibVLC to playing RTSP stops

### ISSUE THREAD

**Issue by tomasfil** [caprica/vlcj#1034]
Hello,

I am using C# lib to stream RTSP to HTTP.

But after few days of running it stops on "mmdevice audio output error: session disconnected: session disconnected"

Is there any way to catch this error, to be able to restart the stream? Or how to prevent it?

Thanks.

![image](https://user-images.githubusercontent.com/34779382/105171429-8137db00-5b1e-11eb-9809-5b0e8cb43e90.png)

**Comment by caprica** [comment]
Are you sure you're in the right place? What has C# got to do with this project?
