### ISSUE TITLE
NativeDiscovery ServiceLoader Issue

### ISSUE THREAD

**Issue by PulseBeat02** [caprica/vlcj#1066]
Hello, I seemed to encounter some sort of roadblock for NativeDiscovery. There is quite some odd behavior where it works in a testing environment (in my IDE it discovers the proper path), however, in a server environment (where the server is running on my PC and no VLC app files have been altered in any way), it seems to not be able to find the proper search paths. One of the classes deeply involved in this is the `DirectoryProviderDiscoveryStrategy` class.

Within that class is the `directoryProviders` variable. This is returning an empty list when in a server environment compared to my testing environment.

After taking further research about what `ServiceLoader` really does, I found out that `ServiceLoader.load(DiscoveryDirectoryProvider.class)` will only use the classloader in the current thread. In a server environment, there are ideally going to be multiple threads running at the same time, which leads me to think that this may be the cause of why it's returning an empty list.

Do you perhaps know any workarounds or solutions to this? In my honest opinion, I am not extremely a big fan of `ServiceLoader` due to its limitations sometimes.

**Comment by PulseBeat02** [comment]
Please also note this isn't an Operating System specific issue. I have tried running the server on Windows too and it seems to have led to the same results.

**Comment by caprica** [comment]
I can't dig too deeply into the specifics of this, but if what you say is correct then why not just invoke discovery once from your application main thread (i.e. create the media player factory in your main thread)?

IMO ServiceLoader works great for discovery for the most common use-cases.

In any case, nothing prevents you writing your own NativeDiscovery implementation that works however you want it to.

**Comment by PulseBeat02** [comment]
It seems like the only best option here is to make my own NativeDiscovery implementation because there are some classloaders that I can't interact with in my server (that are out within my reach). In terms of creating my own, would I first add the search path as so:
```java
          NativeLibrary.addSearchPath(
              RuntimeUtil.getLibVlcLibraryName(), "/Applications/VLC.app/Contents/MacOS/lib");
```
and also set the VLC_PLUGIN_PATH variable by doing the following:
```java
    final String env = System.getenv("VLC_PLUGIN_PATH");
    if (env == null || env.length() == 0) {
        LibC.INSTANCE.setenv(VLC_PLUGIN_PATH, "/Applications/VLC.app/Contents/MacOS/lib", 1);
    }
 ```
And finally load the library:
```java
    try {
      final libvlc_instance_t instance = libvlc_new(0, new StringArray(new String[0]));
      if (instance != null) {
        libvlc_release(instance);
        final LibVlcVersion version = new LibVlcVersion();
        if (version.isSupported()) {
          Logger.info("supported");
        }
      }
    } catch (final UnsatisfiedLinkError e) {
      Logger.info(e.getMessage());
    }
    Logger.info("not supported");
  ```
  
  Would this be correct? (In the scope of MacOS only of course).

**Comment by caprica** [comment]
Look at the source code of the existing implementations is the best advice I can give.

**Comment by PulseBeat02** [comment]
After implementing my own discovery method, it worked! Thank you for the advice.

**Comment by PulseBeat02** [comment]
Commenting on this for future reference if anyone encounters this issue. After around a year or so I found the reason why ServiceLoader wasn't working. In my case (since I was working with a Minecraft plugin), the ClassLoader uses some quirky hacks that cause ServiceLoader to break (and subsequently, not only just libraries but also many other Java internal modules to break). This includes the algorithm used which detects discovery implementations here.
