### ISSUE TITLE
Inconsistent equalizer behaviour

### ISSUE THREAD

**Issue by caprica** [caprica/vlcj#1069]
Updating an equalizer then applying it seems to be fine - i.e. the change can be heard in playback soon after.

But setting a new equalizer instance on the media player seems to have no discernible effect.

Relates to #1068.

This may be a native limitation when swapping native equalizer instances, although I did think this used to work either way.

In any event, the mitigation is to keep the same equalizer instance and just set new values.

Alternatively there's just a bug, but more investigation is required to determine if so or not.

**Comment by mfkl** [comment]
Should this be reported to libvlc? (haven't tested it on my side)

**Comment by caprica** [comment]
Honestly, I'm not sure if there's an issue in the native code or not. When I wrote that implementation for libvlc, I forget how many years ago now, I was pretty thorough testing it so I would be surprised if I missed this particular issue at the time.

I can provide a workable solution by making some changes to vlcj, that's the subject of this particular issue.

**Comment by caprica** [comment]
In fact, the recommended approach is to set a single equalizer instance for the lifetime of the media player and just change the values of that instance - so there is nothing to do for this ticket.

However, #1068 is still worth consideration.
