### ISSUE TITLE
Video switch black screen

### ISSUE THREAD

**Issue by zeegates** [caprica/vlcj#1071]
I use EmbeddedMediaListPlayerComponent to develop an ad player. There is a short black screen phenomenon when I switch ads. how can I solve this problem?

My code is as follows：
```
public class MtListPlayer extends JFrame {

	private final EmbeddedMediaListPlayerComponent mediaPlayer;
	/**
	 * 
	 */
	private static final long serialVersionUID = -1827997502219875330L;
	
	private static String val(String val) {
        return val != null ? val : "<not set>";
    }
	
	private MediaListRef mediaListRef;
	
	static {
		
		System.setProperty("java.awt.headless", "false");
	}
	
	public MtListPlayer() {
		this(PlaybackMode.DEFAULT);
	}
	
	public MtListPlayer(PlaybackMode playMode) {

//		Marquee 支持弹幕
		Info info = Info.getInstance();

        System.out.printf("vlcj             : %s%n", info.vlcjVersion() != null ? info.vlcjVersion() : "<version not available>");
        System.out.printf("os               : %s%n", val(info.os()));
        System.out.printf("java             : %s%n", val(info.javaVersion()));
        System.out.printf("java.home        : %s%n", val(info.javaHome()));
        System.out.printf("jna.library.path : %s%n", val(info.jnaLibraryPath()));
        System.out.printf("java.library.path: %s%n", val(info.javaLibraryPath()));
        System.out.printf("PATH             : %s%n", val(info.path()));
        System.out.printf("VLC_PLUGIN_PATH  : %s%n", val(info.pluginPath()));
        if (RuntimeUtil.isNix()) {
            System.out.printf("LD_LIBRARY_PATH  : %s%n", val(info.ldLibraryPath()));
        } else if (RuntimeUtil.isMac()) {
            System.out.printf("DYLD_LIBRARY_PATH          : %s%n", val(info.dyldLibraryPath()));
            System.out.printf("DYLD_FALLBACK_LIBRARY_PATH : %s%n", val(info.dyldFallbackLibraryPath()));
        }
        mediaPlayer = new EmbeddedMediaListPlayerComponent();
        mediaPlayer.setBackground(new Color(255, 255, 255));
//		this.setSize(800, 600);
		this.setTitle("广告播放器");
		this.setDefaultCloseOperation(EXIT_ON_CLOSE);
		this.setVisible(true);
		this.setContentPane(mediaPlayer);
		mediaPlayer.mediaPlayer().controls().setRepeat(true);
		
		mediaPlayer.mediaPlayer().fullScreen().strategy(new AdaptiveFullScreenStrategy(this));
		mediaPlayer.mediaPlayer().fullScreen().toggle();
		mediaListRef = mediaPlayer.mediaPlayerFactory().media().newMediaListRef();
		mediaPlayer.mediaPlayer().subitems().list().setMediaList(mediaListRef);
		mediaPlayer.mediaPlayer().subitems().controls().setMode(playMode);
	}
	
	public void addMedia(String mrl) {
		log.debug("add media {} to list", mrl);
		log.debug("media add to media list status of {}", mediaPlayer.mediaPlayer().subitems().list().media().add(mrl));
	}
	
	public void initMediaList(String... mrls) {
		for(String mrl : mrls) {
			addMedia(mrl);
		}
	}
	
	public void play(int index) {
		log.debug("play media {}", mediaPlayer.mediaPlayer().subitems().list().media().mrl(index));
		if(mediaPlayer.mediaPlayer().subitems().list().media().count() > index && index >= 0) {
			mediaPlayer.mediaPlayer().subitems().controls().play(index);
		}
	}
	
	public static void main(String[] args) {
		MtListPlayer mtListPlayer = new MtListPlayer(PlaybackMode.LOOP);
		
		mtListPlayer.initMediaList("data/01.mp4", "data/demo.mp4");
		mtListPlayer.play(0);
		
	}
}
```

**Comment by zeegates** [comment]
`public class MtListPlayer extends JFrame {

	private final EmbeddedMediaListPlayerComponent mediaPlayer;
	/**
	 * 
	 */
	private static final long serialVersionUID = -1827997502219875330L;
	
	private static String val(String val) {
        return val != null ? val : "<not set>";
    }
	
	private MediaListRef mediaListRef;
	
	static {
		
		System.setProperty("java.awt.headless", "false");
	}
	
	public MtListPlayer() {
		this(PlaybackMode.DEFAULT);
	}
	
	public MtListPlayer(PlaybackMode playMode) {

//		Marquee 支持弹幕
		Info info = Info.getInstance();

        System.out.printf("vlcj             : %s%n", info.vlcjVersion() != null ? info.vlcjVersion() : "<version not available>");
        System.out.printf("os               : %s%n", val(info.os()));
        System.out.printf("java             : %s%n", val(info.javaVersion()));
        System.out.printf("java.home        : %s%n", val(info.javaHome()));
        System.out.printf("jna.library.path : %s%n", val(info.jnaLibraryPath()));
        System.out.printf("java.library.path: %s%n", val(info.javaLibraryPath()));
        System.out.printf("PATH             : %s%n", val(info.path()));
        System.out.printf("VLC_PLUGIN_PATH  : %s%n", val(info.pluginPath()));
        if (RuntimeUtil.isNix()) {
            System.out.printf("LD_LIBRARY_PATH  : %s%n", val(info.ldLibraryPath()));
        } else if (RuntimeUtil.isMac()) {
            System.out.printf("DYLD_LIBRARY_PATH          : %s%n", val(info.dyldLibraryPath()));
            System.out.printf("DYLD_FALLBACK_LIBRARY_PATH : %s%n", val(info.dyldFallbackLibraryPath()));
        }
        mediaPlayer = new EmbeddedMediaListPlayerComponent();
        mediaPlayer.setBackground(new Color(255, 255, 255));
//		this.setSize(800, 600);
		this.setTitle("广告播放器");
		this.setDefaultCloseOperation(EXIT_ON_CLOSE);
		this.setVisible(true);
		this.setContentPane(mediaPlayer);
		mediaPlayer.mediaPlayer().controls().setRepeat(true);
		
		mediaPlayer.mediaPlayer().fullScreen().strategy(new AdaptiveFullScreenStrategy(this));
		mediaPlayer.mediaPlayer().fullScreen().toggle();
		mediaListRef = mediaPlayer.mediaPlayerFactory().media().newMediaListRef();
		mediaPlayer.mediaPlayer().subitems().list().setMediaList(mediaListRef);
		mediaPlayer.mediaPlayer().subitems().controls().setMode(playMode);
	}
	
	public void addMedia(String mrl) {
		log.debug("add media {} to list", mrl);
		log.debug("media add to media list status of {}", mediaPlayer.mediaPlayer().subitems().list().media().add(mrl));
	}
	
	public void initMediaList(String... mrls) {
		for(String mrl : mrls) {
			addMedia(mrl);
		}
	}
	
	public void play(int index) {
		log.debug("play media {}", mediaPlayer.mediaPlayer().subitems().list().media().mrl(index));
		if(mediaPlayer.mediaPlayer().subitems().list().media().count() > index && index >= 0) {
			mediaPlayer.mediaPlayer().subitems().controls().play(index);
		}
	}
	
	public static void main(String[] args) {
		MtListPlayer mtListPlayer = new MtListPlayer(PlaybackMode.LOOP);
		
		mtListPlayer.initMediaList("data/01.mp4", "data/demo.mp4");
		mtListPlayer.play(0);
		
	}
}`

**Comment by caprica** [comment]
Instead of playing the individual items by index, play the playlist itself.

**Comment by caprica** [comment]
If that doesn't work, there's nothing else you can do.

A solution for gapless playback is supposedly coming with VLC 4.0.0.

**Comment by zeegates** [comment]
> If that doesn't work, there's nothing else you can do.
> 
> A solution for gapless playback is supposedly coming with VLC 4.0.0.

Well, thank you very much.
