### ISSUE TITLE
Option to set frame rate for EmbeddedMediaPlayer?

### ISSUE THREAD

**Issue by PulseBeat02** [caprica/vlcj#1073]
Hello, I was wondering if there was an option to set the frame rate for an EmbeddedMediaPlayer. For example, even though the video frame rate itself might be 30 frames per second, you can play it at a lower frame per second such as 25 instead.

**Comment by caprica** [comment]
It is important to remember for questions like this, that vlcj is not playing your video. VLC is playing your video.

So depending on which decoder VLC is using, you *might* be able to set some options on the media player factory or when you play the media - see "vlc -H" and experiment.

Or perhaps you could transcode the video using VLC's "sout" options, but again, no straightforward answer you will have to research and experiment.

**Comment by PulseBeat02** [comment]
In the command line arguments (located [here](https://wiki.videolan.org/VLC_command-line_help/)), I see this

```
FPS conversion video filter (fps)
      --fps-fps=<string>         Frame rate
          Frame rate
 ```
 
 Would that likely be the correct argument for controlling frame rate?

**Comment by caprica** [comment]
All I can say is "try it".

I'm not all that familiar with the huge number of options that VLC supports.

**Comment by caprica** [comment]
I'd also suggest you go to a command-line and type "vlc -H" rather than relying on that WIKI page.

**Comment by PulseBeat02** [comment]
Ok, thank you!

**Comment by caprica** [comment]
Report back if it works or not :-)

**Comment by PulseBeat02** [comment]
Sorry for not replying for a while. I have finals at my highschool. But it seems that the argument is indeed valid as of VLC 3.0.12 (as shown in this picture. I ran `vlc -H` for an exhaustive list of command-line arguments and they seem to match).

<img width="1312" alt="Screen Shot 2021-06-04 at 3 31 32 PM" src="https://user-images.githubusercontent.com/40838203/120853768-27263800-c54a-11eb-9f30-107ce30f0dc6.png">

I will try to get back to you after finals which would be in a week or so if the option works. Maybe it would be cool to add this feature into VLCJ 😄

**Comment by caprica** [comment]
It's not really a good candidate for inclusion in vlcj because it's a basically just a command-line switch and not some native method exposed by LibVLC. The fact that it might work as a media option is just fortuitous.

If you really want this function in vlcj, what needs to happen is for it to be exposed in LibVLC first - this means submitting a patch to VLC that enables this funcitonality and hoping the VLC core developers are OK with it.

If it gets exposed by LibVLC, I will make sure it's available through vlcj as well.

Good luck with your exams!

**Comment by caprica** [comment]
It's been over a month since any activity on this ticket so I'm going to close it. It can be reopened if anything new transpires.
