### ISSUE TITLE
Broken links to Javadoc

### ISSUE THREAD

**Issue by himawari-san** [caprica/vlcj#1081]
Links to Javadoc are broken at https://github.com/caprica/vlcj/tree/vlcj-4.x#documentation.
They refer to http://caprica.github.com/vlcj/javadoc.
http://caprica.github.io/vlcj/javadoc ?
Thanks for vlcj.

**Comment by caprica** [comment]
Thanks for the report.

Did GitHub remove GitHub Pages or something!? All those links used to work, even quite recently.

**Comment by caprica** [comment]
Updated links.

**Comment by himawari-san** [comment]
Thanks!
