### ISSUE TITLE
VLC Delay at First Load

### ISSUE THREAD

**Issue by PulseBeat02** [caprica/vlcj#1086]
Hi, I'm not sure if this is a bug or not with VLC, but it seems that every time I play the first video in my application, it is always delayed 1 second before the frames appear. Any other media that I play afterhand seems to play instantly. In other words, suppose I loaded up a video file from my file system. On the first run, the video takes a second before the frames come in. However, if I run it again, the frames come up instantly. 

I was thinking perhaps VLC uses some sort of buffer where it buffers its frame first for certain videos? But this wouldn't make sense because if I play different media after the first run their frames come up instantly right after the play method is called.

Do you have any idea on perhaps why this could be happening and a solution? The reason why this is a big issue for me is that the audio playback is handled differently from how VLC does it, and I want to sync the two together. This means that buffer frames or blank frames before can really mess up the sync on the first run.

**Comment by caprica** [comment]
I suppose VLC may not be loading all its plugins until they're first accessed, after which they will probably be cached.

An aside, but you are relying on hope to keep your audio and video in sync, even if they did start at the same time - anything can happen to knock them out of sync, but I don't know what else you can do here.

Anyway, the usual trick is to have a hidden or 1x1 sized no audio media player created when your application starts up with a one frame 1x1 black background video or something. That can be enough to "warm up" your media player so when you use it for your first real video it's already ready.

**Comment by PulseBeat02** [comment]
That seemed to work. Thanks for the suggestion!

**Comment by PulseBeat02** [comment]
Hi. Sorry for the late response, but after I tested this on Mac, I seemed to get some odd JVM crashes:

```java
  public void executePhantomPlayers() {
    // loads all necessary VLC plugins before actual playback occurs
    final MediaPlayerFactory factory = new MediaPlayerFactory("--no-video", "--no-audio");
    final EmbeddedMediaPlayer player = factory.mediaPlayers().newEmbeddedMediaPlayer();
    player.videoSurface().attachVideoSurface();
    player
        .media()
        .play("https://github.com/MinecraftMediaLibrary/EzMediaCore/raw/master/vlc-prerender.mp4");
    player
        .events()
        .addMediaPlayerEventListener(
            new MediaPlayerEventAdapter() {
              @Override
              public void finished(final MediaPlayer mediaPlayer) {
                player.release();
                factory.release();
              }
            });
  }
  ```

When I tried on Windows, I didn't seem to get the JVM crash. But on Mac, I seemed to get one. Here is what the error report looks like:

```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fff204186dd, pid=51291, tid=56583
#
# JRE version: OpenJDK Runtime Environment Temurin-16.0.2+7 (16.0.2+7) (build 16.0.2+7)
# Java VM: OpenJDK 64-Bit Server VM Temurin-16.0.2+7 (16.0.2+7, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, bsd-amd64)
# Problematic frame:
# C  [libsystem_pthread.dylib+0x36dd]  pthread_rwlock_rdlock+0x1
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/bli24/Desktop/paper server/hs_err_pid51291.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
zsh: abort      java -Xms3G -Xmx3G -XX:+UseG1GC -XX:+ParallelRefProcEnabled 
```

[hs_err_pid51291.log](https://github.com/caprica/vlcj/files/7116690/hs_err_pid51291.log)

I read the MediaPlayerFactory class and kept note to keep both the MediaPlayerFactory and EmbeddedMediaPlayer as hard references. I wonder, could it be due to how I am running the code asynchronously? let me try and see.

**Comment by PulseBeat02** [comment]
Running it synchronously didn't seem to fix it. Hmm

**Comment by caprica** [comment]
Releasing the media player and factory in an event handler is not a good idea.

I always recommend keeping your factory and media player instances hanging around and re-using them, even if that means some sort of player-pool. While in theory releasing those native resources should be OK, you have to make sure you release them only at the right time, and while the native media player is calling your event handler back is certainly not the right time.

**Comment by PulseBeat02** [comment]
Thank you for the reply! I managed to keep a singleton instance of the player and now it works perfectly.

**Comment by caprica** [comment]
This is where native concerns leak into Java. What is actually happening is the native media player is calling you back in a native event handler on a native thread.
Your handler executes and returns back to the native media player, which you have just this instant destroyed... so you end up executing garbage and crashing.
