### ISSUE TITLE
Aspect ratio incorrect for certain video and .setAspectRatio not working

### ISSUE THREAD

**Issue by hasen6** [caprica/vlcj#1089]
Two issues. Everything works fine with other videos, whether tv shows or movies but one certain video displays with the wrong aspect ratio in VLCJ but for some reason displays perfectly in VLC media player 3.0.8. It looks like it's displayed at 16:10 whereas it should be 16:9 or wider - quite a noticeable issue in any case. To save posting an issue here I attempted to simply change the Aspect ratio in VLCJ since the problem is only with this one video but I couldn't get `setAspectRatio` to register a change either.

All my videos are widescreen so I tested `embeddedMediaPlayer.video().setAspectRatio("4:3");` to see a very noticeable change but nothing happened. I noticed `embeddedMediaPlayer.video().setGamma(0.1f);` and `embeddedMediaPlayer.video().setHue(180);` also did not work but picked up elsewhere that I needed to call `embeddedMediaPlayer.video().setAdjustVideo(true);` just before this, and sure enough that fixed the gamma and hue calls....but still `setAspectRatio` does not work.

Also I don't know why it displays only this one video incorrectly. It's MPEG-H Part 2/ HEVC (H.265) (hvc1) at 720x464. Pretty much the same as my other videos so not sure what the problem is. Any ideas on either issue would be great.

**Comment by caprica** [comment]
For aspect ratio, try the AspectTest in the vlcj test sources (vlcj 3.x) or the vlcj-examples project (vlcj 4.x) with your video just to check what happens.

**Comment by hasen6** [comment]
> I can't see two issues here, you['re saying your video adjust issue is solved? So what's the second issue.
> 
> If you have two unrelated issues post them as separate issues.

There's two issues listed in the title. 1. the video opens in the wrong aspect ratio in VLCJ while it opens in correct ratio in VLC media player. 2. `setAspectRatio` doesn't work. Two different but related issues.

**Comment by caprica** [comment]
For setAspectRatio look at the code in the example I quoted, that's all you do: https://github.com/caprica/vlcj/blob/vlcj-4.x/src/test/java/uk/co/caprica/vlcj/test/aspect/AspectTest.java

**Comment by caprica** [comment]
Are you using JavaFX?

**Comment by hasen6** [comment]
Yeah it's JavaFX. So there's no reason why my code shouldn't work then. I just added this as a quick test to see if it would fix the broken video issue I posted separately but it didn't do anything.

```
private void aspect() {
    embeddedMediaPlayer.video().setAspectRatio("4:3");
}
```
java.version: 12.0.1,javafx.version: 16, on MacOS.

**Comment by hasen6** [comment]
Yeah you're right, that was stupid. It was the video image view set to preserve ratio and with `setFitHeight`. Thanks.

**Comment by caprica** [comment]
No worries, like I said I could have get there quicker if I knew it was JavaFX.

I would prefer if the normal aspect ratio methods were enough, but with JavaFX things are different.

**Comment by hasen6** [comment]
To repeat what I said on the other issue, I always assumed the 'J' in VLCJ stood for 'JavaFX' so didn't think it needed mentioning.
