### ISSUE TITLE
Video opens with incorrect aspect ratio for certain video

### ISSUE THREAD

**Issue by hasen6** [caprica/vlcj#1090]
Everything works fine with other videos, whether tv shows or movies but one certain video displays with the wrong aspect ratio in VLCJ but for some reason displays perfectly in VLC media player 3.0.8. It looks like it's displayed at 16:10 whereas it should be 16:9 or wider - quite a noticeable issue in any case.

It's MPEG-H Part 2/ HEVC (H.265) (hvc1) at 720x464. Pretty much the same as my other videos so not sure what the problem is. Any ideas on either issue would be great.

**Comment by hasen6** [comment]
So if that's the case it should display incorrectly in the same way on VLC media player 4.

**Comment by caprica** [comment]
No.

You missed a critical piece of information from your original issue report in that you are using JavaFX. Reasoning is posted in your other issue.

**Comment by hasen6** [comment]
I always assumed the 'J' in VLCJ stood for 'JavaFX' so didn't think it needed mentioning.
