### ISSUE TITLE
Is it possible to use vlcj on ubuntu without installing vlc

### ISSUE THREAD

**Issue by ArishSultan** [caprica/vlcj#1096]
What i mean is i do not want to install whole vlc, i want to use libvlc.so and libvlccore.so have used the native library loader but not working.

**Comment by caprica** [comment]
Depends what you mean by "install", but generally, no.

**Comment by caprica** [comment]
Unlike Windows DLLs, there is not a single set of shared libraries that can be copied for all Linux distributions.

You can't just copy the files from one distribution to another. In theory you could build on Ubuntu and then copy those files to another Ubuntu, as long as the install directory names where the same.

BUT... run-time linking is not a straightforward subject, for example on Linux the shared libraries have their installation paths baked into them - look into "rpath" for some details.

The right (IMO) approaches are:

1. Deliver your own software as a proper package (a .deb file or whatever) and have it depend on LibVLC
2. Deliver your own software and LibVLC as a snap package or AppImage or something

Option 1 is easier.

Option 2 has difficulties relating to relocation.

Honestly though, it's beyond the scope of this project.

**Comment by ArishSultan** [comment]
OK, the current situation is that is have installed two ubuntu packages namely libvlc-dev and libvlccore-dev which then gives me two shared library files namely libvlc.so and libvlccore.so these are located in /usr/lib/x86.../

The problem is that is am unable to load libraries from that location. but when i install full version of vlc i.e. sudo apt install vlc it also places its own libvlc and libvlccore files and the vlcj is able to load them automatically without me providing the path to libraries explicityly.

What is want to do is to bundle the libvlc and libvlccore (or any other shared library files that are needed) with my software so that the client should not have to install vlc on their device and then use my software.

**Comment by caprica** [comment]
One of the options I already posted in my previous comment is what you need to do.

**Comment by ArishSultan** [comment]
@caprica I am not able to use vlcj 5.0.0.

Could not resolve dependencies for project uk.co.caprica:vlcj-lwjgl-demo:jar:0.1.0-SNAPSHOT: Could not find artifact uk.co.caprica:vlcj:jar:5.0.0-SNAPSHOT

mvn install gives me this error

**Comment by caprica** [comment]
Since there is no full release version of vlcj-5.0.0 yet, only vlcj-5.0.0-SNAPSHOT, you have to enable the Maven snapshot repository in your pom.xml.

```
    <repositories>
        <repository>
            <id>oss.sonatype.org-snapshot</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>
```
