### ISSUE TITLE
Pause on last frame

### ISSUE THREAD

**Issue by taras2480** [caprica/vlcj#1100]
Hi)
My name is Taras

We updated your product to 3-x version and  we are very pleased it. 
 We can't  make decision find a solution on one moment. After playing video doesn't stop on last frame. 
Can you help us?

**Comment by caprica** [comment]
When I play video, it _does_ stop on the last frame.

Using the MinimalTestPlayer example from the vlcj test sources, this is what the video window looks like when my sample media stops playing:

![image](https://user-images.githubusercontent.com/1385879/146691174-fb4e9d16-90fe-4a49-acf7-58a486acff24.png)

**Comment by taras2480** [comment]
Thank you for your answering. In my player after stopping video doesn't show last frame. May is it special method for adjustment this one?

**Comment by taras2480** [comment]
For example in vlc player we can change this property.
![pauseLastFrame](https://user-images.githubusercontent.com/31446780/147157540-6ff8097b-2e27-4dff-afc3-930c2181a098.JPG)

How do I can adjustment this property in vlcj?
Thanks

**Comment by caprica** [comment]
You can try passing "--play-and-pause" via your MediaPlayerFactory, or something like ":play-and-pause" as a media option when you invoke mediaPlayer.play(mrl, options).

**Comment by taras2480** [comment]
Thank you! You helped me very much, mediaPlayer.play(mrl, play-and-pause) worked well
