### ISSUE TITLE
how to display pre frame

### ISSUE THREAD

**Issue by cale96b4** [caprica/vlcj#1121]
i know display next frame by 
`getMediaPlayer().controls().nextFrame()`
but i can't find some func like 
`getMediaPlayer().controls().preFrame()`
to display previous frame,also i can't find in lib vlc, am i can do that?

**Comment by caprica** [comment]
As you've discovered, there is no API in LibVLC to go to the previous frame, nor is there any such feature in VLC itself.

It simply is not possible, and I'm afraid that's all there is to it.
