### ISSUE TITLE
Snapshot Timeout

### ISSUE THREAD

**Issue by ledahu** [caprica/vlcj#1128]
Hello,

Could you implement the snapshot Timeout in the 4. branch (i saw you did it in the 5. ) ?

Because sometime my app crash on the infinite waiter :(

Thank you

**Comment by caprica** [comment]
Seeing as you found the commit in 5.x, you could provide a link here and I'll take a look...

**Comment by caprica** [comment]
I would say however it points to there being something else wrong if the snapshot actually does time out.

**Comment by caprica** [comment]
Presumably this cd01d6c2f6ccde90740b0431b6c3a883630f33f7.

**Comment by caprica** [comment]
Unfortunately that can't just be cherry-picked due to merge conflicts.

**Comment by ledahu** [comment]
well , i have imported in my app the `WaitForSnapshot` class 
and now my app is stable if the webcam im monitoring encounter some network problems : the snapshot doesnt crash anymore,

but, just to let you know,  even if it doesn't seems to be a problem, now i have fork-join-pool thread waiting, im sure its from the snapshot not really ending at timeout. 

`ForkJoinPool.commonPool-worker-19" #31371 daemon prio=5 os_prio=0 cpu=1899358.98ms elapsed=205257.96s tid=0x00000000538b5000 nid=0x1d48 waiting on condition  [0x0000000056abe000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@11.0.9/Native Method)
        - parking to wait for  <0x0000000083c07298> (a java.util.concurrent.ForkJoinPool)
        at java.util.concurrent.locks.LockSupport.parkUntil(java.base@11.0.9/LockSupport.java:275)
        at java.util.concurrent.ForkJoinPool.runWorker(java.base@11.0.9/ForkJoinPool.java:1619)
        at java.util.concurrent.ForkJoinWorkerThread.run(java.base@11.0.9/ForkJoinWorkerThread.java:183)

   Locked ownable synchronizers:
        - None
`
