### ISSUE TITLE
Please release jar files instead of sources in Releases section.

### ISSUE THREAD

**Issue by 100doses** [caprica/vlcj#1130]
I don't have Maven and i don't even want to install it.
It is possible to release jar files in the Releases section to be able to use it in Build Path in Eclipse without Maven ?
Thanks in advance. ^^

**Comment by caprica** [comment]
Maybe in future I will start using GitHub Releases feature, but it's not a priority at the moment.

Maven/Gradle etc are far and away the most common method for building software, and in any case if you just want the jar files without installing such a build tool you can just search the Maven repos and download the jar files from there:

https://search.maven.org/artifact/uk.co.caprica/vlcj

Pick the version you want, find the Download link.
