### ISSUE TITLE
Play folder using "random" and "loop" option

### ISSUE THREAD

**Issue by jan-tennert** [caprica/vlcj#1135]
Hey! I wanted to play a folder with the random and loop option but this doesnt work:
```kotlin
mediaPlayerComponent.mediaPlayer().media().play("folder", "loop", "random")
```
(Kotlin btw)

**Comment by caprica** [comment]
Your syntax for "loop" and "random" as media options is wrong.

Try: ":loop" and ":random".

If that doesn't work on media options, then you have to pass them as arguments when creating the media player factory like this: "--loop" and "--random".

**Comment by jan-tennert** [comment]
Doesn't work, it gave me different videos at the start in comparison to without but its still always the same

**Comment by caprica** [comment]
"different videos"
"it's still always the same"

Unclear what you mean.

**Comment by jan-tennert** [comment]
Okay so I tried both of the options you gave me but the still doesn't play random videos from the folder its always the same

**Comment by jan-tennert** [comment]
this works perfectly fine (in cmd): vlc --random --loop folder

**Comment by caprica** [comment]
Show your code.

**Comment by jan-tennert** [comment]
MediaPlayerFactory: `CallbackMediaListPlayerComponent(MediaPlayerFactory("--loop", "--random"), null, null, true, null)`
Playing the folder: `mediaPlayerComponent.mediaPlayer().media().play("folder", ":random", ":loop")`

And also as I said it did change the order of the videos but its still not random

**Comment by caprica** [comment]
It changed the order but it's not random... so what order is it it.

Anyway, the point is that the options you specify in the factory are exactly the same as you specify on the command-line. There is no difference.

vlcj is not controlling the order your playlist plays, it is all VLC, 

So those options either work, or they don't. It is feasible I suppose that it doesn't work the same way via LibVLC.

Maybe your only option is to manage the playlist yourself.

**Comment by jan-tennert** [comment]
"It changed the order but it's not random... so what order is it it."
It was like this order without these options:
A - B - C - D
with these options always this order (doesn't change at all):
C - A - D - B

**Comment by caprica** [comment]
OK, well, what that shows is that the options you passed made it to VLC and VLC used those options.

But, it is not working via LibVLC the same way as it works in VLC, and that is unfortunate but feasible.

The VLC developers will tell you that _none_ of those arguments are supported in LibVLC - if it works, great, but if it doesn't then that's just tough.

Your only option then is to manage the playlist yourself.

**Comment by jan-tennert** [comment]
yea ok I'll just make that myself thanks tho for the help
