### ISSUE TITLE
Cannot disable hardware accelerator in vlcj 

### ISSUE THREAD

**Issue by AKMANSoft** [caprica/vlcj#1139]
In vlc i can disable hardware accelerator using this option in preference. 

[https://wiki.videolan.org/VLC_HowTo/Hardware_acceleration/#:~:text=From%20the%20menu%20toolbar%20select,To%20disable%2C%20select%20Disable.](VLC HowTo/Hardware acceleration)

I'm passing the argument "--avcodec-hw=none" to MediaPlayerFactory class, to disable Hardware acceleration, but its not working. 

vlc dotnet have the same issue, i found it in my research online. 
[https://github.com/ZeBobo5/Vlc.DotNet/issues/498](url)

**Comment by caprica** [comment]
Passing those arguments via libvlc_new (which is what the factory does) is not guaranteed to work. If one of those arguments works, great, but there is no guarantee. There are other things that simply dont't work that way, like some of the audio filter options.

So then the question becomes what is the proper way to disable hardware acceleration when using LibVLC?

Well, there is no LibVLC API to deal with it, so... I don't know.

According to the LibVLC forum linked in the issue you posted, it should work if you forget the factory and instead pass ":avcodec-hw=none" as a media option when you invoke play().

**Comment by AKMANSoft** [comment]
Thank you passing to play method resolve the issue.
