### ISSUE TITLE
Embed necessary lib with app, so that VLC installation isn't required?

### ISSUE THREAD

**Issue by ScottPierce** [caprica/vlcj#1149]
Is it possible to embed the necessary library / app so that VLC installation isn't required? Many people who have tried this library with [compose](https://github.com/JetBrains/compose-jb) have found that it won't function unless VLC is installed. I tried looking through the documentation and I didn't see anything that clearly explained this.

**Comment by caprica** [comment]
It generally isn't possible.

It might work on Windows, but you would have to include the dlls in some installation file, or your jar file, and then you have to write something to unpack those dlls to a temporary folder or something.

On Linux and macOS as far as my understanding goes the shared objects are generally not relocatable, so it won't work.

Whenever this comes up, I really don't comprehend why developers won't just use the standard OS installation methods to install those dependencies.

**Comment by ScottPierce** [comment]
What files does vlcj use? It's not possible to just download those at runtime, or package them with the installed application?

> Whenever this comes up, I really don't comprehend why developers won't just use the standard OS installation methods to install those dependencies.

Primarily because it's a very ugly solution. Asking the user to do something else in addition to what they've done. What happens if they uninstall VLC, or have the wrong version installed, etc. It's something that becomes difficult to control, and it's a bad user experience.

**Comment by caprica** [comment]
I don't agree that it's ugly or bad UX to use a standard OS installation package solution.

In any case, the files vlcj uses are the shared libraries (*.dll, *.so, *.dylib) installed by VLC, starting with e.g. libvlc.dll and libvlccore.dll, and then all the files in the VLC plugins directory.

If you want to include them all in your own Java app, go for it. Be prepared to write code to unpack those shared objects from your jar file at run-time. And be prepared for it probably only working on Windows.

**Comment by mahozad** [comment]
I'm creating a Desktop app with ability to play video (with [Compose Multiplatform](https://github.com/JetBrains/compose-multiplatform)).

Unfortunately, we cannot simply assume that VLC has been installed on users systems.
Instructing users to install VLC is a little hard too.
Also, embedding the VLC setup file in our installer (if that's possible) makes its size bigger.

I found this library called [JavaCV](https://github.com/bytedeco/javacv). It uses JNI to interface with [FFmpeg](https://ffmpeg.org/) and more.
The author seems to publish library artifacts for all platforms. For example, for FFmpeg:
https://repo1.maven.org/maven2/org/bytedeco/ffmpeg/5.1.2-1.5.8/

So, to call FFmpeg libraries or even run its executable binary we can include this two dependencies and we are good to go:

```kotlin
implementation("org.bytedeco:javacv:1.5.8")
runtimeOnly("org.bytedeco:ffmpeg:5.1.2-1.5.8:windows-x86_64") // Platform-specific artifact
```

Is there any chance you could embed the required VLC *dll* or *so* files in the published artifact like what that library does?


I think the issue https://github.com/caprica/vlcj/issues/1041 is related.

**Comment by caprica** [comment]
Indeed, nothing prevents you from including the DLLs directly in your own application, as long as you extract them at run-time.

**Comment by mahozad** [comment]
Is it at least possible for you to specify exactly which DLLs should be included for Windows x64?

**Comment by caprica** [comment]
Unfortunately no.

There is no VLC documentation that says which plugins are needed for which functionality.

But the plugins are much more than the basic high-level items you list - it depends what input sources you want to support, what video codecs you need, and so on.

That's for you to work out for yourself based on your own project's requirements.

**Comment by mahozad** [comment]
There is a new Gradle plugin called [vlc-setup](https://github.com/mahozad/vlc-setup/) for Compose Multiplatform to automatically prepare and embed VLC plugin files in the app. It still requires the developer to add some code in their build and do some modification in their media player.
See [this project](https://github.com/mahozad/cutcon/) for real-world example.

I tested the plugin only on my system on some different OSes. See [the table of tested OSes](https://html-preview.github.io/?url=https://github.com/mahozad/vlc-setup/blob/main/tested-operating-systems.html):
- Windows XP, Windows 7, Windows 8, Windows 10, Windows 11 all worked OK
- Common and popular Linux distros worked OK (except Ubuntu 16.04)
- macOS 10.13 worked OK (did not test on newer versions)

Also, as far as I have found out, there are so many things in a video/audio file (format, codec, resolution, framerate, sample rate, bitrate, bit depth, HDR/SDR, codec profile, etc.) but I tested a single sample of the most common formats and codecs using the base vlc files (`shouldIncludeAllVlcFiles = false`) and most of them played OK. See the [botom table here](https://html-preview.github.io/?url=https://github.com/mahozad/vlc-setup/blob/main/supported-formats-codecs.html).

Note that VLC 3.0.21 itself still does not support AV1 and H.266 (aka VVC) codecs.

**Comment by caprica** [comment]
Yeah, Linux is a big problem tbh. I started looking at Docker to build VLC then deploy LibVLC + JVM + vlcj + your app as a Snap package or AppImage or something. It's not straightforward, unfortunately. At the present time, I still think the least friction approach is just to have an OS installation package that depends on VLC/LibVLC.

Good work on what you've done, though.
