### ISSUE TITLE
Is it possible to select index in EXTM3U file with pre-caching?

### ISSUE THREAD

**Issue by orlovsn** [caprica/vlcj#1150]
When I use plain (without any meta) .m3u file like this:

```
220613-235951.ts
220613-235956.ts
220614-000002.ts
220614-000007.ts
220614-000012.ts
220614-000018.ts
```

```
String url = "http://..../list.m3u";
String[] options = new String[]{"--http-reconnect"};
embeddedMediaListPlayerComponent.mediaPlayer().media().play(url, options);
```

I can switch playlist parts with embeddedMediaListPlayerComponent.mediaPlayer().subitems().controls().play(index) because vlc correctly fills subitems from such playlist.  
All tracks are played normally and respecting frame rate (some are 25fps some are 6 or 12 fps) but the problem is - when one file ends and next one starts, there is black ~1 second "blink" (when new file is cached?)  
Same behaviour is when I fill playlist manually with mediaPlayerComponent.mediaListPlayer().list().media().add() but for some reason player refuses to respect frame rate and plays 6 and 12 fps tracks @25 fps (faster then it should)

If I add meta data to playlist:

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:3,1
220613-235951.ts
#EXTINF:2.1,2
220613-235956.ts
#EXTINF:2.1,3
220614-000002.ts
#EXTINF:2.1,4
220614-000007.ts
#EXTINF:2.1,5
220614-000012.ts
#EXTINF:2.1,6
220614-000018.ts
#EXT-X-ENDLIST
```

All tracks are displayed correctly without any blinks and at right fps (like a live HLS) but subitems are not filled and I can't select exact tracks neither with embeddedMediaListPlayerComponent.mediaPlayer().subitems().controls().play(index) nor with embeddedMediaListPlayerComponent.mediaListPlayer().controls().play(index)

Is there any way to either avoid blinking in dumb playlists or jump to exact position of EXT-X ones?

**Comment by caprica** [comment]
As far as I know, the only thing that might help you here is the upcoming gapless playback with VLC 4.x.

**Comment by caprica** [comment]
vlcj does not load your M3U, it passes the location of your M3U directly to VLC and VLC plays it.

So vlcj can only do whatever VLC can do.

Honestly though, I would expect if you played your M3U you shouldn't really even have to deal with subitems. If you just let it play, does it still have those "blinks", or is it only if you navigate the playlist?

**Comment by caprica** [comment]
I think the bottom line is there is nothing that can be done in the vlcj/Java side to help you here.

**Comment by orlovsn** [comment]
> I think the bottom line is there is nothing that can be done in the vlcj/Java side to help you here.

I tried to set fixed size with:
```
String[] options = new String[]{"--no-qt-video-autoresize", "--no-embedded-video", "--no-autoscale", "--width=720", "--height=350", "--zoom=0.25"};
MediaPlayerFactory factory = new MediaPlayerFactory(options);
        mediaPlayerComponent = new EmbeddedMediaPlayerComponent(
                factory,
                null,
                null,
                null,
                null
        );
```
but no improvement - still blinks when it auto lists files in plain (no meta) playlist

If I call vlc directly via ProcessBuilder without any tweaks  
```
vlc.exe + "--intf=http", "--http-host=127.0.0.1", "--http-port=9090", "--http-password=..." 
```
and use internal http server to load same playlist 
```
http://127.0.0.1:9090/requests/status.xml?command=in_play&input=http://.../list.m3u
```
 = zero blinks (and working seek by status.xml?command=pl_play&id= )  

So looks like problem is somewhere on the Java side

**Comment by caprica** [comment]
> So looks like problem is somewhere on the Java side

That's a leap.

I already said it is VLC that plays your playlist, not vlcj. All vlcj does here is pass the MRL of the playlist to LibVLC, which then passes it to VLC. VLC then plays the playlist.

If you think you can find some problem in the Java code related to this by all means point it out. But I doubt you'll find anything in vlcj that is implicated here.

**Comment by caprica** [comment]
You also need to realise the VLC does not itself use LibVLC, so it is not out of the question that there are some differences in behaviour.

**Comment by orlovsn** [comment]
> I already said it is VLC that plays your playlist, not vlcj. All vlcj does here is pass the MRL of the playlist to LibVLC, which then passes it to VLC. VLC then plays the playlist.

I understand that, that's why I tried to find out "easy way" with selecting index in EXT list, where all files in list seems to be interpreted as parts of single video and nothing leads to blinking problem   

My initial thoughts were that blink problem is related to cache (file starts to download from http only when it is selected to play as next track so it takes some time to get enough data to start playing) but as long as there is no blink when I set index directly with subitems().controls().play (1-100-1000 so for sure they are not in some kind of local cache) blink is generated by some render procedure - I suppose it is rescaling because rescale happens also in pure VLC (without blink) when same plain playlist is playing on it's own.    
Will try to dig deeper :-)

**Comment by caprica** [comment]
There are some VLC command-line cache switches you can set, but your issue seems beyond my experience really.

**Comment by caprica** [comment]
I think there's nothing to be done here in vlcj itself so I'll close this issue. If more details come to light the issue can be reopened.
