### ISSUE TITLE
How can i implement the RTMP server using vlcj

### ISSUE THREAD

**Issue by SpringStudent** [caprica/vlcj#1158]

**Comment by caprica** [comment]
Maybe something in here can help you:

https://github.com/caprica/vlcj-examples/tree/master/src/main/java/uk/co/caprica/vlcj/test/streaming

**Comment by SpringStudent** [comment]
ok,i already saw examples,but there is no implement for rtmp,hope vlcj can support stream rtmp, finally vlc is really good project and thanks you.

**Comment by caprica** [comment]
If VLC supports streaming via RTMP, then you can do the same with vlcj, and it will be very similar to those examples.
