### ISSUE TITLE
question over rtsp

### ISSUE THREAD

**Issue by SpringStudent** [caprica/vlcj#1159]
I made an RTSP service reference to the StreamRtsp example, and this is my code
```
public class StreamRtsp2 extends VlcjTest{
    public static void main(String[] args) throws Exception {
        String media = "rtsp://admin:Aa123456@172.16.1.43:554/Streaming/Channels/101";
        String options = formatRtspStream("127.0.0.1", 5552, "2");
        System.out.println("Streaming '" + media + "' to '" + options + "'");
        MediaPlayerFactory mediaPlayerFactory = new MediaPlayerFactory();
        MediaPlayer mediaPlayer = mediaPlayerFactory.mediaPlayers().newMediaPlayer();
        mediaPlayer.media().play(media,
                options,
                ":no-sout-rtp-sap",
                ":no-sout-standard-sap",
                ":sout-all",
                ":sout-keep"
        );

        // Don't exit
        Thread.currentThread().join();
    }

    private static String formatRtspStream(String serverAddress, int serverPort, String id) {
        StringBuilder sb = new StringBuilder(60);
        sb.append(":sout=#rtp{sdp=rtsp://@");
        sb.append(serverAddress);
        sb.append(':');
        sb.append(serverPort);
        sb.append('/');
        sb.append(id);
        sb.append("}");
        return sb.toString();
    }
}
```
However, it is not stable enough. When the program starts running, the RTSP stream output can be played through VLC, but after a period of time, the RTSP stream cannot be opened. I tried to use netstat-ano to check the port usage, and found that the port listening is normal, but cannot be accessed through the telent command. Please help me
![image](https://user-images.githubusercontent.com/14833956/176800184-ce918c9f-2ec1-4949-92e8-d3a236c940de.png)
![image](https://user-images.githubusercontent.com/14833956/176800444-81337352-371d-4e47-81bb-16af1f9b2c2e.png)

**Comment by caprica** [comment]
vlcj is only hosting an instance of VLC , it is VLC itself that is providing your streaming server, not vlcj.

So as long as your vlcj objects are not being garbage collected prematurely, there's nothing to be done in vlcj.
