### ISSUE TITLE
[macOS] JavaFX callback player not working well

### ISSUE THREAD

**Issue by acely** [caprica/vlcj#1160]
Test Environment:

> System=macOSX 10.11
> JDK=11.0.15 by Jetbrains
> JavaFX=16
> VLC=4.0.0-dev-d7d51df0 (2022-07-04)
> vlcj & vlcj-javafx & vlcj-natives=git-latest@2022-07-04
> jna=5.12.1

Use case:
Embed javafx video surface in a swing-based gui.

Problems:
The mediaplayer can be inited with a javafx video furface, but when I load a video file, the player can only show one frame of the video and then stops responding, while console prints this error `JNA: callback object has been garbage collected`. After this, the video frame never updates, and any control commands send to the player does not respond.

I start my app with these args `-Xms512M -Xmx12800M`. So theoratically will be enough ram. How can I locate where the error comes from?

Other info:
Works fine when using awt window as video surface under same test environment.

**Comment by caprica** [comment]
You will need to post code, because the message about the JNA callback object being garbage collected implies that you are not properly holding on to some reference.

**Comment by acely** [comment]
Ok, here is th code I use:
```
public void initPlayer(PlayerType type) {
  Component vc = null;
  switch (type) {
  case MPV:
	  //...
	  break;
  case VLC:
	  if (RuntimeUtil.isMac()) {
		  if (!usejavafx) {
			  //use awt window...
		  }else {
			  JFXPanel jfxPanel = new JFXPanel();
			  jfxPanel.setBackground(playerComponentContainer.getBackground());
			  vc = jfxPanel;
			  playerComponentContainer.add(vc,BorderLayout.CENTER);
			  Platform.runLater(new Runnable() {
				  @Override
				  public void run() {
					  ImageView fxiv = new ImageView();
					  fxiv.setPreserveRatio(true);
					  BorderPane borderPane = new BorderPane();
					  fxiv.fitWidthProperty().bind(borderPane.widthProperty());
					  fxiv.fitHeightProperty().bind(borderPane.heightProperty());
					  borderPane.setCenter(fxiv);
					  Scene scene = new Scene(borderPane);
					  scene.setFill(Color.CYAN);
					  jfxPanel.setScene(scene);
					  jfxPanel.putClientProperty("fximageview", fxiv);
					  System.out.println("JavaFX="+VersionInfo.getVersion());
					  System.out.println("javafx video surface ok");
				  }
			  });
		  }
	  }else {
		  //use awt canvas...
	  }
	  player = new VlcPlayerHandler();
	  break;
  default:break;
  }
  if (player != null) {
	  player.setInitListener(this);
	  player.init(vc);
  }
}
```

And in the `VlcPlayerHandler` class:
```
public void init(Component c) {
	this.playerComponent = c;
	new initVlcPlayer().start();
}
private class initVlcPlayer extends Thread{

  @Override
  public void run() {
  MediaPlayerFactory pf = new MediaPlayerFactory(nd,vlcargs);
	  //...
	  vlcplayer = pf.mediaPlayers().newMediaPlayer();
	  if (playerComponent instanceof JFXPanel) {
              JFXPanel jfxpane = (JFXPanel) playerComponent;
              ImageViewVideoSurfaceFactory.videoSurfaceForImageView((ImageView) jfxpane.getClientProperty("fximageview")).attach(vlcplayer);
	  }else {
              long cid = getVideoComponentID(playerComponent);
              System.out.println("[Player] video component id="+cid);
              ComponentIdVideoSurface wvs = pf.videoSurfaces().newVideoSurface(cid);
              wvs.attach(vlcplayer);
	  }
          //...
  }
}
```

**Comment by caprica** [comment]
Honestly, I don't recall why I wrote that comment. It would have been to solve some problem, I Just can't remember.

I'll take a deeper look.

**Comment by caprica** [comment]
Actually, I think this could be done better with a VideoSurface implementation that encapsulated the factory, and then it will be the vlcj media player that keeps the references and prevent garbage collection.

This JavaFX factory API was always a bit weird.

**Comment by caprica** [comment]
Would you please be able to try this: https://github.com/caprica/vlcj-javafx/commit/7f565650ca1fc3f1b133c66462f8b819d341185a

Unfortunately you would have to clone the repo and build the project, if you confirm it works for you I'll make a new release.

Thank you for your trouble-shooting and investigation on this.

**Comment by caprica** [comment]
I did push a 1.1.0-SNAPSHOT build so if you have Maven snapshot repo's enabled you should be able to pull it from there.

**Comment by acely** [comment]
Thanks, I've tried the latest git source, but unfortunately the media player was not able to keep the `ImageViewVideoSurface` object alive, I still have to keep frefrence to it manually. That's a bit weird.

**Comment by caprica** [comment]
I don't understand it.

The EmbeddedMediaPlayer has a hard reference to a VideoSurfaceApi. The VideoSurfaceApi has a hard reference to the VideoSurface.

Everything in the ImageViewVideoSurface has hard references to everything it needs.

So, if you keep your own reference to the EmbeddedMediaPlayer (or EmbeddedMediaPlayerComponent) it should be fine.

In my own testing I didn't see any problem with these changes.

**Comment by acely** [comment]
I see, it's kinda my fault.
I was using **MediaPlayer** and then attach the player **to the video surface**
```
MediaPlayerFactory pf = new MediaPlayerFactory(nd,vlcargs);
vlcplayer = pf.mediaPlayers().newMediaPlayer();
...
videofurface.attach(vlcplayer);
```
In this case the MediaPlayer does not keep refrence to the video surface.

Then I change to use **EmbeddedMediaPlayer** and then attach video surface **to the player**
```
MediaPlayerFactory pf = new MediaPlayerFactory(nd,vlcargs);
vlcplayer = pf.mediaPlayers().newEmbeddedMediaPlayer();
...
vlcplayer.videoSurface().set(videosurface);
```
In this case the video surface is kept alive.

**Comment by caprica** [comment]
Ah! I could maybe add a comment to videoSurface.attach that it is not really intended to be called be end users - although it can be OK to do so in certain circumstances I guess.

Anyway, your original report was very helpful and the new implementation I have now is much better.

**Comment by caprica** [comment]
Pushed release 1.1.0 to Maven Central repo.
