### ISSUE TITLE
Meta.TITLE String's char set is incorrect

### ISSUE THREAD

**Issue by SkyD666** [caprica/vlcj#1162]
The title is chinese character: "白天不懂夜的黑", but player.media().meta()?.get(Meta.TITLE) returns "鐧藉ぉ涓嶆噦澶滅殑榛�".

![](https://user-images.githubusercontent.com/32453770/180902929-b3d758cd-f0a3-4b1f-b63b-417ab220d66a.png)

![](https://user-images.githubusercontent.com/32453770/180902936-8e8757bc-6092-454a-b400-27e129c35efb.png)

**Comment by caprica** [comment]
Could you create e.g. a short silent audio file, or a short black video file, with the metadata title set as you described, and then upload that file here?

But please do not upload any sample that is subject to copyright.

**Comment by SkyD666** [comment]
[TEST.zip](https://github.com/caprica/vlcj/files/9188057/TEST.zip)
The correct title is "汉字测试标题"
![QQ截图](https://user-images.githubusercontent.com/32453770/180961718-fc67a253-e058-42b7-8c58-71d6d615a07b.png)

The incorrect title is: 
![QQ截图](https://user-images.githubusercontent.com/32453770/180961624-56d35efa-e389-48ec-add8-93b1d113b04e.png)

**Comment by caprica** [comment]
When I run this, with your sample file...

```
    @Test
    void itGetsTitleMetadata() throws Exception {
        libvlc_instance_t instance = libvlc_new();
        libvlc_media_t mediaInstance = libvlc_media_new_path("/home/mark/Desktop/TEST.mp3");

        CountDownLatch latch = new CountDownLatch(1);

        libvlc_event_cb eventCallback = eventCallbackFor((event, userData) -> {
            latch.countDown();
        });

        libvlc_event_attach(
            libvlc_media_event_manager(mediaInstance),
            libvlc_event_e.libvlc_MediaParsedChanged,
            eventCallback,
            null
        );

        parseMedia(instance, mediaInstance);

        latch.await();

        String title = libvlc_media_get_meta(mediaInstance, libvlc_meta_t.libvlc_meta_Title);
        System.out.println(title);

        libvlc_media_release(mediaInstance);
        libvlc_release(instance);
    }
```
...it outputs this:
```
汉字测试标题
```

This is on Linux, which in my experience is always better than Windows with UNICODE characters.

Can you try the above code in your environment?

**Comment by caprica** [comment]
Can you also give me an English translation of the wrong title?

**Comment by caprica** [comment]
On Windows 10, my example code returns "汉字测试标题".

**Comment by SkyD666** [comment]
I also don't know what the wrong title means.
I use vlcj's version is 4.7.3
```
implementation("uk.co.caprica:vlcj:4.7.3")
```
But when I try your java code, idea gives an error:
![9](https://user-images.githubusercontent.com/32453770/181136139-cd13eca0-9930-488c-8843-e55d96e35a48.png)

![10](https://user-images.githubusercontent.com/32453770/181136167-287d867d-abf5-4d2f-995e-abbed5bddff0.png)

**Comment by SkyD666** [comment]
Please try Meta.ARTIST. The correct title is "艺术家". But it will show 艺术�?

**Comment by SkyD666** [comment]
Maybe it's a coincidence that the title is correct.

**Comment by caprica** [comment]
Windows 10, for me returns this:
![image](https://user-images.githubusercontent.com/1385879/181292554-29f74cf7-72d5-474c-9f76-20f47a00c775.png)

**Comment by caprica** [comment]
> But when I try your java code, idea gives an error: ![9](https://user-images.githubusercontent.com/32453770/181136139-cd13eca0-9930-488c-8843-e55d96e35a48.png)
> 
> ![10](https://user-images.githubusercontent.com/32453770/181136167-287d867d-abf5-4d2f-995e-abbed5bddff0.png)

Well, you're supposed to change the filename to match your own environment of course. Is that the error you mean?

**Comment by caprica** [comment]
Here's an example that uses vlcj classes rather than just the native binding classes, just to prove that vlcj is not introducing a problem:

```java
import uk.co.caprica.vlcj.factory.MediaPlayerFactory;
import uk.co.caprica.vlcj.media.Media;
import uk.co.caprica.vlcj.media.MediaEventAdapter;
import uk.co.caprica.vlcj.media.MediaParsedStatus;
import uk.co.caprica.vlcj.media.Meta;

import java.util.concurrent.CountDownLatch;

public class Test2 {

    public static void main(String[] args) throws Exception {
        CountDownLatch latch = new CountDownLatch(1);

        Media media = new MediaPlayerFactory().media().newMedia("TEST.mp3");
        media.events().addMediaEventListener(new MediaEventAdapter() {
            @Override
            public void mediaParsedChanged(Media media, MediaParsedStatus newStatus) {
                latch.countDown();
            }
        });
        media.parsing().parse();
        latch.await();

        System.out.printf(" Title: %s%n", media.meta().get(Meta.TITLE));
        System.out.printf("Artist: %s%n", media.meta().get(Meta.ARTIST));
    }
}
```

**Comment by caprica** [comment]
Seems to work:

![image](https://user-images.githubusercontent.com/1385879/181354654-2cb7cfae-0c52-4f4c-a929-91025278fded.png)

**Comment by caprica** [comment]
I don't know what else I can say on this, it seems to work for me on Linux and Windows 10.

If new information comes to light the issue can be reopened.
