### ISSUE TITLE
Getting Null exception in overlayApi class, sometime when panel resize, or video finish

### ISSUE THREAD

**Issue by AKMANSoft** [caprica/vlcj#1179]
The Listeners is overlayApi is inner class, i cannot change or add any check to it. 
```
java.lang.NullPointerException: Cannot invoke "uk.co.caprica.vlcj.player.embedded.videosurface.ComponentVideoSurface.component()" because the return value of "uk.co.caprica.vlcj.player.embedded.VideoSurfaceApi.getVideoSurface()" is null
	at uk.co.caprica.vlcj@4.7.2/uk.co.caprica.vlcj.player.embedded.OverlayApi.getComponent(OverlayApi.java:269)
	at uk.co.caprica.vlcj@4.7.2/uk.co.caprica.vlcj.player.embedded.OverlayApi.access$200(OverlayApi.java:36)
	at uk.co.caprica.vlcj@4.7.2/uk.co.caprica.vlcj.player.embedded.OverlayApi$OverlayComponentAdapter.componentResized(OverlayApi.java:193)
```

**Comment by caprica** [comment]
Post a minimal, single-class, executable, sample if you want help on this one.

**Comment by AKMANSoft** [comment]
I will extract the code and create a minimal single class executable today. just for info, if we have an overlay window set on video player, and we minimize or sometime resize the code, then this null exception is coming. 

the location of the exception is uk.co.caprica.vlcj.player.embedded.OverlayApi.java componentListener() method.

**Comment by caprica** [comment]
Well, the exception thinks there is no video surface set. Which is very suspicious. This is why I need to see your code.
