### ISSUE TITLE
Is it possible to use vlcj in a sandboxed macOS app?

### ISSUE THREAD

**Issue by rjuszczyk** [caprica/vlcj#1189]
Hello,

I am getting this error:

`“jna4748417494588670388.tmp” can’t be opened because Apple cannot check it for malicious software.
`

when trying to run it in a JVM app jpackaged for macstore.

I have VLC player installed (x86-64) and if I run my app without sandboxing/signing then it runs fine. 

Is it possible to use it in a sandboxed macOS app?

**Comment by caprica** [comment]
Well, the tmp file in question is generated by JNA, not vlcj itself.

I suspect that tmp file is the JNA shared library that is unpacked from the JNA jar at run-time.

Maybe there's some knowledge around this in the JNA project, but I don't know.

**Comment by caprica** [comment]
Search results don't return much unfortunately, the closest I found that mentioned JNA was this:

https://github.com/elastic/elasticsearch/issues/46498

**Comment by rjuszczyk** [comment]
Thanks that gives me some clue where to search! 

I will explore the approach presented [here](**https://stackoverflow.com/a/74341678/2318843**):

**Comment by rjuszczyk** [comment]
reporting back that I was able to resolve that problem by following this answer: https://stackoverflow.com/a/74341678/2318843
