### ISSUE TITLE
Pom is missing from 5.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by chikapachimecho** [caprica/vlcj#1190]
I tried to install like mentioned using this dependency

                <dependency>
			<groupId>uk.co.caprica</groupId>
			<artifactId>vlcj</artifactId>
			<version>5.0.0-SNAPSHOT</version>
                </dependency>

But when I try to run maven install, it throws this error.
"The POM for uk.co.caprica:vlcj:jar:5.0.0-SNAPSHOT is missing, no dependency information available"

**Comment by chikapachimecho** [comment]
Same with

		<dependency>
			<groupId>uk.co.caprica</groupId>
			<artifactId>vlcj</artifactId>
			<version>5.0.0</version>
		</dependency>

**Comment by chikapachimecho** [comment]
Tried starting a fresh maven project and 
"Could not find artifact uk.co.caprica:vlcj:jar:5.0.0-SNAPSHOT"

**Comment by chikapachimecho** [comment]
4.8.2 works and is listed as the most recent.

**Comment by chikapachimecho** [comment]
I see that 5.0.0 is not considered stable.

**Comment by caprica** [comment]
If you add the "official" Maven snapshot repository to your pom,  you can use 5.0.0-SNAPSHOT.

Or if you add the GitHub project page as a snapshot repository, that will also work.

Or, use 4.8.x until the final release of 5.x.
