### ISSUE TITLE
How to catch a mediaPlayer error?

### ISSUE THREAD

**Issue by HeeJoon-Kim** [caprica/vlcj#1196]
Hello, @caprica. Come again. :)

I add a eventListener for mediaplayer, like this.

```java
    @Override
    public void error(MediaPlayer mediaPlayer) {
        log.error("{} Media Error", channelInfo.getChannelId());
    }
```

But not triggered error event method when got errors..

```error
[00007fb03818e0c0] cache_read stream error: cannot pre fill buffer
[00007fb03818e0c0] cache_read stream error: cannot pre fill buffer
[00007fb070003ac0] cache_read stream error: cannot pre fill buffer
[00007fb070003ac0] cache_read stream error: cannot pre fill buffer
```

So, mediaPlayer was stopped when occurred stream error. 
How can I solve this issue. I'd like to...

1. Most of all, want solve a cache_read error!!
 - i did not know why. A cvlc options, '--sout-mux-caching' and '--file-caching' was not a solution. 
2. Or, re-starting a media play when an error happened.
3. Or, skip a problem music in playlist.

I don't know what is a best solution.. :(
I look forward to sharing a your wisdom... Thanks..

**Comment by caprica** [comment]
Those "errors" you see are  native errors that come from VLC itself (or one of its many plugins). There is no way for any users of LibVLC (and obviously that includes vlcj) to catch those errors.

The error listener you added only fires if the media fails to start playback for some reason.

For your options, you can try "--network-caching" I suppose.

But the only way you can "fix" these errors is by fixing the underlying streams.

**Comment by HeeJoon-Kim** [comment]
Hello. @caprica..

Yes.. those errors come from native libVLC.. You are right.. 100%.
So. there is no way that catch an error in java..?
I'll try to add a "--network-caching" option..

Thanks, all the time. :)

**Comment by caprica** [comment]
No, not really.

The only thing you could do is to capture the native log statements and search for patterns (e.g. with regex).

You can grab every log message that comes from VLC by adding a LogEventListener to the media player.

**Comment by HeeJoon-Kim** [comment]
Oh! I did not know about LogEventListener.. Ok.. I'll try out.. Thanks very much!

**Comment by HeeJoon-Kim** [comment]
Hi..

I did try to use LogEventListener.. but, it was not working.. i got a message, 'JNA: callback object has been garbage collected'..

1. add a LogEventListener to  MediaPlayerFactory..
```java
MediaPlayerFactory mediaFactory = new MediaPlayerFactory(arg);
mediaFactory.application().newLog().addLogListener(new LogEventListener() {
            @Override
            public void log(LogLevel logLevel, String s, String s1, Integer integer, String s2, String s3, Integer integer1, String s4) {
                
            }
        });
```

2.  add to libvlc_instance_t
```java
LibVlc.libvlc_log_set(mediaFactory.getNativeInstance(), new libvlc_log_cb() {
            @Override
            public void log(Pointer pointer, int i, libvlc_log_t libvlcLogT, String s, Pointer pointer1) {
                log.error("Native log: [{}] {}", i, s);
            }
        }, null);
```

How to add MediaPlayerFactory to MediaPlayer...??

Thanks to you, always.

**Comment by caprica** [comment]
You need to keep your Log instance "alive" so the garbage collector doesn't release it. This means keeping a hard reference to it, like you must keep a hard reference to your media player.

**Comment by caprica** [comment]
Also, in your step 2, you should NOT be doing that. You should not be using the native binding methods directly. It's all inside the Log class where that happens.

**Comment by HeeJoon-Kim** [comment]
Yes.. you was right.
JNA error was gone when change my code to using a strong reference.
After then, I tried to restart media player or list player when did catch an error message, 'cannot peek'.

But. it was failed.

```java
        @Override
        public void log(LogLevel logLevel, String module, String file, Integer line, String name, String header, Integer id, String message) {
            log.info("NativeLog: {} {} {}", module, name, message);
            if ("cannot peek".equals(message)) {
                Map<Integer, MediaServerInstance> basic = mediaServerService.getBasicInstanceMap();
                for (Integer k : basic.keySet()) {
                    MediaServerInstance instance = basic.get(k);
                    MediaListPlayer player = instance.getListPlayer();
                    ChannelInfo channelInfo = instance.getChannelInfo();
                    log.debug("{} {} is playing {} - {}.", channelInfo.getChannelName(), player.status().getMediaListPlayerState().intValue(), player.status().isPlaying(), player.mediaPlayer().mediaPlayer().status().isPlaying());
                    if (!player.mediaPlayer().mediaPlayer().status().isPlaying()) {
                        try {
                            log.debug("{} play next - {}.", channelInfo.getChannelName(), basic.get(k).getInfo().getMusicUrl());

                            retryPlay(instance);
                        } catch (Exception e) {
                            log.error(e.getMessage(), e);
                        }
                    }
                }
           }
        }

        private void retryPlay(MediaServerInstance instance) {
            Thread thread = new Thread(() -> {
                log.debug("NewThread start.");

                instance.getListPlayer().mediaPlayer().mediaPlayer().controls().play();
                instance.play();

                log.debug("ListPlayer: {}, MediaPlayer: {}", instance.getListPlayer().status().isPlaying(), instance.getListPlayer().mediaPlayer().mediaPlayer().status().isPlaying());
                log.debug("NewThread end.");
            });
            thread.start();
        }
    }
```

At first time, I tried to restart media player in log-events thread, but not did not response..So tried a new thread, not a log-events thread.

But, list player and media player's status did not changed. I tried also playNext(), but was same result....
I got stuck on the problem... :(

**Comment by caprica** [comment]
You should definitely not be doing that from the native log thread.

But I don't know, you have a problem specific to your use-case, I can't really help any more.

**Comment by HeeJoon-Kim** [comment]
Sure.. I understand..
To be honest, just helping me this far has helped me a lot. :)
I send you coffee for  appreciation.

**Comment by caprica** [comment]
That's very kind, thank you.
