### ISSUE TITLE
 TLS handshake error with proxy (cmd line)

### ISSUE THREAD

**Issue by CichyBart** [caprica/vlcj#1202]
VLC version 3.0.18
Windows 10

* Run VLC using command line:
`vlc --http-proxy=http://PROXY:PORT`
* open stream (ctrl+n)
Result (from logs; ctrl+m):
```
gnutls error: TLS handshake error: Error in the push function.
main error: TLS session handshake error
main error: connection error: Connection timed out
access error: HTTP connection failure
```

The same proxy set in the VLC properties works properly, but from command line and using VLCJ `new MediaPlayerFactory("--http-proxy", yourProxySettings);` doesn't work.

**Comment by caprica** [comment]
Well, vlcj does nothing with your command-line arguments other than to pass them on to VLC.

Pass "-vvv" in VLC and your vlcj application and compare the differences in logs.
