### ISSUE TITLE
During loop play, the screen is briefly black each time you switch to the next one.

### ISSUE THREAD

**Issue by Curtaingit** [caprica/vlcj#1205]
There will be no black screen on computers that support hardware acceleration,
But computers that don't support hardware acceleration (and don't have a separate graphics card) will have a black screen

Whether I can optimize it by direct software decoder ?(on computers without a separate graphics card), but I can't find the parameter Settings for this.

I wanted to simulate this on the developer machine by disabling hardware decoding but this parameter doesn't seem to work.

```
public class MyEmbeddedMediaPlayerComponent extends EmbeddedMediaListPlayerComponent {

    private static String[] libvlcArgs = new String[] {"--no-xlib", "--avcodec-hw=none"};

    @Override
    protected String[] onGetMediaPlayerFactoryExtraArgs() {
        return libvlcArgs;
    }
}
```

**Comment by Curtaingit** [comment]
```
vlc 3.8.0
java 1.8
vlc 3.0.8
```

**Comment by Curtaingit** [comment]
```
        mediaPlayerComponent.getMediaPlayer().addMediaPlayerEventListener(new MediaPlayerEventAdapter() {
  @Override
            public void finished(MediaPlayer mediaPlayer) {

                SwingUtilities.invokeLater(() -> {
                    // 列表循环播放
                        if (mrlList.size() == 1) {
                            mediaPlayer.setRepeat(true);
                        } else {
                            if (++playIndex >= mrlList.size()) {
                                playIndex = 0;
                            }
                            mediaPlayer.prepareMedia(mrlList.get(playIndex));
                            playingMrl = mrlList.get(playIndex);
                            mediaPlayer.play();
                        }
               });
          }
 });
```

**Comment by caprica** [comment]
You should really not be using the --no-xlib switch.

What is the actual question here? How to disable hardware decoding? If so, that is a VLC question and not a vlcj question.

If you do "vlc -H" in a command-prompt/terminal window, have a look for any relevant switches.

**Comment by Curtaingit** [comment]
Back to the core issue, I want to check whether the specified software decoding is supported, because some devices do not have the condition of hardware decoding, resulting in a delayed black screen every time the playback is switched again.

**Comment by caprica** [comment]
There is no way through LibVLC/vlcj to check any hardware device capabilities.

Generally speaking, VLC will pick the "best" values for video output/decoding etc.

**Comment by Curtaingit** [comment]
Since I'm new to VLC, I'm not very clear on the core parts. There is a black screen for one second when switching video playback, but this problem now only exists on devices without a separate graphics card. So I was wondering if there was an initiative to specify the decoding method to optimize the loading speed of the next video after the completion of one video.
Of course this is just my idea, or if there are other optimization ways to solve this problem.
Because there is no search for the relevant problem situation on the Internet, so I came to vlcj/github.

**Comment by Curtaingit** [comment]
[https:forum.videolan.org/viewtopic.php?f=14&t=163540&p=540959&hilit=black%20screen#p540959](url)

It seems to be a problem inherent in VLC itself, I will look for other ways to try to solve it without vlc.

**Comment by caprica** [comment]
Sure, it's no problem to raise the issue here, but as you've found out there wasn't really anything could be done in vlcj here.

**Comment by caprica** [comment]
Confirmed that setting input-repeat works, but it has a maximum of 65535 iterations:
```
package uk.co.caprica.vlcj;

import uk.co.caprica.vlcj.player.component.EmbeddedMediaPlayerComponent;

import javax.swing.JFrame;

public class ListTest {

    public static void main(String[] args) throws Exception {
        JFrame f = new JFrame();
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        EmbeddedMediaPlayerComponent mpc = new EmbeddedMediaPlayerComponent();
        f.setContentPane(mpc);
        f.setSize(800, 600);
        f.setVisible(true);

        mpc.mediaPlayer().media().play("/home/mark/normal_05.mp4", "input-repeat=65535");

        Thread.currentThread().join();
    }
}

```

**Comment by caprica** [comment]
Maybe #1243 will provide a viable solution for this.
