### ISSUE TITLE
JVM crash on `jni_CallVoidMethod` frames using MacOS (m1)

### ISSUE THREAD

**Issue by SrRapero720** [caprica/vlcj#1206]
https://gist.github.com/SrRapero720/5887241df214dd418c56e008f5959a9d
https://gist.github.com/SrRapero720/cf1b2d7b4fd5eb81359f5800e78f5bf1

Problem "starts happening" (because i am not sure) since VLC release 3.0.19. i was having a quite large discussion about it and issue was more confusing for me. See https://github.com/SrRapero720/watermedia/issues/29

I can't test old versions on my side because i haven't a mac. I open this issue in case can be solved/replicable on VLCJ.

**Comment by caprica** [comment]
Is there a _minimal_, _executable_, _single-class_ test case that reproduces this problem?

**Comment by SrRapero720** [comment]
here is

https://github.com/SrRapero720/watermedia/blob/master/src/test/java/me/srrapero720/watermedia/tests/uncannonical/RawMacOSTester.java

**Comment by caprica** [comment]
Please also write here the exact versions of vlcj and the JDK you're using, including the JDK vendor. Also the macOS version. I don't have access to latest mac hardware/OS, only previous generation.

I will try and find some time to take a look but I can't promise a timescale.

**Comment by caprica** [comment]
Well, it would be nice and convenient if you were to write it here rather than refer me to a hard-to read hotspot log.

**Comment by caprica** [comment]
I suppose nothing has changed and this is still a problem?

**Comment by SrRapero720** [comment]
no idea
people with the issue is not longer interesting on test and i didn't get any bug report about.
i suggest keep this open until someone with the same issue appears and help us to find why this happen. Because try to do something is try to cross the street blinded.

**Comment by caprica** [comment]
I am going to close this issue. I don't have access to M1 hardware to even try to reproduce it.

If in future someone posts additional information, it can be reopened.

**Comment by SrRapero720** [comment]
someone reports me downgrading to VLC 3.0.18 fixes the issue...

**Comment by caprica** [comment]
Interesting, this gives hope that it might actually also be fixed in a later version of VLC at some point.

**Comment by Him188** [comment]
Having the same issue...  Downgrading to VLc 3.0.18 did not work for me

**Comment by Him188** [comment]
@SrRapero720 Which version of vlcj are you using, please? @SrRapero720

**Comment by Him188** [comment]
Added dependency "net.java.dev.jna:jna:5.12.1" and it now works!

**Comment by SrRapero720** [comment]
4.7.3. but 4.7.3 and 4.8.x doesn't have any difference

**Comment by caprica** [comment]
> Added dependency "net.java.dev.jna:jna:5.12.1" and it now works!

Interesting.

**Comment by caprica** [comment]
If this is confirmed, probably worth making a new release with updated depdendencies.

**Comment by Him188** [comment]
There are already many similar issues about JNA versions on Mac. 

https://github.com/caprica/vlcj/issues?q=is%3Aissue+is%3Aclosed+m1

I think it is worth making a new release.

**Comment by caprica** [comment]
4.8.3 released today with latest JNA dependency.
