### ISSUE TITLE
`uk.co.caprica.vlcj.player.list.ControlsApi` Has no getter for playback mode

### ISSUE THREAD

**Issue by Ramblurr** [caprica/vlcj#1207]
Many thanks for vlcj!

One can [setMode(..)](https://javadoc.io/static/uk.co.caprica/vlcj/4.8.2/uk.co.caprica.vlcj/uk/co/caprica/vlcj/player/list/ControlsApi.html#setMode(uk.co.caprica.vlcj.player.list.PlaybackMode)) for an Audio List Player, but there is no getter for the playback mode.

Have I just overlooked it?

**Comment by caprica** [comment]
I can't remember with absolute certainty, but this is probably because LibVLC provides no native API to get the mode, and you are expected to know the mode you set in your own application code.

**Comment by caprica** [comment]
Also, if such a thing existed, it would probably be on a "StatusApi" rather than "ControlsApi".

Anyway, this was implemented a long time ago, this is the reason I don't really remember the fine detail.

**Comment by caprica** [comment]
Well, that's not quite comparing apples to apples.

The "repeat" flag in ControlsApi has no native LibVLC API counterpart, for both set and get. It's something vlcj provides on top of the native API.

The repeat mode _does_ have native LibVLC API, at least for setting it.

Now, _could_  vlcj manage such a repeat mode flag as well? It would clearly not be impossible to do so, it's just not like that, right now.
