### ISSUE TITLE
[Suggestion] Vlc can't be discovery when install 32-bit vlc in 64-bit machines

### ISSUE THREAD

**Issue by Greatwallcorner** [caprica/vlcj#1214]
I found this in registry editor: HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\VideoLAN\VLC
refer: https://stackoverflow.com/questions/5698690/check-if-vlc-is-installed, first answer's comments
Maybe Can add this registry key in uk.co.caprica.vlcj.factory.discovery.provider.WindowsInstallDirectoryProvider

**Comment by caprica** [comment]
What if both 64-bit and 32-bit versions of VLC are installed? What should vlcj's discovery do then?

Also, why would you install 32-bit VLC on 64-bit Windows?

Anyway, these "unusual" cases are why the discovery implementation is designed to be trivially extended. You could very easily write your own DiscoveryDirectoryProvider that looked for the registry key you mentioned, and give it the highest priority.

**Comment by caprica** [comment]
I'll close this I think, the suggestion is a fair suggestion, but for a bespoke case like this I would just reiterate that the intention is to make it easy for developers to extend the vlcj discovery mechanism themselves. Please check the Javadoc around "discovery" for more information how to do this.
