### ISSUE TITLE
Transparent Overlay on Pi 4 and Pi 5

### ISSUE THREAD

**Issue by FolsomMike** [caprica/vlcj#1222]
Adding this issue + solution to contribute to the wiki...

On  Pi 4, the xcompmgr daemon must be running in the background for transparency to work. It can be enabled in raspi-config, but that does NOT work as it starts the daemon using 'xcompmgr -aR'. Those flags seem to prevent the transparency from working in the Java/VLCJ combo.

Disable compositor in raspi-config and then run it before starting the Java program. It can be put in a startup file (Google it), but I just invoke it in my bash script which starts the Java program (after removing any existing process):

killall xcompmgr
nohup xcompmgr &

On the Pi 5, there is a compositor already running by default and transparency works fine.

I am also running Java 22 and so far everything works fine.

**Comment by caprica** [comment]
Very interesting, thanks.
