### ISSUE TITLE
Playing two files in sync

### ISSUE THREAD

**Issue by mainrs** [caprica/vlcj#1230]
I have two audio tracks. The first track contains the vocals of a song. The second the instruments. 

I want to play them in sync. For that I create two instances of `AudioMediaComponent` and prepare the files.

I then call play on both of them. However, this does introduce _sometines_ a noticable delay. Sometimes it doesn't. 

What can be the cause for that? My guess would be that it puts the playback onto another thread, one for each component. And this it can introduce small delays when calling the play method (since one is called before the other).

**Comment by caprica** [comment]
You can't synchronise like that reliably, there's nothing in VLC to keep them in sync either. What you said is almost certainly right, I mean the reasons for the drift.

However, what you can try is adding a new "slave" track, although I don't think you can play two audio tracks at the same time. Might be worth a quick try though.

I do seem to remember there was some kind of support for multi-track audio in the LibVLC API, but I never got it working. I can't remember how hard I tried tbh.

**Comment by caprica** [comment]
I know this is late, but interestingly there is native API in LibVLC 4.x (still in development) to select multiple tracks.

However, the VLC source code has this comment (abridged):

```
/**
 * Select multiple tracks for one type
 *
 * \version LibVLC 4.0.0 and later.
 *
 * \note The internal track list can change between the calls of
 * libvlc_media_player_get_tracklist() and
 * libvlc_media_player_set_tracks(). If a track selection change but the
 * track is not present anymore, the player will just ignore it.
 *
 * \note selecting multiple audio tracks is currently not supported.
 */
```

i.e. it says selecting multiple audio tracks is not currently supported, but presumably may be in the future. I wonder if this would work for your use case.
