### ISSUE TITLE
for some strream length returned stay at 0 

### ISSUE THREAD

**Issue by kodeplateform** [caprica/vlcj#1231]
Hello,

Thanks for your library.

I use it in combination with Jetpack Compose Multiplatform on the desktop side. I'm facing a problem with the length (duration) of streams. For some streams, the length returned by lengthChanged(mediaPlayer: MediaPlayer, newLength: Long) is 0, and the same issue occurs with val duration = mediaPlayer.media().info().duration(), even if it is called after the stream has started to play.

For info , on android side , i'm able to get the correct duration with exoplayer

**Comment by kodeplateform** [comment]
Hello,

Thanks for your response.

Indeed, when using VLC Player, the duration is not displayed, but interestingly, the progress bar works for tracking the advancement and allows jumping directly to a specific position in the video.

**Comment by caprica** [comment]
I really don't think there's anything can be "fixed" in vlcj here, so closing issue. It can be reopened if new information comes to light.
