### ISSUE TITLE
Some Questions

### ISSUE THREAD

**Issue by kagg886** [caprica/vlcj#1236]
> Ha, I see Jetbrains themselves use vlcj in at least their experimental repo:
> 
> https://github.com/JetBrains/compose-jb/blob/master/experimental/components/VideoPlayer/library/src/desktopMain/kotlin/org/jetbrains/compose/videoplayer/DesktopVideoPlayer.kt
> Originally posted by @caprica in https://github.com/caprica/vlcj/issues/1098#issuecomment-991050755_

I use this video-view, but i can't hover a text above a video, that is my code:
```kotlin
Box(modifier = Modifier.fillMaxSize()) {
                VideoPlayer(url = file.absolutePath, state = state,modifier = Modifier.fillMaxSize(0.1f))
                Text("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
}
```
result is here:
![image](https://github.com/caprica/vlcj/assets/68730049/6ecb1a83-2925-4e0b-9434-0685715896b0)

**Comment by caprica** [comment]
I don't know anything about that JetBrains code.

What you can do with overlaying text or controls all depends how they've done the vlcj integration.

I'm going to close this as off-topic for now since we don't support other company's projects here. If you find a specific problem related to vlcj, by all means comment back here and this can be re-opened.

**Comment by mahozad** [comment]
@kagg886

As an example see [this project](https://github.com/mahozad/cutcon) and [this pull requeset](https://github.com/JetBrains/compose-multiplatform/pull/3336). Using the solution in these you can use a simple box to overlay whatever you want on the video.

**Comment by Him188** [comment]
You might also want to check https://github.com/open-ani/ani/tree/master/app/shared/video-player/desktop/ui/VideoPlayer.desktop.kt
 for a production-level working example (though not very good).
