### ISSUE TITLE
[question] why can't get time change event from MediaPlayerEventAdapter when video is psused

### ISSUE THREAD

**Issue by Greatwallcorner** [caprica/vlcj#1237]
I think i need to update user surface when the time slider was changed in the video paused status.
![图片](https://github.com/caprica/vlcj/assets/49832311/33e6fb4a-781b-4b76-93b3-d5c167e2478e)
, But I can't get time change event in actually. what is the reason? It was designed like this? Looking forward your reply.

**Comment by caprica** [comment]
vlcj will deliver _any_ event that LibVLC sent, at _any_ time, regardless of the media player being paused.

So your question is really a question for VLC/LibVLC.

So to answer the "why" in your question, it's because that's how VLC/LibVLC works.

**Comment by caprica** [comment]
Looks somewhat, but not directly, related to this: https://code.videolan.org/videolan/vlc/-/issues/28353

> Looks like it's due to the fact that there is no vlc_player_UpdateTimerState after the pause
