### ISSUE TITLE
Unable to Retrieve "Now Playing" Metadata for Internet Radio Streams

### ISSUE THREAD

**Issue by tawhidmonowar** [caprica/vlcj#1245]
I'm attempting to retrieve the "Now Playing" metadata (e.g., currently playing song title) from an internet radio stream using vlcj. However, my code is not successfully retrieving this metadata, and I consistently get null or an empty result instead.

Here's a simplified version of my code in Kotlin that initializes and plays the internet radio stream
```
class PlayerController {
    
    private val audioPlayerComponent = AudioPlayerComponent()
    
    fun prepare(pathSource: String) {

        audioPlayerComponent.mediaPlayer().media().startPaused(pathSource)
        audioPlayerComponent.mediaPlayer().controls().play()
        audioPlayerComponent.mediaPlayer().media().parsing().parse();

        audioPlayerComponent.mediaPlayer().events().addMediaEventListener(object : MediaEventAdapter() {
            override fun mediaParsedChanged(media: Media?, newStatus: MediaParsedStatus?) {
                val mediaPlayer = audioPlayerComponent.mediaPlayer();
                val audioTracks = mediaPlayer.media().meta().get(Meta.NOW_PLAYING)

                println("Media Parsed Status: $audioTracks")
                super.mediaParsedChanged(media, newStatus)
            }
        })

    }
}
```

**Comment by caprica** [comment]
It depends on the stream what's available or not.

In my own test, using random stations from https://dir.xiph.org/, i found some cases where there was nothing available, others where it got the initial now playing, but I was not able to find a stream that generated new now playing each time the track changed. I think it depends on the server the station is using.

In any event, vlcj simple asks LibVLC to get the meta, so it's unlikely there's a problem in vlcj here.

**Comment by caprica** [comment]
Here's my test, even though the now playing meta doesn't update via event, it can be polled:

```java
package wibble;

import uk.co.caprica.vlcj.media.Meta;
import uk.co.caprica.vlcj.player.component.EmbeddedMediaPlayerComponent;

import javax.swing.JFrame;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;

public class TempTest {
    public static void main(String[] args) {
        JFrame f = new JFrame();
        f.setSize(600, 600);
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        f.setVisible(true);

        final EmbeddedMediaPlayerComponent mpc = new EmbeddedMediaPlayerComponent();
        f.setContentPane(mpc);

        mpc.mediaPlayer().media().play("http://cheetah.streemlion.com:2960/stream");

        ScheduledExecutorService executor = Executors.newScheduledThreadPool(1);
        Runnable task = () -> System.out.printf("Now playing: %s%n", mpc.mediaPlayer().media().meta().get(Meta.NOW_PLAYING));
        executor.scheduleAtFixedRate(task, 0, 1, TimeUnit.SECONDS);
    }
}
```

**Comment by tawhidmonowar** [comment]
Hi, thanks for your replay, now I’m able to fetch the 'Now Playing' metadata, but it only works with 'http' streams and not with 'https'!

**Comment by caprica** [comment]
Well, if it's not working with https, that means VLC probably can't get it either. If you play your https stream in VLC does it show the now playing correctly?

**Comment by tawhidmonowar** [comment]
VLC also can't display 'Now Playing' metadata for https streams. I checked this with several radio streams.

**Comment by caprica** [comment]
So that means it's simply not available with such streams.

I'm going to close this as there is no problem in vlcj here.

**Comment by tawhidmonowar** [comment]
Using Media3 ExoPlayer on Android, I can successfully fetch metadata from the same "https" stream, but VLC doesn't display any metadata at all. Is there really no way to retrieve metadata over "https" with VLCJ

**Comment by caprica** [comment]
vlcj will give you it if VLC/LibVLC provide it. It's as simple as that.
