### ISSUE TITLE
Transition in/out of slow modes is choppy and delayed

### ISSUE THREAD

**Issue by emontellese** [caprica/vlcj#146]
For example, transitioning from normal playback speed to 1/4 speed takes significantly longer than with native VLC, has audio stutters, and audio does not restart until a second after video begins.

Bug timeline:
1. Audio/Video pause/delay with Audio stutter
2. Video begins for a few frames
3. Audio doesn't come in until a moment later.

Transitioning back to 1.0 from 0.25 has similar issues.  Other slow-speed transitions exhibit the same, or worse, behavior -- occasionally there can be a very long delay before audio comes back in after the video transitions.

Transitions are made using calls to mediaPlayer.setRate().

Rate transitions with native VLC do not show these artifacts.

Testing was done with the "basic" vlcj test:  src/test/java/uk/co/caprica/vlcj/test/basic
For testing purposes, I hacked the "pause" and "play" buttons to call setRate() with hardcoded values for testing.

I dug into vlcj code and found DefaultMediaPlayer.java, where it looks like the setRate() call just gets passed directly to libvlc:

```
@Override
public int setRate(float rate) {
    Logger.debug("setRate(rate={})", rate);
    return libvlc.libvlc_media_player_set_rate(mediaPlayerInstance, rate);
}
```

If so, this is a libvlc issue and not vlcj.  However, since native VLC does not show this issue, I am interested in your thoughts, and any workarounds we might consider.

**Comment by hasen6** [comment]
I have this problem as well. Transitioning back and forth from 0.5 to 1.0 or 0.75 to 1.0 the audio cuts out for about a second. My whole code right now is literally only a few lines so not sure what could be causing it other than VLCJ itself.

**Comment by caprica** [comment]
Literally all that happens from vlcj's side is to invoke a single native method to change the playback speed.

Everything else from that point onwards is happening inside LibVLC/VLC.

**Comment by hasen6** [comment]
So what can be done? Must be a workaround to allow for VLC's delay?

**Comment by caprica** [comment]
Nothing can be done from vlcj's side. You can maybe transcode into a format more amenable to fast seeking/resynchronising, but I don't know that side of things at all.

You are at the mercy of VLC's implementation. Some media types, and therefore some codecs, will perform better than others I suppose.

**Comment by hasen6** [comment]
But I noticed that the exact same videos don't lag in VLC itself. For example I tried a 2 hour plus long video in VLCJ and it even lagged when skipping 3 second increments, not even changing the rate....but in VLC itself there's no lag at all when doing this.

**Comment by caprica** [comment]
Are you using the native playback for Swing, or the callback playback for JavaFX?

**Comment by hasen6** [comment]
I'm using the embeddedMediaPlayer. Is there any documentation or a code example on using the callback player instead of embeddedMediaPlayer? It wasn't easy to get it set up as it is. :/

**Comment by caprica** [comment]
There are fully working examples provided for all aspects of vlcj. Have a look in the vlcj-examples project for vlcj 5.x, or the src/test/java directory in vlcj for vlcj-4.x.

If, like you say, you found setting up an embedded media player wasn't easy, then maybe this library just isn't a good fit  for you. But I have to say it takes only about half a page of trivial code to get a working media player. I even show this in under two minutes in a video I have on YouTube.

I will remind here that in the general case vlcj is not playing your video - VLC is playing your video. vlcj only embeds a video surface that it tells VLC to use. It interacts with VLC with the LibVLC API. vlcj just isn't involved in the playback of your video at all, so there's limited answers I can give you. When using the callback rendering, then OK vlcj is basically providing your application the means to render the video in software, and in this case the performance won't be as good. Will this explain the lag you're seeing, probably no. But can vlcj do anything other than invoke the LibVLC API, no.

If there are differences you are seeing between vlcj playback and VLC playback, then enable verbose logging with "-vvv" on the command-line and the MediaPlayerFactory and compare the logs.

**Comment by hasen6** [comment]
Coding-wise it was easy but it was a nightmare to get it working since the demo project wouldn't work for me (and still doesn't) and I was getting a black screen with audio only no matter what I tried. There was nothing wrong with my actual initial code, it should've worked. I like VLCJ since it's not a media player, you have to code all the controls and everything yourself which is the way I prefer it since I have to have everything work the way I want it.

If there's some examples then that's great, otherwise you have to deconstruct the classes to find how everything is supposed to go together and end up with probably a bad structure. I prefer to work from a basic template of a one page app that works and turn it into a 100 page app of my own.

But you say with callback rendering (I assume you mean callbackmediaplayer?) the performance won't be as good, but I'm not using that, I'm using embeddedMediaPlayer - so that wouldn't explain the lag?

**Comment by caprica** [comment]
No it wouldn't explain the lag.

**Comment by hasen6** [comment]
Seems to be a legitimate issue then, previously Emontellese was experiencing it but you couldn't reproduce it but now I also am seeing that issue.
