### ISSUE TITLE
"Can't load JAWT" on Oracle Java 7 for OS X

### ISSUE THREAD

**Issue by davidfstr** [caprica/vlcj#205]
**Environment:** vlcj 2.4.1, Oracle Java 7, OS X 10.7, vlc 2.0.0

**Summary:** DefaultMediaPlayer.playMedia() throws a `java.lang.UnsatisfiedLinkError: Can't load JAWT` exception when using Oracle Java 7 on OS X. Apple Java 6 works.

**Repro Steps:**
- Install a fresh copy of OS X 10.7 on physical hardware.
  - Virtualizing it inside Parallels does not work because VLC needs hardware acceleration support to play certain videos and my version of Parallels does not provide hardware acceleration.
- Install the [JDK for Oracle Java 7](http://www.oracle.com/technetwork/java/javase/downloads/jdk7-downloads-1880260.html).
- Install VLC 2.0.0 in /Applications/vlc-2.0.0.
- Install VLCJ 2.4.1 and add its JAR to your $CLASSPATH.
- Copy the [Tutorial2B.java](https://gist.github.com/davidfstr/6477528) code to a local file.
  - This code is adapted from the [second code sample on your tutorial part 2](http://www.capricasoftware.co.uk/projects/vlcj/tutorial2.html).
- `javac Tutorial2B.java`
- `java Tutorial2B TestVideo.m4v`

**Expected Results:**
A window appears and the specified video plays inside of it.

**Actual Results:**
A black window appears. The following stack trace is printed:

```
$ java Tutorial2B TestVideo.m4v 
JavaVM WARNING: JAWT_GetAWT must be called after loading a JVM
Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: Can't load JAWT
    at com.sun.jna.Native.getWindowHandle0(Native Method)
    at com.sun.jna.Native$AWT.getComponentID(Native.java:1879)
    at com.sun.jna.Native.getComponentID(Native.java:253)
    at uk.co.caprica.vlcj.player.embedded.videosurface.CanvasVideoSurface.attach(CanvasVideoSurface.java:69)
    at uk.co.caprica.vlcj.player.embedded.DefaultEmbeddedMediaPlayer.attachVideoSurface(DefaultEmbeddedMediaPlayer.java:156)
    at uk.co.caprica.vlcj.player.embedded.DefaultEmbeddedMediaPlayer.onBeforePlay(DefaultEmbeddedMediaPlayer.java:315)
    at uk.co.caprica.vlcj.player.DefaultMediaPlayer.play(DefaultMediaPlayer.java:696)
    at uk.co.caprica.vlcj.player.DefaultMediaPlayer.playMedia(DefaultMediaPlayer.java:213)
    at Tutorial2B.<init>(Tutorial2B.java:46)
    at Tutorial2B.<init>(Tutorial2B.java:13)
    at Tutorial2B$1.run(Tutorial2B.java:29)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

**Notes:** This exact same code works correctly when run on Apple Java 6. Therefore Oracle broke something during their port. I have run all tests on fresh installs of OS X 10.7 so there isn't anything else in my environment that would be causing conflicts.

**Comment by caprica** [comment]
There's still no satisfactory answer for this.

I note that SWT has apparently been made to work:

This bug relates https://bugs.eclipse.org/bugs/show_bug.cgi?id=374199

This seems to hinge around CViewEmbeddedFrame, but after some investigations and testing I can't quite understand if it will be useful for this issue in vlcj or not.

If the SWT_AWT bridge still works on JDK 1.7 and 1.8, then in theory vlcj in SWT is an option (albeit far from ideal) for for OSX.

**Comment by caprica** [comment]
See also https://bugs.eclipse.org/bugs/show_bug.cgi?id=418245.

No answers.

**Comment by caprica** [comment]
Also http://mail.openjdk.java.net/pipermail/awt-dev/2013-December/006711.html.

What I find hilariously depressing about this is that according to that mailing list thread the justification for this is "because applets" and "because web browsers".

Who *really* cares about the sub-standard Java applets experience nowadays when HTML5 is so superior, especially with applets as a significant attack vector.

**Comment by caprica** [comment]
I don't know if this will help, but there is a new "caopengllayer" video output in VLC 2.2.0 that also allows to set a video surface with libvlc_media_player_set_nsobject.

I can't investigate this further until VLC 2.2.0 final is released.

**Comment by caprica** [comment]
In my testing, I can't do anything with the caopengllayer video output from Java. It is still totally unknown what should be used for the nsobject parameter value.

This is effectively a dead end, and native rendering on OSX after Java 6 looks pretty much a bust unless someone else posts some useful information.

**Comment by caprica** [comment]
In the impossible quest to find a solution to this, another tidbit...

From http://jira.icesoft.org/browse/PDF-826:

    private static long getNSWindowViewPtr(Window window) {
        try {
            Object componentPeer = window.getClass().getMethod("getPeer").invoke(window);
            Object platformWindow = componentPeer.getClass().getMethod("getPlatformWindow").invoke(componentPeer);
            Object contentView = platformWindow.getClass().getMethod("getContentView").invoke(platformWindow);
            return (Long) contentView.getClass().getMethod("getAWTView").invoke(contentView);
        } catch (Exception exception) {
            throw new RuntimeException(exception);
        }
    }

**Comment by caprica** [comment]
Right now I think that SWT is the only way to get this working on OSX on any JDK after 1.6.

SWT and Swing can co-exist, so using SWT for video and Swing for everything else (if that's what is wanted) is probably the best that can be done here.

I think that approach would be better in terms of performance than using a direct media player.

**Comment by paulholder** [comment]
Two things.

1.  If you intend to leave this "broken" in the existing code, can you please implement a call to some exception such as NotImplemented and that links back here or something?

2.  I am new to VCLj and want to have the simplest code possible (to begin) with that *works* on all platforms that simply plays a supplied video.  I started with code I copied out of the docs that looks like this:
    final JFrame frame = new JFrame();
    final EmbeddedMediaPlayerComponent mediaPlayerComponent = new EmbeddedMediaPlayerComponent();
    frame.setContentPane(mediaPlayerComponent);
    frame.setSize(1050, 600);
    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    frame.setVisible(true);
    final String uriToPlay = "file:///temp/...mp4";
    mediaPlayerComponent.getMediaPlayer().playMedia(uriToPlay);

Was quite pleased that I got it working on Windows and then quite frustrated when that led me here as I started testing on Mac.  Could you possibly document a link here to something similar that is know to simply play a file on Windows, Mac and Linux ?

**Comment by caprica** [comment]
Example showing how to embed vlcj inside SWT that is itself embedded inside a Swing applicaiton at https://github.com/caprica/vlcj-swt-swing

**Comment by caprica** [comment]
Example showing how to embled vlcj inside SWT, not using Swing, at https://github.com/caprica/vlcj-swt-demo

**Comment by ryantheseer** [comment]
FYI: I'm trying to make my VLCJ-based RTSP streamer work cross-platform on Windows, Mac and Linux. Windows is working fine, but I'm running into this same issue. However, when I try to use the SWT Composite solution, the new swt.jar I can download from the website (v [4.7.1a](http://download.eclipse.org/eclipse/downloads/drops4/R-4.7.1a-201710090410/)) has hidden the "embeddedHandle" property of the Composite object. I am trying with v [4.5.2](http://archive.eclipse.org/eclipse/downloads/drops4/R-4.5.2-201602121500/), as you've included in your pom.xml maven build file, but it seems to have the same issue... Not sure if I want to modify the Composite.java source code to gain access...

**Comment by caprica** [comment]
Ultimately, a native window handle is needed by LibVLC - if the toolkit you use does not provide an official/public API to get that handle, you must resort to workarounds. The least bad workaround is to use reflection to e.g. make a private native window handle class field public instead, and extract that value. If that's not possible, then... good luck.

This particular issue is very difficult to do anything about.

**Comment by ivanooi** [comment]
found this code to get the Composite handle. it work with JDK8 
replace this 
long componentId = composite.embeddedHandle;

with this 
long componentId = getControlHandle(  composite );

https://stackoverflow.com/questions/29889540/how-to-get-the-handle-of-swt-control-in-mac-64-bit-cocoa-enviornment

**Comment by caprica** [comment]
Any idea if this works on later JDKs, i.e. 9, 10, 11?

Having said that, if it does indeed work on at least JDK 8, it will be definitely be worth putting that code into vlcj itself.

**Comment by ivanooi** [comment]
my current setting. 10.13.6, Eclipse Neon, JDK8. didn't try 9, 10 or 11..... 
only one problem.. sometimes image did not auto resize according to the window... not sure is it VLC problem or others.... so far so good

**Comment by caprica** [comment]
Oh, I just realised this was in relation to SWT. Damn. I was hoping it was finally a solution for using Canvas on OSX but it's clearly not.

**Comment by ivanooi** [comment]
hahaha well, rather than VLCJ totally dead in OS X. that what happen when i tried to run it in OS X....now because of SWT, VLCJ back to business

**Comment by caprica** [comment]
Linking this purely for reference, as it seems somewhat related and interesting:

https://github.com/LWJGLX/lwjgl3-awt/issues/1
