### ISSUE TITLE
Getting subtitle/spu Text

### ISSUE THREAD

**Issue by andre111** [caprica/vlcj#263]
Is it possible to implement a method for getting the current subtitle/Spu(what does this abbreviation stand for) text so I could render it myself. It would be perfect if it was possible to do this without having vlc render the subtitle itself.

PS: I'm sorry if this sounds rude/demanding. I'm german and I was struggling to express what I would like to be able to do.

**Comment by AbdelkarimTayache** [comment]
after two, i still searching for a solution for  the same problem, i'm wondering if you found a fix for this problem, i wont to read the content of SPu/subtitles, i have times in my video and i can't read it automatically, so i thinked if there a way to do it programmatically without need to do it manually, please if you have any idea a will appreciate it.

**Comment by caprica** [comment]
It's a shame, but it's just not possible. It is not exposed through LibVLC, and so it can't be exposed through vlcj either.

It needs a patch to VLC, but that is a significant piece of work and it needs a volunteer to do it.

I can only suggest loading the sub-title file yourself and somehow decoding it and using it based on the timing information it contains.

**Comment by khrykin** [comment]
You can extract embedded .srt's via ffmpeg/libavcodec. See [this](https://stackoverflow.com/questions/17388253/extracting-subtitles-from-mp4?rq=1) SO post for example.
