### ISSUE TITLE
GnuTLS error on YouTubePlayerTest

### ISSUE THREAD

**Issue by CharlesHD** [caprica/vlcj#275]
Hi i'm using your [YouTubePlayerTest](https://github.com/caprica/vlcj/blob/vlcj-3.0.1/src/test/java/uk/co/caprica/vlcj/test/youtube/YouTubePlayer.java) with vlcj 3.0.1 and vlc 2.1.6 .

When I try to acces a youtube link i get this message :

```
    [0x7fee50001278] gnutls tls client error: unsupported GnuTLS version
    [0x7fee50001278] main tls client error: TLS client plugin not available
    [0x7fee180db398] main input error: open of `https://www.youtube.com/watch?v=CZ0ZU04U7lM' failed
```

When i try to launch the same video in VLC i have no problems.

**Comment by Joe-Merten** [comment]
I have the same issue (using vlcj 3.1.0):

    Preparing (http://www.youtube.com/watch?v=0w1mP3oFXRU)
    Starting (http://www.youtube.com/watch?v=0w1mP3oFXRU)
    [0x7f6b64006408] gnutls tls client error: unsupported GnuTLS version
    [0x7f6b64006408] main tls client error: TLS client plugin not available
    [0x7f6b64004b48] main stream error: cannot pre fill buffer
    Error: Failed to start http://www.youtube.com/watch?v=0w1mP3oFXRU"

Tested on:

* Kubuntu 14.04, 32 Bit, Vlc 2.1.4  →  fail
* Kubuntu 14.04, 64 Bit, Vlc 2.1.4  →  fail
* OS X 10.10, 64 Bit, Vlc 2.1.5  →  succeed
* Windows XP, 32 Bit, Vlc 2.1.5  →  succeed

On all machines, the standalone vlc application works without problems (for both http and https), but my vlcj based java application failed with »unsupported GnuTLS version« when running on (k)ubuntu.

**Comment by Joe-Merten** [comment]
Ok, fixed.
I'd read, that VLC 2.1.5 has got fixes regarding GnuTLS.
Now I'd updated to 2.2.0rc2 (using [this ppa](https://launchpad.net/~djcj/+archive/ubuntu/vlc-stable)) and it works.

**Comment by caprica** [comment]
Just FYI Kubuntu 14.10 includes VLC 2.2.0rc2, so you wouldn't need to use a PPA anymore.
