### ISSUE TITLE
MediaListPlayer should track the current MRL

### ISSUE THREAD

**Issue by caprica** [caprica/vlcj#276]
At the present time, the only way to get the MRL of the "current" item is to track it via event listeners.

This can be encapsulated inside the MediaListPlayer.

See #271.

**Comment by sense42** [comment]
how do i acces this in Vlcj 4.1

**Comment by caprica** [comment]
You can't, it will come eventually with vlcj 5.x

**Comment by sense42** [comment]
I don't want to spam but, this was available in 3.1 but got removed in 4.1 ? 
Or did i get something wrong ?

**Comment by caprica** [comment]
Sorry my previous comment was garbage, I was responding to something else.

**Comment by caprica** [comment]
mediaPlayer.media().info().mrl();
mediaList.media().mrl();

**Comment by sense42** [comment]
mediaPlayer.media().info().mrl(); 
This one and several other ways i tried to acces lead to a NullPointerException. 

mediaList.media().mrl();
This was the way i already found, to acces mrls, but i dont know how to get the index of which media is actually playing.

**Comment by caprica** [comment]
You are supposed to be responsible for checking  the return value of the media() function as it will return null if there is no current media.

**Comment by caprica** [comment]
Your other comment about tracking the index is unrelated to this issue.

**Comment by sense42** [comment]
but media is there. 
i do add it to medialist and can navigate through it. the media plays and all works fine. i can acces mrl through: 
mediaList.media().mrl(int index); 
so how should there be no media ? 

I dont know if im using something immense wrong or the acces via .. media().info().mrl(); is not working.

**Comment by caprica** [comment]
Determining which is the null reference would be a useful first step.

**Comment by sense42** [comment]
I am for sure using mediaListPlayer. 
mediaListPlayer.mediaPlayer().mediaPlayer().media().info().mrl();
but as i told, i tried to acces this through different ways but all end in nullPointerException.

**Comment by caprica** [comment]
But which of those objects in your chain of dereferences is null?

There's an issue related to media list media player that may be relevant.  #877

**Comment by sense42** [comment]
embeddedMediaListPlayerComponent.mediaListPlayer().mediaPlayer().mediaPlayer().media() is null 

embeddedMediaListPlayerComponent.mediaListPlayer().mediaPlayer().mediaPlayer() is not nul.

**Comment by caprica** [comment]
And you have previously invoked something like playMedia or setMedia?

**Comment by sense42** [comment]
mediaList.media().add(files[i].getPath(), options);
mediaListPlayer.list().setMediaList(mediaList.newMediaListRef());

and. 

mediaListPlayer.controls().playNext();

this plays the media.

**Comment by caprica** [comment]
So I knocked up this class:
```
import uk.co.caprica.vlcj.player.component.EmbeddedMediaListPlayerComponent;

import javax.swing.*;

public class BasicEmbeddedMediaListPlayerComponentTest {

    private final EmbeddedMediaListPlayerComponent mediaListPlayerComponent;

    public static void main(String[] args) throws Exception {
        args = new String[]{"https://www.youtube.com/watch?v=hplXXJDCyLw"};
        final String mrl = args[0];

        BasicEmbeddedMediaListPlayerComponentTest app = new BasicEmbeddedMediaListPlayerComponentTest();
        app.start(mrl);

        Thread.currentThread().join();
    }

    private BasicEmbeddedMediaListPlayerComponentTest() {
        JFrame frame = new JFrame("vlcj Media Player Component Test");

        mediaListPlayerComponent = new EmbeddedMediaListPlayerComponent();
        frame.setContentPane(mediaListPlayerComponent);

        frame.setLocation(100, 100);
        frame.setSize(1050, 600);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);
    }

    private void start(String mrl) {
        mediaListPlayerComponent.mediaListPlayer().list().media().add(mrl);
        System.out.println(mediaListPlayerComponent.mediaListPlayer().list().media().mrl(0));

        mediaListPlayerComponent.mediaListPlayer().controls().playNext();
    }
}
```
Prints the MRL, no exception.

**Comment by caprica** [comment]
The media list stuff is not pretty, partly because of the native API, and it is not impossible there's bugs in usage like your example:
```
mediaListPlayer.list().setMediaList(mediaList.newMediaListRef());
```
I don't mind looking into specific bugs so long as there's a self-contained runnable example posted. 

Please open new issues if you find problems.

**Comment by sense42** [comment]
your example works, but only when accessing through the list with a known index. 
I was not able to get the index of a played file. 

`import javax.swing.JFrame;

import uk.co.caprica.vlcj.player.component.EmbeddedMediaListPlayerComponent;

public class BasicEmbeddedMediaListPlayerComponentTest {

    private final EmbeddedMediaListPlayerComponent mediaListPlayerComponent;

    public static void main(String[] args) throws Exception {
        args = new String[]{"https://www.youtube.com/watch?v=hplXXJDCyLw"};
        final String mrl = args[0];

        BasicEmbeddedMediaListPlayerComponentTest app = new BasicEmbeddedMediaListPlayerComponentTest();
        app.start(mrl);

        Thread.currentThread().join();
    }

    private BasicEmbeddedMediaListPlayerComponentTest() {
        JFrame frame = new JFrame("vlcj Media Player Component Test");

        mediaListPlayerComponent = new EmbeddedMediaListPlayerComponent();
        frame.setContentPane(mediaListPlayerComponent);

        frame.setLocation(100, 100);
        frame.setSize(1050, 600);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);
    }

    private void start(String mrl) {
        mediaListPlayerComponent.mediaListPlayer().list().media().add(mrl);
        System.out.println(mediaListPlayerComponent.mediaListPlayer().mediaPlayer().mediaPlayer().media().info().mrl());
        
        mediaListPlayerComponent.mediaListPlayer().controls().playNext();
    }
}`

this is the way you said the actual played mrl should be given. 
No success. NullPointerException.

**Comment by caprica** [comment]
I gave you an example off the top of my head to get the MRL. I couldn't remember for sure.
I also gave you a full code example that worked and got the MRL without an NPE.
So, OK, your code fragment below gives you an NPE, but do you really need to do it that way?
```
System.out.println(mediaListPlayerComponent.mediaListPlayer().mediaPlayer().mediaPlayer().media().info().mrl());
```
On the face of it, it looks like that shouldn't give an NPE, but I don't think you have to do it that way.
Also, that bug you're describing is new, and nothing to do with this particular issue.
