### ISSUE TITLE
Github-pages not linking to 3.1.0 javadoc

### ISSUE THREAD

**Issue by masterX244** [caprica/vlcj#284]
the LInk to the docs doesnt show the 3.1.0 javadoc link even though it exists already

**Comment by caprica** [comment]
Which link are you talking about?

i.e. on which page is the link?

**Comment by masterX244** [comment]
http://caprica.github.io/vlcj/
you tell that VLCJ 3.0.0 is latest while the readme tells VLCJ 3.1.0 is latest

**Comment by caprica** [comment]
I just spotted it.

Thanks for reporting it.

Should be OK now.
