### ISSUE TITLE
vlc_xlib_init: Xlib not initialized for threads

### ISSUE THREAD

**Issue by olaseimpi** [caprica/vlcj#293]
Hi,

I'm using vlcj 2.4.1 because I could not use the newer 3.x version at the time.
(We use the VLC generally available in Linux distributions, but we don't want to require users to have the very latest version. Ubuntu before 14.10 did have an older VLC; only since Ubuntu 14.10 it has VLC version 2.2.0-pre2 Weatherwax (2.2.0-pre1-15-g5178b24)).

Since recently, and I think it is since the update to Ubuntu 14.10 with VLC 2.2.0-pre2, I get these messages:
```
../../../include/vlc_xlib.h:46:vlc_xlib_init: Xlib not initialized for threads.
This process is probably using LibVLC incorrectly.
Pass "--no-xlib" to libvlc_new() to fix this.
[00007f31acc6f1d8] vdpau_avcodec generic error: Xlib is required for VDPAU
```
I do use multiple players, and until recently I never got such messages. The players mostly play fine.
I have tried adding the --no-xlib option, and it does supporess the "vlc_xlib_init" complaint, but not the VDPAU complaint (perhaps not surprisingly).

As an experiment, I built a version of my program with vlcj 3.1.0, but that didn't fix the issue: the same messages were still there. I got even more complaints: several copies of the text "This object event manager doesn't know about 'Unknown Event' events" (without newline).

Is there anything I can do? Somehow call XInitThreads() if I can somehow detect running on X (and if so, how and how?) Although currently we use vlc and vlcj only when the program runs on Linux, I tried it on the Macintosh too and in principle, it works there as well.

See https://tla.mpi.nl/tools/tla-tools/elan/ for a download of the program.

**Comment by caprica** [comment]
I noticed this recently too, it definitely was not always like this, and I mean for like 5+ years it was not like this. It was sometimes needed for multiple video players, but never for single video players (until now).

vlcj already provides a workaround for this, and it is used in the all the vlcj test examples:

```
LibXUtil.initialise();
```

The `LibXUtil` class is in the `uk.co.caprica.vlcj.runtime.x` package.

This will be safely ignored on platforms where it's not supported.

**Comment by caprica** [comment]
Your "Unknown Events" errors with vlcj 3.1.0 are to be expected - vlcj 3.x requires as a baseline a more up-to-date version of VLC.

**Comment by olaseimpi** [comment]
Ah great, thanks! Apparently the place where I put the "LibXUtil.initialise();" was early enough to be effective since both the complaints seem to be gone.
And I won't worry about the Unknown Events then.
Thanks!

**Comment by caprica** [comment]
Well, you say you won't worry about the Unknown Events, I really would not recommend running newer versions of vlcj with older versions of VLC - some strange things might happen...

The LibXUtil initialise call must go before LibVLC is loaded, I always put it in a static block inside my main application class.

I've never actually seen any real problem due to that warning message, but this workaround makes it moot.

**Comment by olaseimpi** [comment]
Ok, I meant that I was going to switch back to vlcj 2.4.1, and then I certainly won't have vlc version issues.
I put the call to LibXUtil.initialise(); in a static block in my "VLCJMediaPlayer" class which is the only class that uses vlcj, so that should be timely enough. I was a bit concerned that it would probably also need to run before the first Xlib call is made (the manpage for XInitThreads(3) says so). Some classes in this program are loaded dynamically so it is sometimes a bit difficult to predict when static blocks will run.
If this proves to be an issue in the future, I can move the call.
