### ISSUE TITLE
The vlcj-3.1.0 project crashed with JDK1.7

### ISSUE THREAD

**Issue by che302956637** [caprica/vlcj#295]
I have download the vlcj-vlcj-3.1.0.zip, then use jna-4.1.0.jar and jna-platform-4.1.0.jar.

When I run the project(TestMediaListPlayer.java) in the Eclipse,
In windows, with JDK7_32bit, it works.
In ubuntu, with JDK1.6_32bit or JDK1.6_64bit or JDK1.7_64bit, it works.
But, in ubuntu, with JDK1.7_32bit, it crashed!

Please help to see the issue, Thanks!

**Comment by caprica** [comment]
Maybe #62 relates.

In any case, you have not posted enough information for anyone to realistically help you. How about vlcj logs with -Dvlcj.log=DEBUG, and VLC native logs with "-vvv"...

**Comment by che302956637** [comment]
Sorry for it! It really works if I remove:
/usr/local/lib/vlc/lua/meta/reader/filename.luac
Thanks a lot !...

**Comment by caprica** [comment]
Well, don't be sorry, there's a real problem here, but it's not a problem in vlcj.

Fixing it the way you did is ok, but you need to know that if you delete those LUA files then things like playlists (e.g. YouTube) probably won't work.

**Comment by frankred** [comment]
Same with me with Windows8 and Java8. The problem is in libvlc right? A workarround in vlcj would be great =)

**Comment by caprica** [comment]
The problem is not in LibVLC.

I wrote a "pure" C test-case that simply executes a compiled LUA script. It crashes on Ubuntu 32-bit - no vlcj, no LibVLC and not even Java involved.

A workaround in vlcj is impossible based on my current analysis of the problem.

**Comment by che302956637** [comment]
I don't know if it could work well on Java8, please see the release notes:

At least JDK 1.6 is required, and it works without changes on JDK 1.7.
Version 3.0.0+ of vlcj requires version 2.1.0+ of vlc, earlier versions of vlc are not supported and will not work.
Version 3.0.0+ of vlcj requires version 4.0.0+ of JNA.

And the root case for me is just LUA.

**Comment by caprica** [comment]
vlcj works generally with Java8.

I don't test on Windows8.

I am pretty confident that @frankred's problem is not the same as this issue.

**Comment by frankred** [comment]
I will investigate soon, maybe tomorrow. Then I can send you the native log.

**Comment by che302956637** [comment]
@caprica 
There is another trouble, when I use TestMediaListPlayer.java
(jdk7_32bit on Win7_32bit or Ubuntu 14.04.1_32bit, jna-3.5.1.jar, platform-3.5.1.jar)

If I add these code in the end:
Thread.sleep(3000);
mediaListPlayer.stop();
mediaList.removeMedia(0); //change the mediaList and replay
mediaListPlayer.play();

"mediaList.removeMedia(0)" or "mediaList.clear()", it will be crashed!
(The mediaList.size() is not zero)

**Comment by caprica** [comment]
That's a different issue, please don't mix different problems in the same issue.
