### ISSUE TITLE
Crashes on 32 bit linux targets when playback ogg, flac or video

### ISSUE THREAD

**Issue by Joe-Merten** [caprica/vlcj#300]
I'm currently playing around with vlcj for a spare time project.
I'd compiled your source (git rev 20e63beece758dc23695e34f65114bc0fa3330da) to do some tests.
My main build & testmachine is Kubuntu 14.04 32 bit, but I do also perform tests on some 64 Bit Linux, OSX and Windows.

Running your PlayerTest, I got the following output at startup:

    vlcj: (Info.java:70)                                 | INFO  | vlcj: 3.2.0-SNAPSHOT
    vlcj: (Info.java:71)                                 | INFO  | java: 1.7.0_65 Oracle Corporation
    vlcj: (Info.java:72)                                 | INFO  | java home: /usr/lib/jvm/java-7-openjdk-i386/jre
    vlcj: (Info.java:73)                                 | INFO  | os: Linux 3.13.0-44-generic i386
    vlcj: (LibVlcFactory.java:164)                       | INFO  | vlc: 2.2.0-rc2 Weatherwax, changeset 2.2.0-rc1-118-g22fda39
    vlcj: (LibVlcFactory.java:165)                       | INFO  | libvlc: libvlc.so
    vlcj: (TestPlayer.java:105)                          | INFO  |   version: 2.2.0-rc2 Weatherwax
    vlcj: (TestPlayer.java:106)                          | INFO  |  compiler: gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1)
    vlcj: (TestPlayer.java:107)                          | INFO  | changeset: 2.2.0-rc1-118-g22fda39
    vlcj: (LibVlcFactory.java:164)                       | INFO  | vlc: 2.2.0-rc2 Weatherwax, changeset 2.2.0-rc1-118-g22fda39
    vlcj: (LibVlcFactory.java:165)                       | INFO  | libvlc: libvlc.so
    This object event manager doesn't know about 'Unknown Event' eventsThis object event manager doesn't know about 'Unknown Event' eventsThis object event manager doesn't know about 'Unknown Event' events

and when I try to play e.g. a ogg audio file:

    # A fatal error has been detected by the Java Runtime Environment:
    #
    #  SIGSEGV (0xb) at pc=0xb76709b8, pid=15804, tid=1712524096
    #
    # JRE version: OpenJDK Runtime Environment (7.0_65-b32) (build 1.7.0_65-b32)
    # Java VM: OpenJDK Server VM (24.65-b04 mixed mode linux-x86 )
    # Derivative: IcedTea 2.5.3
    # Distribution: Ubuntu 14.04 LTS, package 7u71-2.5.3-0ubuntu0.14.04.1
    # Problematic frame:
    # C  [libc.so.6+0x1289b8]  _IO_file_underflow+0x68
    #
    # Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
    #
    # An error report file with more information is saved as:
    # /D/git/Joe/vlcj/hs_err_pid15804.log
    #
    # If you would like to submit a bug report, please include
    # instructions on how to reproduce the bug and visit:
    #   http://icedtea.classpath.org/bugzilla

- the crash occours, when I try to play e.g. ogg, flac, alac or video files
- mp3 playback works
- tested on some different 32 and 64 bit ubuntu distributions (ubuntu, ubuntu-gnome, kubuntu, xubuntu, lubuntu, mate)
- all 32 bit machines had crashes, all 64 bit installations are working well
- hmm, I'll try to attach the hs_err_pid15804.log to this ticket …

Cheers, Joe

Stepping throu your code I see the crash raising within DefaultMediaPlayer.play() when calling libvlc.libvlc_media_player_play().

**Comment by Joe-Merten** [comment]
Seems that I cannot upload logfiles here, but only pictures. So for a hack, I just renamed the logfile to a png.

![hs_err_pid15804 log](https://cloud.githubusercontent.com/assets/6552470/5886700/371eadf2-a3ad-11e4-8cf7-cfbe1f23834b.png)

**Comment by Joe-Merten** [comment]
Seems that I cannot upload logfiles here, but only pictures. So for a hack, I just renamed the logfile to a png.
![hs_err_pid15804 log](https://cloud.githubusercontent.com/assets/6552470/5886715/dc0acca6-a3ad-11e4-9e04-7e43a92c00be.png)

**Comment by caprica** [comment]
The first problem is this:

This object event manager doesn't know about 'Unknown Event' eventsThis object event manager doesn't know about 'Unknown Event' eventsThis object event manager doesn't know about 'Unknown Event' events

This is because the OS you are using includes a pre-release version of VLC 2.2.0. VLC 2.2.0 is still being developed and has added new events, which the latest vlcj code requires.

Having said that, you should be able to ignore that warning.

**Comment by caprica** [comment]
For your crash see #62.

There is no perfect solution for that issue.

**Comment by caprica** [comment]
If you want to post logs, just post them inline in your comment. Faking it with a PNG just makes it look like a broken image, or if you really must, link to Pastebin or something like that.

**Comment by caprica** [comment]
I'm going to close this, not because it isn't an issue as it clearly is, but for the same reasons in the other linked issue - there's nothing that can be changed in Java code in vlcj to prevent this crash on a 32-bit Linux platform I'm afraid.
