### ISSUE TITLE
Curious »This object event manager doesn't know about 'Unknown Event' events«

### ISSUE THREAD

**Issue by Joe-Merten** [caprica/vlcj#301]
Running your PlayerTest (git rev 20e63beece758dc23695e34f65114bc0fa3330da) on a linux machine gives me the following output at startup:

    vlcj: (Info.java:70)                                 | INFO  | vlcj: 3.2.0-SNAPSHOT
    vlcj: (Info.java:71)                                 | INFO  | java: 1.7.0_65 Oracle Corporation
    vlcj: (Info.java:72)                                 | INFO  | java home: /usr/lib/jvm/java-7-openjdk-i386/jre
    vlcj: (Info.java:73)                                 | INFO  | os: Linux 3.13.0-44-generic i386
    vlcj: (LibVlcFactory.java:164)                       | INFO  | vlc: 2.2.0-rc2 Weatherwax, changeset 2.2.0-rc1-118-g22fda39
    vlcj: (LibVlcFactory.java:165)                       | INFO  | libvlc: libvlc.so
    vlcj: (TestPlayer.java:105)                          | INFO  |   version: 2.2.0-rc2 Weatherwax
    vlcj: (TestPlayer.java:106)                          | INFO  |  compiler: gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1)
    vlcj: (TestPlayer.java:107)                          | INFO  | changeset: 2.2.0-rc1-118-g22fda39
    vlcj: (LibVlcFactory.java:164)                       | INFO  | vlc: 2.2.0-rc2 Weatherwax, changeset 2.2.0-rc1-118-g22fda39
    vlcj: (LibVlcFactory.java:165)                       | INFO  | libvlc: libvlc.so
    This object event manager doesn't know about 'Unknown Event' eventsThis object event manager doesn't know about 'Unknown Event' eventsThis object event manager doesn't know about 'Unknown Event' events

I wonder about the output of "This object event manager doesn't know about 'Unknown Event' events" (3 times).
Stepping throu your code I see that this was generated inside of `DefaultMediaPlayer.registerEventListener()` during the calls to `libvlc.libvlc_event_attach()`, for the 3 events `libvlc_MediaPlayerESAdded`, `libvlc_MediaPlayerESDeleted` and `libvlc_MediaPlayerESSelected`. 

Well, this output won't really scares me - it's just a bit ugly on the console.
I don't see such output on my mac, were vlc 2.1.5 is installed.

Cheers, Joe

**Comment by caprica** [comment]
As per your other issue #300, that is happening because you are using a pre-release version of VLC 2.2.0 that is not up to date with vlc-git. Current vlcj-git tracks current vlc-git very closely, and there is a new event which you don't have yet.

For the time being it should be safe to ignore that warning.

Or wait for the final release of VLC 2.2.0.

**Comment by caprica** [comment]
The situation with VLC 2.1.5 is different, because vlcj checks which version 2.2.0 vs 2.1.0 before deciding which events to register.

In the instant case, vlcj looks for version 2.2.0 and finds it... so what else can it do.
