### ISSUE TITLE
Cannot execute PlayerTest from jar

### ISSUE THREAD

**Issue by Joe-Merten** [caprica/vlcj#302]
Successfully compiled vlcj (git rev 20e63beece758dc23695e34f65114bc0fa3330da), just got some javadoc warnings:

    $ mvn  -Dmaven.test.skip=true clean install  
    [INFO] Scanning for projects...
    [INFO]                                                                         
    [INFO] ------------------------------------------------------------------------
    [INFO] Building vlcj 3.2.0-SNAPSHOT
    [INFO] ------------------------------------------------------------------------
    [INFO] 
    [INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ vlcj ---
    [INFO] Deleting /home/joe/git/vlcj/target
    [INFO] 
    [INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ vlcj ---
    [INFO] 
    [INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ vlcj ---
    [INFO] Using 'UTF-8' encoding to copy filtered resources.
    [INFO] Copying 1 resource
    [INFO] 
    [INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ vlcj ---
    [INFO] Changes detected - recompiling the module!
    [INFO] Compiling 317 source files to /home/joe/git/vlcj/target/classes
    [WARNING] /home/joe/git/vlcj/src/main/java/uk/co/caprica/vlcj/player/DefaultMediaPlayer.java: Some input files use or override a deprecated API.
    [WARNING] /home/joe/git/vlcj/src/main/java/uk/co/caprica/vlcj/player/DefaultMediaPlayer.java: Recompile with -Xlint:deprecation for details.
    [INFO] 
    [INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ vlcj ---
    [INFO] Not copying test resources
    [INFO] 
    [INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ vlcj ---
    [INFO] Not compiling test sources
    [INFO] 
    [INFO] --- maven-surefire-plugin:2.10:test (default-test) @ vlcj ---
    [INFO] Tests are skipped.
    [INFO] 
    [INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ vlcj ---
    [INFO] Building jar: /home/joe/git/vlcj/target/vlcj-3.2.0-SNAPSHOT.jar
    [INFO] 
    [INFO] --- maven-jar-plugin:2.4:test-jar (default) @ vlcj ---
    [INFO] Skipping packaging of the test-jar
    [INFO] 
    [INFO] --- maven-source-plugin:2.2.1:jar-no-fork (attach-sources) @ vlcj ---
    [INFO] Building jar: /home/joe/git/vlcj/target/vlcj-3.2.0-SNAPSHOT-sources.jar
    [INFO] 
    [INFO] --- maven-source-plugin:2.2.1:test-jar-no-fork (attach-sources) @ vlcj ---
    [INFO] Building jar: /home/joe/git/vlcj/target/vlcj-3.2.0-SNAPSHOT-test-sources.jar
    [INFO] 
    [INFO] --- maven-javadoc-plugin:2.9.1:jar (attach-javadocs) @ vlcj ---
    [INFO] 
    6 warnings
    [WARNING] Javadoc Warnings
    [WARNING] /home/joe/git/vlcj/src/main/java/uk/co/caprica/vlcj/binding/LibVlc.java:614: warning - Tag @see:illegal character: "123" in "{@link libvlc_media_parse_flag_t}"
    [WARNING] /home/joe/git/vlcj/src/main/java/uk/co/caprica/vlcj/binding/LibVlc.java:614: warning - Tag @see:illegal character: "64" in "{@link libvlc_media_parse_flag_t}"
    [WARNING] /home/joe/git/vlcj/src/main/java/uk/co/caprica/vlcj/binding/LibVlc.java:614: warning - Tag @see: reference not found: {@link libvlc_media_parse_flag_t}
    [WARNING] /home/joe/git/vlcj/src/main/java/uk/co/caprica/vlcj/binding/LibVlc.java:1723: warning - @param argument "mp" is not a parameter name.
    [WARNING] /home/joe/git/vlcj/src/main/java/uk/co/caprica/vlcj/binding/LibVlc.java:1723: warning - @param argument "module" is not a parameter name.
    [WARNING] /home/joe/git/vlcj/src/main/java/uk/co/caprica/vlcj/binding/LibVlc.java:1723: warning - @param argument "device_id" is not a parameter name.
    [INFO] Building jar: /home/joe/git/vlcj/target/vlcj-3.2.0-SNAPSHOT-javadoc.jar
    [INFO] 
    [INFO] --- maven-assembly-plugin:2.4:attached (user_distribution) @ vlcj ---
    [INFO] Reading assembly descriptor: src/main/assembly/dist.xml
    [INFO] Building tar: /home/joe/git/vlcj/target/vlcj-3.2.0-SNAPSHOT-dist.tar.gz
    [INFO] Building zip: /home/joe/git/vlcj/target/vlcj-3.2.0-SNAPSHOT-dist.zip
    [INFO] 
    [INFO] --- maven-install-plugin:2.3:install (default-install) @ vlcj ---
    [INFO] Installing /home/joe/git/vlcj/target/vlcj-3.2.0-SNAPSHOT.jar to /home/joe/.m2/repository/uk/co/caprica/vlcj/3.2.0-SNAPSHOT/vlcj-3.2.0-SNAPSHOT.jar
    [INFO] Installing /home/joe/git/vlcj/pom.xml to /home/joe/.m2/repository/uk/co/caprica/vlcj/3.2.0-SNAPSHOT/vlcj-3.2.0-SNAPSHOT.pom
    [INFO] Installing /home/joe/git/vlcj/target/vlcj-3.2.0-SNAPSHOT-sources.jar to /home/joe/.m2/repository/uk/co/caprica/vlcj/3.2.0-SNAPSHOT/vlcj-3.2.0-SNAPSHOT-sources.jar
    [INFO] Installing /home/joe/git/vlcj/target/vlcj-3.2.0-SNAPSHOT-test-sources.jar to /home/joe/.m2/repository/uk/co/caprica/vlcj/3.2.0-SNAPSHOT/vlcj-3.2.0-SNAPSHOT-test-sources.jar
    [INFO] Installing /home/joe/git/vlcj/target/vlcj-3.2.0-SNAPSHOT-javadoc.jar to /home/joe/.m2/repository/uk/co/caprica/vlcj/3.2.0-SNAPSHOT/vlcj-3.2.0-SNAPSHOT-javadoc.jar
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD SUCCESS
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 9.358s
    [INFO] Finished at: Sat Jan 24 10:11:11 CET 2015
    [INFO] Final Memory: 23M/340M
    [INFO] ------------------------------------------------------------------------
 
But after them, I failed to start `TestPlayer`:

    $ java -jar target/vlcj-3.2.0-SNAPSHOT-tests.jar 
    Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/jna/NativeLong
            at uk.co.caprica.vlcj.test.VlcjTest.<clinit>(VlcjTest.java:76)
    Caused by: java.lang.ClassNotFoundException: com.sun.jna.NativeLong
            at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
            at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
            at java.security.AccessController.doPrivileged(Native Method)
            at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
            at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
            ... 1 more

and the same output when I try like this:

    java -cp target/vlcj-3.2.0-SNAPSHOT-tests.jar uk.co.caprica.vlcj.test.basic.TestPlayer

When running from within eclipse (using a selfmade trivial run configuration), the TestPlayer starts as expected. What do I wrong?

Tested on Kubuntu 14.04 both 32 bit and 64 bit.

When running maven including test execution (without `-Dmaven.test.skip=true`), all tests are passed.

**Comment by caprica** [comment]
I can live with Javadoc warnings, that's a separate issue.

The vlcj jar has a manifest classpath that expects the dependencies (JNA and Platform) to be in the same directory as the vlcj jar. 

After a maven build, the target root directory does not contain the JNA dependencies.

You're supposed to unzip the distribution package (zip or tgz), which includes the dependencies, into an installation directory and then run the vlcj jar inside there.

**Comment by Joe-Merten** [comment]
Yep, that works.
But … now build & trying this bleeding edge vlcj 3.2.0 on my 64 bit Kubuntu causes also crashes when playing video (for both local files and youtube, looks a bit like #300 and #62). Were in contrast my own application (which based on vlcj 3.1.0) works without those problems.

**Comment by caprica** [comment]
Well, my primary development platform is 64-bit 14.10 Kubuntu, vlc-git (always latest version) and vlcj-3.2.0 snapshot and I see absolutely no crashes, not on local files and not on YouTube. In fact, I just tested it now and it worked fine.

Please do not conflate issues. If you have a real crash report, then that's nothing to do with this issue, please raise a new issue instead and post full logs (vlcj log and native VLC log) and if it's your own code then you need to post a minimal test case that triggers the crash.

**Comment by bpallavi** [comment]
In Streamhttp class i am getting error for  line "import uk.co.caprica.vlcj.test.VlcjTest;"
if i comment this line and run the code it is giving me exception as "Exception in thread "main" java.lang.NoClassDefFoundError: ch/qos/logback/core/joran/spi/JoranException"
How do i ressolve this error?

**Comment by caprica** [comment]
Add the dependant jar file to your class path.

It's much simpler if you just check out the entire project into your IDE.

But why ressurect this old issue?!?

**Comment by bpallavi** [comment]
thank you its working now.
