### ISSUE TITLE
Linux NativeLibrary.setSearchPath not working

### ISSUE THREAD

**Issue by uyt95** [caprica/vlcj#313]
I'm using following line of code at the start of my program:
NativeLibrary.addSearchPath(RuntimeUtil.getLibVlcLibraryName(), libpath);
libpath is a string with the path to the folder that contians libvlc, libvlccore and the plugins folder.

But when I run the program, following error:
Exception in thread "main" java.lang.RuntimeException: Failed to load the native library.
The error was "Unable to load library 'vlc' ...

The same program works fine on both 32 and 64 versions of Windows, but fails on Linux (Debian 64 bits version and Ubuntu 32 bits version).
When VLC is installed, vlcj works fine but when it isn't it stops working on Linux.
I included libvlc.so, libvlccore.so and the plugins folder in the folder that I set the searchpath to.

Does anybody have the same problem or a solution for this problem?

**Comment by caprica** [comment]
You can't just copy shared objects around to different directories on Linux and expect it to work. 

In Linux, when you build something that creates shared libraries, the location of those shared library dependencies is "baked in". If you use e.g. the "strings" command on those shared objects you will be able to see the baked in paths.

You have to tell the runtime-linker how to resolve those dependencies.

So NativeLibrary.setSearchPath will tell JNA where to load the shared object from, but it will do *nothing* about run-time linking of that shared object.

You can try and set the LD_LIBRARY_PATH environment variable. To the directory that contains the libvlc.so files. You must also ensure that the plugins directory structure is what VLC expects.

IMHO, the "correct" way to "install" a vlcj application on Linux is to build a package, like an RPM, DEB or whatever, and declare LibVLC as a package dependency. This will ensure that all of VLC's dependencies are also brought in.

**Comment by uyt95** [comment]
Thank you for the quick reply, I have been trying to solve this problem for the past 3 days. So it is impossible to deliver my application as a jar file with a lib folder that contains the shared libraries?

**Comment by caprica** [comment]
Well it's "impossible" to just copy the shared objects into your application folder and have it just work.

What happens for example if you redistribute all of VLC, the shared objects and all the plugins... well are you going to redistribute all of the transitive dependencies of all the plugins too!? Can you even know what they are? Or are you just assuming they're available already on your end-user Linux installation? If you are going to assume all of the transitive dependencies are already installed, you might as well assume VLC is already installed.

This is why the correct answer on Linux is to use an OS package manager package like RPM or DEB.

**Comment by uyt95** [comment]
Ok, thank you for the explenation, I will look into your solution.

**Comment by caprica** [comment]
Personally, I always just pre-install VLC, but an actual packaging script for [UKu]buntu would be really useful.

**Comment by caprica** [comment]
See #314.

**Comment by caprica** [comment]
The vlcj pom.xml now uses the jdeb maven plugin to build a .deb package for vlcj.

It's not perfect, but if you want to down this route it might give you a head start with your own application.
