### ISSUE TITLE
Youtube videos returning an error?

### ISSUE THREAD

**Issue by Lordmau5** [caprica/vlcj#321]
http://puu.sh/fMeC9/045035f5d3.txt

It's trying to play the video, but is going from
*Opening -> Playing -> Error -> Ending -> Idle*

Did I miss out on some update?
Do I have to supply some arguments to the *playMedia* method?

VLCJ Version: 3.2.0
VLC Version: 2.1.5

**Comment by caprica** [comment]
Probably what happened is YouTube changed their HTML page.

YouTube video in VLC works by scraping the HTML looking for the streaming URL. This is implemented in the VLC LUA scripts.

You will probably need to wait until there is a new version of VLC that provides updated LUA scripts.

I'm going to close this issue because there's nothing that can be done in vlcj to resolve this.

**Comment by caprica** [comment]
I just tested this with vlc-git and it works.

The version of vlcj is irrelevant to this issue.

So I can only suggest you look for an updated VLC 2.1.x and hope that fixes it.

**Comment by Lordmau5** [comment]
I just played around with 2.1.5 and the code of your FallbackPlayer. That worked fine, so we know that it's not 2.1.5 that caused it.

Apparently, my server is running 2.1.4 and does **not** work...
Currently trying to update it to either 2.1.5 (which I doubt will be findable) or 3.0.0.

Will report back then.

**Comment by caprica** [comment]
Well, I know for sure this is not a vlcj problem.

**Comment by caprica** [comment]
VLC 2.1.5 is the latest release in that series.

VLC 2.2.0 is not released yet, it's been at RC2 for something like three months.

VLC 3.0.0 is quite some distance away I expect since major releases tend to be >1 year apart.

**Comment by Lordmau5** [comment]
I finally got it working, through very stupid methods. But hey, if it works - it works :)

Though, my console is being spammed *to death*.
Only on the Ubuntu server, not on my local PC (Windows):

http://puu.sh/fMwTD/cd1021e80e.txt

Is *this* error on your end now, perhaps?

~ Greets.

**Comment by caprica** [comment]
Indeed that is my bug.
