### ISSUE TITLE
Get audio visualisation data from vlcj

### ISSUE THREAD

**Issue by frankred** [caprica/vlcj#332]
Is there somehow the possibility to get the audio signal visualization data from vlcj?

Background:
I have a LED Wall connected with usb and want to visualize the audio signal from my vlcj application (https://github.com/frankred/jSona).  Like this...  
![Audio Signal](http://rapid-img.de/images/4a088476.jpg)

Is this somehow possible or would it be better to grep the signal via the OS or libVLC.

Sorry for this generally question. 

PS: Greate project!

**Comment by caprica** [comment]
You can use a DirectAudioPlayer to get the raw sample data.

The problem is if you do that, there is no 'pass-through' to actually hear the audio, so you have to play it yourself using JavaSound or some other Java API. It can be done. There are examples in the vlcj test sources.

Search the vlcj test sources for JavaSoundTest.java.

You don't have to use JavaSound, you can use any API you want, but the point is that your application must play the audio.

**Comment by caprica** [comment]
If you want to play video at the same time, you may have to wait until #184. But that is quite a bit more work and is not scheduled to be done any time soon.

**Comment by frankred** [comment]
K thank you, maybe I can play my music twice on the same time. With the DirectAudioPlayer to grep the sample data and with the help of the regular Mediaplayer?

**Comment by caprica** [comment]
But it won't be synchronised.

The thing is, if you really wanted to do this now you could extend the DefaultMediaPlayer and implement the audio callback stuff yourself (the MediaPlayer interface provides everything you need). In that way you could do it with one media player.

The difficulty in me doing it right now in vlcj is that it's kinda hard to do it a nice clean way while preserving backwards API compatibility. If you do it yourself, you have no such considerations.

If you only have audio, and not video, just use the direct audio player and use JavaSound to play the audio - it works just fine and there's a vlcj sample that does it. It's dead easy, there's no reason to complicate matters by using another media player.

The only problem you really have is if you need audio and video at the same time.  If so, if it were my app right now I'd do what I said and extend the DefaultMediaPlayer and re-implement the audio callback stuff, and use JavaSound, it's not *that* hard.

**Comment by caprica** [comment]
Actually I just did a quick test. It seems in principle it should be possible for a direct audio player to have its video embedded too, it's just right now it's not possible with the vlcj API. I might be able to do something quickly here.

**Comment by caprica** [comment]
Try 518f93dca7efecdfe834d33cabc0a8bbd003bd90 and see if it works for you.

Part of that commit is a new test case that shows embedding video in a JFrame and playing audio samples via JavaSound.

In your case, the idea is that you do your analysis on the raw sample buffer before sending the samples to JavaSound.

**Comment by caprica** [comment]
Can you tell me what hardware you are using for your USB "LED Wall", and do you know if works on Linux?

**Comment by frankred** [comment]
Thank you for the commit I will check that now: 

The Hardware setup is the following. https://www.tinkerforge.com/en/shop/kits/blinkenlights-base-kit.html. Tinkerforge has an awesome API for all common languages and it runs on all commons OS.

**Comment by caprica** [comment]
Wow... thanks for the link.

**Comment by frankred** [comment]
Ah ok thank you for the EmbeddedJavaSoundTest.java. Do you know something about the byte data? What format it has and how I can analyse it?

**Comment by caprica** [comment]
The sound format is whatever you configure it to be, as long as it is supported by VLC.

The example I wrote uses 2 channel 44.1kHz S16N PCM (I think) which is a signed 16-bit integer format I presume, the S16N part is defined by VLC. Nothing says you have to use that format, use whatever is most comfortable for your DSP algorithm, as long as VLC supports it.

DSP is a science all of its own and is outside the scope of vlcj, I can't help you with that.

**Comment by frankred** [comment]
Ok thank you for that information, now I got it. Yeah I think I have to make a research about that topic. If I have any results I will post it here.

**Comment by caprica** [comment]
By the way, your project looks really nice.

**Comment by frankred** [comment]
Thank you!
