### ISSUE TITLE
Return null rather than throw exception

### ISSUE THREAD

**Issue by caprica** [caprica/vlcj#345]
Certain methods throw an exception with a null parameter, particular examples are when calling a method that expects there to be a current media.

This can be problematic and I would prefer to return null, or false or whatever, instead.

Unfortunately, this will change the public API.

**Comment by caprica** [comment]
Actually, returning null causes problems for the remoting library used by vlcj-pro. It is much more preferable to e.g. return an empty list rather than null. So part of this task should address this returning null issue as well.

**Comment by AlihassanProgrammer** [comment]
if you a function which return some string then function throws null

**Comment by caprica** [comment]
Some of these have been changed to return null as part of the major refactoring under #690.

**Comment by caprica** [comment]
I will just address any remaining instances of this as they are discovered.
