### ISSUE TITLE
plugins path in mac os x

### ISSUE THREAD

**Issue by Abu-Abdullah** [caprica/vlcj#349]
Hi,

in Mac OSX, VLCJ startup is showing "No plugins found" with an error that the path <libvlc-path>/vlc/plugins  is not available.

the path <libvlc-path> of libvlc.dylib is:
VLC.app\Contents\MacOS\lib

so the vlcj is expecting the plugin folder in:
VLC.app\Contents\MacOS\lib\vlc\plugins

but the correct plugin path is:
VLC.app\Contents\MacOS\plugins

I tried to set the env variable VLC_PLUGIN_PATH without success.

any support is appreciated.

**Comment by caprica** [comment]
vlcj does not load the plugins, vlcj loads (via JNA) the LibVLC native library. It is this LibVLC native library that loads  the plugins.

There must be something wrong with the VLC build on OSX.

Coincidentally, I was just reading this post which looks very similar:

https://forum.videolan.org/viewtopic.php?f=32&t=124521

**Comment by Abu-Abdullah** [comment]
OK thanks, i will try to look into VLC forms/documentation. 

I believe the path VLC_PLUGIN_PATH will work if it is done through the shell not in my java application itself but this will not help me since I'm trying to bundle the application and cannot find how to set env variable in Info.plist

in all cases, thanks for your quick support.

**Comment by caprica** [comment]
It really looks like a VLC build problem to me, a fixed version will probably come soon.

**Comment by caprica** [comment]
You could maybe try this right at the beginning of your application:

uk.co.caprica.vlcj.binding.LibC.INSTANCE.setenv("VLC_PLUGIN_PATH", "whatever");

No guarantees but it might work.

**Comment by Abu-Abdullah** [comment]
great, it is starting up now.

i believe you have updated the API in the latest version to:
setenv(String name, String value, int overwrite)

**Comment by caprica** [comment]
Wow, did that actually work? Can you please describe exactly what you did so I can include it in the FAQ?

**Comment by Abu-Abdullah** [comment]
this is the first 2 lines after main(String args[])

try
{
File programFolder = new File(AudioCataloger.class.getProtectionDomain().getCodeSource().getLocation().toURI().getPath()).getAbsolutePath()+"/";
uk.co.caprica.vlcj.binding.LibC.INSTANCE.setenv("VLC_PLUGIN_PATH", programFolder + "bin/VLC.app/Contents/MacOS/plugins", 1);

}
        catch(Exception ex){ex.printStackTrace();}

**Comment by caprica** [comment]
Thanks!

**Comment by caprica** [comment]
See #363.
