### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Zomis** [caprica/vlcj#354]
This repository links to http://www.capricasoftware.co.uk/projects/vlcj/index.html but the real link seems to be http://www.capricasoftware.co.uk/#/projects/vlcj

The same problem also exists on this wikipage: https://wiki.videolan.org/Java_bindings/

**Comment by caprica** [comment]
Thanks for the report, I fixed it.

I'm not really affiliated with VideoLAN and I don't maintain that Java Bindings page.

**Comment by Zomis** [comment]
The [repository link](https://github.com/caprica/vlcj) now points to http://www.capricasoftware.co.uk/#/projects/vlcj/index.html , which is also not correct. Remove `/index.html` at the end.

Correct is http://www.capricasoftware.co.uk/#/projects/vlcj

**Comment by caprica** [comment]
Fixed properly now, thanks.
