### ISSUE TITLE
VLC statistics is broken with VLC 2.2.0

### ISSUE THREAD

**Issue by dhirwin** [caprica/vlcj#358]
It looks like the VLC statistics are broken with the latest VLC 2.2.0 release. Using the uk.co.caprica.vlcj.test.stats.StatsTest test class, when I point to an RTSP streaming source and VLC 2.1.5 the statistics appear, however if I point to VLC 2.2.0 no statistics. 

Using Windows 7 64-bit, vlcj 3.5.0, Oracle Java 7_u67

Thanks,
Dave

**Comment by caprica** [comment]
See #356.

**Comment by caprica** [comment]
Should be fixed in VLC 2.2.1, hopefully soon to be released.

**Comment by caprica** [comment]
In case it's not clear, in VLC 2.2.0 you can make it work again by passing "--stats" when you create the media player factory.

**Comment by dhirwin** [comment]
Very good...thank you for the update and sorry for not seeing the existing #356 issue.

**Comment by caprica** [comment]
No problem... nice to have an easy ticket to clear... :-D
