### ISSUE TITLE
how to play online video by vlcj

### ISSUE THREAD

**Issue by lichuntingaq** [caprica/vlcj#360]
I have a question which need to be solved quickly.I want to play online video such as rtsp(Real Time Streaming Protocol) ,but i don't know how to use the vlcj to play it.Can you tell me how to use it in java.Thanks!

**Comment by caprica** [comment]
I really don't care how quickly you need your question solved.

Anyway:

    mediaPlayer.playMedia(rtspUrl);

If you don't know what the RTSP URL should be, search the VLC documentation.
