### ISSUE TITLE
RV32BufferFormat 3 byte with no pudding

### ISSUE THREAD

**Issue by gunther82** [caprica/vlcj#364]
Hi,
I'm using a DirectMediaPlayerComponent, and according to the documentation and the example provided I need to specify the BufferFormat to be returned for each frame.
vlcj provides the RV32BufferFormat class that has 24-bit BGR format with 8-bit of padding (no alpha) in a single plane. Is it possible to return just the 24-bit BGR, with no padding at all? I need this to convert it to a BufferedImage. 
If so, how I have to set the chroma, the pitches and the lines parameters of the BufferFormat? Can you please show me an example?

Thanks,
Claudio V.

**Comment by caprica** [comment]
Well, you *can* use that format already to create a `BufferedImage`, that's what the example player in vlcj uses.

If you really don't want to use this format, you have to find a compatible format that VLC knows about natively and configure the buffer accordingly.

Supposedly VLC can provide a buffer in RV24 format which would appear to be what you want. I don't know how to get a `BufferedImage` from that, the Javadoc at http://docs.oracle.com/javase/8/docs/api/java/awt/image/BufferedImage.html#TYPE_INT_RGB has stuff about needing to pre-multiply the values. Maybe there's some mileage in that, I've never done it.

**Comment by gunther82** [comment]
Thanks for the quick reply.
I wasn't complete in the description of my scenario. I need to put the BufferFormat I receive from vlcj in an OpenCV Mat, then process this Mat and finally convert it to a BufferedImage. 
Since I receive 4 bytes per pixel from vlcj with RV32BufferFormat (with pudding), I need to create the Mat with type "CvType.CV_8UC4", then I fill the Mat with the byte[] received:
```java
public void display(DirectMediaPlayer mediaPlayer, Memory[] nativeBuffers, BufferFormat buffForm) {
	int rows = buffForm.getHeight();
	int cols = buffForm.getWidth();

	byte[] bytepixels = new byte[(int) nativeBuffers[0].size()];
	nativeBuffers[0].getByteBuffer(0, nativeBuffers[0].size()).get(bytepixels, 0, (int)nativeBuffers[0].size());

	int type = CvType.CV_8UC4;
	Mat frame = new Mat(rows,cols,type);
	frame.put(0,0,bytepixels);
}
```

Then I do something with the Mat and finally I need to convert it to a BufferedImage, and I use this code:
```java
public static BufferedImage matToBufferedImage(Mat m) {
		int type = BufferedImage.TYPE_3BYTE_BGR;
		int bufferSize = m.channels() * m.cols() * m.rows(); //m.channels() is 4, the bytes per pixel
		byte[] b = new byte[bufferSize];
		m.get(0, 0, b); // get all the pixels
		BufferedImage image = new BufferedImage(m.cols(), m.rows(), type);
		final byte[] targetPixels = ((DataBufferByte) image.getRaster().getDataBuffer()).getData();
		System.arraycopy(b, 0, targetPixels, 0, b.length);
		return image;
	}
```
but if I use TYPE_3BYTE_BGR as type for the BufferedImage, the length of targetPixels array is smaller than the length of the Mat (that has 4 bytes per pixel), while if I use TYPE_4BYTE_ABGR the length is fine, but I guess that the position of the bytes for each pixel is wrong (I guess it writes the blue in the alpha position, the green in the blue position and the red in the green position), since I see everything rose.

So I guess that if I can obtain pixels of 3 bytes from vlc, I can use the type CV_8UC3 for the Mat and the type TYPE_3BYTE_BGR for the BufferedImage and everything should work fine.
My problem is that I don't know how to define the BufferFormat for returning just 3 bytes:

```java
BufferFormatCallback bufferFormatCallback = new BufferFormatCallback() {
    @Override
    public BufferFormat getBufferFormat(int sourceWidth, int sourceHeight) {
        //return new RV32BufferFormat(width, height); //old one
        return new BufferFormat("RV24", sourceWidth, sourceHeight, new int[sourceWidth*3], new int[sourceHeight]); //gives java.lang.IllegalArgumentException: pitches and lines must have equal length
    }
};
```

**Comment by caprica** [comment]
Your array initialisation syntax is wrong.
```
return new BufferFormat("RV24", sourceWidth, sourceHeight, new int[] {sourceWidth * 3}, new int[] {sourceHeight});
```

**Comment by gunther82** [comment]
Shame on me, I forgot the basics... thanks a lot!
Now I receive 3 bytes and everything seems to work fine.

However I have another small issue: I receive 32 bytes more than I expect. I'm sending frames at 640x480, 3 bytes per pixels, so I expect to receive 921600 bytes, but the size of the nativeBuffers[0] is 921632, and when I call 
```java
frame.put(0,0,bytepixels);
```
I get 
```java
java.lang.UnsupportedOperationException: Provided data element number (921632) should be multiple of the Mat channels count (3)
```

This happened also before with 4 bytes, but in that case the size was multiple, by coincidence, and it didn't complain.

I copied the byte[] received in one 32 bytes smaller, and then I use that one to fill the Mat and everything works fine, but knowing why I receive those 32 bytes more, and how I can avoid this, would save me an additional arraycopy.
Thanks in advance.

**Comment by caprica** [comment]
It's because of alignment. The native buffer must be aligned to a 32 byte boundary, this is a requirement of VLC.

In vlcj, it's used like this:
```
    nativeBuffers[i] = new Memory(pitchValues[i] * lineValues[i] + 32).align(32);
```
That is the only way, as far as I know, to ensure there is enough memory allocated and it is properly aligned.

**Comment by gunther82** [comment]
Ok, anyway I edited my comment with the solution to avoid the additional arraycopy.
Thanks so much for your help!
