### ISSUE TITLE
Can I play and record stream in the same time?

### ISSUE THREAD

**Issue by asadman1523** [caprica/vlcj#370]
I followed the tutorial "How do I transcode and save video?" playMedia on ubuntu.

 I cannot see the display but I can get the mp4 file after terminate my application and it can watch.

In addition, I can see display when I use webm transcode. But it show

"fcpattern object size does not accept value 0"

and didn't create file in my disk.

Is there any solution? Thanks!

**Comment by caprica** [comment]
Look at CaptureTest in the vlcj test sources.

You have to use sout strings with duplicate in there.

I am not sure it works in all cases.

**Comment by caprica** [comment]
Closed due to abandonment.
