### ISSUE TITLE
Stream RTSP source and save to file at the same time

### ISSUE THREAD

**Issue by ofirattia** [caprica/vlcj#371]
There is option to stream "RTSP stream" and at the same time to save it to file? 
Its like as an intermediate server, and this server save to file while streaming.
For example - StreamRtsp @ test can stream only file on the pc and not an rtsp source, maybe if this example can stream "rtsp stream" and we will set new options it will be able , what do you think?
```
String media ="rtsp://184.72.239.149/vod/mp4:BigBuckBunny_115k.mov";
        String options = formatRtspStream("127.0.0.1", 5555, "demo2");

        System.out.println("Streaming '" + media + "' to '" + options + "'");

        MediaPlayerFactory mediaPlayerFactory = new MediaPlayerFactory(args);
        HeadlessMediaPlayer mediaPlayer = mediaPlayerFactory.newHeadlessMediaPlayer();
        mediaPlayer.playMedia(media,
            options,
            ":no-sout-rtp-sap",
            ":no-sout-standard-sap",
            ":sout-all",
            ":sout-keep"
            
       
        );
``` 
thanks.

**Comment by caprica** [comment]
StreamRtsp is basically an RTSP server.

I think you want your client to play the RTSP stream, and your client to save it to disk - i.e. not a 'server'.

There is no API in vlcj or LibVLC to do that, you need to mess about with "sout" strings. Have a look at CaptureTest and the various other vlcj test sources.

I don't recall specifically streaming RTSP and saving it myself.

I have stream MP3, played it locally and saved it, so in principle it should be possible.
