### ISSUE TITLE
waveOutPrepareHeader failed when usb audio out device unplug

### ISSUE THREAD

**Issue by ayubali** [caprica/vlcj#375]
audio output name: waveout 
Audio device ID:  (C-Media USB Headphone ($ffff,$ffff)
when i select above usb audio device as output then play it works fine.
problem is, during running , if i unplug above audio usb device then application hang-up and it gives following message in console continuouly.

[0000000000152020] waveout audio output error: waveOutPrepareHeader failed
[0000000000152020] waveout audio output error: waveOutPrepareHeader failed
[0000000000152020] waveout audio output error: waveOutPrepareHeader failed
..............

**Comment by caprica** [comment]
Those errors come from VLC itself, not vlcj.

vlcj knows nothing about media sources or outputs, nor USB, nor anything like that. It just hosts VLC's media player.

So I don't think anything can be done in vlcj here.

**Comment by ayubali** [comment]
As application is hanged-up(struck) when this event occurs, is any way to get around from here.  like i can catch such error and set another audio device id as the output device.

**Comment by caprica** [comment]
No, because you can't handle an error/condition that occurs in native code, from the Java side.

It looks to me like VLC is not handling the unplug.

I'm afraid you can't do anything.

**Comment by caprica** [comment]
I have to close this, there's nothing that can be done in vlcj.
