### ISSUE TITLE
Video Effects.

### ISSUE THREAD

**Issue by edgarEACG** [caprica/vlcj#390]
Greetings,

I've been trying to implement a video effect cosole (for hue, brightness, constrast, saturation and gamma) like the one in the VLC programa Tools>Effects and Filters> Video Effects > Adjust Image.

I'm using 
- setAdjustVideo(true),
- setBrightness();
- setHue();
- setContrast();
- setSaturation();
- setGamma();
but nothing happens.

The following is the snippet where I'm testing de above functions:
```
mpf = new MediaPlayerFactory();
player1 = mpf.newEmbeddedMediaPlayer();
player1.setVideoSurface(mpf.newVideoSurface(videoSurface1));		
player1.setAdjustVideo(true);

Button btnFiltros = new Button(container, SWT.NONE);
Button btnFiltros = new Button(container, SWT.NONE);
		btnFiltros.addSelectionListener(new SelectionAdapter() {
			@Override
			public void widgetSelected(SelectionEvent e) {				
				player1.setBrightness(0.45f);
				player1.setHue(50);
				player1.setContrast(2.0f);
				player1.setSaturation(2.65f);
		                player1.setGamma(2.1f);
                        }
		});
```
Can you, please, help me. Maybe I've not yet understood how to use these methods.

Thanks in advance.

**Comment by caprica** [comment]
Did you look at the vlcj examples? My vlcj-player project (also on Github) implements exactly what you're describing.

You also may be affected by this: https://trac.videolan.org/vlc/ticket/11750

**Comment by edgarEACG** [comment]
I found this link:
https://groups.google.com/forum/#!topic/vlcj-users/0oZ_p3xWm8A

It states that it's not possible do this "dynamically" (while video is playing). 
Sorry, I've not caught it. Is it posible or no? Could you please provide me with an example link where these video adjustments are implemented? (I've not found an example about this specific point)

Thanks.

**Comment by caprica** [comment]
That link pertains to video filters generally, not the video adjustment filter which has a dedicate LibVLC API.

I already pointed you to the vlcj-player project that contains an example of how to do it. It does not work with *some* versions of VLC 2.x, and definitely does not work currently with VLC 3.x.

https://github.com/caprica/vlcj-player

**Comment by caprica** [comment]
Did you solve your problem yet?

**Comment by edgarEACG** [comment]
well, not at all. I'm using version 3.7.0. I have tried the vlcj-player you mention (using vlcj version 2.4.1) but there is no NativeStream class (uk.co.caprica.vlcj.runtime.streams.NativeStreams). In fact, this class is not available but up to version 3.1.0 according to this page (http://grepcode.com/project/repo1.maven.org/maven2/uk.co.caprica/vlcj/)

**Comment by caprica** [comment]
Hold on... you can look at the source code for vlcj-player to see how it implements the video adjustment, and compare that to your own code. That's why I was recommending it.

If you do want to run it, just change the version of vlcj in the vlcj-player pom.xml to 3.7.0 - I'll get around to making that change for vlcj-player soon enough, but that shouldn't stop you in the meantime, just change it yourself.

Please will you also tell me which version of VLC (not vlcj) you're using. That is critical for this issue.

**Comment by caprica** [comment]
In fact I just checked the vlcj-player pom and it specifies vlcj 3.6.0 so that should have been good enough. I don't understand the problem.

**Comment by edgarEACG** [comment]
Thanks a lot. It's working! I need just to adjust the ranges because they seem not to be consistent. But it's working.

Greetings for your great api
