### ISSUE TITLE
Vlcj 3.8 and YouTube videos

### ISSUE THREAD

**Issue by CodeGuru0** [caprica/vlcj#392]
Hello!
My question is why youtube videos working with vlcj 3.3 (or lower) and not with the new versions?
Environment:
Windows 7 64 bit (- Java 64 bit)
Vlcj 3.8 - Vlc 2.2.1

It can't extract the mrl from the url I guess.This "feature" should depends on the vlc not the vlcj isn't it?
Anyway, it works fine with 3.3 but it is worth to state this somewhere in the code in VlcjTest.java

I'd like to compliment to you, vlcj is useful and well documented program.

Alex

**Comment by caprica** [comment]
Probably because of #391

**Comment by CodeGuru0** [comment]
Didn't find this one. Thank you!

**Comment by caprica** [comment]
Will be fixed with the upcoming 3.9.0 release.
