### ISSUE TITLE
Delay to start transmission RTP

### ISSUE THREAD

**Issue by dimachiaveli** [caprica/vlcj#393]
I am creating a code for transmitting a webcam via RTP using as an example the class "ChatTest", The problem is that when you start the webcam just get the message:

121 [AWT-EventQueue-0] INFO uk.co.caprica.vlcj.Info - vlcj: 3.8.0
121 [AWT-EventQueue-0] INFO uk.co.caprica.vlcj.Info - java: 1.6.0_25 Sun Microsystems Inc.
121 [AWT-EventQueue-0] INFO uk.co.caprica.vlcj.Info - java home: C:\Program Files\Java\jdk1.6.0_25\jre
121 [AWT-EventQueue-0] INFO uk.co.caprica.vlcj.Info - os: Windows 7 6.1 x86
278 [AWT-EventQueue-0] INFO uk.co.caprica.vlcj.discovery.NativeDiscovery - Discovery found libvlc at 'D:\VLC'
3492 [AWT-EventQueue-0] INFO uk.co.caprica.vlcj.binding.LibVlcFactory - vlc: 2.2.1 Terry Pratchett (Weatherwax), changeset 2.2.1-0-ga425c42
3492 [AWT-EventQueue-0] INFO uk.co.caprica.vlcj.binding.LibVlcFactory - libvlc: D:\VLC\libvlc.dll
[09c6bb94] x264 encoder: using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.1 Cache64

[09c6bb94] x264 encoder: profile High, level 1.1

And it is in this state for several minutes to finally start broadcasting, any suggestions of what would be? I do not think a solution. Thank des already.

**Comment by caprica** [comment]
What happens when you set up the same arrangement in VLC itself?

**Comment by dimachiaveli** [comment]
When transmitted directly by VLC the connection is instantaneous. I am using the following code, with only a few changes from the original:

```
private void send() {
        String mrl = mediaTextField.getText();
        if(mrl.length() > 0) {
            String streamTo = streamToTextField.getText();
            String[] parts = streamTo.split(":");
            if(parts.length == 2) {
                String host = parts[0];
                int port = Integer.parseInt(parts[1]);

                String[] localOptions = {formatRtpStream(host, port), ":sout-all", ":sout-keep",};

                localMediaPlayer.playMedia(mrl, localOptions);
            }
            else {
                JOptionPane.showMessageDialog(frame, "You must specify host:port to stream to.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        else {
            JOptionPane.showMessageDialog(frame, "You must specify source media, e.g. v4l2:///dev/video0 on Linux or dshow:// on Windows.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

private static String formatRtpStream(String serverAddress, int serverPort) {
        StringBuilder sb = new StringBuilder(60);
        sb.append(":sout=#transcode{vcodec=h264,scale=Automático,width=160,height=120,acodec=mpga,ab=128,channels=2,samplerate=22050}:duplicate{dst=display,dst=rtp{dst=");
        sb.append(serverAddress);
        sb.append(",port=");
        sb.append(serverPort);
        sb.append(",mux=ts}}");
        return sb.toString();
    }

```

**Comment by caprica** [comment]
Have you confirmed the exact same options in use when you use VLC and when you use vlcj?

Run both applications by using "-vvv" (on the command-line for VLC) or when you create the media player factory for vlcj, and compare the logs to see what's different.

Otherwise it's pretty much impossible to say what's wrong here.
