### ISSUE TITLE
mute() function not working?

### ISSUE THREAD

**Issue by asadman1523** [caprica/vlcj#395]
if(!mediaPlayerComponent.getMediaPlayer().isMute())
{
    mediaPlayerComponent.getMediaPlayer.mute();
}

But I still hear the sound, Do I do wrong?

I use mediaPlayerComponent link rtsp stream

**Comment by caprica** [comment]
If I use the vlcj-player example, I added some trace, isMute() returns the correct status, and mute() toggles the mute correctly.

So I don't know what could be wrong, but I think vlcj works properly here.

**Comment by caprica** [comment]
mute() toggles mute, making your if clause redundant.

If you want to do it that way with your if clause, there's a mute(boolean) instead.

**Comment by asadman1523** [comment]
I found the problem. If mediaPlayerComponent are not playing, mute() is not working. 
I add this and mute function work perfectly.

mediaPlayerComponent .getMediaPlayer().Play();
while(!mediaPlayerComponent .getMediaPlayer().isPlaying())
{
    Thread.sleep(5000);
}
mediaPlayerComponent .getMediaPlayer().mute();

Thank you.

**Comment by caprica** [comment]
Ah, ok. Some things do indeed require the media to be playing - this is not a limitation of vlcj, it is how LibVLC works.

Thanks!

**Comment by caprica** [comment]
Also, note with the latest version of vlcj and LibVLC 3.0.0 (not yet released) you get more control of and notification of volume and mute status thanks to some new events - i.e. you should be able to get reliable notification of the mute/unmute status and the current volume.

**Comment by asadman1523** [comment]
Got it!
