### ISSUE TITLE
prepareMedia(media: RandomAccessFileMedia) causes Error looking up function 'libvlc_media_new_callbacks'

### ISSUE THREAD

**Issue by chumak-it** [caprica/vlcj#396]
Hi,
I have found a possible bug. My environment is Windows 7 x64 with jdk 1.8.0_40 x64, VLC 2.2.1 Terry Pratchett (Weatherwax) and Vlcj 3.8.0.

Code to reproduce the bug:
```
public class VlcWithRandomAccessFileMedia {
	public static void main(String[] args) {
		if(new NativeDiscovery().discover()) {
			System.out.println(LibVlcVersion.getVersion().version());
			AudioMediaPlayerComponent mediaPlayerComponent = new AudioMediaPlayerComponent();
			try {
				Media media = new RandomAccessFileMedia(new File("Kalimba.mp3"));
				mediaPlayerComponent.getMediaPlayer().prepareMedia(media);
				Thread.sleep(2000);
			} catch (InterruptedException e) {
			} finally {
				mediaPlayerComponent.release();
			}
		} else {
			throw new RuntimeException("Vlc not found");
		}
	}
}
```
Console output:
```
    2.2.1 Terry Pratchett (Weatherwax)
    Exception in thread "main" java.lang.UnsatisfiedLinkError: Error looking up function 'libvlc_media_new_callbacks': Die angegebene Prozedur wurde nicht gefunden.

	at com.sun.jna.Function.<init>(Function.java:179)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:430)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:410)
	at com.sun.jna.Library$Handler.invoke(Library.java:205)
	at com.sun.proxy.$Proxy13.libvlc_media_new_callbacks(Unknown Source)
	at uk.co.caprica.vlcj.player.DefaultMediaPlayer.createMediaInstance(DefaultMediaPlayer.java:2140)
	at uk.co.caprica.vlcj.player.DefaultMediaPlayer.setMedia(DefaultMediaPlayer.java:2085)
	at uk.co.caprica.vlcj.player.DefaultMediaPlayer.prepareMedia(DefaultMediaPlayer.java:282)
	at de.chumak.usenetmanager.VlcWithRandomAccessFileMedia.main(VlcWithRandomAccessFileMedia.java:19)
```
According to the source of DefaultMediaPlayer, the bug concerns all prepareMedia() calls with CallbackMedia as parameter and probably also other  methods which call createMediaInstance() with CallbackMedia as parameter. My current workround is as following:
```
public class VlcWithSimpleMedia {
	public static void main(String[] args) {
		if(new NativeDiscovery().discover()) {
			System.out.println(LibVlcVersion.getVersion().version());
			AudioMediaPlayerComponent mediaPlayerComponent = new AudioMediaPlayerComponent();
			try {
				String mrl = new File("Kalimba.mp3").toURI().toString();
				mediaPlayerComponent.getMediaPlayer().prepareMedia(mrl);
				Thread.sleep(2000);
			} catch (InterruptedException e) {
			} finally {
				mediaPlayerComponent.release();
			}		
		} else {
			throw new RuntimeException("Vlc not found");
		}
	}
}
```
The snippet above produces no exceptions. But with that workaround I cannot pass my own CallbackMedia to the MediaPlayer. For me it would be very useful if I could do so.

Regards and thank youf or the nice project.

Vladislav Chumak

**Comment by caprica** [comment]
The functionality you are trying to use requires LibVLC 3.0.0+.

**Comment by chumak-it** [comment]
Thank you for your fast response. Maybe it would be nice to add such information to Javadoc if not already. Otherwise the exception is not obvious.

**Comment by caprica** [comment]
28b7f73d06aeac8110dd9782bcd2235e25a3cf50.

**Comment by caprica** [comment]
LibVLC 3.0.0 comes with VLC 3.0.0. It's not officially released yet. Search the videolan website.

**Comment by rybak** [comment]
Is it possible that such error is caused by using 64 bit JDK and 32 bit VLC (or vice versa)?

**Comment by caprica** [comment]
No. The reported error is wholly dependent on the particular API version of VLC/LibVLC. It is nothing specifically to do with 32bit vs 64bit VLC (assuming your 32bit and 64bit VLC are the same version of course).

**Comment by rybak** [comment]
@caprica Thanks for fast response!

[The vlcj Tutorial](http://capricasoftware.co.uk/#/projects/vlcj/tutorial/prerequisites) says:

> More usefully, the latest vlcj version supports the current release version of VLC, right now this is 2.2.0

I have VLC 2.2.4 installed and am using vlcj-3.8.0.jar (added via Gradle dependency). I'm getting the same `UnsatisfiedLinkError: Error looking up function 'libvlc_media_new_callbacks'`.

Do I still need to upgrade to nightly VLC?

**Comment by caprica** [comment]
It's exactly as already described. The callbacks API is not available until LibVLC 3.0.0.

So, either upgrade your VLC to 3.0.0 or do not use the callbacks (InputStream) API.

**Comment by rybak** [comment]
Is there any way to check, whether or not the API is available in the installed version of libvlc other than running it?

**Comment by caprica** [comment]
http://caprica.github.io/vlcj/javadoc/3.10.1/index.html

**Comment by rybak** [comment]
Sorry, I didn't make myself clear. I mean that Javadocs for both [`prepareMedia` method](http://caprica.github.io/vlcj/javadoc/3.10.1/uk/co/caprica/vlcj/player/MediaPlayer.html#prepareMedia-uk.co.caprica.vlcj.player.media.Media-) and for [`FileInputStreamMedia` class](http://caprica.github.io/vlcj/javadoc/3.10.1/uk/co/caprica/vlcj/player/media/callback/nonseekable/FileInputStreamMedia.html) say nothing about the versions of libvlc they are available in.

**Comment by caprica** [comment]
Well, in most cases the Javadoc does state such things, but, you know, Javadoc isn't always perfect in most projects.

**Comment by caprica** [comment]
Actually, according to a comment above I already committed this to the Javadoc. It just hasn't made it into a formal release yet. vlcj is pretty much stable and feature-complete now so the releases are on a slower track.
