### ISSUE TITLE
DirectMediaPlayer on SWT implementation

### ISSUE THREAD

**Issue by edgarEACG** [caprica/vlcj#398]
Greetings.
I need to play HD videos without quality loss as I suppose it's done with EmbeddedMediaPlayer. I'm trying to use DirectMediaPlayer and I've gotten it to  work. But I need an implementation for SWT. I couln'd find an example implementation for it. Could you please, provide me with one Little example or some guidelines to do it?

Thanks a lot.

**Comment by caprica** [comment]
I'm not quite sure what you mean. If you can embed a Canvas in SWT (like with the bridge) then you could just use the EmbeddedMediaPlayer.

If you want to use the DirectMediaPlayer, you're basically rendering the video yourself - so however best to do that in SWT is what you should do... in Swing you render a BufferedImage, in JOGL or something you can render into a texture. SWT must have something equivalent.

I think at one time I did have an SWT implementation working, because I had vlcj embedded inside Eclipse, but I can't recall how I did it, or where that code is.

**Comment by caprica** [comment]
I found a code fragment I used that used an embedded media player (not direct media player) for best performance in an SWT app using the AWT bridge.
```
    videoPanel = new Composite(shell, SWT.NONE);
    videoPanel.setLayout(new FillLayout());
    videoPanel.setBackground(display.getSystemColor(SWT.COLOR_BLACK));

    videoComposite = new Composite(videoPanel, SWT.EMBEDDED | SWT.NO_BACKGROUND);
    videoComposite.setLayoutData(new GridData(GridData.FILL_BOTH));
    videoFrame = SWT_AWT.new_Frame(videoComposite);
    videoSurfaceCanvas = new Canvas();
    videoSurfaceCanvas.setBackground(java.awt.Color.black);
    videoFrame.add(videoSurfaceCanvas);

    mediaPlayerFactory = new MediaPlayerFactory(args);
    mediaPlayer = mediaPlayerFactory.newEmbeddedMediaPlayer();
    videoSurface = mediaPlayerFactory.newVideoSurface(videoSurfaceCanvas);
    mediaPlayer.setVideoSurface(videoSurface);
```

**Comment by edgarEACG** [comment]
I have that code working.
What I want to implement is the same but with "mediaPlayer=mediaPlayerFactory.newDirectMediaPlayer();" instead "mediaPlayer = mediaPlayerFactory.newEmbeddedMediaPlayer();". Is that possible? or even Does it make sense?

Thanks.

**Comment by caprica** [comment]
OK, but I have to ask why. The embedded player is by far the best choice.

If you really do want to use the direct media player with SWT, then I'm afraid you need to figure out how to render a byte[] or integer[] into however SWT renders images into a composite. I don't know such things.

**Comment by edgarEACG** [comment]
Right now I have to play HD videos with *.MTS extension. It plays, but fires some errors:
[00000000337c15a0] core stream error: corrupt module: C:\Program Files\VideoLAN\VLC\plugins\stream_filter\libdash_plugin.dll
[000000002ad5cec0] core demux error: corrupt module: C:\Program Files\VideoLAN\VLC\plugins\demux\libsid_plugin.dll
[000000002ad5cec0] core demux error: corrupt module: C:\Program Files\VideoLAN\VLC\plugins\demux\libmkv_plugin.dll
[000000002ad5cec0] core demux error: corrupt module: C:\Program Files\VideoLAN\VLC\plugins\access\liblive555_plugin.dll
[000000002ad5cec0] core demux error: corrupt module: C:\Program Files\VideoLAN\VLC\plugins\demux\libgme_plugin.dll
[000000002ad5cec0] ts demux: HDMV registration not implemented for pid 0x1100 type 0x81
[000000002ad12560] core demux meta error: corrupt module: C:\Program Files\VideoLAN\VLC\plugins\meta_engine\libtaglib_plugin.dll
[00000000337c33d0] core vout display error: Failed to set on top

I think that could be due to the codecs or rendering proccess so that I'm trying alternatives. Direct Media player could be one. But I'm developing in SWT.

**Comment by caprica** [comment]
OK, that's fair enough. I still can't really help though. vlcj gives you either an array of 32-bit integer values, or it gives you direct access to the video buffer raw bytes. You need to find a way to render that into an SWT composite, however you'd normally render images I guess.

**Comment by caprica** [comment]
You should really not be seeing those corrupt module errors, are you sure your VLC build is valid?

**Comment by edgarEACG** [comment]
I downloaded it from the official website: vlc-2.2.1-win64.exe

**Comment by caprica** [comment]
I don't use Windows much, is it possible to run the 32-bit VLC on 64-bit Windows?

**Comment by edgarEACG** [comment]
It's right. A 32-bit JVM is nedeed. I'll try that option.
Thanks.
