### ISSUE TITLE
Cannot load LibVlc second time after providing wrong vlc path first time

### ISSUE THREAD

**Issue by chumak-it** [caprica/vlcj#399]
Hi,
I am building a UI with that a user can provide his custom path to his vlc player installation.
When the user enters a path, I want to check if the path which user entered is correct.
Currently I am doing that by a snippet like this:
```
NativeLibrary.addSearchPath(RuntimeUtil.getLibVlcLibraryName(), newVlcPath);
try {
	String versionStr = LibVlc.INSTANCE.libvlc_get_version();
	if(versionStr == null) {
		return null;
	}
	return new Version(versionStr);
} catch(Throwable e) {
	e.printStackTrace();
	return null;
}
```
It works, when the user enters a corrent path to his vlc first time after application startup. But if the path was one time incorrect, then I cannot use classes like LibVlc in the same running JVM anymore, because the classes get broken with their static initializations. Therefore the next attempt of the validation snippet above ends with the following error when I am trying to access the LibVlc interface:
```
java.lang.NoClassDefFoundError: Could not initialize class uk.co.caprica.vlcj.binding.LibVlc
```
Are there any other solutions for my problem?
I have also read somewhere in the past some advices which recommend to start Vlcj in a different JVM because some people claimed about jvm crashes. Is this issue still up to date? If yes, are there any examples how I can accomplish that without decoupling my JavaFX GUI?

Regards,

chumak-it

**Comment by caprica** [comment]
Before you touch the vlcj LibVLC class, just try loading the library using JNA or System.loadLibrary yourself.

vlcj does this:
```
Native.loadLibrary(RuntimeUtil.getLibVlcLibraryName(), LibVlc.class)
```

Nothing stops you from doing that in your own code, and when it works, *then* load vlcj.

**Comment by caprica** [comment]
I do agree however it would be better if vlcj did not break in this way.

**Comment by chumak-it** [comment]
Native.loadLibrary(RuntimeUtil.getLibVlcLibraryName(), LibVlc.class)
works fine when LibVlc hasn't been already loaded. However, if LibVlc has been already loaded with a version like 2.0.0 and my application relies on at least 2.1.0, than there is no chance to change the INSTANCE constant inside the LibVlc interface without a JVM restart. Correct me if I am wrong. I have already tried to find some solution for that with reflection API and class overriding without touching the jar of vlcj, but I failed, because of the interface constants. With a static final field in a class I would have a better chance, because they seem to be treated by java compiler other way than interface constants.
To give the user the easiest way of configuring the path to his VLC installation, I have decided to take the ugliest but working solution which could implement my requirement - source code modification of vlcj. My main goal was to implement a custom uk.co.caprica.vlcj.binding.LibVlc with a reloading functionality without touching other vlcj files. I have succeeded. The solution is very ugly, especially the automatically created delegators for ILibVlc, but it works.
I have attached the 3 files I have added to uk.co.caprica.vlcj.binding. A feedback for them would be much appreciated. Maybe there are also some helpful snippets for vlcj 4.0.0 you can extract.
The 3 mentioned files can be found here:

https://www.dropbox.com/sh/6q11all50umotki/AADKQdZTtxDARtflNsympwkGa?dl=0

**Comment by caprica** [comment]
Why not post a pull request or patch rather than having to download some files from Dropbox and apply the changes myself...

**Comment by chumak-it** [comment]
There are 3 reasons
1) I am not very familiar with Git, so it takes me more time to read about how to make a pull request or patch, than for you to download and apply the changes for yourself :) Its embarrassing for me, but its the true truth.
2) As mentioned in my last post, my solution is very ugly and should not be used for releases. A better solution would be a refactoring of the whole source with the intention to separate current LibVlc into a loading class (statics of my AbstractLibVlc) and the actual native library instance.
3) My source code is based on vlcj 3.8.0 which my application uses. It could be incompatible with 3.9.0

But if you still want a pull request or a patch with my 3 files, then tell it. Then I will have a reason to see how to do it.

**Comment by caprica** [comment]
OK, we'll see.

The approach in vlcj4 does not use this instance variable anyway so it
might be moot.

**Comment by caprica** [comment]
#378 is related. I'll use that issue to track this.
