### ISSUE TITLE
How to make VLC support the Chinese path?

### ISSUE THREAD

**Issue by whxmm0608** [caprica/vlcj#400]

**Comment by caprica** [comment]
Please be more specific, give me a line of code that does not work...

**Comment by whxmm0608** [comment]
It like this.II added this code in the main class, and added the event listener in another class.When I chose the Chinese file name in the file selector, it went wrong.
	public static void openVedio() {
		JFileChooser chooser = new JFileChooser();
		int value = chooser.showOpenDialog(null);
		if (value == JFileChooser.APPROVE_OPTION) {
			File file = chooser.getSelectedFile();
			String pathString = file.getAbsolutePath();
			window.getMediaPlayer().playMedia(pathString);
		}
	}

**Comment by whxmm0608** [comment]
Error information is as follows：
[000000000cc52290] core input error: open of `file:///F:/%D1%B8%C0%D7%CF%C2%D4%D8/%5B%B1%E4%D0%CE%BD%F0%B8%D54%A3%BA%BE%F8%BC%A3%D6%D8%C9%FA%5DDVD%B0%E6_bd.mp4' failed
[000000000cc52290] core input error: 
[000000000cc52290] core input error: VLC

**Comment by caprica** [comment]
Can the VLC application open your file?

**Comment by caprica** [comment]
You can reopen this if you provide more information.
