### ISSUE TITLE
If I use MediaPlayerFactory my program crashes

### ISSUE THREAD

**Issue by user2006** [caprica/vlcj#402]
Hi,
I'm trying to use a HeadlessMediaPlayer to record a stream, but when I use MediaPlayerFactory I get this error: Unable to load library 'libvlc'... because libvlccore.dll and libvlc.dll are not found. I've tried to solve that, but it has been impossible. If I use only HeadlessMediaPlayer, I have to add all its methods and, moreover, it neither work properly (it doesn't save the stream). What can I do to solve it?
Thanks.

**Comment by caprica** [comment]
Please look at the examples in the vlcj test sources and the Javadoc. You do not have to implement those methods yourself, there is a default implementation and a component abstraction for the headless media player.

**Comment by user2006** [comment]
OK, but when I have tried to extend my class from VlcjTest I've just discovered that although I have set vlcj-3.9.0.jar as a dependency of Maven, I have no access to the test import. In fact, I cannot see that inside the jar. So how can I add the tests to my Maven project?

**Comment by caprica** [comment]
Import the project from GitHub, or just browse the  test sources at GitHub.

**Comment by user2006** [comment]
Import problem solved. But now I still have the problem related to use MediaPlayerFactory. Here is my code:
![screen shot 2015-09-10 at 11 33 02](https://cloud.githubusercontent.com/assets/14178500/9785085/048bf43c-57b0-11e5-8816-95b9e951a174.png)
It doesn't crash, but when I discomment the lines as in the next image...
![screen shot 2015-09-10 at 11 32 25](https://cloud.githubusercontent.com/assets/14178500/9785104/2183759c-57b0-11e5-910b-e01c4e61cc57.png)
I get this error:
![screen shot 2015-09-10 at 11 33 46](https://cloud.githubusercontent.com/assets/14178500/9785119/2d58b06c-57b0-11e5-9627-0b1ab46349a4.png)

**Comment by caprica** [comment]
In your non working code you are creating the media player and factory
before you are setting the native library path.
