### ISSUE TITLE
isAdjust() method causes JVM to crash

### ISSUE THREAD

**Issue by edgarEACG** [caprica/vlcj#407]
Greetings,

I've been developing a vlcj application. I found that the isAdjustVideio() method from MediaPlayer class causes the JVM to crash when invoked. Here you have the error:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000000006bd0ca3c, pid=4224, tid=2756
#
# JRE version: Java(TM) SE Runtime Environment (8.0_60-b27) (build 1.8.0_60-b27)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.60-b23 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [libvlccore.dll+0x8ca3c]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# E:\eWorkspace\H60005\hs_err_pid4224.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```
Do you have any ideas why it happens and more important how to solve this issue?

Thanks a lot.

**Comment by caprica** [comment]
Is your media actually playing?

Which version of LibVLC?

**Comment by edgarEACG** [comment]
Yes, it's playing. I'm using 3.7.0 of vlcj version and the LibVLC included in the 2.2.1 VLC media player for 64 bits.

Let me try to make to work the logger, I tried before but I wasn't able. 
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".

**Comment by caprica** [comment]
For vlcj logging, you need to configure SLF4J.

Here's the vlcj code implicated in your issue:

        public boolean isAdjustVideo() {
            logger.debug("isAdjustVideo()");
            return libvlc.libvlc_video_get_adjust_int(mediaPlayerInstance, libvlc_video_adjust_option_t.libvlc_adjust_Enable.intValue()) == 1;
        }

So mediaPlayerInstance can't be null if your video is playing.

As you can see, vlcj does not really do anything at all here. It just calls the native API.

**Comment by caprica** [comment]
I also changed the vlcj-player project to invoke isAdjustVideo every second on a timer while the media is playing. It does *not* crash for me.

**Comment by caprica** [comment]
This can be re-opened if any new information comes to light.
