### ISSUE TITLE
Taglib meta writer error when setting metadata on video file

### ISSUE THREAD

**Issue by dh1118** [caprica/vlcj#410]
Hello,

I am using Vlcj to write some metadata to video files to create a video library which could be sorted by title, date, artist, etc.

When I am trying to save the metadata that I set to the file, the following error appears:

<pre>
 [00007ff7043d8f48] taglib meta writer error: File test.mp4 can't be opened for tag writing
</pre>

I have based my test in the test <b>UpdateMetaTest.java</b> of the official repo at Github: https://github.com/caprica/vlcj/blob/99b0f7f1a97a085bbe27513eba6dc8014ede9081/src/test/java/uk/co/caprica/vlcj/test/meta/UpdateMetaTest.java

This is the code that I am using:
```java
public static void main(String[] args) {
	// Create a media player
	MediaPlayerFactory factory = new MediaPlayerFactory();

	// Get the meta data and dump it out
	MediaMeta mediaMeta = factory.getMediaMeta(args[0], true);
	logger.info("Metadata:");
	logger.info(mediaMeta);
	logger.info(LibVlcVersion.getVersion());

	// Set the artist of the video if it is not set
	if (mediaMeta.getArtist() == null) {
		mediaMeta.setArtist("Unknown");
		mediaMeta.save();
	}

	mediaMeta.release();
	factory.release();
}
```

This is my program output:

<pre>
2015-10-04 13:51:27 INFO  MetaTest:65 - Metadata:
2015-10-04 13:51:27 INFO  MetaTest:66 - DefaultMediaMeta[title=test.mp4,artist=null,genre=null,copyright=null,album=null,trackNumber=null,description=null,rating=null,date=null,setting=null,url=null,language=null,nowPlaying=null,publisher=null,encodedBy=null,artworkUrl=null,trackId=null,trackTotal=null,director=null,season=null,episode=null,showName=null,actors=null,length=0]
2015-10-04 13:51:27 INFO  MetaTest:67 - 2.2.1 Terry Pratchett (Weatherwax)
[00007fbc3c3e3138] taglib meta writer error: File test.mp4 can't be opened for tag writing
</pre>

My Vlcj version is 3.9.0 and my Libvlc library is 2.2.1.

Thanks in advance.

**Comment by caprica** [comment]
This is hard to diagnose, because it is VLC that is reading and writing your tags, not vlcj.

I will look into it further, but first impressions are that this is not something that can be fixed in vlcj.

**Comment by dh1118** [comment]
Hello, thanks for the quick reply.

Also if it is in any way helpful, I tried executing the program in Windows and Ubuntu 14.04.

Greetings.

**Comment by caprica** [comment]
Since you cross-posted at Stackoverflow, maybe you'll get your answer there.

**Comment by caprica** [comment]
There is an UpdateMetaTest in the vlcj sources.

I tried that, and your example code, and it worked for me (Linux Mint, 64-bit).

So long as you get the filename correct...

Note that it is unfortunate but it seems that VLC will give you meta data even if the media does not exist.

**Comment by dfh1118** [comment]
That was it, I was trying to modify the metadata specifying a wrong filename.

Many thanks for the help.
