### ISSUE TITLE
Implement Closeable to support try with resources

### ISSUE THREAD

**Issue by paulholder** [caprica/vlcj#411]
Starting in Java 7, we have try clauses that automatically call close to prevent memory leaks.  It would be nice if VLCj would support this structure as well, instead of the calls to release().  It seems as simple as adding the implements Closable on the necessary classes  and the adding a close() method that calls your current release() method.

https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html

try (final EmbeddedMediaPlayer mediaPlayer = mediaPlayerFactory.newEmbeddedMediaPlayer(fullScreenStrategy))
{
...
}
// no longer need mediaPlayer.release() and the IDE can know no leak is happening

**Comment by caprica** [comment]
I don't need a link to the Java tutorial, thanks.

Anyway...

The IDE only thinks there's a leak if you don't close in the same method, right?

What's the use case for creating a media player and closing it in the same method?

**Comment by paulholder** [comment]
Your attitude apparently sucks.  Assuming you actually understand the concept, then what does it even matter about the use case?  Why would one open and close a file or a socket, or indeed anything all in one method.  Maybe that is up to the user of an API to decide?  Since it would be like a two second change, and maybe 10 lines at best, how about you don't decide which APIs of the JDK you like or don't like because they don't fit with the way you apparently work and think that others should work?
