### ISSUE TITLE
What event in MediaPlayer is generated if internet is disconnected while player is streaming online resource?

### ISSUE THREAD

**Issue by pablo7** [caprica/vlcj#414]
Any suggestions how to handle this event?

**Comment by caprica** [comment]
Unless you see error or finished, there is nothing else unfortunately.
LibVLC provides no other way to get notified about this.

**Comment by pablo7** [comment]
Unfortunately non of above events (error nor finished) are triggered in original scenario. There is no change in player state also.

I noticed that 'finished' event is triggered in case when I reconnect to internet (as continue of scenario).

**Comment by pablo7** [comment]
Any hope :) ?

**Comment by caprica** [comment]
Not without patching VLC.

**Comment by pablo7** [comment]
OK, I'm looking for workaround and thinking of some media player options (http-reconnect-something?) that could force vlc to fire error event. If I start media player without internet connection it would fire events 'state stopped' and 'error' as expected. If I could only simulate that when player is already playing and connection is lost in the meanwhile. Can You think of any media player options.

**Comment by caprica** [comment]
I really don't know. Those options are nothing to do with vlcj really.

All I can suggest is:

vlc -H

**Comment by caprica** [comment]
You could try enabling the native log (search the Javadoc for NativeLog, or look in the vlcj test sources) and scan for error messages.

This would be totally unsupported of course, but might be worth looking at.
