### ISSUE TITLE
MediaListPlayer opens new window "vlcj video output" when using "playItem"

### ISSUE THREAD

**Issue by LeovR** [caprica/vlcj#416]
I try to use the EmbeddedMediaListPlayerComponent to play a specific media list item but a new window "vlcj video output" is opened everytime.

I can reproduce the same results using the ``BasicEmbeddedMediaListPlayerComponentTest``.

However the method ``play`` is working fine and no new window is opened.

**Comment by LeovR** [comment]
I guess a ``attachVideoSurface`` is missing if ``playItem`` is used without a ``play``.

**Comment by caprica** [comment]
Good catch, thanks.

Change applied at 24b1c02d33c0c896d3fb19fc080f9eb4bdf0c9f2.

Please try the latest code and report back.

**Comment by LeovR** [comment]
Commit is working for me

**Comment by caprica** [comment]
Thanks, it will be in the next release. Don't yet know when that is.
