### ISSUE TITLE
Problems saving RTSP Stream on file

### ISSUE THREAD

**Issue by mguacci** [caprica/vlcj#419]
Hi,
I'm an Italian software developer and, at present, I'm using VLCJ to save a RTSP stream on a file. 
If I use VLC, I can see the streaming without any problem. But in my application I see this log:

[063b6c94] x264 encoder: using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX
[063b6c94] x264 encoder: profile High, level 3.0
[05182874] core input error: ES_OUT_RESET_PCR called
[051f29a4] core decoder error: cannot continue streaming due to errors.

My options for playMedia method are ":sout=#transcode{vcodec=h264,venc=x264{cfr=16},scale=1,acodec=mp4a,ab=160,channels=2,samplerate=44100}:file{dst=/home/video/test.mp4}".

What can be the problem?
Can you help me?

Thank you,
M

**Comment by caprica** [comment]
Those errors are native errors from VLC itself.

Did you try using those transcode options with VLC?

Otherwise you probably need to post a self-contained test-case so I can try and see what's wrong. It's impossible to say with what you've posted so far.

**Comment by mguacci** [comment]
Dear Mark,
first of all thank you for your answer.

My code is:

                    String mrl = ...  /*hidden due to company rules*/

                    MediaPlayerFactory factory = new MediaPlayerFactory();
                    MediaPlayer player = factory.newHeadlessMediaPlayer();

                    //String options =
":sout=#transcode{vcodec=h264,venc=x264{cfr=16},scale=1,acodec=mp4a,ab=160,channels=2,samplerate=44100}:file{dst=/data/test.mp4}";

                    String options =
":sout=#transcode{}:duplicate{dst=std{access=file,mux=ts,dst={/data/test.mp4}}}";

                    //String options =
":sout=#standard{mux=ts,access=file,dst=/data/test.avi}";

                    player.playMedia(mrl, options);

                    Thread.sleep(60000);

                    player.stop();
                    player.release();
                    factory.release();

I think that the problem concerns the options, even if for a while with
these options my code worked.

Do you need something else?

Thank you since now for your support.

Massimiliano Guacci



2015-10-30 19:11 GMT+01:00 Mark Lee <notifications@github.com>:

**Comment by caprica** [comment]
I really need a self-contained example, a single runnable class, that demonstrates your problem.

There are some common mistakes, like your media player being garbage collected, that all depends on how exactly you wrote your code.

The other thing is, vlcj doesn't really do anything with those options other than pass them on to VLC. I would struggle to see how vlcj is doing anything wrong here.
