### ISSUE TITLE
Problem with playing local media 

### ISSUE THREAD

**Issue by yura0202** [caprica/vlcj#424]
->here is code 

        
        NativeLibrary.addSearchPath(RuntimeUtil.getLibVlcLibraryName(),
        "C:/Program Files (x86)/VideoLAN/VLC");
        Native.loadLibrary(RuntimeUtil.getLibVlcLibraryName(),LibVlc.class);
      
        MediaPlayerFactory mpf = new MediaPlayerFactory();
        EmbeddedMediaPlayer emp = mpf.newEmbeddedMediaPlayer();
        emp.setVideoSurface(mpf.newVideoSurface(c));
        emp.toggleFullScreen();

        emp.setEnableMouseInputHandling(true);
        emp.setEnableKeyInputHandling(true);

        String audiostream = "http://a.tumblr.com/tumblr_lxkra7aIn91qj3lsgo1.mp3";
        String localvideo = "C:/Downloads/Music/attila.mp4";
        String localaudio = "C:/Downloads/Music/audio.mp3";

        emp.prepareMedia(localvideo);
        emp.play();

-> Here is Log

15:04:12.528 [JavaFX Application Thread] DEBUG                             uk.co.caprica.vlcj.player.DefaultMediaPlayer - prepareMedia(mrl=C:/Downloads/Music/audio.mp3,mediaOptions=[])
15:04:12.528 [JavaFX Application Thread] DEBUG                           uk.co.caprica.vlcj.player.MediaResourceLocator - encodeMrl(mrl=C:/Downloads/Music/audio.mp3)
15:04:12.529 [JavaFX Application Thread] DEBUG                           uk.co.caprica.vlcj.player.MediaResourceLocator - MRL does not contain any Unicode characters
15:04:12.529 [JavaFX Application Thread] DEBUG                           uk.co.caprica.vlcj.player.MediaResourceLocator - result=C:/Downloads/Music/audio.mp3
15:04:12.529 [JavaFX Application Thread] DEBUG                             uk.co.caprica.vlcj.player.DefaultMediaPlayer - prepareMedia(media=SimpleMedia[mrl=C:/Downloads/Music/audio.mp3,mediaOptions=[Ljava.lang.String;@eaf304])
15:04:12.529 [JavaFX Application Thread] DEBUG                             uk.co.caprica.vlcj.player.DefaultMediaPlayer - setMedia(media=SimpleMedia[mrl=C:/Downloads/Music/audio.mp3,mediaOptions=[Ljava.lang.String;@eaf304])
15:04:12.529 [JavaFX Application Thread] DEBUG                             uk.co.caprica.vlcj.player.DefaultMediaPlayer - createMediaInstance(media=SimpleMedia[mrl=C:/Downloads/Music/audio.mp3,mediaOptions=[Ljava.lang.String;@eaf304])
15:04:12.529 [JavaFX Application Thread] DEBUG                             uk.co.caprica.vlcj.player.DefaultMediaPlayer - Treating mrl as a path
15:04:12.529 [JavaFX Application Thread] DEBUG                             uk.co.caprica.vlcj.player.DefaultMediaPlayer - mediaInstance=null
15:04:12.529 [JavaFX Application Thread] ERROR                             uk.co.caprica.vlcj.player.DefaultMediaPlayer - Failed to create native media resource for 'SimpleMedia[mrl=C:/Downloads/Music/audio.mp3,mediaOptions=[Ljava.lang.String;@eaf304]'
15:04:12.529 [JavaFX Application Thread] DEBUG                             uk.co.caprica.vlcj.player.DefaultMediaPlayer - result=false
15:04:12.529 [JavaFX Application Thread] DEBUG                             uk.co.caprica.vlcj.player.DefaultMediaPlayer - play()
15:04:12.529 [JavaFX Application Thread] DEBUG            uk.co.caprica.vlcj.player.embedded.DefaultEmbeddedMediaPlayer - onBeforePlay()
15:04:12.529 [JavaFX Application Thread] DEBUG            uk.co.caprica.vlcj.player.embedded.DefaultEmbeddedMediaPlayer - attachVideoSurface()
15:04:12.529 [JavaFX Application Thread] DEBUG       uk.co.caprica.vlcj.player.embedded.videosurface.CanvasVideoSurface - attach()
15:04:12.530 [JavaFX Application Thread] DEBUG       uk.co.caprica.vlcj.player.embedded.videosurface.CanvasVideoSurface - componentId=134664
15:04:12.530 [JavaFX Application Thread] DEBUG  u.c.c.v.player.embedded.videosurface.windows.WindowsVideoSurfaceAdapter - attach(componentId=134664)
15:04:12.530 [JavaFX Application Thread] DEBUG       uk.co.caprica.vlcj.player.embedded.videosurface.CanvasVideoSurface - video surface attached
15:04:12.531 [JavaFX Application Thread] DEBUG                             uk.co.caprica.vlcj.player.DefaultMediaPlayer - after play

I SEE THIS IN EVERY CASE EXCEPT ON  audiostream
       
Can you suggest smth ?
Thank you!

**Comment by caprica** [comment]
Don't use forward slashes on Windows.

**Comment by yura0202** [comment]
Thank you so much!!!!
My fault...

**Comment by caprica** [comment]
Well this one is not exactly obvious. Sure, with Java using forward slash is OK, but you need to realise that the filenames you specify are passed to VLC, i.e. a native Win32/64 application. In native Windows, using forward slash in filenames is not allowed. So it fails.
