### ISSUE TITLE
Can't find org.slf4j.impl.StaticLoggerBinder

### ISSUE THREAD

**Issue by marinica94** [caprica/vlcj#428]
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
java.lang.RuntimeException: Failed to load the native library.

The error was "Unable to load library 'libvlc': JNA native support (win32-amd64/libvlc.dll) not found in resource path.
The required native libraries are named "libvlc.dll" and "libvlccore.dll".

Any solution ? I am using dependencies:

    compile 'uk.co.caprica:vlcj:3.9.0'

**Comment by caprica** [comment]
The slf4j message is just a warning that you have not configured logging
properly (see the tutorial at capricasoftware.co.uk).

Your actual error is a failure to load libVLC which can happen for a
variety of reasons. Again, please go through the first tutorial for more
info.

**Comment by marinica94** [comment]
I have installed VLC on 64 bits because I didn't have it, my java arhitecture is on x64 but I still get the same error.

**Comment by caprica** [comment]
Look at the ways to set the native library search path.

**Comment by marinica94** [comment]
I see, it's trying to find the lib in JDK path: C:\Program Files\Java\jdk1.8.0_66\jre\lib\

**Comment by caprica** [comment]
The tutorial describes how to set the right path.

**Comment by marinica94** [comment]
I managed to make it work. I should not hurry anymore to get things done. Thank you for your support.

**Comment by caprica** [comment]
Glad to hear it!
