### ISSUE TITLE
How to add VideoPlayerComponent in JavaFX

### ISSUE THREAD

**Issue by marinica94** [caprica/vlcj#429]
Hi, I am trying to add the VideoPlayerComponent to JavaFX, I found that the EmbeddedMediaPlayerComponent extends Panel which I don't know exactly how can I add it to Scene.

                            FXMLLoader fxmlLoader = new FXMLLoader(getClass().getResource("VLCPlayer.fxml"));
                            Parent root1 = (Parent) fxmlLoader.load();
                            Stage stage = new Stage();
                            stage.initModality(Modality.APPLICATION_MODAL);
                            stage.initStyle(StageStyle.UNDECORATED);
                            stage.setTitle("ABC");
                            stage.setScene(new Scene(root1));

                            Pane mainLayout = (Pane) scene.lookup("#mainLayout");
                            mainLayout.getChildren().add(videoPlayerComponent);

                            stage.show();

I tried like this but I can't figure it out.Thank you for your help.

**Comment by caprica** [comment]
See the vlcj-javafx project also on GitHub.

**Comment by marinica94** [comment]
This is the class I should looking for: https://github.com/caprica/vlcj-javafx/blob/master/src/test/java/uk/co/caprica/vlcj/javafx/test/JavaFXDirectRenderingTest.java (Also if I understand this is the resizable Canvas: https://github.com/caprica/vlcj-javafx/blob/master/src/test/java/uk/co/caprica/vlcj/javafx/test/resize/ResizableJavaFXPlayerTest.java ) However I don't understand, in JavaFX we use DirectMediaPlayerComponent instead of EmbeddedMediaPlayerComponent because we cannot Embed it directly ?

**Comment by caprica** [comment]
You can't use the embedded version because it requires a heavyweight panel, and you can't embed a heavyweight panel in a Java FX scene.

**Comment by marinica94** [comment]
Any ideea why I get this error:

[0000000029d93ea0] core stream error: corrupt module: C:\Program Files\VideoLAN\VLC\plugins\stream_filter\libdash_plugin.dll
[0000000025cfd330] core demux meta error: corrupt module: C:\Program Files\VideoLAN\VLC\plugins\meta_engine\libtaglib_plugin.dll
[000000002baecd10] core window error: corrupt module: C:\Program Files\VideoLAN\VLC\plugins\gui\libskins2_plugin.dll

I use last version of VLC.

**Comment by caprica** [comment]
Corrupt module is a native error from VLC when it loads its plugins.

The usual, sub optimal, solution is to use 32bit VLC and JVM rather than 64bit.

I don't know why.

**Comment by marinica94** [comment]
I cannot use the 32bit vlc and 64 or 32 bit JVM ?

**Comment by caprica** [comment]
No.

**Comment by marinica94** [comment]
What does this meaning ? [h264 @ 1e67bbc0] mmco: unref short failure

**Comment by caprica** [comment]
VLC native warning or error, I have no idea.

Don't obsess about VLC messages in the log if your application is working.

Please don't post multiple different problems in the same issue.
