### ISSUE TITLE
Cannot find logback.groovy and logback-test in artifact

### ISSUE THREAD

**Issue by marinica94** [caprica/vlcj#433]
13:23:19,806 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT
 find resource [logback.groovy]
13:23:19,806 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT
 find resource [logback-test.xml]
13:23:19,806 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found res
ource [logback.xml] at [jar:file:/D:/nameOfProject/out/artifacts/DigiStora
geStreamer/nameOfJar.jar!/logback.xml]

Is there a way how can I change the path of logback ?

**Comment by caprica** [comment]
What has rhiebro dobwith vlcj?
