### ISSUE TITLE
Seek not working using directplayer approach

### ISSUE THREAD

**Issue by jdiligence** [caprica/vlcj#435]
Using the directplayer approach as am on OS X using Java 8.

All videos I have tried report isSeekable() as false. setPosition() and setTime() are ignored. Always plays from the beginning.

Is this a bug or do I need to do something special to get seek to work via vlcj?

**Comment by caprica** [comment]
There's nothing to do in vlcj to make that work.

If isSeekable() returns false, then it's VLC that is telling you that, not vlcj. Are you trying it after the media actually starts playing?

**Comment by jdiligence** [comment]
After calling prepareMedia but before I called play.

**Comment by caprica** [comment]
It may be counter-intuitive, but that's how VLC works. It would be the same even if it were not the "direct" media player.
