### ISSUE TITLE
vlc on raspberry pi vout error xvideo adaptor

### ISSUE THREAD

**Issue by kscorpio** [caprica/vlcj#439]
i run vlcj  to play a mpg video on raspberry pi
it can not play the video but has sound 
and with tips no available xvideo adaptor

when i just run vlc player to play the mpg video with vout x11 successfully

**Comment by caprica** [comment]
Insufficient information.

Enable logs, inspect them, thebbif you're still stuck post them.

**Comment by caprica** [comment]
Or try selecting the x11 output explicitly when you create the media player factory.

vlc -H

Will give you the options.
