### ISSUE TITLE
Youtube video not playing in loop

### ISSUE THREAD

**Issue by amrit-sbagga** [caprica/vlcj#440]
Hi caprica,

I'm trying to play youtube video in loop using youtube url with parameters loop=1 & playlist=Video_Id,
but the video is not playing in loop, it stops after 1st play, tested in browser too same is happening. But if I replace <b>"watch?v="</b> in url "http://www.youtube.com/watch?v=Video_Id&loop=1&playlist=Video_Id" with <b>"/embed/Video_Id"</b> or <b>"/v/Video_Id"</b> it's displaying black screen frame while same is well supported in browser i.e video is playing in loop with <b>"/embed/Video_Id"</b> or <b>"/v/Video_Id"</b>.

(<b>"/embed/Video_Id"</b> working well in browsers - tested in Chrome, IE8, Firefox while 
<b>"/v/Video_Id"</b> is working well in chrome but opening application/x-shockwave-flash file with IE8 & firefox)

![capture1](https://cloud.githubusercontent.com/assets/7499477/11743137/1c7ce416-a02b-11e5-818b-84aab8516751.PNG)

![capture2](https://cloud.githubusercontent.com/assets/7499477/11743141/269631c8-a02b-11e5-84e4-b9a2c23b0baf.PNG)

Here is code which I've tried-
[TestYoutubePlay.txt](https://github.com/caprica/vlcj/files/59345/TestYoutubePlay.txt)

And since, I think both /embed & /v are not supported in vlcj, so, is there is any work around in which we can play video in loop using <b>"watch?v="</b> which vlcj supports?
Note - I am using vlcj3.9.jar with jna & platform jars both v3.5.2 & slf4j v1.7.10

**Comment by caprica** [comment]
As far as I know you need to wait for the finished event and play the media again yourself.

You could also try mediaPlayer.setAutoRepeat.

**Comment by amrit-sbagga** [comment]
Thanks a lot Mark, after setting <b>mediaPlayer.setRepeat(true);</b> it's working like a charm, but it's frequently printing following logs, is this behaviour normal?

[057e322c] core vout display error: Failed to change zoom
[057e322c] core vout display error: Failed to set on top
[057e322c] core vout display error: Failed to change source AR
[057e322c] core vout display error: Failed to change zoom
[057e322c] core vout display error: Failed to change source AR

**Comment by caprica** [comment]
Just ignore those native messages from VLC. You can suppress that in the
usual way or capture the output using vlcj's NativeLog class if it bothers
you.

**Comment by amrit-sbagga** [comment]
Alright then, no problem with this native messages & once again thank you for your response and :+1: for this awesome project.
