### ISSUE TITLE
Interruption and resetting cached media data during playing audiostream.

### ISSUE THREAD

**Issue by yura0202** [caprica/vlcj#441]
May you help with this problem? During playing some audio streams i have such error

[19c300c4] core input error: ES_OUT_SET_(GROUP_)PCR  is called too late (pts_delay increased to 2009 ms)
[19c300c4] core input error: ES_OUT_RESET_PCR called

and then buffered data resetting and starting buffering again form zero percents. 
So i can have a lot of interruptions during particular audio file.

So what the reason could be here ?

**Comment by caprica** [comment]
That can't be fixed programmatically, apaprt from maybe increasing caching. Probably network problems with the stream.
