### ISSUE TITLE
Audio Waveform from VLC

### ISSUE THREAD

**Issue by marinica94** [caprica/vlcj#442]
Is there a way how to get audio data from VLC to build a waveform/spectrum in Java ?

**Comment by caprica** [comment]
DirectAudioPlayer.

**Comment by marinica94** [comment]
Which part of DirectAudioPlayert I should use to get this data ? Thank you !

**Comment by caprica** [comment]
Look at the examples in the vlcj test sources.

**Comment by marinica94** [comment]
The example you are talking about it's TestAudioCallbackAdapter in DirectAudioPlayerTest ?

    /**
     * Implementation of an audio callback that writes the decoded data to a local file.
     */
    private class TestAudioCallbackAdapter extends DefaultAudioCallbackAdapter {

        /**
         * Output stream.
         */
        private final BufferedOutputStream out;

        /**
         * Create an audio callback.
         */
        public TestAudioCallbackAdapter(File output) throws IOException {
            super(4); // 4 is the block size for the audio samples
            out = new BufferedOutputStream(new FileOutputStream(output));
        }

        @Override
        protected void onPlay(DirectAudioPlayer mediaPlayer, byte[] data, int sampleCount, long pts) {
            try {
                out.write(data);
            }
            catch(IOException e) {
                // Can't really do anything, should stop the media player I suppose...
                e.printStackTrace();
            }
        }

        @Override
        public void flush(DirectAudioPlayer mediaPlayer, long pts) {
            Logger.info("flush()");
        }

        @Override
        public void drain(DirectAudioPlayer mediaPlayer) {
            Logger.info("drain()");
            try {
                out.flush();
                out.close();
            }
            catch(IOException e) {
                e.printStackTrace();
            }
        }
    }

**Comment by caprica** [comment]
No, there are a few example applications in the vlcj test sources that use the direct audio player.

https://github.com/caprica/vlcj/tree/master/src/test/java/uk/co/caprica/vlcj/test/directaudio

The downside is that you have to play the audio yourself after you've processed it. One example uses the JavaSound API.

You can't get the audio samples from VLC and have VLC play your modified buffer.
