### ISSUE TITLE
Segfault Releasing Player

### ISSUE THREAD

**Issue by darkfrog26** [caprica/vlcj#444]
On Linux I get:

```
[info] #
[info] # A fatal error has been detected by the Java Runtime Environment:
[info] #
[info] #  SIGSEGV (0xb) at pc=0x00007f5c68103ac4, pid=3252, tid=140033832929024
[info] #
[info] # JRE version: OpenJDK Runtime Environment (8.0_65-b17) (build 1.8.0_65-b17)
[info] # Java VM: OpenJDK 64-Bit Server VM (25.65-b01 mixed mode linux-amd64 compressed oops)
[info] # Problematic frame:
[info] # C  [libpthread.so.0+0x9ac4]  pthread_mutex_lock+0x4
[info] #
[info] # Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
[info] #
[info] # An error report file with more information is saved as:
[info] # /home/mhicks/projects/open-source/sgine/examples/hs_err_pid3252.log
[info] #
[info] # If you would like to submit a bug report, please visit:
[info] #   http://bugreport.java.com/bugreport/crash.jsp
[info] # The crash happened outside the Java Virtual Machine in native code.
[info] # See problematic frame for where to report the bug.
[info] #
```

When I try to release my player. In this use-case I'm simply creating a new directmediaplayer from the factory, preparing the media (prepareMedia), parsing the media (parseMedia), reading the meta data, and then releasing the player (release). It crashes (most of the time) after the release call returns.

**Comment by caprica** [comment]
To debug segfaults, what's really needed is a full thread back-trace using a debug build of VLC with gdb or something.

**Comment by caprica** [comment]
I wrote a test case with the steps you outlined:

1. Create factory
2. Create direct media player
3. Prepare media
4. Parse media
5. Read meta (via getMediaMeta)
6. Release media player

I ran this 20 times with zero crashes.

I also added an additional step to release the factory too, and again no crashes.

So unless you post a test-case and a native thread backtrace, I'm not sure what I can do to help here.

**Comment by darkfrog26** [comment]
For now I simply stopped releasing the player (I created a player pool since the purpose of this is to get metadata for many files asynchronously) and everything works fine now.

**Comment by caprica** [comment]
You don't need the player to get meta data, just use the factory.

The vlcj "SearchMetaTest" example does this.

**Comment by darkfrog26** [comment]
The meta data doesn't have all of the information I need.  I also need track information which doesn't seem to be available apart from `player.getTrackInfo`
