### ISSUE TITLE
TagLib: Vorbis::File::read() - Could not find the Vorbis comment header.

### ISSUE THREAD

**Issue by darkfrog26** [caprica/vlcj#445]
Loading the 1080p Big Buck Bunny trailer I get that message and there is no track information available.  Initially I thought it was a missing codec in VLC or something wrong with the video, but opening directly in VLC it provides video and audio codec information.

**Comment by caprica** [comment]
So that is a native error message.

I don't know what's going on there, but at least post full logs.

**Comment by darkfrog26** [comment]
I believe it's a parsing error with VLCJ trying to parse the data coming from VLC.  I'm using the 1080p Ogg Theora trailer here: https://peach.blender.org/trailer-page/

I'm not doing anything special, just parsing the media and then attempting to iterate over the tracks to get information about it.  I've tested it and it works fine on other video files but it seems to have specific problems with that one.

I am running openSUSE Tumbleweed 64-bit using VLC version 2.2.1 and VLCJ version 3.10.0.

If you are unable to reproduce it I can attempt to generate logs, but there is no other information output right now for me to give you apart from that error and everything continues to run.

**Comment by caprica** [comment]
But vlcj does not parse anything itself, all it does is call the native libvlc_media_player_parse. I will download that sample and see if I can reproduce it.

**Comment by caprica** [comment]
I downloaded the 1080p trailer from the link you provided..

Using the vlcj "MediaInfoTest" example it produces this:

     Track Information: [VideoTrackInfo[codec=0x6f656874,codecName=theo,originalCodec=0x6f656874,originalCodecName=theo,id=0,profile=-1,level=-1,bitRate=0,language=null,description=null,codecDescription=][width=0,height=0,sampleAspectRatio=0,sampleAspectRatioBase=0,frameRate=25,frameRateBase=1], AudioTrackInfo[codec=0x62726f76,codecName=vorb,originalCodec=0x62726f76,originalCodecName=vorb,id=1,profile=-1,level=-1,bitRate=80000,language=null,description=null,codecDescription=][channels=2,rate=48000]]
    Title Descriptions: []
    Video Descriptions: [TrackDescription[id=-1,description=Disable], TrackDescription[id=0,description=Track 1]]
    Audio Descriptions: [TrackDescription[id=-1,description=Disable], TrackDescription[id=1,description=Track 1]]
       Extended Titles: []
     Extended Chapters: []

Sometimes the track information is not available until some (short) time after the media player has started playing.

**Comment by darkfrog26** [comment]
Is there no way to access the information without starting the video?  It's very strange that some videos would give immediate access to that information and others requires the video to start playing.

**Comment by caprica** [comment]
That's just how VLC works for some media, unfortunately. It depends on the necessary codec.
