### ISSUE TITLE
vlcj does not play url

### ISSUE THREAD

**Issue by frankred** [caprica/vlcj#447]
If I want to play a url eg: ```https:\\r3---sn-35cxacf-nugl.googlevideo.com\videoplayback?key=yt6&pcm2cms=yes&source=youtube&upn=bvh7NDrR9gE&signature=CF37DF8E86925FD61ADC6AC1936AD549AB5C2F16.9BEAEBFB6B07D129EE7284D85DFE59BB895A40E3&ratebypass=yes&lmt=1446860625193672&expire=1451316500&sver=3&ipbits=0&requiressl=yes&mime=video%2Fmp4&mt=1451294852&dur=284.815&mv=m&initcwndbps=1945000&ms=au&itag=22&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&fexp=9407705%2C9416126%2C9420452%2C9420772%2C9422481%2C9422596%2C9423037%2C9423662%2C9424822%2C9426471%2C9426494&id=o-AMUCyoCu4OKOwPw2ipCHDXxGMPqgaP6LQjwsN67E3LrN&mm=31&ip=46.223.128.50&mn=sn-35cxacf-nugl&pl=17```

I get the following error: 
```
 core access error: VLC could not open the file "D:\workspace-javafx\jSona-maven\https:\\r3---sn-35cxacf-nugl.googlevideo.com\videoplayback?key=yt6&pcm2cms=yes&source=youtube&upn=bvh7NDrR9gE&signature=CF37DF8E86925FD61ADC6AC1936AD549AB5C2F16.9BEAEBFB6B07D129EE7284D85DFE59BB895A40E3&ratebypass=yes&lmt=1446860625193672&expire=1451316500&sver=3&ipbits=0&requiressl=yes&mime=video%2Fmp4&mt=1451294852&dur=284.815&mv=m&initcwndbps=1945000&ms=au&itag=22&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&fexp=9407705%2C9416126%2C9420452%2C9420772%2C9422481%2C9422596%2C9423037%2C9423662%2C9424822%2C9426471%2C9426494&id=o-AMUCyoCu4OKOwPw2ipCHDXxGMPqgaP6LQjwsN67E3LrN&mm=31&ip=46.223.128.50&mn=sn-35cxacf-nugl&pl=17
```

For some reasons vlc thinks that this url is a local file. Do someone know what the problem is there?

I play the url with the following code line:
```
mediaPlayer.playMedia(url);
```

```mediaPlayer``` is a ```EmbeddedMediaPlayer```

**Comment by frankred** [comment]
I'm using vlcj ```3.9.0``` and vlc ```vlc-3.0.0-git-20151220-0402-win64```

**Comment by caprica** [comment]
"\\" and "\" are not valid in URLs. Should be "//" and "/".

**Comment by frankred** [comment]
*facepalm* thank you for that I didn't see that :+1:
