### ISSUE TITLE
Polymorphism problem

### ISSUE THREAD

**Issue by gam2046** [caprica/vlcj#452]
Hello

I hope to do a MediaListPlayer, but I am not satisfied with the implementation of EmbeddedMediaListPlayerComponent.
So I try to inherit EmbeddedMediaPlayerComponent. I also inherited the MediaPlayerFactory/MediaList. But all of MediaList's method is the final state, I cannot override him, MediaList is a class and not an interface.
So, I can only low-level interfaces to achieve, may I ask whether you can MediaList/MediaPlayerFactory abstraction of a interface?

I just want to change the behavior of MediaList, because the class does not really achieve a playlist.

Thanks

**Comment by caprica** [comment]
What methods of MediaList do you want to override, and why?

MediaList must deal with native implementation details of LibVLC, it is not a general purpose playlist.

**Comment by gam2046** [comment]
Thanks.

[EmbeddedMediaListPlayerComponent][1] provides a simple play list support. The method `getMediaList()` and `getMediaListPlayer()`  are returned to the [`MediaList`][2] object and the [`MediaListPlayer`][3] object, respectively. `MediaList` only provides `addMedia (mrl, mediaOptions)` method to add media information. But I would like to add media information, including titles, artists, etc., is not just a MRL. Like the structure of [libvlc_meta_t][4]. But these are not available in `EmbeddedMediaListPlayerComponent`/`MediaListPlayer`/`MediaList`. So I want to achieve these functions.

My approach is to inherit the class `EmbeddedMediaPlayerComponent`, and override the construction method and `onGetMediaPlayerFactory`(return my factory that inherit `MediaPlayerFactory`). The factory build the MediaList which I inherited.

I hope to add media, in addition to the MRL can also set the title, subtitles, artists, and so on. And these information can show to the user in the future.

[1]:http://caprica.github.io/vlcj/javadoc/3.9.0/uk/co/caprica/vlcj/component/EmbeddedMediaListPlayerComponent.html
[2]:http://caprica.github.io/vlcj/javadoc/3.9.0/uk/co/caprica/vlcj/medialist/MediaList.html
[3]:http://caprica.github.io/vlcj/javadoc/3.9.0/uk/co/caprica/vlcj/player/list/MediaListPlayer.html
[4]:http://www.videolan.org/developers/vlc/doc/doxygen/html/group__libvlc__media.html#ga90e7814a020f87d4c443d8d09b6dd4a0

**Comment by caprica** [comment]
I don't understand why you can't just maintain that information in your own classes.

**Comment by gam2046** [comment]
I think this information is related to the play list, which is more suitable for maintenance in the play list. And LibVlc provides such a method [libvlc_media_set_meta][2].

There is a reason, and I hope that when playing, showing titles, subtitles, VLC has this feature, and I don't need to write it again. Just need to tell the information to VLC.

[1]:http://www.videolan.org/developers/vlc/doc/doxygen/html/group__libvlc__media__list.html#gab1dea4f59a23ee3e151a34704f2b8bc5
[2]:http://www.videolan.org/developers/vlc/doc/doxygen/html/group__libvlc__media.html#gae116bf2e93c0e51aa5824f6e69aeaa64

**Comment by caprica** [comment]
But the intent of MediaList is not to be a general purpose play-list. The intent has always been that you maintain a play-list in your own application using your own classes, and only use the vlcj classes to interface with the media player.

The libvlc_media_set_meta method is supposed to be used to update the media meta information in the media file.

Whatever you come up with here, you will still have to have your own application be responsible for showing sub-titles. Whether that information comes from a vlcj class or one of your own classes doesn't really matter, so it might as well be your own implementation of a play-list.

vlcj does not implement a general purpose play-list because your requirements for a play-list are likely to be a little bit different to someone else's requirements for a play-list. A play-list is inherently application code, in my view at least.

I just don't see a compelling reason to build this into vlcj quite honestly.

**Comment by gam2046** [comment]
Anyway thank you for your reply.
Well, I think so. I think play list should be maintained by myself,  but many of the class / method / field  in vlcj are `final` or `private`, so I have no way to inheritance and overriding. I have two ways, one is download the source code, then remove the `final` or  changing `private` to `protected`; another is use reflection to access private members(final method cannot override anyway). But these two are not a good choice, I can only choose the former.

**Comment by caprica** [comment]
When I've used play-lists before with vlcj, I implement my own play-list class. It can have whatever meta-data I want associated with it, and it has an MRL. That MRL can be used to tie together the item in the vlcj MediaList and the play-list item in a non-vlcj PlayList class.

Keep the play-list and the vlcj MediaList completely separate, linked only by the MRL.

I think you are trying to use the vlcj MediaList for a purpose for which it was not intended when I originally designed it this way - that is why things are intentionally declared final.

**Comment by AlihassanProgrammer** [comment]
i think you use interface concept ..... all the methods must be implements which use frequently .. after that just implement interface
