### ISSUE TITLE
Problem playing video in Ubuntu 32bit with JDK1.6

### ISSUE THREAD

**Issue by amrit-sbagga** [caprica/vlcj#453]
Hi caprica,

I'm trying to play video file (.mp4 video) in Ubuntu 32 bit (14.04 LTS) using vlcj (v3.9.0), but application is getting crashed after playing video for some 1-2 sec and it's throwing this log exception:

 <b>A fatal error has been detected by the Java Runtime Environment:
 SIGSEGV (0xb) at pc=0x25deb260, pid=9426, tid=634358592
JRE version: 6.0_45-b06
Java VM: Java HotSpot(TM) Server VM (20.45-b01 mixed mode linux-x86 )
Problematic frame:
C  [libswscale.so.2+0x3c260]  short+0x10d60
If you would like to submit a bug report, please visit:</b>
http://java.sun.com/webapps/bugreport/crash.jsp

Full log here:
[hs_err_pid9426.txt](https://github.com/caprica/vlcj/files/80766/hs_err_pid9426.txt)

I tried searching for some workarounds & had already gone through this link (https://github.com/caprica/vlcj/issues/62) where it is mentioned that vlcj has problems with Ubuntu 32 bit and JDK 1.7, so I tried switching it to JDK1.6 (currently using JDK1.6.0_45), but still I'm getting this issue.

FYI, The same code works well in Windows7 with both JDK1.6 & 1.7. So, is there any solution for this issue. Let me know if you need more information.

**Comment by caprica** [comment]
Does the vlcj test player (from the vlcj test sources) work without crashing?

**Comment by amrit-sbagga** [comment]
The above error with <b>problematic frame C [libwscale.so.2+0x3c260] </b> occurs when I try to play video file along with loading images in my project, however I have created sample project & tried playing video file alone without images, program similar to Example2 in vlcj.
https://github.com/caprica/vlcj/blob/master/src/test/java/uk/co/caprica/vlcj/test/quickstart/Example2.java

Sample Program:

    public class MyVLCJPlayer {

	public static String FILE_TO_PLAY_WINDOWS = "D:" + File.separator + "root"
			+ File.separator + "TipScreenCapture" + File.separator + "data"
			+ File.separator + "Sharp.mp4";

	public static String FILE_TO_PLAY_LINUX = File.separator + "root"
			+ File.separator + "TipScreenCapture" + File.separator + "data"
			+ File.separator + "Sharp.mp4";

	/*
	 * public static String OS = System.getProperty("os.name").toLowerCase();
	 * 
	 * public static boolean isWindows() { return (OS.indexOf("win") >= 0); }
	 */

	private final JFrame frame;

	private final EmbeddedMediaPlayerComponent mediaPlayerComponent;

	public static void main(String[] args) {
		new NativeDiscovery().discover();

		// final String mrl = args[0];

		SwingUtilities.invokeLater(new Runnable() {
			@Override
			public void run() {

				MyVLCJPlayer vlcjPlayer = new MyVLCJPlayer();

				if (RuntimeUtil.isWindows()) {
					vlcjPlayer.start(FILE_TO_PLAY_WINDOWS);
				} else if (RuntimeUtil.isNix()) {
					vlcjPlayer.start(FILE_TO_PLAY_LINUX);
				} else {
					System.out.println("--Another OS--");
				}
			}
		});

	}

	public MyVLCJPlayer() {
		mediaPlayerComponent = new EmbeddedMediaPlayerComponent();

		frame = new JFrame("MyVLCJPlayer");
		frame.setLocation(50, 50);
		frame.setSize(1400, 800);
		frame.setContentPane(mediaPlayerComponent);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.setVisible(true);
	}

	private void start(String file_to_play) {

		mediaPlayerComponent.getMediaPlayer().playMedia(file_to_play);
		
	}

But now it's crashing with this error:
 # A fatal error has been detected by the Java Runtime Environment:
 #
 #  SIGSEGV (0xb) at pc=0xb7735036, pid=4424, tid=771324736
 #
 # JRE version: 6.0_45-b06
 # Java VM: Java HotSpot(TM) Server VM (20.45-b01 mixed mode linux-x86 )
 # Problematic frame:
 # C  [libpthread.so.0+0x9036]  __pthread_mutex_lock+0x16
 #
 # If you would like to submit a bug report, please visit:
 #   http://java.sun.com/webapps/bugreport/crash.jsp
 # The crash happened outside the Java Virtual Machine in native code.
 # See problematic frame for where to report the bug.
 #

Full log here: 
[hs_err_pid4424.txt](https://github.com/caprica/vlcj/files/81046/hs_err_pid4424.txt)

**Comment by caprica** [comment]
Please try an *unchanged* vlcj test application.

**Comment by amrit-sbagga** [comment]
Hi Mark,

I tried to run unchanged version of TestPlayer from vlcj, but while running <b>java -jar vlcj-3.11.0-SNAPSHOT-tests.jar</b> I'm getting 
<b>
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
        at uk.co.caprica.vlcj.test.VlcjTest.<clinit>(VlcjTest.java:53)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 1 more</b

where META-INF/MANIFEST.MF file for vlcj-3.11.0-SNAPSHOT-tests.jar contains:

<b>Manifest-Version: 1.0
Built-By: amritsingh
Build-Jdk: 1.6.0_45
Class-Path: vlcj-3.11.0-SNAPSHOT.jar jna-4.1.0.jar jna-platform-4.1.0.
 jar slf4j-api-1.7.10.jar
Created-By: Apache Maven 3.0.4
Main-Class: uk.co.caprica.vlcj.test.basic.TestPlayer
Archiver-Version: Plexus Archiver</b>

& META-INF/MANIFEST.MF for vlcj-3.11.0-SNAPSHOT.jar contains:
<b>
Manifest-Version: 1.0
Built-By: amritsingh
Build-Jdk: 1.6.0_45
Class-Path: jna-4.1.0.jar jna-platform-4.1.0.jar slf4j-api-1.7.10.jar
Created-By: Apache Maven 3.0.4
Archiver-Version: Plexus Archiver</b>

Hence, I experimented changing sl4j version to 1.7.12 / 1.7.13 in pom.xml but both of them won't worked & same issue (NoClassDefFoundError: org/slf4j/LoggerFactory) often arises while running jar after mvn package. So, I need your support to solve this issue to proceed further with video test in linux with jdk1.6. Also, I'm not an expert in maven builds, so kindly help me I'm doing anything wrong.

**Comment by caprica** [comment]
The easiest (imho) thing to do is to clone the vlcj tagged version you want from the github repository, import it as a maven project into your IDE, and then and run the vlcj test from your IDE.

**Comment by amrit-sbagga** [comment]
All those things I've done in my Windows7-PC, imported as maven project & succesfully able to build and run project , TestPlayer is working fine but I need a runnable jar file to be able to test video player in linux box.

**Comment by caprica** [comment]
You can't put an IDE on your Linux box?

**Comment by amrit-sbagga** [comment]
As of now I won't have linux box with me, it's with another guy, so will try to install IDE in it & test run the vlcj Testplayer, will update you further with my test results when I'll get the box.

**Comment by caprica** [comment]
The alternative is to put the dependent jars in the right place, set the classpath (in a shell script if you want) and do it that way.

You must already be doing something like this with your own code, so why can't you do the same with the vlcj app?

I mean, old-school something like "java -cp vlcj.jar:jna.jar:platform.jar:slf4j.jar uk.co.caprica.vlcj.test.TestPlayer".

It would be better if the test jar had a correct manifest of course.

**Comment by amrit-sbagga** [comment]
Hi Mark, thanks for the old-school method, I've tested vlcj TestPlayer in Ubuntu with JDK1.6_45 and it works very well without any crash, but I'm still not able to figure out why sample program (MyVLCJPlayer.java that I've posted in above comments) is getting crashed after 2-3 sec throwing fatal error with problemetic frame C [libpthread.so.0+0x9036] . 

Also I've tried to execute another sample example VLCPlayer.java code slightly different from MyVLCJPlayer.java with usage of canvas and mediaplayerfactory 
[VLCPlayer.txt](https://github.com/caprica/vlcj/files/82631/VLCPlayer.txt)

With this video plays very well but sometimes it crashes with this logs in terminal window:
<b>
Fontconfig warning: FcPattern object size does not accept value "0"
Fontconfig warning: FcPattern object size does not accept value "0"
Fontconfig warning: FcPattern object size does not accept value "0"
Fontconfig warning: FcPattern object size does not accept value "0"
[0x29e4ba50]
vmem vout display error: video format setup failure (no pictures)
[0x29e229c0] 
main video output error: video output creation failed
[0x2d977d98] 
main decoder error: failed to create video output
Fontconfig warning: 
FcPattern object size does not accept value "0"
Fontconfig warning: FcPattern object size does not accept value "0"
[0x957d6d8]
main vout display error: Failed to change zoom
[0x957d6d8] 
main vout display error: Failed to set on top
[0x957d6d8] 
main vout display error: Failed to change source AR
</b>

**Comment by caprica** [comment]
If the vlcj sample works, then only you can work out the difference with your own code. The most obvious mistake is that your vlcj objects get garbage collected when you don't expect it.

For the FontConfig stuff, you say "crash" but is it really a crash or just message sin the log?

The FontConfig stuff smacks of multiple concurrent media players to me.

**Comment by amrit-sbagga** [comment]
Kindly excuse for the word "crash", actually it won't crash but it won't allow to view the output frame,  I'll try to figure out differences in my sample code & thanks a lot for all your support.

**Comment by caprica** [comment]
Maybe post a minimal test case.

**Comment by caprica** [comment]
Actually, after further review it's probably that your objects are being garbage collected, look at this:

```
@Override
public void run() {
    MyVLCJPlayer vlcjPlayer = new MyVLCJPlayer();
    ...
}
```
When that run() method exits, your `vlcjPlayer` object is no longer reachable by any live object in the system, and so is eligible for garbage collection. When you Java object is garbage collected, the native VLC thread is still running and trying to call back into Java, and eventually something crashes.

You must make sure you keep a hard reference to your object to pin it in memory.
