### ISSUE TITLE
Compatibility between vlcj.x.x.x.jar and vlc version

### ISSUE THREAD

**Issue by ferrusqui** [caprica/vlcj#454]
os: windows 7 64bit
java version: jdk1.8.0_45

I didn't find a guide in order to understand which version of the vlcj library is compatible with which version of VLC.

I need to open an rtsp h264 stream from a FOSCAM camera.

the only configuration let me open the stream is 
vlcj.3.9.0
jna.3.5.2
vlc 2.1.2

unfortunatelly with this version of vlc, after some minutes of streaming, something appens and the image freezes. ( I can reproduce the situation also using directly VLC).
For this reason I downloaded the VLC 2.2.1. With this version there is no freeze problem using VLC, but I'm not able to use vlcj with this version of VLC. 
This is the log

[Thread-2] INFO uk.co.caprica.vlcj.Info - vlcj: 3.9.0
[Thread-2] INFO uk.co.caprica.vlcj.Info - java: 1.8.0_45 Oracle Corporation
[Thread-2] INFO uk.co.caprica.vlcj.Info - java home: C:\Program Files\Java\jdk1.8.0_45\jre
[Thread-2] INFO uk.co.caprica.vlcj.Info - os: Windows 7 6.1 amd64
[Thread-2] INFO uk.co.caprica.vlcj.binding.LibVlcFactory - vlc: 2.2.1 Terry Pratchett (Weatherwax), changeset 2.2.1-0-ga425c42
[Thread-2] INFO uk.co.caprica.vlcj.binding.LibVlcFactory - libvlc: D:\vlc-2.2.1\libvlc.dll
[0000000000362980] core input error: open of `rtsp://admin:admin@192.168.0.106:88/videoMain' failed
[0000000000362980] core input error: Your input can't be opened
[0000000000362980] core input error: VLC is unable to open the MRL 'rtsp://admin:admin@192.168.0.106:88/videoMain'. Check the log for details.

I tried to download also the vlcj-3.10.1 with the jna-4.1.0.
but using this libraries I receive an error:

[Thread-2] INFO uk.co.caprica.vlcj.Info - vlcj: 3.10.1
[Thread-2] INFO uk.co.caprica.vlcj.Info - java: 1.8.0_45 Oracle Corporation
[Thread-2] INFO uk.co.caprica.vlcj.Info - java home: C:\Program Files\Java\jdk1.8.0_45\jre
[Thread-2] INFO uk.co.caprica.vlcj.Info - os: Windows 7 6.1 amd64
[Thread-2] INFO uk.co.caprica.vlcj.binding.LibVlcFactory - vlc: 2.2.1 Terry Pratchett (Weatherwax), changeset 2.2.1-0-ga425c42
[Thread-2] INFO uk.co.caprica.vlcj.binding.LibVlcFactory - libvlc: D:\vlc-2.2.1\libvlc.dll
[000000000030fdb0] core libvlc error: No plugins found! Check your VLC installation.
[Thread-2] ERROR uk.co.caprica.vlcj.player.MediaPlayerFactory - Failed to initialise libvlc
Exception in thread "Thread-2" java.lang.RuntimeException: Failed to initialise libvlc.

This is most often caused either by an invalid vlc option being passed when creating a MediaPlayerFactory or by libvlc being unable to locate the required plugins.

at uk.co.caprica.vlcj.player.MediaPlayerFactory.<init>(MediaPlayerFactory.java:300)
	at uk.co.caprica.vlcj.player.MediaPlayerFactory.<init>(MediaPlayerFactory.java:259)
	at uk.co.caprica.vlcj.component.DirectMediaPlayerComponent.onGetMediaPlayerFactory(DirectMediaPlayerComponent.java:180)
	at uk.co.caprica.vlcj.component.DirectMediaPlayerComponent.<init>(DirectMediaPlayerComponent.java:112)
	at videosurv.live.Playervlcj$4.<init>(Playervlcj.java:250)
	at videosurv.live.Playervlcj.connect(Playervlcj.java:250)
	at videosurv.live.Playervlcj.run(Playervlcj.java:450)
	at java.lang.Thread.run(Thread.java:745)

Clearly the VLC used works normally. I checked and libvlc.dll and libvlccore.dll are present.

The playervlcj.java:250 is 

 mediaPlayerComponent = new DirectMediaPlayerComponent(bufferFormatCallback) {
            @Override
            protected RenderCallback onGetRenderCallback() {
                return new TutorialRenderCallbackAdapter();
            }
        };

**Comment by caprica** [comment]
You say this:

> I can reproduce the situation also using directly VLC

So that's not a vlcj issue.

All recent versions of vlcj require vlc 2.x or later. There is conditional code in vlcj to enable extra features if you are running VLC 2.1.x, VLC 2.2.x or the development snapshot VLC 3.0.x.

Your log shows VLC can not open this MRL:

> rtsp://admin:admin@192.168.0.106:88/videoMain

vlcj does not care about your MRL, it passes it directly to LibVLC. There is at least one other issue here about playing RTSP MRLs not working, I don't recall which number it is, but it was not a problem with vlcj.

For the last part of your post:

I explicitly tested vlcj 3.10.1 on Windows with JNA 4.1.0 and it worked for me.

Going from JNA 3.x to JNA 4.x has unfortunately caused some really annoying problems with LibVLC.

I would like to understand why it's not working for you, so please would you post some idea of what your VLC installation directory looks like - I need to see where the plugins directory is in relation to libvlc.dll.

**Comment by caprica** [comment]
I am thinking about reverting vlcj back to JNA 3.x rather than 4.x because frankly the latest JNA does nothing for vlcj except make it more difficult to use.

**Comment by ferrusqui** [comment]
Did you try vlcj3.10.1 and what version of VLC?
you suggest to set the VLC_PLUGIN_PATH at start time of the JVM, but in my tests with the old version of jvlc this variable was not set. Now is it needed with the latest version of vlcj?

**Comment by caprica** [comment]
I tried vlcj 3.10.1 and VLC 2.2 on Windows.

Setting VLC_PLUGIN_PATH is needed because of the upgrade to JNA 4.x, but vlcj 3.10.1 attempts to set it automatically.

**Comment by ferrusqui** [comment]
I tried to come back with JNA 3.x, and I tested a lot of VLC versions, but I receive always the same answer:

[0000000000288420] core input error: open of `rtsp://admin:admin@192.168.0.106:88/videoMain' failed
[0000000000288420] core input error: Your input can't be opened
[0000000000288420] core input error: VLC is unable to open the MRL 'rtsp://admin:admin@192.168.0.106:88/videoMain'. Check the log for details.

Can I ask you what kind of test you did?
Did you try to get a rtsp h264 stream?

**Comment by caprica** [comment]
There are two different issues here. The first relates to JNA 4.1 and VLC_PLUGIN_PATH. That is *supposed* to be solved with vlcj 3.10.1, and I'd like to know why it doesn't work in your case.

The second different issue is a failure to play an RTSP MRL. I can only refer you to the issue you raised before #427 and the related #362.

**Comment by ferrusqui** [comment]
Do you think it could be a good idea to try with Linux? I have no constraints on windows, I will not  be happy if Linux is the solution, but it's better than nothing

**Comment by caprica** [comment]
I use Linux all the time.

I occasionally test on Windows.

**Comment by ferrusqui** [comment]
What distribution?

And what version of VLC?

**Comment by caprica** [comment]
Linux Mint 17.2 64bit

VLC 2.2.x, or VLC 3.0.0-git

Probably the root of your problem is something wrong with secured RTSP
streams through LibVLC on Windows. I can't say any more than that.

The linked issue above proves that vlc can successfully play a secured RTSP
stream, although unfortunately not in your case.

**Comment by ferrusqui** [comment]
I was really sure you was right with the problem about the secured RTSP, and for this reason I disabled the firewall, but I receive always the same error.
Could you please give me the sources of the example that runs for you? Also all the libraries..
Maybe I did a mistake somewere in the code.....

**Comment by caprica** [comment]
Please see https://github.com/caprica/vlcj/issues/362#issuecomment-83991403 and https://github.com/caprica/vlcj/issues/362#issuecomment-83990005.

**Comment by ferrusqui** [comment]
But there are sources in c language, do you have Java sources?

**Comment by caprica** [comment]
Quoting the first linked comment:
>I used the vlcj "MinimalTestPlayer" [Java] with the URL exactly as you provided. I did not mess around with --rtsp-user switches."

The second linked comment shows an MRL with credentials, e.g.:

>rtsp://admin:9999@1.2.3.4:8888/h264

That's what I used to successfully test this (on Linux).

No "C" code is needed.

**Comment by ferrusqui** [comment]
I tried with Ubuntu 14.04 and VLC 2.2.1, and it works fine.
I tried again also with windows 10, but there is always the same error.
I think it's a bad limitation if we can't use windows, where can I find an help?
How can I enable a more verbose log?
Any other suggestions?

**Comment by caprica** [comment]
I understand your frustration, but really vlcj does nothing different here when you run on Linux or Windows 10. Your problem must be down to some issue with VLC on Windows 10.

You can enable native logging with "-vvv" when you create the media player factory.

You could then compare the output on Linux with that on Windows.

**Comment by ferrusqui** [comment]
I tried with a different camera.
This camera has in the password a character "@", this means that the mrl is like this:
admin:xxxx@yyy@192.168.1.10/onvif/profile2/media.smp.

Always in windows, if I try to use VLC 2.1.2 all works normally, if I try to use a greater VLC (2.2.1 e.g.) I receive this error:

[00000000001a61d0] core demux error: corrupt module: D:\vlc-2.2.1\plugins\access\liblive555_plugin.dll
[00000000001a61d0] core access error: cannot resolve yyy@192.168.1.10 port 554 : Errore irreversibile durante una ricerca del database. 
[00000000001a61d0] access_realrtsp access error: cannot connect to yyy@192.168.1.10:554
[00000000001a61d0] core access error: Connection failed
[00000000001a61d0] core access error: VLC could not connect to "yyy@192.168.1.10:554".
[000000000018f070] core input error: open of `rtsp://admin:xxxx@yyy@192.168.1.10/onvif/profile2/media.smp' failed
[000000000018f070] core input error: Your input can't be opened
[000000000018f070] core input error: VLC is unable to open the MRL 'admin:xxxx@yyy@192.168.1.10/onvif/profile2/media.smp'. Check the log for details.
 

Starting from this log it seems that there is a different way to get username and password using VLC 2.1.2 and VLC 2.2.1, is it possible? 
In general terms I think we can say that there is a difference in the use of the MRL from those two VLC version.....
Do you think this could be the problem?
I can't test with linux here.....

**Comment by ferrusqui** [comment]
I forgot to say that using the mrl directly inside VLC I can see the images......also in the 2.2.1

**Comment by caprica** [comment]
I think in this case VLC is getting confused about the "@" in the password when it parses the MRL. It tries to resolve "yyy@192.168.1.10" as the host name it seems.

The obvious thing to try is a password without that @ character.

**Comment by ferrusqui** [comment]
Yes sure, but with VLC 2.1.2 this exact string works perfectly. It seems that something is changed in the procedure to pass the MRL to VLC, at least with the windows release of VLC.
Do you agree with me or do I forget something in my analysis?

**Comment by caprica** [comment]
I can only speak from vlcj's point of view. vlcj does nothing with your MRL at all, it just gets passed to to LibVLC. The only thing that's different here is VLC isn't it.

**Comment by ferrusqui** [comment]
Yes, I agree with you.
I think that the libvlc.dll related to VLC 2.2.1 should be different from libvlc.so in the way it get the MRL.
For this reason, can you check if something is changed in the latest version of VLC, please?
It will be very appreciated, and I think it should be good also in order to have a better compatibility with windows for JVLC.

**Comment by caprica** [comment]
This really can't be fixed in vlcj - there is one native API method in
libVLC that vlcj uses for this, there is no other option. So I can't change
anything in vlcj here.

**Comment by ferrusqui** [comment]
Ok I got it.
Where can I ask info about the development of the libvlc.dll (and libvlc.so I hope....)?
