### ISSUE TITLE
Possible GC issue?

### ISSUE THREAD

**Issue by hjohn** [caprica/vlcj#455]
Not sure if this is considered an issue, but it threw me off when debugging something, and may throw off other users or explain some of the problems people sometimes see.  It seems the below program, even though it keeps playing video, garbage collects the event listener (or maybe the mediaplayer) after a short while -- this stops the System.out output, but the video keeps playing.

Assigning the mediaPlayer to a static variable solves the gc issue.  The docs don't seem to make mention of this.

``` Java
import java.awt.BorderLayout;
import java.awt.Canvas;
import java.awt.Frame;
import java.util.ArrayList;
import java.util.List;

import com.sun.jna.NativeLibrary;

import uk.co.caprica.vlcj.player.MediaPlayer;
import uk.co.caprica.vlcj.player.MediaPlayerEventAdapter;
import uk.co.caprica.vlcj.player.MediaPlayerFactory;
import uk.co.caprica.vlcj.player.embedded.EmbeddedMediaPlayer;

public class PlayVideo {
  public static void main(String[] args) {
    NativeLibrary.addSearchPath("libvlc", "c:/program files/VideoLAN/VLC");

    List<String> arguments = new ArrayList<>();

    MediaPlayerFactory factory = new MediaPlayerFactory(arguments);

    EmbeddedMediaPlayer  mediaPlayer = factory.newEmbeddedMediaPlayer();

    Canvas canvas = new Canvas();

    mediaPlayer.setVideoSurface(factory.newVideoSurface(canvas));
    mediaPlayer.addMediaPlayerEventListener(new Listener());

    Frame playerFrame = new Frame();

    playerFrame.setLayout(new BorderLayout());
    playerFrame.setSize(200, 200);
    playerFrame.setBackground(new java.awt.Color(0, 0, 0));
    playerFrame.setVisible(true);
    playerFrame.add(canvas, BorderLayout.CENTER);
    playerFrame.doLayout();

    mediaPlayer.setRepeat(false);
    mediaPlayer.setPlaySubItems(true);
    mediaPlayer.playMedia("some-video-file.mkv");
  }

  static class Listener extends MediaPlayerEventAdapter {
    @Override
    public void timeChanged(MediaPlayer mediaPlayer, long newTime) {
      System.out.println(Thread.currentThread().getName() + " (" + Thread.currentThread().getId() + "): Time: " + newTime);
    }
  }
}
```

**Comment by caprica** [comment]
This, or something very similar, is actually documented - albeit in the tutorial rather than the Javadoc. I should probably add more to the Javadoc. At least I should make it more prominent.

**Comment by hjohn** [comment]
Nice tutorial, I see I'm a bit behind with some newer developments.

Looks like the problems I'm having are all related to the 64-bit version of VLC (2.2 seems to be the first time a 64-bit version was created for Windows).  Some of the plugins just don't seem to work that well.  Even the native player is having problems with some files, although there's big differences between libvlc and VLC itself.

**Comment by caprica** [comment]
I see various problems with Win64 builds, there are a number of issues raised here already that are due I think to bad plugins with VLC on Win64.
