### ISSUE TITLE
run java vlcj in raspberry pi has several errors

### ISSUE THREAD

**Issue by kscorpio** [caprica/vlcj#456]
1 This object event manager doesn't know about 'MediaListPlayerStopped' events

[0x1e59d80] pulse audio output error: PulseAudio server connection failure: Connection refused
[0x5d702a80] xcb_xv vout display error: no available XVideo adaptor
[swscaler @ 0x6186d360] No accelerated colorspace conversion found from yuv420p to rgb565le.

**Comment by kscorpio** [comment]
does vclj support raspiberry pi arm architecture？

when i used  MediaListPlayer in windows 7 64 it works well
but in raspiberry pi cannot work well . it cannot play next video ，when pass a list of video to it

and when i  add MediaPlayerEventListener to it, raspiberry cannot respond to method  
@Override
public void finished(MediaPlayer arg0) {

**Comment by kscorpio** [comment]
public class VLCPlayer {  
      private volatile static VLCPlayer singleton;  
      private MediaPlayerFactory mediaPlayerFactory;
      private EmbeddedMediaPlayerComponent mediaPlayerComponent;
  	  private EmbeddedMediaPlayer mediaPlayer;
  	  private MediaListPlayer mediaListPlayer;

  	  // this used to make mediaPlayer to play list of videos
  	  private List<String> destFile;
  	  private int index=0;
     private VLCPlayer ( ){ 
     }   
      public static VLCPlayer getSingleton( ) {  
     if (singleton == null) {  
          synchronized (VLCPlayer.class) {  
         if (singleton == null) {  
              singleton = new VLCPlayer();  
         }  
         }  
      }  
     return singleton;  
      }  
      
      
      public boolean initVlc(){
    	  String lib=Os.isWindows()?"C:/Program Files/VideoLAN/VLC/":"";
       
  		try {
  			 
  			 NativeLibrary.addSearchPath(RuntimeUtil.getLibVlcLibraryName(), lib);
  			 Native.loadLibrary(RuntimeUtil.getLibVlcLibraryName(), LibVlc.class);  			 
  			 LibXUtil.initialise(); 
  		     return true;
  	  		 
		} catch (Throwable  e) {
			// TODO: handle exception  
			return false; 
		}  
      }
      
      
      
     public void initPlayer(){
     	//
     	//  here is another problem ，when system is linux , will has black screen 
     	//  so i use the list to init MediaPlayerFactory
     	//
    	  if(Os.isWindows()){ 
     		 mediaPlayerFactory = new MediaPlayerFactory( ); 
     	 }else{ 
     	   List<String> vlcArgs = new ArrayList<String>();
            vlcArgs.add("--file-caching=1000");
            vlcArgs.add("--sout-ts-pcr=40 ");
            vlcArgs.add("--no-ts-es-id-pid");
            vlcArgs.add("--sout-keep");
            vlcArgs.add("--ignore-config");
            vlcArgs.add("--dscp=144");
            vlcArgs.add("--sout-udp-group=5");
            vlcArgs.add("--sout-all");
            vlcArgs.add("--sout-ts-dts-delay=100");
            vlcArgs.add("--vout=dummy");
            vlcArgs.add("--audio-language=eng");
            vlcArgs.add("--no-xlib");
            vlcArgs.add("--swscale-mode=0");
            mediaPlayerFactory = new MediaPlayerFactory(vlcArgs); 
     	 }
    	 mediaPlayer = mediaPlayerFactory.newEmbeddedMediaPlayer(  );
    	 mediaPlayer.setFullScreen(true);
 	     mediaPlayer.setAdjustVideo(false);	 
 	     mediaPlayer.setRepeat(false);
 	     mediaPlayer.addMediaPlayerEventListener(new MediaPlayerEventListener() {
			
			@Override
			 // several methods

			  .... ...
			 
		});
         mediaPlayer.toggleFullScreen();
  	 
      }
      
    public void initListPlayer(){
   	  initPlayer();
   	  mediaListPlayer = mediaPlayerFactory.newMediaListPlayer();
//          mediaListPlayer.addMediaListPlayerEventListener(new MediaListPlayerEventAdapter() {
//              
//          }); 
         mediaListPlayer.setMediaPlayer(mediaPlayer); 
     }
      
public void setContainer(Canvas VideoPanel){
  if(mediaPlayer!=null){ 
     mediaPlayer.setVideoSurface(mediaPlayerFactory.newVideoSurface(VideoPanel));
    }     	  
 }
      
      
      
/*
 *  paly a single video
 */
public void play(String path) {
 		if(mediaPlayer.isPlaying()){ 
 			mediaPlayer.stop(); 
 		}  
  		mediaPlayer.playMedia(path);  
}
 
/*
 *  play a list of viedos
 */
public void playList(List<String> destFile){
	this.destFile=destFile;
	play(destFile.get(index));

	MediaList mediaList = mediaPlayerFactory.newMediaList();
// String[] options = {"--no-sout-keep"};
   String[] options = { };
   for(int i=0;i < destFile.size();i++){
   	
   	mediaList.addMedia(destFile.get(i) , options);
   	
   }
  
   mediaListPlayer.setMediaList(mediaList);
   mediaListPlayer.setMode(MediaListPlayerMode.LOOP);
	 mediaListPlayer.play();
	
}
 


}

**Comment by caprica** [comment]
1. This object event manager doesn't know about 'MediaListPlayerStopped' events

Wrong VLC version, which VLC version are you using, with which vlcj version?

2, [0x1e59d80] pulse audio output error: PulseAudio server connection failure: Connection refused

Native error message, PulseAudio probably not available on RPI, so pick an audio output that is supported. 

Not a vlcj issue.

3, [0x5d702a80] xcb_xv vout display error: no available XVideo adaptor

Native error message, no XVideo output on RPI, pick a supported video output.

Not a vlcj issue.

4. [swscaler @ 0x6186d360] No accelerated colorspace conversion found from yuv420p to rgb565le.

Native error message, not sure what the implications of this one are.

To answer your question of is vlcj supported on RPI, well, not formally. But if VLC works on RPI, and JNA works on RPI, then vlcj should work on RPI.

**Comment by caprica** [comment]
Your last comment looks like a different issue, so please don't conflate multiple different issues into the same project issue - create a new one.

**Comment by caprica** [comment]
The MediaListPlayerStopped event was added to VLC in December 2012.

**Comment by kscorpio** [comment]
About
[swscaler @ 0x6186d360] No accelerated colorspace conversion found from yuv420p to rgb565le

i find this error may has something with ffmpeg， can vlcj can lead to errors frome ffmpeg?

**Comment by caprica** [comment]
vlcj does not care about ffmpeg. vlcj uses whatever VLC uses.

**Comment by caprica** [comment]
For information...

I do actually own an RPI-2 and have done some *limited* testing.

Passing {"--aout", "alsa"} with media player factory arguments gets past one problem.

According to my reading, the video output should be omxil, so that would mean {"--vout", "omxil"}. However, that doesn't actually work - no video is visible.

Some functions do cause segfaults... like the audio device functions, so be careful.
