### ISSUE TITLE
Is thera a vlcj demo code for linux (arm)

### ISSUE THREAD

**Issue by kscorpio** [caprica/vlcj#458]
When to init vlc ,i use the code like this
         
           if(Os.isWindows()){
               		 mediaPlayerFactory = new MediaPlayerFactory( ); 
                        --------------------------------------------------------------------  1
               	 }else{
                       --------------------------------------------------------------------  2
               	   List<String> vlcArgs = new ArrayList<String>();
                      vlcArgs.add(":file-caching=1000");
                      vlcArgs.add(":sout-ts-pcr=40 ");
                      vlcArgs.add(":no-ts-es-id-pid");
                      vlcArgs.add(":sout-keep");
                      vlcArgs.add(":ignore-config");
                      vlcArgs.add(":dscp=144");
                      vlcArgs.add(":sout-udp-group=5");
                      vlcArgs.add(":sout-all");
                      vlcArgs.add(":sout-ts-dts-delay=100");
                      vlcArgs.add(":vout=dummy");
                      vlcArgs.add(":audio-language=eng");
                      vlcArgs.add(":no-xlib");
                      vlcArgs.add(":swscale-mode=0");-----------------------------------2.1
                      mediaPlayerFactory = new MediaPlayerFactory(vlcArgs);
                    
     	 }
  
              mediaPlayer = mediaPlayerFactory.newEmbeddedMediaPlayer( ); 
 	     mediaPlayer.setAdjustVideo(true);	 
 	     mediaPlayer.setRepeat(true);
 	     mediaPlayer.setFullScreen(true);
    	  
      }
-  when i use code 1 to init vlc in linux, the video can just load the tittle and will be in black
-  so i fine the code 2 , 
- about code 2.1 will lead the video screen blurred ，

When i use MediaListPlayer ， it just stop at the end of first video, can not jump to next
for a few seconds ,terminal will show :
          [0x64e87e30] avcodec decoder error: more than 5 seconds of late video -> dropping frame (computer too slow ?)

where can i fine a standard demo code for linux？？

**Comment by kscorpio** [comment]
i use vlcj-2.4.1

**Comment by caprica** [comment]
Well, vlcj does not care (for the most part) about different OS or different architecture. Pretty much all of the standard vlcj examples in the test sources in this project should work on any OS. 

You're using RPI, right? That's an under-powered platform isn't it. Is it really capable of using Java and VLC on that platform?

**Comment by kscorpio** [comment]
But i use vlc player to play these videos in RPI  can performance well, 

however use vlcj to writer a player can not work well.

i guess something wrong in these code , without these code the player can not work in linux (but work well in windows 7)

 List<String> vlcArgs = new ArrayList<String>();
                  vlcArgs.add(":file-caching=1000");
                  vlcArgs.add(":sout-ts-pcr=40 ");
                  vlcArgs.add(":no-ts-es-id-pid");
                  vlcArgs.add(":sout-keep");
                  vlcArgs.add(":ignore-config");
                  vlcArgs.add(":dscp=144");
                  vlcArgs.add(":sout-udp-group=5");
                  vlcArgs.add(":sout-all");
                  vlcArgs.add(":sout-ts-dts-delay=100");
                  vlcArgs.add(":vout=dummy");
                  vlcArgs.add(":audio-language=eng");
                  vlcArgs.add(":no-xlib");
                  vlcArgs.add(":swscale-mode=0");-----------------------------------2.1
                  mediaPlayerFactory = new MediaPlayerFactory(vlcArgs);

**Comment by kscorpio** [comment]
or 
   vlcArgs.add("-- file-caching=1000");

replace “： ” with “ - - ”

**Comment by caprica** [comment]
So how is this expected to display video when you do ":vout=dummy" ?

**Comment by caprica** [comment]
The EmbeddedMediaPlayerComponent specifies such arguments like this:

    protected static final String[] DEFAULT_FACTORY_ARGUMENTS = {
        "--video-title=vlcj video output",
        "--no-snapshot-preview",
        "--quiet-synchro",
        "--sub-filter=logo:marq",
        "--intf=dummy"
    };

**Comment by kscorpio** [comment]
When i pass DEFAULT_FACTORY_ARGUMENTS  to MediaPlayerFactory and play video

[0x5cf9ab38] main image decoder error: no suitable decoder module for fourcc `    '. VLC probably does not support this image format.

**Comment by caprica** [comment]
The point was to show you the format the arguments used, not to say you should use those particular arguments.

You didn't answer why you are using the dummy vout... That disables video output.

**Comment by kscorpio** [comment]
Sorry  that code is from network ，i didn't know the meaning.

 I use it to play one video in raspbian-wheezy (RPI) , It can solve the black screen problem, but now just play the first frame ,then stop at the first frame,but audio work well.

Because i could not fine which value can i set,  i could not find the api or document how to set arguments  for MediaPlayerFactory

**Comment by caprica** [comment]
Essentially #456.
