### ISSUE TITLE
How to clear canvas when mediaplayer is finished

### ISSUE THREAD

**Issue by dongfangshangren** [caprica/vlcj#459]
When mediaplyer is finished, the last scene of the video is remain on the canvas, it also can't be resized, how to clear.

**Comment by caprica** [comment]
Use a CardLayout, show the video view when you get a started event, and a blank view when you get a finished or error event.

**Comment by dongfangshangren** [comment]
CardLayout will set canvas unvisible, which cause an IllegalStateException when invoke attachVideoSurface method, I create an JPanel to cover the canvas, it can work.
thanks

**Comment by caprica** [comment]
I use this exact solution, it works. You don't make the card layout
invisible at all.
