### ISSUE TITLE
Subtitle overlay not working on Windows when transcode using VLCj

### ISSUE THREAD

**Issue by acely** [caprica/vlcj#460]
Hi,I have a problem which I've been trying to fix for 1month,but still cannot be solved.I've tried everything I can find on internet.

The problem is,Subtitle overlay does not work on Windows when transcode,but works fine on Mac and Linux with the same code.Logo overlay has the same problem too.
I am using vlcj 3.10.1,VLC 2.2.1-64bit,jre1.8.0-64bit,the problem occurs in both win7-64bit and win10-64bit.

My arguments when creating MediaPlayerFactory are:
```
        "--ignore-config",
        "--no-plugins-cache",
        "--sub-type=ass",
        "--subsdec-encoding=UTF-8",
        "--sout-transcode-soverlay",
        "--sub-filter=logo:marq",
        "--no-repeat",
        "--no-loop",
        "--quiet",
        "--quiet-synchro",
        "--intf=dummy"
```
and I use this code to transcode video:
```
mediaPlayerFactory = new MediaPlayerFactory(MY_ARGUMENTS);
mediaPlayer = mediaPlayerFactory.newHeadlessMediaPlayer();
mediaPlayer.playMedia(new File("C:\1.mp4"), ":sout=#transcode{vcodec=h264,vb=2400,venc=x264{profile=main,level=4.0,keyint=30,ref=8},scale=1,deinterlace",acodec=mp3,ab=128,channels=2,samplerate=44100,soverlay,sfilter=logo}:standard{mux=ts,access=file,dst="C:\1.ts"}");

mediaPlayer.setSubTitleFile("C:\1.ass"));
```
After transcoding,I can only get a video output file without subtitle overlay,but av encoding setting are right.

At first I think maybe my VLC itself under windows may have some problem,so I created one bat file:
```
vlc.exe --no-repeat --no-loop -I dummy "C:\1.mp4" --sout=#transcode{vcodec=h264,vb=2400,venc=x264{profile=main,level=4.0,keyint=30,ref=8},scale=1,deinterlace",acodec=mp3,ab=128,channels=2,samplerate=44100,soverlay,sfilter=logo}:standard{mux=ts,access=file,dst="C:\1.ts"} vlc://quit
```
After running this bat,I can get "C:\1.ts" successfully with subtitle overlay.So my VLC itself seem to be all right.

So where is the problem?
Thanks in advance.

**Comment by acely** [comment]
Here is additional information.
If I use EmbeddedMediaPlayerComponent to play video in swing gui,subtitles will show normally.

**Comment by caprica** [comment]
You did not escape your backslash as per.

**Comment by caprica** [comment]
Closing, reopen if any more feedback.
