### ISSUE TITLE
How to disable vlc to show the file & set full screen?

### ISSUE THREAD

**Issue by kscorpio** [caprica/vlcj#461]
1  When the vlc prepare to play a video, it will show the fine name first.
How to disable it?

2 when the screen is 16:9 but video is 4:3 , how to set vlc to stretch video to full screen

 mediaPlayer.setAdjustVideo( );	   mediaPlayer.setFullScreen( );  does not work well

**Comment by caprica** [comment]
Please post separate issues, one problem per issue.

#185
