### ISSUE TITLE
RTSP stream does not open

### ISSUE THREAD

**Issue by diegotsu** [caprica/vlcj#462]
Hi, I'm having problems trying to play a rtsp streaming using VLCJ. Opening the streaming in VLC it works fine, but when trying with VLCJ it doesn't. I'm running on windows. Here is the code:

    package snitchplayer;
    
    import java.awt.Dimension;
    
    import javax.swing.JFrame;
    import com.sun.jna.NativeLibrary;
    import uk.co.caprica.vlcj.component.EmbeddedMediaPlayerComponent;
    import uk.co.caprica.vlcj.runtime.RuntimeUtil;
    import uk.co.caprica.vlcj.discovery.NativeDiscovery;
    
    public class SnitchPlayer
    {
    	private JFrame ourFrame = new JFrame();
    	private EmbeddedMediaPlayerComponent ourMediaPlayer;
    	private String mediaPath="";
    	
    	SnitchPlayer(String mediaURL)
    	{
    		new NativeDiscovery().discover();
    		this.mediaPath = mediaURL;
    		//NativeLibrary.addSearchPath(RuntimeUtil.getLibVlcLibraryName(), vlcPath);
    		ourMediaPlayer = new EmbeddedMediaPlayerComponent();
    		ourFrame.setContentPane(ourMediaPlayer);
    		ourFrame.setSize(1200, 738);
    		ourFrame.setVisible(true);
    		ourFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    	}
    	
    	public void run()
    	{
    	    //ourMediaPlayer.getMediaPlayer().playMedia(mediaPath);
    	    //Dimension videoDim = ourMediaPlayer.getMediaPlayer().getVideoDimension();
    	    //ourFrame.setSize(videoDim.width, videoDim.height);
    	    ourMediaPlayer.getMediaPlayer().playMedia("rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov");
    	}
    }

Here we have the logs:

[main] INFO uk.co.caprica.vlcj.Info - vlcj: 3.10.1
[main] INFO uk.co.caprica.vlcj.Info - java: 1.7.0_80 Oracle Corporation
[main] INFO uk.co.caprica.vlcj.Info - java home: C:\Program Files\Java\jre7
[main] INFO uk.co.caprica.vlcj.Info - os: Windows 8.1 6.3 amd64
[main] INFO uk.co.caprica.vlcj.discovery.NativeDiscovery - Discovery found libvlc at 'C:\Program Files\VideoLAN\VLC'
[main] INFO uk.co.caprica.vlcj.binding.LibVlcFactory - vlc: 2.2.1 Terry Pratchett (Weatherwax), changeset 2.2.1-0-ga425c42
[main] INFO uk.co.caprica.vlcj.binding.LibVlcFactory - libvlc: C:\Program Files\VideoLAN\VLC\libvlc.dll
[0000000010401020] core demux error: corrupt module: C:\Program Files\VideoLAN\VLC\plugins\access\liblive555_plugin.dll
[0000000010401020] core demux error: corrupt module: C:\Program Files\VideoLAN\VLC\plugins\access\liblive555_plugin.dll
[00000000103868f0] core input error: open of `rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov' failed
[00000000103868f0] core input error: Your input can't be opened
[00000000103868f0] core input error: VLC is unable to open the MRL 'rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov'. Check the log for details.

**Comment by caprica** [comment]
Search the existing issues in this repo for "rtsp windows", this is not a new problem...

**Comment by diegotsu** [comment]
I'm writting just to leave my solution here. I just reinstalled both VLC and JRE in 32 bits and it worked out.

**Comment by caprica** [comment]
Yep, the 64-bit builds of VLC have been reported to have "issues" at least with JNA/vlcj.
