### ISSUE TITLE
Title bar/Overlay issue on Ubuntu

### ISSUE THREAD

**Issue by MrDhim** [caprica/vlcj#464]
Hi, I'm using an EmbeddedMediaplayer with a home made overlay on it (I have 2 logos to display, and more stuff...), **it works well on Windows**, but I'm experiencing some issues on Ubuntu : 
 - With Ubuntu 15.10-i386 Unity the Title bar remains on top of the video, and pushes the overlay down.
 - With the Gnome version I only have the overlay issue.

Also when I update anything in the Overlay the previous value stays displayed, so I have the media title on top of the previous... until a ComponentSizeChanged event is fired on it.

I'm running my project with Java 1.8.0_66-i386, last version of VLC, JNA4.1.0 and VLCJ 3.8.0

**Comment by caprica** [comment]
I don't know what you expect me to say given what little you've posted... at least post a test-case.
