### ISSUE TITLE
How to use the libvlc_vlm_add_broadcast

### ISSUE THREAD

**Issue by Thenck** [caprica/vlcj#466]
i try to add_broadcast
but it is out put the 
0
0
then the jvm close
code
 String[] option = {""};
			 libvlc_instance_t instance = LibVlc.SYNC_INSTANCE.libvlc_new(0, option);
			 String s = "a";
			 System.out.println(LibVlc.INSTANCE.libvlc_vlm_add_broadcast(instance, s, "udp://@:1234", "#rtp{sdp=rtsp://:8554/1}", 0, option, 1, 1));
			 System.out.println(LibVlc.SYNC_INSTANCE.libvlc_vlm_play_media(instance, s));

**Comment by caprica** [comment]
Please post a full test case, this code fragment is not enough to help you.
