### ISSUE TITLE
Cannot Open File with Non-ASCII Characters

### ISSUE THREAD

**Issue by Joe-Silver** [caprica/vlcj#467]
I am having the same issue that is described by Issue #173 and the same workaround (calling toURI().toASCIIString()) gets me by it.  The issue was reportedly fixed in vlcj 2.4.0 but I am still seeing it while trying to play an audio file in vlcj 3.8.0

MediaPlayer mediaPlayer = new AudioMediaPlayerComponent().getMediaPlayer();
StartTheDay.mediaPlayer.playMedia(mrl);

mrl is "C:\Users\IBM_ADMIN\Google Drive\Misha Mishenko - Vakning að elska.mp3"

**Comment by caprica** [comment]
See #415
