### ISSUE TITLE
Problem with length of video

### ISSUE THREAD

**Issue by eliaszkubala** [caprica/vlcj#470]
Hello,

I capture a video from RTSP. It's 720p resolution. 
Here is my code: 

```
File dir = new File(System.getProperty("user.home"), "Videos");
        dir.mkdirs();
        DateFormat df = new SimpleDateFormat("yyyyMMdd-HHmmss");
        String name = "Capture-" + df.format(new Date());
        String path = dir.getAbsolutePath() + "\\";
        String fileName = path + name + ".mpg";
        String[] optionsRecord = {
                ":file-caching=0",
                ":network-caching=500",
                ":no-video-title-show",
                ":sout=#transcode{vcodec=mp4v,scale=1}:duplicate{dst=file{dst=" + fileName + "},dst=display}"};
        mediaPlayer.playMedia(address, optionsRecord);
```

The problem is that 4 seconds video have 1:53:49 length. Why?
Here is one example:
http://s21.postimg.org/onijlc4iv/2016_02_03_15_24_29_Centrum_akcji.png

**Comment by caprica** [comment]
Since you didn't post a complete test-case I can't say.

Are you releasing the media player when the stream finishes? Sometimes the media file is not written fully until you release the media player.

**Comment by eliaszkubala** [comment]
Okey, here is my code:

```
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

import uk.co.caprica.vlcj.binding.LibVlc;
import uk.co.caprica.vlcj.player.MediaPlayerFactory;
import uk.co.caprica.vlcj.player.embedded.EmbeddedMediaPlayer;
import uk.co.caprica.vlcj.player.embedded.videosurface.CanvasVideoSurface;
import uk.co.caprica.vlcj.runtime.RuntimeUtil;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

public class Main {

    private final camera camera = new camera();
    private MediaPlayerFactory factory;
    private EmbeddedMediaPlayer mediaPlayer;
    private CanvasVideoSurface videoSurface;
    private Canvas canvas;
    private testowy testowy;
    private final String address = "rtsp://192.168.1.10:554/user=admin&password=&channel=1&stream=0.sdp?";
    private FileMaker fileMaker;

    public static void main(final String[] args) {
        NativeLibrary.addSearchPath(RuntimeUtil.getLibVlcLibraryName(), "C:\\Program Files\\VideoLAN\\VLC");
        Native.loadLibrary(RuntimeUtil.getLibVlcLibraryName(), LibVlc.class);
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Main(args);
            }
        });
    }

    private Main(String[] args) {
        startCameraPreview();
        configuareGUIListeners();
    }

    private void createCameraCanvas() {
        canvas = new Canvas();
        factory = new MediaPlayerFactory();
        mediaPlayer = factory.newEmbeddedMediaPlayer();
        videoSurface = factory.newVideoSurface(canvas);
        mediaPlayer.setVideoSurface(videoSurface);
    }

    private void createGUI() {
        if(testowy == null)
            testowy = new testowy();

        if(testowy.getPanel1().getComponents().length > 0 )
            testowy.getPanel1().remove(0);

        testowy.getPanel1().add(canvas);
        testowy.setVisible(true);
        testowy.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }


    private void reloadCamera() {
        if(mediaPlayer != null)
            mediaPlayer.release();
        if(mediaPlayer != null)
            factory.release();

        createCameraCanvas();
        createGUI();
    }

    private void configuareGUIListeners() {
        testowy.getButton4().addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                camera.zoomIn();
            }
        });
        testowy.getButton6().addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                camera.zoomOut();
            }
        });
        testowy.getZoomInAll().addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                camera.zoomInAll();
            }
        });
        testowy.getZoomOutAll().addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                camera.zoomOutAll();
            }
        });
        testowy.getStopZoom().addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                camera.stopZoom();
            }
        });
        testowy.getStartRecord().addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                startRecord();
            }
        });
        testowy.getStopRecord().addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                startCameraPreview();
            }
        });
    }

    void startCameraPreview() {
        releaseFilesMaker();
        reloadCamera();

        String[] options = {
                ":file-caching=0",
                ":network-caching=500",
                ":no-sout-rtp-sap",
                ":no-sout-standard-sap",
                ":sout-all",
                ":rtsp-caching=100",
                ":sout-keep"};

        mediaPlayer.playMedia(address, options);
    }

    private void releaseFilesMaker() {
        if (fileMaker != null) fileMaker.release();
    }

    void startRecord() {
        reloadCamera();

        File dir = new File(System.getProperty("user.home"), "Videos");
        dir.mkdirs();
        DateFormat df = new SimpleDateFormat("yyyyMMdd-HHmmss");
        String name = "Capture-" + df.format(new Date());
        String path = dir.getAbsolutePath() + "\\";
        String fileName = path + name + ".mpg";
        String[] optionsRecord = {
                ":file-caching=0",
                ":network-caching=500",
                ":no-video-title-show",
                ":sout=#transcode{vcodec=mp4v,scale=1}:duplicate{dst=file{dst=" + fileName + "},dst=display}"};

        mediaPlayer.playMedia(address, optionsRecord);

        fileMaker = new FileMaker(name, path);
        fileMaker.addEvents("przyłącz dziki");
        fileMaker.addGyroData("1,1,1");
        fileMaker.addDistanceInCentimeter("100");
    }
}
```


When I record or start preview I got this debug and error. 


> 19:18:39.593 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - release()
> 19:18:39.593 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - destroyInstance()
> 19:18:39.593 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - Detach media events...
> 19:18:39.593 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - deregisterMediaEventListener()
> 19:18:39.593 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - event=libvlc_MediaMetaChanged
> 19:18:39.593 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - event=libvlc_MediaSubItemAdded
> 19:18:39.593 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - event=libvlc_MediaDurationChanged
> 19:18:39.593 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - event=libvlc_MediaParsedChanged
> 19:18:39.593 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - event=libvlc_MediaFreed
> 19:18:39.593 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - event=libvlc_MediaStateChanged
> 19:18:39.593 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - Media events detached.
> 19:18:39.594 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - Release media...
> 19:18:39.594 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - Media released.
> 19:18:39.594 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - Detach media player events...
> 19:18:39.594 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - deregisterEventListener()
> 19:18:39.594 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - event=libvlc_MediaPlayerMediaChanged
> 19:18:39.594 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - event=libvlc_MediaPlayerNothingSpecial
> 19:18:39.594 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - event=libvlc_MediaPlayerOpening
> 19:18:39.594 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - event=libvlc_MediaPlayerBuffering
> 19:18:39.595 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - event=libvlc_MediaPlayerPlaying
> 19:18:39.595 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - event=libvlc_MediaPlayerPaused
> 19:18:39.595 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - event=libvlc_MediaPlayerStopped
> 19:18:39.595 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - event=libvlc_MediaPlayerForward
> 19:18:39.595 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - event=libvlc_MediaPlayerBackward
> 19:18:39.595 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - event=libvlc_MediaPlayerEndReached
> 19:18:39.595 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - event=libvlc_MediaPlayerEncounteredError
> 19:18:39.595 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - event=libvlc_MediaPlayerTimeChanged
> 19:18:39.595 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - event=libvlc_MediaPlayerPositionChanged
> 19:18:39.595 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - event=libvlc_MediaPlayerSeekableChanged
> 19:18:39.595 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - event=libvlc_MediaPlayerPausableChanged
> 19:18:39.596 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - event=libvlc_MediaPlayerTitleChanged
> 19:18:39.596 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - event=libvlc_MediaPlayerSnapshotTaken
> 19:18:39.596 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - event=libvlc_MediaPlayerLengthChanged
> 19:18:39.596 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - event=libvlc_MediaPlayerVout
> 19:18:39.596 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - Media player events detached.
> 19:18:39.596 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - Release media player...
> 19:18:39.687 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - Media player released.
> 19:18:39.687 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - Shut down listeners...
> 19:18:39.687 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - Listeners shut down.
> 19:18:39.687 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.MediaPlayerFactory - release()
> 19:18:39.690 [AWT-EventQueue-0] INFO  u.c.c.vlcj.binding.LibVlcFactory - vlc: 2.1.2 Rincewind, changeset 2.1.2-0-ga4c4876
> 19:18:39.690 [AWT-EventQueue-0] INFO  u.c.c.vlcj.binding.LibVlcFactory - libvlc: C:\Program Files\VideoLAN\VLC\libvlc.dll
> 19:18:39.690 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.MediaPlayerFactory - MediaPlayerFactory(libvlc=Proxy interface to Native Library <C:\Program Files\VideoLAN\VLC\libvlc.dll@1432027136>,libvlcArgs=[])
> 19:18:39.690 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.MediaPlayerFactory - jna.library.path=null
> 19:18:39.690 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.MediaPlayerFactory - VLC_PLUGIN_PATH=null
> 19:18:39.724 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.MediaPlayerFactory - instance=native@0x1b77dfc0 (uk.co.caprica.vlcj.binding.internal.libvlc_instance_t@1b77dfc0)
> 19:18:39.724 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.MediaPlayerFactory - equalizerAvailable=false
> 19:18:39.725 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.MediaPlayerFactory - newEmbeddedMediaPlayer()
> 19:18:39.725 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.MediaPlayerFactory - newEmbeddedMediaPlayer(fullScreenStrategy=null)
> 19:18:39.725 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - DefaultMediaPlayer(libvlc=Proxy interface to Native Library <C:\Program Files\VideoLAN\VLC\libvlc.dll@1432027136>, instance=native@0x1b77dfc0 (uk.co.caprica.vlcj.binding.internal.libvlc_instance_t@1b77dfc0))
> 19:18:39.725 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - createInstance()
> 19:18:39.725 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - mediaPlayerInstance=native@0x1b7837e0 (uk.co.caprica.vlcj.binding.internal.libvlc_media_player_t@1b7837e0)
> 19:18:39.725 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - mediaPlayerEventManager=native@0x1b81c7b0 (uk.co.caprica.vlcj.binding.internal.libvlc_event_manager_t@1b81c7b0)
> 19:18:39.725 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - registerEventListener()
> 19:18:39.725 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - event=libvlc_MediaPlayerMediaChanged
> 19:18:39.726 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - result=0
> 19:18:39.726 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - event=libvlc_MediaPlayerNothingSpecial
> 19:18:39.726 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - result=0
> 19:18:39.726 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - event=libvlc_MediaPlayerOpening
> 19:18:39.726 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - result=0
> 19:18:39.726 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - event=libvlc_MediaPlayerBuffering
> 19:18:39.726 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - result=0
> 19:18:39.726 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - event=libvlc_MediaPlayerPlaying
> 19:18:39.726 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - result=0
> 19:18:39.726 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - event=libvlc_MediaPlayerPaused
> 19:18:39.726 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - result=0
> 19:18:39.727 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - event=libvlc_MediaPlayerStopped
> 19:18:39.727 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - result=0
> 19:18:39.727 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - event=libvlc_MediaPlayerForward
> 19:18:39.727 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - result=0
> 19:18:39.727 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - event=libvlc_MediaPlayerBackward
> 19:18:39.727 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - result=0
> 19:18:39.727 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - event=libvlc_MediaPlayerEndReached
> 19:18:39.727 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - result=0
> 19:18:39.727 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - event=libvlc_MediaPlayerEncounteredError
> 19:18:39.727 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - result=0
> 19:18:39.727 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - event=libvlc_MediaPlayerTimeChanged
> 19:18:39.727 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - result=0
> 19:18:39.727 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - event=libvlc_MediaPlayerPositionChanged
> 19:18:39.727 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - result=0
> 19:18:39.727 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - event=libvlc_MediaPlayerSeekableChanged
> 19:18:39.727 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - result=0
> 19:18:39.727 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - event=libvlc_MediaPlayerPausableChanged
> 19:18:39.727 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - result=0
> 19:18:39.727 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - event=libvlc_MediaPlayerTitleChanged
> 19:18:39.727 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - result=0
> 19:18:39.727 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - event=libvlc_MediaPlayerSnapshotTaken
> 19:18:39.727 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - result=0
> 19:18:39.727 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - event=libvlc_MediaPlayerLengthChanged
> 19:18:39.728 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - result=0
> 19:18:39.728 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - event=libvlc_MediaPlayerVout
> 19:18:39.728 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - result=0
> 19:18:39.728 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.MediaPlayerFactory - newVideoSurface(canvas=java.awt.Canvas[canvas1,0,0,0x0,invalid])
> 19:18:39.728 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.MediaPlayerFactory - videoSurface=uk.co.caprica.vlcj.player.embedded.videosurface.CanvasVideoSurface@226a985d
> 19:18:39.728 [AWT-EventQueue-0] DEBUG u.c.c.v.p.e.DefaultEmbeddedMediaPlayer - setVideoSurface(videoSurface=uk.co.caprica.vlcj.player.embedded.videosurface.CanvasVideoSurface@226a985d)
> 19:18:39.731 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - playMedia(mrl=rtsp://192.168.1.10:554/user=admin&password=&channel=1&stream=0.sdp?,mediaOptions=[:file-caching=0, :network-caching=500, :no-video-title-show, :sout=#transcode{vcodec=mp4v,scale=1}:duplicate{dst=file{dst=C:\Users\TheKing\Videos\Capture-20160203-191839.mpg},dst=display}])
> 19:18:39.731 [AWT-EventQueue-0] DEBUG u.c.c.v.player.MediaResourceLocator - encodeMrl(mrl=rtsp://192.168.1.10:554/user=admin&password=&channel=1&stream=0.sdp?)
> 19:18:39.731 [AWT-EventQueue-0] DEBUG u.c.c.v.player.MediaResourceLocator - MRL does not contain any Unicode characters
> 19:18:39.731 [AWT-EventQueue-0] DEBUG u.c.c.v.player.MediaResourceLocator - result=rtsp://192.168.1.10:554/user=admin&password=&channel=1&stream=0.sdp?
> 19:18:39.731 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - playMedia(media=SimpleMedia[mrl=rtsp://192.168.1.10:554/user=admin&password=&channel=1&stream=0.sdp?,mediaOptions=[Ljava.lang.String;@56f0b0c0])
> 19:18:39.731 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - prepareMedia(media=SimpleMedia[mrl=rtsp://192.168.1.10:554/user=admin&password=&channel=1&stream=0.sdp?,mediaOptions=[Ljava.lang.String;@56f0b0c0])
> 19:18:39.731 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - setMedia(media=SimpleMedia[mrl=rtsp://192.168.1.10:554/user=admin&password=&channel=1&stream=0.sdp?,mediaOptions=[Ljava.lang.String;@56f0b0c0])
> 19:18:39.732 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - createMediaInstance(media=SimpleMedia[mrl=rtsp://192.168.1.10:554/user=admin&password=&channel=1&stream=0.sdp?,mediaOptions=[Ljava.lang.String;@56f0b0c0])
> 19:18:39.732 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - Treating mrl as a location
> 19:18:39.732 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - mediaInstance=native@0x1b81c2a0 (uk.co.caprica.vlcj.binding.internal.libvlc_media_t@1b81c2a0)
> 19:18:39.732 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - mediaOption=:file-caching=0
> 19:18:39.732 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - mediaOption=:network-caching=500
> 19:18:39.732 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - mediaOption=:no-video-title-show
> 19:18:39.732 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - mediaOption=:sout=#transcode{vcodec=mp4v,scale=1}:duplicate{dst=file{dst=C:\Users\TheKing\Videos\Capture-20160203-191839.mpg},dst=display}
> 19:18:39.732 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - registerMediaEventListener()
> 19:18:39.732 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - event=libvlc_MediaMetaChanged
> 19:18:39.732 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - result=0
> 19:18:39.732 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - event=libvlc_MediaSubItemAdded
> 19:18:39.732 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - result=0
> 19:18:39.732 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - event=libvlc_MediaDurationChanged
> 19:18:39.732 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - result=0
> 19:18:39.732 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - event=libvlc_MediaParsedChanged
> 19:18:39.733 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - result=0
> 19:18:39.733 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - event=libvlc_MediaFreed
> 19:18:39.733 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - result=0
> 19:18:39.733 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - event=libvlc_MediaStateChanged
> 19:18:39.733 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - result=0
> 19:18:39.734 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - mrl(mediaInstance=native@0x1b81c2a0 (uk.co.caprica.vlcj.binding.internal.libvlc_media_t@1b81c2a0))
> 19:18:39.734 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - result=true
> 19:18:39.734 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - play()
> 19:18:39.734 [pool-2-thread-1] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - mediaChanged(mediaPlayer=uk.co.caprica.vlcj.player.embedded.DefaultEmbeddedMediaPlayer@129d3587,media=native@0x1b81c2a0 (uk.co.caprica.vlcj.binding.internal.libvlc_media_t@1b81c2a0),mrl=rtsp://192.168.1.10:554/user=admin&password=&channel=1&stream=0.sdp?)
> 19:18:39.736 [AWT-EventQueue-0] DEBUG u.c.c.v.p.e.DefaultEmbeddedMediaPlayer - onBeforePlay()
> 19:18:39.736 [pool-2-thread-1] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - Raising event for new media
> 19:18:39.736 [AWT-EventQueue-0] DEBUG u.c.c.v.p.e.DefaultEmbeddedMediaPlayer - attachVideoSurface()
> 19:18:39.736 [AWT-EventQueue-0] DEBUG u.c.c.v.p.e.v.CanvasVideoSurface - attach()
> 19:18:39.736 [AWT-EventQueue-0] DEBUG u.c.c.v.p.e.v.CanvasVideoSurface - componentId=3081852
> 19:18:39.736 [AWT-EventQueue-0] DEBUG u.c.c.v.p.e.v.w.WindowsVideoSurfaceAdapter - attach(componentId=3081852)
> 19:18:39.736 [AWT-EventQueue-0] DEBUG u.c.c.v.p.e.v.CanvasVideoSurface - video surface attached
> 19:18:39.738 [AWT-EventQueue-0] DEBUG u.c.c.vlcj.player.DefaultMediaPlayer - after play
> seconds: 1
> [000000001ba6c040] mux_ps mux: Open
> seconds: 2
> MultiFramedRTPSource::doGetNextFrame1(): The total received frame size exceeds the client's buffer size (100000).  47722 bytes of trailing data will be dropped!
> [mpeg4 @ 000000001b7c7e60] removing common factors from framerate
> [mpeg4 @ 000000001b7c8680] removing common factors from framerate
> [000000001d75bbf0] main vout display error: Failed to set on top
> seconds: 3
> seconds: 4
> seconds: 5
> seconds: 6
> seconds: 7
> seconds: 8


here is some errors (red lines ;) )

> seconds: 1
> [000000001ba6c040] mux_ps mux: Open
> seconds: 2
> MultiFramedRTPSource::doGetNextFrame1(): The total received frame size exceeds the client's buffer size (100000).  47722 bytes of trailing data will be dropped!
> [mpeg4 @ 000000001b7c7e60] removing common factors from framerate
> [mpeg4 @ 000000001b7c8680] removing common factors from framerate
> [000000001d75bbf0] main vout display error: Failed to set on top

**Comment by eliaszkubala** [comment]
Sorry, I have incorrect file extension. I should have mp4 but I had mpg. Sorry, my mistake.

**Comment by caprica** [comment]
So is there a problem or not?

**Comment by eliaszkubala** [comment]
No, I solve it myself. 
You can close or remove this topic. 
Thanks for your time ;)

**Comment by caprica** [comment]
Glad to hear it!

**Comment by pcvijayvignesh** [comment]
> No, I solve it myself.
> You can close or remove this topic.
> Thanks for your time ;)

How was it solved ?
