### ISSUE TITLE
JVM Crash on OSX with vlcj 3.10.1 and VLC 2.2.0 or 2.2.2

### ISSUE THREAD

**Issue by iXo** [caprica/vlcj#472]
Hello, using the simple audio player sample program, I am unable to play a file, and the JVM crash.

OS : Mac OS X 10.11.3 x86_64
JVM up to date : 1.8.0_74

I have tried vlcj 3.8.0 (as my program wasn't on the latest version of vlcj) and 3.10.1, I have tried v2.2.0 and 2.2.2 of vlc without any difference.

Here is the log of the execution : 

> 10:32:03.912 uk.co.caprica.vlcj.Info : 784  INFO  - vlcj: 3.10.1
10:32:03.915 uk.co.caprica.vlcj.Info : 787  INFO  - java: 1.8.0_74 Oracle Corporation
10:32:03.915 uk.co.caprica.vlcj.Info : 787  INFO  - java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre
10:32:03.916 uk.co.caprica.vlcj.Info : 788  INFO  - os: Mac OS X 10.11.3 x86_64
2.2.2 Weatherwax
10:32:04.003 uk.co.caprica.vlcj.component.AudioMediaPlayerComponent : 875  DEBUG - args=[--intf=dummy, --ignore-config]
10:32:04.009 uk.co.caprica.vlcj.player.MediaPlayerFactory : 881  DEBUG - initX=null
10:32:04.068 uk.co.caprica.vlcj.runtime.x.LibXUtil : 940  DEBUG - Did not initialise LibX11: Unable to load library 'X11': Native library (darwin/libX11.dylib) not found in resource path ([file:/Users/ixo/Desktop/studiong/ihm/VocalProReplay2/studiong-record_player/target/classes/, file:/Users/ixo/.m2/repository/org/netbeans/api/org-netbeans-api-annotations-common/RELEASE81/org-netbeans-api-annotations-common-RELEASE81.jar, file:/Users/ixo/.m2/repository/org/netbeans/api/org-openide-windows/RELEASE81/org-openide-windows-RELEASE81.jar, file:/Users/ixo/.m2/repository/org/netbeans/api/org-openide-filesystems/RELEASE81/org-openide-filesystems-RELEASE81.jar, file:/Users/ixo/.m2/repository/org/netbeans/api/org-openide-nodes/RELEASE81/org-openide-nodes-RELEASE81.jar, file:/Users/ixo/.m2/repository/org/netbeans/api/org-openide-dialogs/RELEASE81/org-openide-dialogs-RELEASE81.jar, file:/Users/ixo/.m2/repository/org/netbeans/api/org-openide-util/RELEASE81/org-openide-util-RELEASE81.jar, file:/Users/ixo/.m2/repository/org/netbeans/api/org-openide-util-ui/RELEASE81/org-openide-util-ui-RELEASE81.jar, file:/Users/ixo/.m2/repository/org/netbeans/api/org-openide-util-lookup/RELEASE81/org-openide-util-lookup-RELEASE81.jar, file:/Users/ixo/.m2/repository/org/netbeans/api/org-openide-awt/RELEASE81/org-openide-awt-RELEASE81.jar, file:/Users/ixo/.m2/repository/org/netbeans/api/org-netbeans-modules-settings/RELEASE81/org-netbeans-modules-settings-RELEASE81.jar, file:/Users/ixo/.m2/repository/org/netbeans/modules/org-netbeans-bootstrap/RELEASE81/org-netbeans-bootstrap-RELEASE81.jar, file:/Users/ixo/.m2/repository/org/netbeans/modules/org-netbeans-core-startup/RELEASE81/org-netbeans-core-startup-RELEASE81.jar, file:/Users/ixo/.m2/repository/org/netbeans/api/org-netbeans-libs-asm/RELEASE81/org-netbeans-libs-asm-RELEASE81.jar, file:/Users/ixo/.m2/repository/org/ow2/asm/asm-all/5.0.1/asm-all-5.0.1.jar, file:/Users/ixo/.m2/repository/org/netbeans/modules/org-netbeans-core-startup-base/RELEASE81/org-netbeans-core-startup-base-RELEASE81.jar, file:/Users/ixo/.m2/repository/org/netbeans/api/org-openide-actions/RELEASE81/org-openide-actions-RELEASE81.jar, file:/Users/ixo/.m2/repository/org/netbeans/api/org-openide-explorer/RELEASE81/org-openide-explorer-RELEASE81.jar, file:/Users/ixo/.m2/repository/org/netbeans/api/org-netbeans-swing-outline/RELEASE81/org-netbeans-swing-outline-RELEASE81.jar, file:/Users/ixo/.m2/repository/org/netbeans/api/org-netbeans-swing-tabcontrol/RELEASE81/org-netbeans-swing-tabcontrol-RELEASE81.jar, file:/Users/ixo/.m2/repository/org/netbeans/api/org-openide-text/RELEASE81/org-openide-text-RELEASE81.jar, file:/Users/ixo/.m2/repository/org/netbeans/api/org-openide-filesystems-nb/RELEASE81/org-openide-filesystems-nb-RELEASE81.jar, file:/Users/ixo/.m2/repository/org/netbeans/api/org-openide-loaders/RELEASE81/org-openide-loaders-RELEASE81.jar, file:/Users/ixo/.m2/repository/org/netbeans/api/org-netbeans-api-progress/RELEASE81/org-netbeans-api-progress-RELEASE81.jar, file:/Users/ixo/.m2/repository/org/netbeans/api/org-netbeans-api-progress-nb/RELEASE81/org-netbeans-api-progress-nb-RELEASE81.jar, file:/Users/ixo/.m2/repository/org/netbeans/api/org-netbeans-modules-editor-mimelookup/RELEASE81/org-netbeans-modules-editor-mimelookup-RELEASE81.jar, file:/Users/ixo/.m2/repository/org/netbeans/api/org-netbeans-modules-queries/RELEASE81/org-netbeans-modules-queries-RELEASE81.jar, file:/Users/ixo/.m2/repository/org/netbeans/api/org-netbeans-api-templates/RELEASE81/org-netbeans-api-templates-RELEASE81.jar, file:/Users/ixo/.m2/repository/org/netbeans/api/org-openide-modules/RELEASE81/org-openide-modules-RELEASE81.jar, file:/Users/ixo/.m2/repository/org/jfree/jfreechart/1.0.19/jfreechart-1.0.19.jar, file:/Users/ixo/.m2/repository/org/jfree/jcommon/1.0.23/jcommon-1.0.23.jar, file:/Users/ixo/Desktop/studiong/VProTools/target/classes/, file:/Users/ixo/.m2/repository/ch/qos/logback/logback-classic/1.1.1/logback-classic-1.1.1.jar, file:/Users/ixo/.m2/repository/ch/qos/logback/logback-core/1.1.1/logback-core-1.1.1.jar, file:/Users/ixo/.m2/repository/org/apache/commons/commons-exec/1.3/commons-exec-1.3.jar, file:/Users/ixo/Desktop/studiong/libs/gson/target/classes/, file:/Users/ixo/.m2/repository/joda-time/joda-time/2.8/joda-time-2.8.jar, file:/Users/ixo/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar, file:/Users/ixo/.m2/repository/com/googlecode/soundlibs/tritonus-share/0.3.7-2/tritonus-share-0.3.7-2.jar, file:/Users/ixo/.m2/repository/com/googlecode/soundlibs/mp3spi/1.9.5-1/mp3spi-1.9.5-1.jar, file:/Users/ixo/.m2/repository/com/googlecode/soundlibs/jlayer/1.0.1-1/jlayer-1.0.1-1.jar, file:/Users/ixo/.m2/repository/com/googlecode/soundlibs/vorbisspi/1.0.3-1/vorbisspi-1.0.3-1.jar, file:/Users/ixo/.m2/repository/com/googlecode/soundlibs/jorbis/0.0.17-2/jorbis-0.0.17-2.jar, file:/Users/ixo/Desktop/studiong/libs/VProI18N/target/classes/, file:/Users/ixo/Desktop/studiong/ihm/VocalProReplay2/studiong-rcp/target/classes/, file:/Users/ixo/.m2/repository/com/vocalpro1/libs/VProCommonsDefs/1.0.0-SNAPSHOT/VProCommonsDefs-1.0.0-SNAPSHOT.jar, file:/Users/ixo/.m2/repository/uk/co/caprica/vlcj/3.10.1/vlcj-3.10.1.jar, file:/Users/ixo/.m2/repository/net/java/dev/jna/jna/4.1.0/jna-4.1.0.jar, file:/Users/ixo/.m2/repository/net/java/dev/jna/jna-platform/4.1.0/jna-platform-4.1.0.jar, file:/Users/ixo/.m2/repository/org/slf4j/slf4j-api/1.7.10/slf4j-api-1.7.10.jar])
10:32:04.069 uk.co.caprica.vlcj.binding.LibVlcFactory : 941  INFO  - vlc: 2.2.2 Weatherwax, changeset 2.2.2-3-gf8c9253
10:32:04.070 uk.co.caprica.vlcj.binding.LibVlcFactory : 942  INFO  - libvlc: /Users/ixo/Desktop/studiong/ihm/VocalProReplay2/studiong-application/lib/libvlc.dylib
10:32:04.070 uk.co.caprica.vlcj.player.MediaPlayerFactory : 942  DEBUG - MediaPlayerFactory(libvlc=Proxy interface to Native Library </Users/ixo/Desktop/studiong/ihm/VocalProReplay2/studiong-application/lib/libvlc.dylib@140399406679264>,libvlcArgs=[--intf=dummy, --ignore-config])
10:32:04.070 uk.co.caprica.vlcj.player.MediaPlayerFactory : 942  DEBUG - jna.library.path=null
10:32:04.070 uk.co.caprica.vlcj.player.MediaPlayerFactory : 942  DEBUG - VLC_PLUGIN_PATH=null
10:32:05.542 uk.co.caprica.vlcj.player.MediaPlayerFactory : 2414 DEBUG - instance=native@0x7fb148c753d0 (uk.co.caprica.vlcj.binding.internal.libvlc_instance_t@48c7d381)
10:32:05.543 uk.co.caprica.vlcj.player.MediaPlayerFactory : 2415 DEBUG - equalizerAvailable=true
10:32:05.543 uk.co.caprica.vlcj.player.MediaPlayerFactory : 2415 DEBUG - createEqualizerBandFrequencies()
10:32:05.543 uk.co.caprica.vlcj.player.MediaPlayerFactory : 2415 DEBUG - numBands=10
10:32:05.545 uk.co.caprica.vlcj.player.MediaPlayerFactory : 2417 DEBUG - result=[31.25, 62.5, 125.0, 250.0, 500.0, 1000.0, 2000.0, 4000.0, 8000.0, 16000.0]
10:32:05.546 uk.co.caprica.vlcj.player.MediaPlayerFactory : 2418 DEBUG - createEqualizerPresetNames()
10:32:05.546 uk.co.caprica.vlcj.player.MediaPlayerFactory : 2418 DEBUG - numPresets=18
10:32:05.546 uk.co.caprica.vlcj.player.MediaPlayerFactory : 2418 DEBUG - result=[Flat, Classical, Club, Dance, Full bass, Full bass and treble, Full treble, Headphones, Large Hall, Live, Party, Pop, Reggae, Rock, Ska, Soft, Soft rock, Techno]
10:32:05.546 uk.co.caprica.vlcj.player.MediaPlayerFactory : 2418 DEBUG - newHeadlessMediaPlayer()
10:32:05.556 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2428 DEBUG - DefaultMediaPlayer(libvlc=Proxy interface to Native Library </Users/ixo/Desktop/studiong/ihm/VocalProReplay2/studiong-application/lib/libvlc.dylib@140399406679264>, instance=native@0x7fb148c753d0 (uk.co.caprica.vlcj.binding.internal.libvlc_instance_t@48c7d381))
10:32:05.556 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2428 DEBUG - createInstance()
[00007fb148c8c2f8] core audio output error: option auhal-volume does not exist
[00007fb148c8c2f8] core audio output error: option auhal-audio-device does not exist
10:32:05.742 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2614 DEBUG - mediaPlayerInstance=native@0x7fb148d6a838 (uk.co.caprica.vlcj.binding.internal.libvlc_media_player_t@48d727e9)
10:32:05.743 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2615 DEBUG - mediaPlayerEventManager=native@0x7fb148c956d0 (uk.co.caprica.vlcj.binding.internal.libvlc_event_manager_t@48c9d681)
10:32:05.743 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2615 DEBUG - registerEventListener()
10:32:05.745 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2617 DEBUG - event=libvlc_MediaPlayerMediaChanged
10:32:05.771 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2643 DEBUG - result=0
10:32:05.771 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2643 DEBUG - event=libvlc_MediaPlayerNothingSpecial
10:32:05.771 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2643 DEBUG - result=0
10:32:05.771 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2643 DEBUG - event=libvlc_MediaPlayerOpening
10:32:05.771 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2643 DEBUG - result=0
10:32:05.771 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2643 DEBUG - event=libvlc_MediaPlayerBuffering
10:32:05.771 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2643 DEBUG - result=0
10:32:05.771 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2643 DEBUG - event=libvlc_MediaPlayerPlaying
10:32:05.771 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2643 DEBUG - result=0
10:32:05.771 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2643 DEBUG - event=libvlc_MediaPlayerPaused
10:32:05.771 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2643 DEBUG - result=0
10:32:05.771 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2643 DEBUG - event=libvlc_MediaPlayerStopped
10:32:05.772 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2644 DEBUG - result=0
10:32:05.772 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2644 DEBUG - event=libvlc_MediaPlayerForward
10:32:05.772 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2644 DEBUG - result=0
10:32:05.772 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2644 DEBUG - event=libvlc_MediaPlayerBackward
10:32:05.772 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2644 DEBUG - result=0
10:32:05.772 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2644 DEBUG - event=libvlc_MediaPlayerEndReached
10:32:05.772 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2644 DEBUG - result=0
10:32:05.772 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2644 DEBUG - event=libvlc_MediaPlayerEncounteredError
10:32:05.772 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2644 DEBUG - result=0
10:32:05.772 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2644 DEBUG - event=libvlc_MediaPlayerTimeChanged
10:32:05.772 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2644 DEBUG - result=0
10:32:05.772 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2644 DEBUG - event=libvlc_MediaPlayerPositionChanged
10:32:05.772 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2644 DEBUG - result=0
10:32:05.772 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2644 DEBUG - event=libvlc_MediaPlayerSeekableChanged
10:32:05.772 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2644 DEBUG - result=0
10:32:05.772 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2644 DEBUG - event=libvlc_MediaPlayerPausableChanged
10:32:05.772 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2644 DEBUG - result=0
10:32:05.772 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2644 DEBUG - event=libvlc_MediaPlayerTitleChanged
10:32:05.773 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2645 DEBUG - result=0
10:32:05.773 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2645 DEBUG - event=libvlc_MediaPlayerSnapshotTaken
10:32:05.773 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2645 DEBUG - result=0
10:32:05.773 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2645 DEBUG - event=libvlc_MediaPlayerLengthChanged
10:32:05.773 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2645 DEBUG - result=0
10:32:05.773 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2645 DEBUG - event=libvlc_MediaPlayerVout
10:32:05.773 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2645 DEBUG - result=0
10:32:05.773 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2645 DEBUG - event=libvlc_MediaPlayerScrambledChanged
10:32:05.773 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2645 DEBUG - result=0
10:32:05.774 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2646 DEBUG - addMediaPlayerEventListener(listener=com.vocalpro1.reecoute.player.VLCPlayer$1@56ac3a89)
10:32:05.775 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2647 DEBUG - prepareMedia(mrl=/Users/ixo/Music/Theme.m4r,mediaOptions=[])
10:32:05.776 uk.co.caprica.vlcj.player.MediaResourceLocator : 2648 DEBUG - encodeMrl(mrl=/Users/ixo/Music/Theme.m4r)
10:32:05.776 uk.co.caprica.vlcj.player.MediaResourceLocator : 2648 DEBUG - MRL does not contain any Unicode characters
10:32:05.776 uk.co.caprica.vlcj.player.MediaResourceLocator : 2648 DEBUG - result=/Users/ixo/Music/Theme.m4r
10:32:05.776 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2648 DEBUG - prepareMedia(media=SimpleMedia[mrl=/Users/ixo/Music/Theme.m4r,mediaOptions=[Ljava.lang.String;@cb644e])
10:32:05.776 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2648 DEBUG - setMedia(media=SimpleMedia[mrl=/Users/ixo/Music/Theme.m4r,mediaOptions=[Ljava.lang.String;@cb644e])
10:32:05.776 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2648 DEBUG - createMediaInstance(media=SimpleMedia[mrl=/Users/ixo/Music/Theme.m4r,mediaOptions=[Ljava.lang.String;@cb644e])
10:32:05.776 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2648 DEBUG - Treating mrl as a path
10:32:05.777 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2649 DEBUG - mediaInstance=native@0x7fb148f37570 (uk.co.caprica.vlcj.binding.internal.libvlc_media_t@48f3f521)
10:32:05.777 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2649 DEBUG - registerMediaEventListener()
10:32:05.777 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2649 DEBUG - event=libvlc_MediaMetaChanged
10:32:05.777 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2649 DEBUG - result=0
10:32:05.777 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2649 DEBUG - event=libvlc_MediaSubItemAdded
10:32:05.777 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2649 DEBUG - result=0
10:32:05.777 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2649 DEBUG - event=libvlc_MediaDurationChanged
10:32:05.777 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2649 DEBUG - result=0
10:32:05.777 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2649 DEBUG - event=libvlc_MediaParsedChanged
10:32:05.777 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2649 DEBUG - result=0
10:32:05.777 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2649 DEBUG - event=libvlc_MediaFreed
10:32:05.778 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2650 DEBUG - result=0
10:32:05.779 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2651 DEBUG - event=libvlc_MediaStateChanged
10:32:05.780 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2652 DEBUG - result=0
10:32:05.780 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2652 DEBUG - event=libvlc_MediaSubItemTreeAdded
10:32:05.780 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2652 DEBUG - result=0
10:32:05.784 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2656 DEBUG - mrl(mediaInstance=native@0x7fb148f37570 (uk.co.caprica.vlcj.binding.internal.libvlc_media_t@48f3f521))
10:32:05.786 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2658 DEBUG - mediaChanged(mediaPlayer=uk.co.caprica.vlcj.player.headless.DefaultHeadlessMediaPlayer@4e9bda79,media=native@0x7fb148f37570 (uk.co.caprica.vlcj.binding.internal.libvlc_media_t@48f3f521),mrl=file:///Users/ixo/Music/Theme.m4r)
10:32:05.786 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2658 DEBUG - Raising event for new media
10:32:05.786 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2658 DEBUG - result=true
10:32:05.786 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2658 DEBUG - parseMedia()
[00007fb148d74f18] core art finder error: option album-art-filename does not exist
10:32:05.905 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2777 DEBUG - getTrackInfo(types=[])
10:32:05.905 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2777 DEBUG - getTrackInfo(media=native@0x7fb148f37570 (uk.co.caprica.vlcj.binding.internal.libvlc_media_t@48f3f521),types=[])
10:32:05.905 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2777 DEBUG - newGetTrackInfo(media=native@0x7fb148f37570 (uk.co.caprica.vlcj.binding.internal.libvlc_media_t@48f3f521),types=null)
10:32:05.906 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2778 DEBUG - numberOfTracks=1
[00007fb148e5b998] core art finder error: option album-art-filename does not exist
10:32:05.915 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2787 DEBUG - getCodecDescription(type=libvlc_track_audio,codec=1630826605)
10:32:05.961 com.vocalpro1.reecoute.player.VLCPlayer : 2833 DEBUG - Track info : AudioTrackInfo[codec=0x6134706d,codecName=mp4a,originalCodec=0x6134706d,originalCodecName=mp4a,id=0,profile=-1,level=-1,bitRate=1411200,language=null,description=null,codecDescription=][channels=2,rate=44100]
10:32:05.961 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2833 DEBUG - play()
10:32:05.971 uk.co.caprica.vlcj.player.DefaultMediaPlayer : 2843 DEBUG - after play
[00007fb148ca0ba8] core access error: option network-caching does not exist
[00007fb148c8c2f8] core audio output error: option spdif does not exist
[00007fb148c8c2f8] core audio output error: option volume-save does not exist
[00007fb14996bcb8] core audio filter error: option scaletempo-stride does not exist
[00007fb14996bcb8] core audio filter error: option scaletempo-overlap does not exist
[00007fb14996bcb8] core audio filter error: option scaletempo-search does not exist
A fatal error has been detected by the Java Runtime Environment:
SIGSEGV (0xb) at pc=0x0000000123ef12c0, pid=5623, tid=37127
JRE version: Java(TM) SE Runtime Environment (8.0_74-b02) (build 1.8.0_74-b02)
Java VM: Java HotSpot(TM) 64-Bit Server VM (25.74-b02 mixed mode bsd-amd64 compressed oops)
Problematic frame:
C  [libscaletempo_plugin.dylib+0x22c0]  Open+0x2e0
Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
An error report file with more information is saved as: /Users/ixo/Desktop/studiong/ihm/VocalProReplay2/studiong-record_player/hs_err_pid5623.log
If you would like to submit a bug report, please visit:   http://bugreport.java.com/bugreport/crash.jsp

Any idea why does it occurs ? I have tryied to play the same file from cli without any problem.

[hs_err_pid5623.log.txt](https://github.com/caprica/vlcj/files/120649/hs_err_pid5623.log.txt)

**Comment by iXo** [comment]
Update : core dump
[hs_err_pid5623.log.txt](https://github.com/caprica/vlcj/files/120647/hs_err_pid5623.log.txt)

**Comment by caprica** [comment]
I don't know, but the native libscaletempo plugin is implicated, and a number of scaletemp errors in your log precede the crash. In fact according to this log you are trying to set a whole bunch of unsupported options.

Use one of the vlcj audio player examples in the test sources and see if you get the same crash.
