### ISSUE TITLE
Save video stream into file

### ISSUE THREAD

**Issue by petervalencic** [caprica/vlcj#476]
Hi,
Is possible to save video stream into file?

**Comment by caprica** [comment]
Yes it is. You need to set a "sout" string, search the vlcj examples in the test sources.

**Comment by petervalencic** [comment]
OK! thank you so much! i will check..

**Comment by caprica** [comment]
For example ScreenRecorder.java and CaptureTest.java.

They don't save streams, but the idea is the same. You will see "...dst=file...", start there.

**Comment by caprica** [comment]
There was a vlcj-radio project on the old googlecode project page that saved streams.
