### ISSUE TITLE
Using VLCJ for DVB-T tuner

### ISSUE THREAD

**Issue by allbirth** [caprica/vlcj#479]
In our country there is a dvb frequency of 570000000 with 3 channels/programs; 16,17,18

This is the mrl i am using to change channel for vlc via batch file by replacing the **:program** value. 

    "C:\Program Files (x86)\VideoLAN\VLC\vlc.exe" dvb-t://frequency=570000000:bandwidth=8 :dvb-adapter=0 :live-caching=1000 :program=16

 
But when i use the same mrl via VLCJ it seems the **:program** does not have any effect and randomly show channel without changing code. 
   

    import uk.co.caprica.vlcj.discovery.NativeDiscovery;
    import uk.co.caprica.vlcj.player.MediaPlayer;
    import uk.co.caprica.vlcj.player.MediaPlayerFactory;

    public class VLCJTest {

        public static void main(String[] args) throws Exception {
            new NativeDiscovery().discover();

            final MediaPlayerFactory factory = new MediaPlayerFactory();
            final MediaPlayer mediaPlayer = factory.newHeadlessMediaPlayer();

            String str = "dvb-t://frequency=570000000 :bandwidth=8 :dvb-adapter=0 :live-caching=1000 :program=16";

            mediaPlayer.playMedia(str);

            Thread.currentThread().join();
        }
    }

Can anyone help me to solve how to change of channel/program of digital tv via VLCJ mrl?

Thank you.

**Comment by caprica** [comment]
The MRL part is everything up to the first space character. 

Everything after the first space is a media option.

So when you call playMedia you must split your string into separate MRL and media options array.

**Comment by allbirth** [comment]
Thanks for your response. 

Even if I do the split. it works the same. The channel/program is still randomly showing.

        String str = "dvb-t://frequency=570000000";
        String option = ":bandwidth=8 :dvb-adapter=0 :live-caching=1000 :program=16";
        
        mediaPlayer.playMedia(str, option);


Thanks again.

**Comment by caprica** [comment]
I said *array* of options.

**Comment by allbirth** [comment]
Thank you.
