### ISSUE TITLE
Can't stop play video from Vlcj

### ISSUE THREAD

**Issue by Alfian24an** [caprica/vlcj#480]
hi admin , thanks before for vlcj it really help me for play video on java ,
i'm using vlcj on canvas inside jframe (box inside box , something like that) when opened jframe , vlcj play video , but when move  it did'nt close video have been playing

is wrong in my code , any help ,please   ?

//class play video

         public void PlayerVid(String modeVid) throws InterruptedException, IOException { 
        NativeLibrary.addSearchPath(RuntimeUtil.getLibVlcLibraryName(), "C:\\Program Files\\VideoLAN\\VLC");
        Native.loadLibrary(RuntimeUtil.getLibVlcLibraryName(), LibVlc.class);
        MediaPlayerFactory mpf = new MediaPlayerFactory();

//        EmbeddedMediaPlayer emp = mpf.newEmbeddedMediaPlayer(new Win32FullScreenStrategy(this));
        EmbeddedMediaPlayer emp = mpf.newEmbeddedMediaPlayer();
        String file = "E:\\sample_iTunes.mov";
       
 if (modeVid.matches("play")) {

            System.out.println("mode play video");
            canvasVidSamsat.setBackground(Color.GREEN);
            emp.setVideoSurface(mpf.newVideoSurface(canvasVidSamsat));
            emp.setAspectRatio("640x480");
            //  emp.toggleFullScreen ();

            emp.prepareMedia(file);
            emp.parseMedia(); //add latest
            emp.setVideoTrack(1);
            emp.play();
        } else {
            System.out.println("mode stop video");
            emp.stop();
            file = null;
            System.gc();

            System.out.println("sudah do stop video");

        }

    }

//call play video 

    private void WindowOpened(java.awt.event.WindowEvent evt) {
        try {
            PlayerVid("play");
        } catch (InterruptedException | IOException ex) {
            Logger.getLogger(MenuPlayVideo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

//close jframe

    private void close() {
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);

    }

// Move Frame

    private void BackFromDataAndaActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            // TODO add your handling code here:
            PlayerVid("stop");
            close();
            MenuUtama Knext = new MenuUtama();
            Knext.setVisible(true);
        } catch (InterruptedException ex) {
            Logger.getLogger(MenuPlayVideo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MenuPlayVideo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

**Comment by caprica** [comment]
Your question is not clear to me. 

Maybe post a full code sample that demonstrate s your problem rather than these fragments you've posted.

**Comment by Alfian24an** [comment]
Here my code , i've try to move from jframe one to another jframe , by close current jframe and set visible true another jframe and  call EmbeddedMediaPlayer.stop()  , but by doing that , a jframe that play video when window opened do not close play video , and then when i open again that window , it play video differ from before page ...
any help  , how to close that jframe , please ?




[JavaApplication9.zip](https://github.com/caprica/vlcj/files/173150/JavaApplication9.zip)

**Comment by caprica** [comment]
I'm sorry but I still don't understand your problem. Is this related to vlcj specifically, or is it just a general problem about your Swing application?

**Comment by Alfian24an** [comment]
i'm sorry for my bad explanation ,i'm using java swing for my front end , and use vlcj to show video on that java swing
specifically , i'm in trouble when i'm trying to switch a single media player component between multiple panels (swing component : jframe).
or can you give me example vlcj play video from swing component (jframe) and then move to another component swing (jframe) ?

**Comment by caprica** [comment]
OK, I think understand now.

You can not switch your single media player between multiple components
(strictly speaking you *could* but it'd not recommended).
Probably you should just use a different media player component in each
window. However there are risks to doing so if you need them both to play
video at the same time.
