### ISSUE TITLE
length is missing from MediaMetaData

### ISSUE THREAD

**Issue by ThisIsAreku** [caprica/vlcj#482]
In commit https://github.com/caprica/vlcj/commit/35501c9a4958f4979ebb292f5361c407b3a39a17 , getLength was added on MediaMeta & DefaultMediaMeta but not in MediaMetaData.
Is it a mistake or intended ?

**Comment by caprica** [comment]
The meta data are a specific set of natively defined fields, like album name, artist and so on. Length is not one of the natively defined meta data fields

So no, it is not a mistake.

**Comment by ThisIsAreku** [comment]
I do not understand. Length is present on `MediaMeta ` (and his implementation: `DefaultMediaMeta`).

As `MediaMetaData` is just a facade for `MediaMeta ` when detached from native media handle (https://github.com/caprica/vlcj/blob/master/src/main/java/uk/co/caprica/vlcj/player/MediaMetaData.java#L25) I would expect all the properties of `MediaMeta ` to be present in `MediaMetaData`

**Comment by caprica** [comment]
This data structure represents something else - it is a direct encapsulation of the *native* meta data fields. Length is not one of those things.

Even if it were, the provided pull request simply added a getter and setter with nothing to actually set the value.

**Comment by caprica** [comment]
Maybe I overlooked something, but when I reviewed the commit it seemed to me that length did not belong there for the reasons I stated.

I might take another look.

Even so, the pull request did not "fix" the issue.

**Comment by ThisIsAreku** [comment]
Actually, the value was set here: https://github.com/ThisIsAreku/vlcj/commit/ef04fbfd7dd642ddd0a0a1695a3462bae814aed3#diff-1a38732e06c58c39b37e614298e7afb1R460

But I think i understand. `MediaMetaData` may represents `libvlc_meta_t`. But so the relation between `MediaMeta ` and `MediaMetaData` feels incomplete :)

**Comment by caprica** [comment]
Yeah, I admit it's not entirely clear, but that was my point about this class supposed to be representing the native meta data fields.

Maybe I was too quick to write this off, I'm no longer sure.

The discussion was useful though.
