### ISSUE TITLE
JVM crash on Kubuntu with [xcb] Unknown sequence number while processing queue; ../../src/xcb_io.c:274: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.

### ISSUE THREAD

**Issue by parg** [caprica/vlcj#484]
I'm having problems getting a simple SWT embedded player running on Kubuntu - the code (and output generated) is below. After seeing the reference to XInitThreads I added a call to 'LibX11.INSTANCE.XInitThreads' but that made no difference.

Linux: Up-to-date Kubuntu 15.10 (KDE Plasma)
Java:
    openjdk version "1.8.0_66-internal"
    OpenJDK Runtime Environment (build 1.8.0_66-internal-b17)
    OpenJDK 64-Bit Server VM (build 25.66-b17, mixed mode)
VLC:  2.2.1 Terry Pratchett (Weatherwax)
VLCJ: 3.10.1 (JNA 4.1.0)
SWT Version: 4611

Code to reproduce:

```
System.out.println("SWT version: " + SWT.getVersion());
Display display = new Display();
Shell  shell = new Shell(display, SWT.SHELL_TRIM );        
shell.setLayout(new FillLayout());
shell.setSize(800, 600);  

Composite  videoPanel = new Composite (shell, SWT.EMBEDDED);

Frame videoFrame = SWT_AWT.new_Frame(videoPanel);         
Canvas videoSurfaceCanvas = new Canvas();

videoSurfaceCanvas.setBackground(java.awt.Color.black);
videoFrame.add(videoSurfaceCanvas);

System.out.println( "XInitThreads: " + LibX11.INSTANCE.XInitThreads());

new NativeDiscovery().discover();

System.out.println( "Version: " + LibVlcVersion.getVersion());

MediaPlayerFactory mediaPlayerFactory = new MediaPlayerFactory("--no-video-title-show");

EmbeddedMediaPlayer mediaPlayer = mediaPlayerFactory.newEmbeddedMediaPlayer();

CanvasVideoSurface videoSurface = mediaPlayerFactory.newVideoSurface(videoSurfaceCanvas);
mediaPlayer.setVideoSurface(videoSurface);

shell.open();

mediaPlayer.playMedia( test_file );         

while(!shell.isDisposed()) {
    if(!display.readAndDispatch()) {
        display.sleep();
    }
}
mediaPlayer.release();
mediaPlayerFactory.release();
display.dispose();   
```

Output:

```
SWT version: 4611
(SWT:9944): Gdk-WARNING **: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.
XInitThreads: 1
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Version: 2.2.1 Terry Pratchett (Weatherwax)
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
java: ../../src/xcb_io.c:274: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Aborted (core dumped)
```

**Comment by caprica** [comment]
I don't know, that's obviously a native error.

I did have a fully working SWT example with vlcj, but that was written a few years ago. I am trying to find it.

**Comment by caprica** [comment]
By the way, "--no-video-title-show" is no longer needed - there is specific API for that now.

**Comment by parg** [comment]
That's there because I grabbed the example code from https://github.com/caprica/vlcj/issues/97 when hacking together some simple example of how to reproduce the problem :)

**Comment by caprica** [comment]
Was this 32-bit or 64-bit?

**Comment by parg** [comment]
64-bit.

By the way, did you ever make any progress on https://github.com/caprica/vlcj/issues/205 ? At the moment I can only get things working on Windows, the opposite of what I was expecting!

**Comment by caprica** [comment]
#205 can't be "fixed". It's fundamentally an issue of no heavyweight AWT on
OSX anymore.

**Comment by parg** [comment]
OK, but how about using SWT? The player that comes with Azureus/Vuze currently uses MPlayer and manages to work with some JNI code that I didn't write (and don't understand), but I can send over if you're interested.

**Comment by caprica** [comment]
vlcj indeed does work with SWT. I used to have example code for SWT but I can't quite locate it at the moment.

SWT indeed have a solution to embedding on OSX, but when I looked into it I couldn't see how to make vlcj work the same way. I think native code may be required. Anyway, everything I know about that subject is in the #205 issue.

Please move any future discussion on #205 to #205.

**Comment by caprica** [comment]
Example showing how to embed vlcj inside SWT that is itself embedded inside a Swing applicaiton at https://github.com/caprica/vlcj-swt-swing

**Comment by parg** [comment]
Nice, I'll check it out tomorrow and tell you how things go. Thanks

**Comment by caprica** [comment]
Example showing how to embled vlcj inside SWT, not using Swing, at https://github.com/caprica/vlcj-swt-demo

**Comment by parg** [comment]
OK, that got things working on Linux - thanks! For SWT on Mac I have managed to use the existing native glue code we had that creates a NSOpenGLView and things are working as well, hurrah!

**Comment by caprica** [comment]
For your OSX solution, are you able and willing to describe your approach or show some code? Maybe others will find it useful.

Does SWT on OSX not work?

**Comment by parg** [comment]
Well, I'm no expert so correct me if I've missed something, but there's no 'embeddedHandle' / 'handle' field in the SWT Composite that you can pass to libvlc as for Linux/Windows. For MPlayer (which runs out-of-process) we have some code that creates an NSOpenGLView as a child of an SWT Canvas who's ID can then be passed to libvlc - MPlayerRendererCanvas. I'm re-using code so I have to use reflection to pull the ID out, it is located within an 'impl' object (there are 32/64 bit impls) - if I could be bothered I'd add more direct access. Anyway, I've attached a zip of the stuff to do this. The java code then ends up being

	swt_composite.setLayout( new GridLayout());

	final MPlayerRendererCanvas mplayer_canvas = new MPlayerRendererCanvas( swt_composite, SWT.NONE );

	mplayer_canvas.setLayoutData( new GridData(  GridData.FILL_BOTH ));
	
	final VideoSurface vs = 
		new VideoSurface( vsa )
		{
			@Override
			public void attach(LibVlc libvlc, MediaPlayer mediaPlayer) {
				
				try{						
					Field f_impl = mplayer_canvas.getClass().getDeclaredField( "impl" );
					
					f_impl.setAccessible( true );
					
					Object impl = f_impl.get( mplayer_canvas );
					
					Field f_handle = impl.getClass().getDeclaredField( "id" );
					
					f_handle.setAccessible( true );
					
					long componentId = f_handle.getLong( impl );
									
					videoSurfaceAdapter.attach( libvlc, mediaPlayer, componentId );
					
				}catch( Throwable e ){
					
					e.printStackTrace();
				}
			}
		};		


[libmprCanvas.zip](https://github.com/caprica/vlcj/files/194427/libmprCanvas.zip)
