### ISSUE TITLE
Disable Subtitles failed

### ISSUE THREAD

**Issue by RyanAfrish7** [caprica/vlcj#485]
I tried to disable the subtitles by
```java
mediaPlayer.setSubTitleFile((String)null);
mediaPlayer.setSubTitleFile((File)null);
```
Also tried,
```java
mediaPlayer.cycleSpu();
```
```java
mediaPlayer.setSpu(-1);
```
Also, I tried to list the available tracks using `getTrackInfo()`
The result consisted only of a single TrackInfo
```
TextTrackInfo[codec=0x74627573,codecName=subt,originalCodec=0x74627573,originalCodecName=subt,id=2,profile=-1,level=-1,bitRate=0,language=null,description=null][encoding=null]
```

How do I solve this problem?

**Comment by caprica** [comment]
Post a single class test case. Disabling SPU definitely works.

**Comment by RyanAfrish7** [comment]
What do you mean by a single class test case?

**Comment by caprica** [comment]
Post a complete example class that demonstrates your problem so I can take
a look at it.

**Comment by RyanAfrish7** [comment]
Oops, I have called setSpu(-1) just after playMedia(), but playMedia() is running asynchronously and it was not finished when I called setSpu().
