### ISSUE TITLE
Length is null

### ISSUE THREAD

**Issue by Tobisaninfo** [caprica/vlcj#487]
I have tried to load an audio file (e.g. mp3) by using the prepareMedia(URL) method in MediaPlayer, followed by the parseMedia(). After all loading, the getLength return just 0. Then I play the file, then the length will be set. Is there a fix for this, so that I can obtain the length before start playing the file?

**Comment by caprica** [comment]
Whether the length is available or not, before playing, depends on the type of media and the native codec.

As you've found, in your case the length simply is not available until the media starts playing. There is nothing you can do about it, it's how VLC works. The codec needs to start decoding the media stream to extract or calculate the length, therefore the media must start playing.

What I do is use Java bindings to the native "MediaInfo" application, see https://github.com/caprica/vlcj-info. You could also try a Java ID3 tag library.
