### ISSUE TITLE
vlcj does not record RTP stream after short break in it

### ISSUE THREAD

**Issue by lichoniespi** [caprica/vlcj#488]
VLC 2.2.2
vlcj 3.9.0

vlcj does not record given video after short break in a stream.

I'm calling  mediaPlayer.playMedia(stream,":sout=#std{access=file,mux=ps,dst=" + tempFile.getAbsolutePath() + "}"); 

on a HeadlessMediaPlayer mediaPlayer, it records given RTP stream 
(stream = "rtp://@" + this.address + ":" + Integer.toString(this.port);) 
properly until there is a short break in stream (the source stops sending stream for a few seconds).
vlcj does not log any errors while stream isin't working.

I guess the stream should be recorded regardless of breaks in it.

Its just this log when we start recording:
[00000000271c8bb0] mux_ps mux: Open
and this when we end it (on purpose, not stream break):
[00000000271c8df0] mux_ps mux: Close

forgot to mention im also using: mediaPlayer.setRepeat(true);

**Comment by caprica** [comment]
This is difficult to do anything about, because vlcj is not recording your stream, VLC is recording it.

If you received a finished or stopped event, you could restart the stream and a new recording - however I suspect that you don't get those events so you're probably stuck I'm afraid.
