### ISSUE TITLE
JVM crash with vlcj 3.10.1 and VLC 2.2.x on Fedora 64-bit and Debian 64-bit

### ISSUE THREAD

**Issue by xinyingho** [caprica/vlcj#489]
I did all my tests on Fedora 22 64-bit and the latest Oracle's JVM available (1.8.0_91) but I could also get the same issues on Debian 8.4.0 64-bit / Oracle's JVM 1.8.0_77 as well. I couldn't reproduce the issue on Kubuntu 14.04.

I simply edited the ResizeJavaFXPlayerTest.java of vlcj-javafx by adding a browse button to open a regular DirectoryChooser dialogbox. After compiling and launching the app without arguments, each time I click on the button, the JVM astonishly crashes and I get a seg fault / core dump about some pthread issues...

I join the source code of my modified java file and the logs of the core dump.
[hs_err_pid11166.txt](https://github.com/caprica/vlcj/files/231683/hs_err_pid11166.txt)

[ResizableJavaFXPlayerTest.java.txt](https://github.com/caprica/vlcj/files/231685/ResizableJavaFXPlayerTest.java.txt)

**Comment by caprica** [comment]
Probably the same as https://github.com/caprica/vlcj-javafx/issues/10

**Comment by xinyingho** [comment]
Yes, this is the same issue. And the workaround given in the other ticket does work for me as well. Even if I enable the flag for Kubuntu 14.04, I don't get any problems anymore.

It seems like LibX11.INSTANCE.XInitThreads() is really not needed anymore.

**Comment by caprica** [comment]
The reason it was added, IIRC, is that without it the JVM splash-screen option won't work.

So you have to decide what the default would be I suppose, one way or the other.
