### ISSUE TITLE
How to Play an RTP Music Stream 

### ISSUE THREAD

**Issue by Markus1397** [caprica/vlcj#498]
For a school project i have to programm an client for an unicast rtp stream. The client should be able to play audio files. Is there already a tutorial or something like that which can help me with my problem?

**Comment by caprica** [comment]
Look here for general tutorials:

http://capricasoftware.co.uk/#/projects/vlcj/tutorial

To play a stream, you just pass the streaming URL via mediaPlayer.playMedia(mrl);

**Comment by Markus1397** [comment]
My problem is that I am not able to get started with your project on mac osx 10.11.5.

**Comment by caprica** [comment]
Your problem description is opaque. How do you expect me to help you further?

**Comment by Markus1397** [comment]
Sry here is the exception i get: 
Exception in thread "main" java.lang.RuntimeException: Failed to load the native library.

The error was "Unable to load library 'vlc': Native library (darwin/libvlc.dylib) not found in resource path ([file:/Library/Java/Extensions/jmf.jar, file:/Users/markus/Downloads/vlcj-3.10.1/vlcj-3.10.1.jar, file:/Users/markus/Downloads/vlcj-3.10.1/vlcj-3.10.1-tests.jar, file:/Users/markus/Downloads/vlcj-3.10.1/slf4j-api-1.7.10.jar, file:/Users/markus/Downloads/vlcj-3.10.1/jna-4.1.0.jar, file:/Users/markus/Downloads/vlcj-3.10.1/jna-platform-4.1.0.jar, file:/Users/markus/Downloads/slf4j-1.7.21/slf4j-nop-1.7.21.jar, file:/Users/markus/AudioStream/Audio_Test/build/classes/])".

The required native libraries are named "libvlc.dylib" and "libvlccore.dylib".

In the text below <libvlc-path> represents the name of the directory containing "libvlc.dylib" and "libvlccore.dylib"...

There are a number of different ways to specify where to find the native libraries:
 1. Include NativeLibrary.addSearchPath("vlc", "<libvlc-path>"); at the start of your application code.
 2. Include System.setProperty("jna.library.path", "<libvlc-path>"); at the start of your application code.
 3. Specify -Djna.library.path=<libvlc-path> on the command-line when starting your application.
 4. Add <libvlc-path> to the system search path (and reboot).

If this still does not work, then it may be necessary to explicitly add the native library directory to the operating
system configuration - e.g. on Linux this might mean setting the LD_LIBRARY_PATH environment variable, or adding
configuration to the "/etc/ld.so.conf" file or the "/etc/ld.so.conf.d" directory. Of these options, setting
LD_LIBRARY_PATH is the only one that would not require root privileges.

Finally, it is not possible to mix CPU architectures - it is not possible for a 64-bit Java Virtual Machine to load
32-bit native libraries.

More information may be available in the log.

	at uk.co.caprica.vlcj.binding.LibVlcFactory.create(LibVlcFactory.java:198)
	at uk.co.caprica.vlcj.player.MediaPlayerFactory.<init>(MediaPlayerFactory.java:259)
	at uk.co.caprica.vlcj.component.AudioMediaPlayerComponent.onGetMediaPlayerFactory(AudioMediaPlayerComponent.java:177)
	at uk.co.caprica.vlcj.component.AudioMediaPlayerComponent.<init>(AudioMediaPlayerComponent.java:109)
	at RTPClient.<init>(RTPClient.java:82)
	at RTPClient.main(RTPClient.java:72)
	at Audio_Test.main(Audio_Test.java:30)
Java Result: 1

I know the exception description is pretty good but I am still not able to fix it.

**Comment by caprica** [comment]
Did you go through this:

http://capricasoftware.co.uk/#/projects/vlcj/tutorial/first-steps

**Comment by Markus1397** [comment]
I did and i got the following output for Option 1:
```
true
2.2.1 Terry Pratchett (Weatherwax)
```
and for the 2. Option the Output was: 
2.2.1 Terry Pratchett (Weatherwax)

**Comment by caprica** [comment]
That shows it is working, so do the exactly the same thing in your own application.

**Comment by Markus1397** [comment]
okay thank you for your help and your patience
