### ISSUE TITLE
Support Bluray disc playing via mrl

### ISSUE THREAD

**Issue by crynspo** [caprica/vlcj#500]
I'm try to open bluray disk using next code:
`mediaPlayer.prepareMedia("bluray:///H:/");`
`mediaPlayer.play();`

Here is error: 

file/libaacs.c:109: No usable AACS libraries found!
[000000001f4719e0] libbluray demux: First play: 1, Top menu: 1
HDMV Titles: 2, BD-J Titles: 1, Other: 0
[000000001f4719e0] core demux error: 
[000000001f4719e0] core demux error: 
[000000001f413900] core input error: open of `bluray:///H:/' failed
[000000001f413900] core input error: 
[000000001f413900] core input error: VLC 

Is there a way to fix this error? Can vlcj support bluray discs now?

Windows 10 x64, VLCx64 2.2.1, vlcj  3.10.1, jna 4.2.2

**Comment by caprica** [comment]
> No usable AACS libraries found!

Your system does not have the libraries necessary for Bluray decryption.

**Comment by crynspo** [comment]
I have no problem when I use VLC standalone. I download aasc library and it successfully plays my Bluray disks. I have problem only with a vlcj. Do I need add any library dll to my project except for libvlc.dll?

**Comment by caprica** [comment]
Are you sure you are using the same version of VLC in standalone vs with vlcj?

This...

>file/libaacs.c:109: No usable AACS libraries found!

...is a native error from VLC.

There's nothing that can be fixed in vlcj here.

**Comment by caprica** [comment]
What command-line do you type to make it work the VLC standalone?

**Comment by crynspo** [comment]
I don't use CLI for it launch. I download files how it describes [here](http://vlc-bluray.whoknowsmy.name/) and then I choose Media-> Open Disc -> Blu-ray and my drive. In "show more options" menu there are: MRL: bluray:///H:/,  Edit options:disc-caching=300

**Comment by caprica** [comment]
I don't know what more I can say. There's nothing that can be fixed in vlcj here. The native log you posted says VLC can't open your Bluray. That's not a vlcj log.

**Comment by caprica** [comment]
Maybe try "-vvv" for the `MediaPlayerFactory` arguments and check the verbose log.

**Comment by crynspo** [comment]
Ok. Problem was really not in vlcj. After I installed solution for bluray decoding it works fine wth "bluray:///H:/". Thanks for support!
