### ISSUE TITLE
How get snapshot image in the correctly time.

### ISSUE THREAD

**Issue by jmanuel1609** [caprica/vlcj#504]
Hi:
I am trying to get the snap shot and save the image and time. I followed this steps:
1- pause the video. 
`application().mediaPlayerComponent().getMediaPlayer().pause(); `
2- in paused event i call a function for get the snapshot. 
getVlcjFrame();
3- i save the snap shot in the specific file.

private void getVlcjFrame()  {

                final  boolean isplaying = application().mediaPlayerComponent().getMediaPlayer().isPlaying();
                if(!isplaying) {
					String filename =  application().mediaPlayerComponent().getMediaPlayer().getTime()+".png";

					File f  = new File(application().getSnapshotDir()+"\\"+filename);
					application().mediaPlayerComponent().getMediaPlayer().saveSnapshot(f);			
             }
}

4- in the snap shot taken event i get the file path and i convert to buffer image and get the time.

 ```
 @Override
public void snapshotTaken(MediaPlayer mediaPlayer, String filename) {
	            	 File file =  new File(filename);
	            	 BufferedImage bufferedImage  =  null;
	            	 if(file.exists()) {
	            		  try {
							bufferedImage =   ImageIO.read(file );
						} catch (IOException e) {
							// TODO Auto-generated catch block
							e.printStackTrace();
						}
	            	 }
	            	if(bufferedImage!=null)	 
					    application().post(new SnopShotWasTakenEvent(mediaPlayer.getTime(),bufferedImage));
				}
```

5- save image and time.

```
@Subscribe
public void onSanpShotWasTakend(SnopShotWasTakenEvent event) 
{
	ImageIcon imageIcon = null;
	if(event.getImage()!=null) {
		imageIcon =  new ImageIcon(event.getImage());
	}
	frameComment.setFrame(imageIcon);
	frameComment.setTime(event.getTime());
             
			
 }

```

6- letter i try to set the specific time to the video and the time is wrong.  some millisecond. and if in this differences of millisecond the video have other different frame you will see the difference.  
 I tried to do the same in the VLCJ java example and have the same issue

**Comment by caprica** [comment]
Please fix your code formatting.

VLC simply does not provide the accuracy you want when setting time.

**Comment by jmanuel1609** [comment]
But vlcj have the functionality to go frame by frame. this is my implementation to go frame by frame

```

	    public void onPrevFrame(PrevFrameEvent event) {
	    	long currentTime = event.getTime();
	    	long newtime = currentTime - getVideoRate();
	    	mediaPlayerComponent.getMediaPlayer().setTime(newtime);
	    	positionPane.setTime(newtime);
            statusBar.setTime(newtime);
	    	
	    }

	    public void onNextFrame(NextFrameEvent event) {
	    	long currentTime = event.getTime();
	    	long newtime = currentTime +  getVideoRate();
	    	mediaPlayerComponent.getMediaPlayer().setTime(newtime);
	    	positionPane.setTime(newtime);
            statusBar.setTime(newtime);
	    //	application().mediaPlayerComponent().getMediaPlayer().nextFrame();
	    	
	    }

 public long getVideoRate() {
	    	 VideoTrackInfo videoTrackInfo = (VideoTrackInfo) application().mediaPlayerComponent().getMediaPlayer().getTrackInfo(TrackType.VIDEO).get(0);
	    	 return Math.round(1000.0f/(videoTrackInfo.frameRate() / videoTrackInfo.frameRateBase()));
	    }
```

**Comment by caprica** [comment]
You can't seek to an arbitrary frame. You can seek to the "next" one, but not a specific one.

Your solution is an approximation, which is good enough for you if you say so.

Even if you argue the point, the vlcj function to do `mediaPlayer.setTime(timeInMilliseconds)` maps directly onto the native `libvlc_media_player_set_time(timeInMilliseconds)` method. So your code is in effect calling the native code and vlcj does not interfere with anything. So you have absolutely hit a limit of the native library, not vlcj.

**Comment by jmanuel1609** [comment]
thanks. then is not possible to get the snapshot save the time that was taken and go to this exactly to this specific time?

**Comment by caprica** [comment]
Unfortunately, no.

This is not a limitation of vlcj, it is (arguably) a limitation of VLC's decoders.

**Comment by jmanuel1609** [comment]
thanks for your help.

**Comment by jmanuel1609** [comment]
hi
what about 
mediaPlayer.nextFrame(): 
libvlc_media_player_next_frame
then this function doesn't go o the right next frame? 
do you have prevframe()?

**Comment by caprica** [comment]
That function does indeed go to the "next" frame. I don't see how that's useful for you in this circumstance. It doesn't change the fact that requesting VLC seek to a particular millisecond does not guarantee you the exact same frame that you want.

There is no native API method in LibVLC to go the previous frame. There is discussion at the VideoLAN forum and/or the vlc-devel mailing list from ages ago that discusses why this is simply not possible due to the architecture of VLC.

**Comment by jmanuel1609** [comment]
thanks i got it.

**Comment by jmanuel1609** [comment]
Sorry but i have other question how can i catch this exception: [168def2c] http access error: seek failed 
here are my logs 
`[168def2c] http access error: seek too far `
`[299c0a94] core decoder error: Could not convert timestamp 113031561392`
`[168def2c] http access error: seek too far`
`[168def2c] http access error: error: HTTP/1.1 500 Object not found`
`[168def2c] http access error: seek failed  `


thanks in advance

**Comment by caprica** [comment]
Please don't conflate different problems/questions into the same issue.

In any case, you can not catch errors like that in Java - the native LibVLC API simply does not provide any notification of any such error.

The best you can do is intercept the native log and search for those error messages. vlcj provides some help for doing that, but frankly it's a pretty poor solution..

Again, this is a limitation of LibVLC, not vlcj.

**Comment by jmanuel1609** [comment]
thanks for you quickly answer . how can i intercept the native log?

**Comment by caprica** [comment]
Search Javadoc and vlcj test sources for NativeLog.
