### ISSUE TITLE
Is possible get a callback for release video function?

### ISSUE THREAD

**Issue by jmanuel1609** [caprica/vlcj#506]
Is possible get a callback for release video function?
    `mediaPlayerComponent.getMediaPlayer().release();`

**Comment by caprica** [comment]
What would be the purpose for such a callback?

When you release a media player, the native resources are destroyed. There's no point doing anything with the media player after you invoke release.

**Comment by jmanuel1609** [comment]
thanks Mark. i resolve the problem
