### ISSUE TITLE
It is posibble to add a logo and then export the video?

### ISSUE THREAD

**Issue by gustavo-am** [caprica/vlcj#507]
Hello, 

I'm trying to make a kind of Video Editor with vlcj, i tried the example found on `package uk.co.caprica.vlcj.test.logo;` and everything works find, i just can't figure how to export the video withe the logo attached to a new file. I tried with media options in many differents way, also reading vlc --sout example but i'cant make it work:

```
  String[] opts = {"--logo-file logo.jpg",
            "--sout #transcode{sfilter=logo}:std{access=file,dst=C:\\new_video.avi }"};
```
Another fail

```
  String[] opts = {":sout=#standard{mux=ts,access=file,dst=C:\\capture.mp4}"};
```
If i'm missing some important info, please let me know.

Thank you

BTW: vlc binaries: 2.2.4 x64 and vlcj 3.10.1 with jna 4.2.2

**Comment by caprica** [comment]
It can't be done. The logo is an overlay and never becomes part of the video stream/frames.

**Comment by gustavo-am** [comment]
Well, thank you for answering!!
