### ISSUE TITLE
Time Scale in VLC

### ISSUE THREAD

**Issue by jmanuel1609** [caprica/vlcj#508]
Hello:
QuickTime have a function  call  GetMediaTimeScale  for the the media time scale:
https://developer.apple.com/library/mac/documentation/QuickTime/RM/Fundamentals/QTOverview/QTOverview_Document/QuickTimeOverview.html 
How can i get the time scale of the media in VLC? do you have a function for that or a way to calculate? 
thanks in advance

**Comment by caprica** [comment]
Look here for the available functions: http://caprica.github.io/vlcj/javadoc/3.10.1/uk/co/caprica/vlcj/player/MediaPlayer.html

If you can't find it here, it doesn't exist.

**Comment by jmanuel1609** [comment]
what about the video metadata
basically i need to get this: Movie unit time scale. 
https://books.google.com/books?id=WwzK0JopNNAC&pg=PA68&lpg=PA68&dq=how+quick+time+calculate+time+scale&source=bl&ots=hOXdHIxDrR&sig=JpCo0yFxB87uc84i5W3VvWH1paE&hl=en&sa=X&ved=0ahUKEwj2x4bz_erOAhXJRyYKHVduDcYQ6AEIUTAH#v=onepage&q=how%20quick%20time%20calculate%20time%20scale&f=true

you don't have the function available you will have in the future?

**Comment by caprica** [comment]
> what about the video metadata
Did you look?

Search the Javadoc for metadata, and maybe trackinfo.

> you don't have the function available you will have in the future?
vlcj already supports everything that LibVLC exposes (well, not some irrelevant functionality).

**Comment by jmanuel1609** [comment]
this information is not there, neither Video Track neither metadata.   .... thanks anyways.

**Comment by caprica** [comment]
Sorry that's not the outcome you wanted - if LibVLC exposed it, it would be available in vlcj too.
