### ISSUE TITLE
Is possible go to specific frame in VLCJ?

### ISSUE THREAD

**Issue by jmanuel1609** [caprica/vlcj#509]
Hi I was trying to go to specific frame in VLC but doesn't refresh the video.. i thought that is a vlc error but i found this plugin: 
http://addons.videolan.org/content/show.php/Jump+to+time+(Previous+frame)+v2.1?content=156396 
and i can jump to specific time in millisecond and go frame by frame. 
for example if the video have 24 fps you can set into the 3rd  input -0.042 and you will go to previous frame. 
is possible add this functionality to vlcj because now next frame function doesn't go to the next frame correctly  and vlcj don't have prev frame function.

**Comment by caprica** [comment]
I thought I already covered this in your other issue.

With VLC, fundamentally it is simply not possible to seek to a particular frame. There is no API like libvlc_media_player_set_frame(frame_number). You get libvlc_media_player_set_position(percent) and libvlc_media_player_set_time(whole_number_of_milliseconds) and that's it.

*Whatever that add-on is doing, it still is subject to the same fundamental limitation.*

In any event, LibVLC does not expose any API for interacting with add-ons, so vlcj can not support that either.

Frankly, it looks to me like VLC is not going to support your particular use-case.

**Comment by jmanuel1609** [comment]
thanks..
then i can not use this lua methods using  LUAJ?
