### ISSUE TITLE
How can I save video within logo

### ISSUE THREAD

**Issue by hongsonitptit** [caprica/vlcj#513]
I want to save my video within logo. 
I have added logo to my video like this example: 
https://github.com/caprica/vlcj/blob/master/src/test/java/uk/co/caprica/vlcj/test/logo/LogoTest.java
It have played perfectly within logo but when I tried to save this video by play media with mediaOption:
String[] options1 = {			":sout=#transcode{vcodec=mp4v,vb=4096,scale=1,acodec=mpga,ab=128,channels=2,samplerate=44100}:duplicate{dst=file{dst="+ savedFilePath + "},dst=display}"};
This video have been played and saved but I could not show logo in my video any more.
How can I do that?

**Comment by caprica** [comment]
Simply put, you can't. The logo is an entirely separate overlay. It is never "part of" the video.

You would have to decode each video frame, render an image into it, and re-encode it. For that you'd need some proper video editing software.

**Comment by hongsonitptit** [comment]
OK, I can not save my video within my logo.
why I can not show my logo when playing video directly???
Why is not this code run when I play with optionMedia to save video?
logo().file("logo.png").location(30, 30).position(libvlc_logo_position_e.top_left).opacity(200).enable(true)
			.apply(mediaPlayer);
