### ISSUE TITLE
Could not show logo when setup mediaOption to save video

### ISSUE THREAD

**Issue by hongsonitptit** [caprica/vlcj#514]
I want to show logo when setup media option to save video.
I have showed logo and saved video independence independent, but when I merge them, video was only saved, not showed logo
How can I do that? Is it impossible?

**Comment by caprica** [comment]
Seems like it is not possible to save the video, with media options, and display the logo at the same time.

That is a "limitation" of VLC, not vlcj.

**Comment by hongsonitptit** [comment]
Thank you!
