### ISSUE TITLE
Problem getting accelerated video under linux

### ISSUE THREAD

**Issue by ozster123** [caprica/vlcj#516]
I am trying to play a stream using JVLC in a linux system. My problem is getting VLC to use hardware acceleration to play the steam. If I use the command line version cvlc I can see the system choose an accelerated video output device. However when I try to play the same stream with my jvlc sample it will not use the accelerated video output device even if I directly request it using vout=xxx.
I am using jvlc 3.10.1 and vlc 2.2.1.
Here is part of the vlc output for each play of the same stream.

Using CVLC
[00891768] core scale debug: looking for video filter2 module matching "any": 57 candidates
[00891768] yuvp scale debug: YUVP to YUVA converter
[00891768] core scale debug: using video filter2 module "yuvp"
[0080f4f0] core video output debug: Deinterlacing available
[0080f4f0] core video output debug: deinterlace 0, mode blend, is_needed 0
[0080f4f0] core video output debug: Opening vout display wrapper
[72b0ae08] core vout display debug: looking for vout display module matching "omxil_vout": 16 candidates
[72b0ae08] omxil_vout vout display debug: component OMX.broadcom.audio_capture
[72b0ae08] omxil_vout vout display debug: component OMX.broadcom.audio_decode
[73d00508] core input debug: Buffering 49%
[72b0ae08] omxil_vout vout display debug: component OMX.broadcom.audio_encode
[72b0ae08] omxil_vout vout display debug: component OMX.broadcom.audio_render
[72b0ae08] omxil_vout vout display debug: component OMX.broadcom.audio_mixer
[72b0ae08] omxil_vout vout display debug: component OMX.broadcom.audio_splitter
[72b0ae08] omxil_vout vout display debug: component OMX.broadcom.audio_processor
[72b0ae08] omxil_vout vout display debug: component OMX.broadcom.camera
[72b0ae08] omxil_vout vout display debug: component OMX.broadcom.clock
[72b0ae08] omxil_vout vout display debug: component OMX.broadcom.coverage
[72b0ae08] omxil_vout vout display debug: component OMX.broadcom.egl_render
[72b0ae08] omxil_vout vout display debug: component OMX.broadcom.image_fx
[72b0ae08] omxil_vout vout display debug: component OMX.broadcom.image_decode
[72b0ae08] omxil_vout vout display debug: component OMX.broadcom.image_encode
[72b0ae08] omxil_vout vout display debug: component OMX.broadcom.image_read
[72b0ae08] omxil_vout vout display debug: component OMX.broadcom.image_write
[72b0ae08] omxil_vout vout display debug: component OMX.broadcom.read_media
[72b0ae08] omxil_vout vout display debug: component OMX.broadcom.resize
[72b0ae08] omxil_vout vout display debug: component OMX.broadcom.source
[72b0ae08] omxil_vout vout display debug: component OMX.broadcom.text_scheduler
[72b0ae08] omxil_vout vout display debug: component OMX.broadcom.transition
[72b0ae08] omxil_vout vout display debug: component OMX.broadcom.video_decode
[72b0ae08] omxil_vout vout display debug: component OMX.broadcom.video_encode
[72b0ae08] omxil_vout vout display debug: component OMX.broadcom.video_render
[72b0ae08] omxil_vout vout display debug: component OMX.broadcom.video_scheduler
[72b0ae08] omxil_vout vout display debug: component OMX.broadcom.video_splitter
[72b0ae08] omxil_vout vout display debug: component OMX.broadcom.visualisation
[72b0ae08] omxil_vout vout display debug: component OMX.broadcom.write_media
[72b0ae08] omxil_vout vout display debug: component OMX.broadcom.write_still
[72b0ae08] omxil_vout vout display debug: found 1 matching components for role iv_renderer
[72b0ae08] omxil_vout vout display debug: - OMX.broadcom.video_render
[72b0ae08] omxil_vout vout display debug: OmxEventHandler (OMX_EventCmdComplete, OMX_CommandStateSet, OMX_StateIdle)
[72b0ae08] omxil_vout vout display debug: OmxEventHandler (OMX_EventCmdComplete, OMX_CommandStateSet, OMX_StateExecuting)
[72b0ae08] core vout display debug: VoutDisplayEvent 'fullscreen' 1
[72b0ae08] core vout display debug: using vout display module "omxil_vout"

Using JVCL
[63fa2da8] core scale debug: looking for video filter2 module matching "any": 57 candidates
[63fa2da8] yuvp scale debug: YUVP to YUVA converter
[63fa2da8] core scale debug: using video filter2 module "yuvp"
[63f88870] core video output debug: Deinterlacing available
[63f88870] core video output debug: deinterlace 0, mode blend, is_needed 0
[63f88870] core video output debug: Opening vout display wrapper
[64c04ce8] core vout display debug: looking for vout display module matching "xid": 16 candidates
[64c052e0] core window debug: looking for vout window xid module matching "embed-xid,any": 4 candidates
[64c052e0] core window debug: using vout window xid module "xcb_window"

I am not sure if the xid is related to the CanvasVideoSurface. Any ideas?

**Comment by caprica** [comment]
It's vlcj, not JVLC.

Anyway...

What precisely are you doing to get it working with "cvlc", and what precisely are you using in vlcj?

Show command-line and code.

All you can really do through LibVLC is tell VLC to render into a particular window, that is indeed the "xid" you refer to.

There may be some tricks you can in the Java/AWT side to try and get an accelerated video surface, but I don't recall what those might be.

**Comment by ozster123** [comment]
The command line for cvlc is simply the stream, ie cvlc udp://@224.10.0.3:5001. I am not specifying any codecs. VLC is automatically using the hardware accelerated video output device.
Below is the code for the vlcj. Do you think I need to create a particular surface type in Java that is compatible with the accelerated video output device?

public final class SimpleStream
{
	//
	// Static Fields (Private)
	//
	private static String TARGET_OSX	= "OSX";
	private static String TARGET_LINUX	= "Linux";
	//
	// Static Methods
	// e.g. static public void 
	//

	/**
	 * @param args
	 */
	public static void main(String[] args)
	{
		SimpleStream simpleStream = new SimpleStream();
		simpleStream.init();
		simpleStream.run();
	}

	//
	// Member Fields (Private)
	//
	private Logger logger = LoggerFactory.getLogger(getClass());
	private String targetOS;
	private Display display;
	private Shell shell;
	private MediaPlayerFactory mediaPlayerFactory;
	private EmbeddedMediaPlayer mediaPlayer;
	private Composite videoComposite;
	private Frame videoFrame;
	private Canvas videoSurface;
	private CanvasVideoSurface canvasVideoSurface;

	//
	// Construction/Finalization
	//
	public SimpleStream()
	{
		//targetOS = TARGET_OSX;
		targetOS = TARGET_LINUX;
		logger.info("Target OS is " + targetOS);
	}

	//
	// Methods
	//
	
	public void init()
	{
		if (targetOS.equals(TARGET_OSX))
		{
			try 
			{
			    LibC.INSTANCE.setenv("VLC_PLUGIN_PATH", "/Applications/VLC.app/Contents/MacOS/plugins", 1);
			}
			catch(Exception ex) 
			{
			    ex.printStackTrace();
			}	        
			NativeLibrary.addSearchPath(
	                RuntimeUtil.getLibVlcLibraryName(), "/Applications/VLC.app/Contents/MacOS/lib"
            );
		}
		else if (targetOS.equals(TARGET_LINUX))
		{
			// need to initialise the xlib properly to make sure that hardware decoding works
			LibXUtil.initialise();
		}
        Native.loadLibrary(RuntimeUtil.getLibVlcLibraryName(), LibVlc.class);

        LibVlc libvlc = LibVlcFactory.factory().create();
        String[] vlcArgs = null;
		if (targetOS.equals(TARGET_OSX))
		{
			String[] macVLCArgs = { "--no-video-title-show" };
			vlcArgs = macVLCArgs;
		}
		else if (targetOS.equals(TARGET_LINUX))
		{
			String[] linuxVLCArgs = { "-vvv", "--no-video-title-show", "--avcodec-hw=any" };
			vlcArgs = linuxVLCArgs;
		}
		mediaPlayerFactory = new MediaPlayerFactory(libvlc, vlcArgs);
		mediaPlayer = mediaPlayerFactory.newEmbeddedMediaPlayer();
		
	    display = new Display ();
		shell = new Shell(display, SWT.NO_TRIM);
		shell.setBackground(display.getSystemColor(SWT.COLOR_CYAN));
		shell.setBounds(0, 0, 800, 500);
		shell.addMouseListener(new MouseListener()
		{
		
			public void mouseUp(MouseEvent e)
			{
			}
		
			public void mouseDown(MouseEvent e)
			{
				logger.info("Closing the shell.");
				mediaPlayer.stop();
				mediaPlayer.setVideoSurface(null);
				shell.close();
			}
		
			public void mouseDoubleClick(MouseEvent e)
			{
			}
		});
		shell.open();
		
		videoComposite = new Composite(shell, SWT.EMBEDDED | SWT.NO_BACKGROUND);
		videoFrame = SWT_AWT.new_Frame(videoComposite);
		videoSurface = new Canvas();
		videoSurface.setBackground(java.awt.Color.black);
		videoSurface.setBounds(0, 0, 720, 405);
		videoFrame.add(videoSurface);
		videoComposite.setBounds(30, 30, 720, 405);
		videoComposite.setVisible(true);
		
		if (targetOS.equals(TARGET_OSX))
		{
			canvasVideoSurface = new CanvasVideoSurface(videoSurface, new MacVideoSurfaceAdapter());
		}
		else if (targetOS.equals(TARGET_LINUX))
		{
			canvasVideoSurface = new CanvasVideoSurface(videoSurface, new LinuxVideoSurfaceAdapter());
		}
		mediaPlayer.setVideoSurface(canvasVideoSurface);
		MediaPlayerEventType[] events = {
//				MediaPlayerEventType.PLAYING, 
//				MediaPlayerEventType.FINISHED
				MediaPlayerEventType.ALL
		};
		mediaPlayer.enableEvents(MediaPlayerEventType.events(events));
		//mediaPlayer.setDeinterlace(DeinterlaceMode.MEAN);
		mediaPlayer.setDeinterlace(null);
		mediaPlayer.addMediaPlayerEventListener(new MediaPlayerEventListener()
		{
		
			public void volumeChanged(MediaPlayer mediaPlayer, float volume)
			{
				logger.info("volumeChanged volume " + String.valueOf(volume));
			}
		
			public void videoOutput(MediaPlayer mediaPlayer, int newCount)
			{
				logger.info("videoOutput newCount " + String.valueOf(newCount));
			}
		
			public void titleChanged(MediaPlayer mediaPlayer, int newTitle)
			{
				logger.info("titleChanged newTitle " + String.valueOf(newTitle));
			}
		
			public void timeChanged(MediaPlayer mediaPlayer, long newTime)
			{
				//logger.info("timeChanged newTime " + String.valueOf(newTime));
			}
		
			public void subItemPlayed(MediaPlayer mediaPlayer, int subItemIndex)
			{
				logger.info("subItemPlayed subItemIndex " + String.valueOf(subItemIndex));
			}
		
			public void subItemFinished(MediaPlayer mediaPlayer, int subItemIndex)
			{
				logger.info("subItemFinished subItemIndex " + String.valueOf(subItemIndex));
			}
		
			public void stopped(MediaPlayer mediaPlayer)
			{
				logger.info("subItemFinished stopped");
			}
		
			public void snapshotTaken(MediaPlayer mediaPlayer, String filename)
			{
				logger.info("snapshotTaken filename " + String.valueOf(filename));
			}
		
			public void seekableChanged(MediaPlayer mediaPlayer, int newSeekable)
			{
				logger.info("seekableChanged newSeekable " + String.valueOf(newSeekable));
			}
		
			public void scrambledChanged(MediaPlayer mediaPlayer, int newScrambled)
			{
				logger.info("scrambledChanged newScrambled " + String.valueOf(newScrambled));
			}
		
			public void positionChanged(MediaPlayer mediaPlayer, float newPosition)
			{
				//logger.info("positionChanged newPosition " + String.valueOf(newPosition));
			}
		
			public void playing(MediaPlayer mediaPlayer)
			{
				logger.info("playing");
				List <TrackDescription> tracks = mediaPlayer.getSpuDescriptions();
				int trackIndex = -1;
				for (TrackDescription td : tracks)
				{
					System.out.println("subtitle track: " + td.description() + " index " + String.valueOf(td.id()));
					if (td.description().contains("subtitles"))
					{
						trackIndex = td.id();
						break;
					}
				}
				if (-1 != trackIndex)
					mediaPlayer.setSpu(trackIndex);
			}
		
			public void paused(MediaPlayer mediaPlayer)
			{
				logger.info("paused");
			}
		
			public void pausableChanged(MediaPlayer mediaPlayer, int newPausable)
			{
				logger.info("pausableChanged newPausable " + String.valueOf(newPausable));
			}
		
			public void opening(MediaPlayer mediaPlayer)
			{
				logger.info("opening");
			}
		
			public void newMedia(MediaPlayer mediaPlayer)
			{
				logger.info("newMedia");
			}
		
			public void muted(MediaPlayer mediaPlayer, boolean muted)
			{
				logger.info("muted muted " + String.valueOf(muted));
			}
		
			public void mediaSubItemTreeAdded(MediaPlayer mediaPlayer,
					libvlc_media_t item)
			{
				logger.info("mediaSubItemTreeAdded");
			}
		
			public void mediaSubItemAdded(MediaPlayer mediaPlayer,
					libvlc_media_t subItem)
			{
				logger.info("mediaSubItemAdded");
			}
		
			public void mediaStateChanged(MediaPlayer mediaPlayer, int newState)
			{
				logger.info("mediaStateChanged newState " + String.valueOf(newState));
			}
		
			public void mediaParsedChanged(MediaPlayer mediaPlayer, int newStatus)
			{
				logger.info("mediaParsedChanged newStatus " + String.valueOf(newStatus));
			}
		
			public void mediaMetaChanged(MediaPlayer mediaPlayer, int metaType)
			{
				logger.info("mediaMetaChanged metaType " + String.valueOf(metaType));
			}
		
			public void mediaFreed(MediaPlayer mediaPlayer)
			{
				logger.info("mediaFreed");
			}
		
			public void mediaDurationChanged(MediaPlayer mediaPlayer, long newDuration)
			{
				logger.info("mediaDurationChanged newDuration " + String.valueOf(newDuration));
			}
		
			public void mediaChanged(MediaPlayer mediaPlayer, libvlc_media_t media,
					String mrl)
			{
				logger.info("mediaChanged mrl " + String.valueOf(mrl));
			}
		
			public void lengthChanged(MediaPlayer mediaPlayer, long newLength)
			{
				logger.info("lengthChanged newLength " + String.valueOf(newLength));
			}
		
			public void forward(MediaPlayer mediaPlayer)
			{
				logger.info("forward");
			}
		
			public void finished(MediaPlayer mediaPlayer)
			{
				logger.info("finished");
			}
		
			public void error(MediaPlayer mediaPlayer)
			{
				logger.info("error");
			}
		
			public void endOfSubItems(MediaPlayer mediaPlayer)
			{
				logger.info("endOfSubItems");
			}
		
			public void elementaryStreamSelected(MediaPlayer mediaPlayer, int type,
					int id)
			{
				logger.info("elementaryStreamSelected type " + String.valueOf(type) + " id " + String.valueOf(id));
			}
		
			public void elementaryStreamDeleted(MediaPlayer mediaPlayer, int type,
					int id)
			{
				logger.info("elementaryStreamDeleted type " + String.valueOf(type) + " id " + String.valueOf(id));
			}
		
			public void elementaryStreamAdded(MediaPlayer mediaPlayer, int type, int id)
			{
				logger.info("elementaryStreamAdded type " + String.valueOf(type) + " id " + String.valueOf(id));
			}
		
			public void corked(MediaPlayer mediaPlayer, boolean corked)
			{
				logger.info("corked corked " + String.valueOf(corked));
			}
		
			public void chapterChanged(MediaPlayer mediaPlayer, int newChapter)
			{
				logger.info("chapterChanged newChapter " + String.valueOf(newChapter));
			}
		
			public void buffering(MediaPlayer mediaPlayer, float newCache)
			{
				logger.info("buffering newCache " + String.valueOf(newCache));
			}
		
			public void backward(MediaPlayer mediaPlayer)
			{
				logger.info("backward");
			}
		
			public void audioDeviceChanged(MediaPlayer mediaPlayer, String audioDevice)
			{
				logger.info("audioDeviceChanged audioDevice " + String.valueOf(audioDevice));
			}
		});
		String[] options = {};
		mediaPlayer.playMedia("udp://@224.10.0.3:5001", options);
	}
	
	public void run()
	{
		while (!shell.isDisposed ()) 
		{
			if (!display.readAndDispatch ()) 
				display.sleep ();
		}
		
		display.dispose ();	
		
		mediaPlayer.release();
		mediaPlayerFactory.release();
	}

	//
	// Getters / Setters
	//
}

**Comment by caprica** [comment]
If you're going to post a code sample, please make sure a) it is formatted correctly; and b) you remove all the irrelevant stuff like your empty listener methods.

In any case, I do not know the details of what is required to make a hardware accelerated video output available in Java. In Java, you use an AWT Canvas, and that is a native control that has a unique window identifier. That window identifier is what is passed to LibVLC. And that's all you get.

So... can you create an AWT Canvas that knows how to render hardware accelerated video... ?

**Comment by ozster123** [comment]
When you get down to it the LinuxVideoSurfaceAdapter uses the VLC call libvlc.libvlc_media_player_set_xwindow to pass the window id.
The real question is how does VLC use this window. I don't know if VLC only uses this window for position information and creates its own video overlay or it renders video directly into the window.
Perhaps this is more of a question for a VLC forum.

**Comment by caprica** [comment]
VLC renders its video natively and directly into that window.
