### ISSUE TITLE
Setting --vout with Raspberry PI 3

### ISSUE THREAD

**Issue by weshinsley** [caprica/vlcj#518]
Appreciating this is relevant to closed cases #456 and #458, but I wondered if there's anything simple I'm missing in using VLCJ on a new RPI3 with the default Raspbian Jessie (23rd Sept, apt-updated). I've compiled VLC 2.2.4 using these instructions:

https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=59814

and it works really nicely. In VLC's GUI prefs, I've got audio out set to ALSA, and video out to OpenMax IL, and it's smooth and fine. I then wondered if it would be ok from VLCJ (3.10.1). My code is very similar to one of  the early tutorials - except I've tried to add the --aout and --vout options -  --aout was successful, but --vout (with omxil or omxil_vout) wasn't. 

My code: TestVLC.java

```
import uk.co.caprica.vlcj.discovery.NativeDiscovery;
import uk.co.caprica.vlcj.component.EmbeddedMediaPlayerComponent;
import javax.swing.SwingUtilities;
import javax.swing.JFrame;
import uk.co.caprica.vlcj.binding.LibVlc;

public class TestVLC {

  private final JFrame frame;
  private final EmbeddedMediaPlayerComponent mediaPlayerComponent;

  public static void main(String[] args) {
    new NativeDiscovery().discover();
    System.out.println(LibVlc.INSTANCE.libvlc_get_version());
    SwingUtilities.invokeLater(new Runnable() {
      @Override
      public void run() {
        new TestVLC();
      }
    });
  }

  public TestVLC() {
    frame = new JFrame("Media Player");
    frame.setBounds(100,100,600,400);
    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    mediaPlayerComponent = new EmbeddedMediaPlayerComponent() {
      protected String[] onGetMediaPlayerFactoryArgs() {
        return new String[] {"--vout=omxil_vout","--aout=alsa"};
      }
    };
    frame.setContentPane(mediaPlayerComponent);
    frame.setVisible(true);
    mediaPlayerComponent.getMediaPlayer().playMedia("LightStreaksDeepBlueHD.mp4");

  }
}
```

I compile with
javac -classpath .:jna-4.1.0.jar:slf4j-api-1.7.10.jar:vlcj-3.10.1.jar TestVLC.java
run with
java -classpath .:jna-4.1.0.jar:slf4j-api-1.7.10.jar:vlcj-3.10.1.jar TestVLC

Output: I get a window with only the first frame of the movie displayed, and:

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2.2.4 Weatherwax
Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory
[641766d0] xcb_xv vout display error: no available XVideo adaptor

Sending the "--aout=alsa" makes a difference and the warning in #456 about PulseAudio server goes away. But I'm stuck on --vout. You mentioned back in Jan (#456) {"--vout","omxil"} didn't work - I suspect from vlc --list that omxil_vout is the right thing to send? Or does that VDPAU error stop it processing the --vout - (I obviously don't have an nvidia card in the Pi, but I don't know how to stop it trying to use that .so file)

Any thoughts greatly appreciated,
Thanks,
Wes

**Comment by weshinsley** [comment]
Sorry about the code format - can't seem to make the insert code button work right...

**Comment by caprica** [comment]
On the "error" messages that you posted...

The SLF4J stuff is irrelevant to your problem and only affects logging.

The libvdpau message happens because your platform doesn't support VDPAU, which is not uncommon. It's a harmless part of VLC's plugin/module initialisation. So this I think is also irrelevant to your problem.

As far as I can remember, when using LibVLC it ignores however you've configured VLC. You need to know exactly how VLC is working, which specific video output it's using and all other options and then we talk about how to replicate that in vlcj.

**Comment by weshinsley** [comment]
Thanks - I knew about SLF4J, but good to remove the VDPAU red herring. So, I believe all my vlc settings are all in ~/.config/vlc/vlcrc. Ignoring comment lines and empty sections, I end up with:

[x264] # H.264/MPEG-4 Part 10/AVC encoder (x264)
sout-x264-preset=ultrafast
sout-x264-tune=film

[alsa] # ALSA audio output
alsa-audio-device=sysdefault:CARD=ALSA

[qt4] # Qt interface
qt-privacy-ask=0

[core] # core program
aout=alsa
vout=omxil_vout
metadata-network-access=1

And that's it. I've naively added those to my list of arguments for onGetMediaPlayerFactoryArgs() - but maybe not that surprisingly, no difference yet. Anywhere else I should be looking for how vlc is configured?

Thanks,
Wes

**Comment by caprica** [comment]
When your media is playing, check the VLC log and/or the UI and look for what it's using.

**Comment by weshinsley** [comment]
[log.txt](https://github.com/caprica/vlcj/files/524131/log.txt)

Attached hopefully is a log from playing the movie - sorry it's a bit of a sprawling mess - I'm not quite sure what I'm looking for...

**Comment by weshinsley** [comment]
I'll download a better SLF JARI and see if I can get any more debug from the VLCJ attempt to play the movie as well.

**Comment by weshinsley** [comment]
And here's a log of what VLC does when called from VLCJ, (by passing -vvv, --file-logging and --logfile=log2.txt in the options. What's critically different....?
[log2.txt](https://github.com/caprica/vlcj/files/524232/log2.txt)

**Comment by weshinsley** [comment]
In log.txt (running vlc directly):-
core debug: Opening vout display wrapper
core debug: looking for vout display module matching "omxil_vout": 15 candidates....
core debug: using vout display module "omxil_vout"

In log2.txt (running from vlcj)
core debug: Opening vout display wrapper
core debug: looking for vout display module matching "xid": 15 candidates...
core debug: looking for vout window xid module matching "embed-xid-any": 4 candidates
core debug: using vout window xid module "xcb_window"
core debug: using vout display module "xcb_glx"

Anything useful? I'm guessing my --vout=omxil_vout is not to be used by vlc?
Attempt to confirm: if I manually call "vlc --vout=xid LightThing.mp4" , then I get similar behaviour to what I'm currently getting via VLCJ - single frame of the movie, and the "no available XVideo adapter" message.

**Comment by weshinsley** [comment]
Possibly related to the first part of this thread: https://groups.google.com/forum/#!topic/vlcj-users/Jhqfism1Nb8

**Comment by weshinsley** [comment]
Right, this code works - using an EmbeddedMediaPlayer, instead of an EmbeddedMediaPlayerComponent.

```
import uk.co.caprica.vlcj.discovery.NativeDiscovery;
import uk.co.caprica.vlcj.player.MediaPlayerFactory;
import javax.swing.SwingUtilities;
import uk.co.caprica.vlcj.binding.LibVlc;
import uk.co.caprica.vlcj.player.embedded.EmbeddedMediaPlayer;

public class TestVLC {

  public static void main(String[] args) {
    new NativeDiscovery().discover();
    System.out.println(LibVlc.INSTANCE.libvlc_get_version());
    SwingUtilities.invokeLater(new Runnable() {
      @Override
      public void run() {
        new TestVLC();
      }
    });
  }

  public TestVLC() {
    String[] libvlcArgs = new String[] {"--vout=omxil_vout","--aout=alsa"};
    MediaPlayerFactory mpf = new MediaPlayerFactory(libvlcArgs);
    EmbeddedMediaPlayer mp = mpf.newEmbeddedMediaPlayer();
    mp.playMedia("vid.mp4");
  }
}
```
But that's full screen only. (And nice speed too.)

If I try and put it in a canvas, then...

```
import uk.co.caprica.vlcj.discovery.NativeDiscovery;
import uk.co.caprica.vlcj.player.MediaPlayerFactory;
import javax.swing.SwingUtilities;
import uk.co.caprica.vlcj.binding.LibVlc;
import uk.co.caprica.vlcj.player.embedded.EmbeddedMediaPlayer;
import uk.co.caprica.vlcj.player.embedded.videosurface.CanvasVideoSurface;

import javax.swing.JFrame;
import java.awt.Canvas;

public class TestVLC {

  final JFrame frame;

  public static void main(String[] args) {
    new NativeDiscovery().discover();
    System.out.println(LibVlc.INSTANCE.libvlc_get_version());
    SwingUtilities.invokeLater(new Runnable() {
      @Override
      public void run() {
        new TestVLC();
      }
    });
  }
  public TestVLC() {
    frame = new JFrame("Media Player");
    frame.setBounds(100,100,600,400);
    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    String[] libvlcArgs = new String[] {"--vout=omxil_vout","--aout=alsa"};
    MediaPlayerFactory mpf = new MediaPlayerFactory(libvlcArgs);
    Canvas canvas = new Canvas();
    CanvasVideoSurface videoSurface = mpf.newVideoSurface(canvas);
    EmbeddedMediaPlayer mp = mpf.newEmbeddedMediaPlayer();
    mp.setVideoSurface(videoSurface);
    frame.add(canvas);
    frame.setVisible(true);
    mp.playMedia("vid.mp4");
  }
}
```

This one doesn't work - I get the "no available XVideo adapter", and a single frame again.

**Comment by weshinsley** [comment]
Sorry for the rambling commentary, but one more interesting thing: setting vout to xcb_x11 seems to work ok too, and in the first example in my previous mail, it's in a window rather than the full screen I always seem to get with omxil_vout. Quite a lot I don't understand about how this all works...!

**Comment by caprica** [comment]
In your code that you say works, you are using a media player without an
associated video surface. So VLC opens up a native video surface and
renders to that. So your video is not actually embedded in your Java
application.

**Comment by caprica** [comment]
Look also at your code here:
```
public TestVLC() {
    String[] libvlcArgs = new String[] {"--vout=omxil_vout","--aout=alsa"};
    MediaPlayerFactory mpf = new MediaPlayerFactory(libvlcArgs);
    Canvas canvas = new Canvas();
    CanvasVideoSurface videoSurface = mpf.newVideoSurface(canvas);
    EmbeddedMediaPlayer mp = mpf.newEmbeddedMediaPlayer();
    mp.setVideoSurface(videoSurface);
    mp.playMedia("vid.mp4");
}
```
This is a classic mistake when using vlcj.

Look at your `mpf` and `mp` variable references.

At the end of your constructor those "automatic" or heap variable references go out of scope and so instantly become eligible for garbage collection. If this works at all, it's a fluke and will likely fail some time soon.

You need to keep a hard reference to those objects.

**Comment by weshinsley** [comment]
And... that's the bug! |I've been messing around with this all day and lost the plot. So declaring mpf and mp as private finals at the top, and then adding a while (true){} loop to stop it terminating prematurely, and the last example works fine. Thanks for spotting that!

So is there a different way that --vout is treated depending on whether you use EmbeddedMediaPlayerComponent overiding onGetMediaPlayerFactoryArgs(), compared to setting up the MPfactory with the args and using it to create an EmbeddedMediaPlayer on a canvas? (I don't quite see the pros/cons of the two different methods yet). My very first bit of code didn't have the garbage collection bug, but had problems getting the --vout message across.

**Comment by caprica** [comment]
This is a really terrible idea:
>adding a while (true){} loop to stop it terminating prematurely

At least use something like Thread.join() instead.

More properly, move them to be class member variables or something.

**Comment by weshinsley** [comment]
I know, I know! I'm just doing really quick dirty debugging tests on the PI to see if it's viable to do this at all.
