### ISSUE TITLE
Overlay: text not drawing

### ISSUE THREAD

**Issue by 0xDubas** [caprica/vlcj#519]
Hi! 
I have some code that draw overlay text and objects. But this code executed differently on multiple computers.
On one computer text drawn, but on the other computer not drawn.

I run vlcj/OverlayTest.java. All objects drawn, but not text! 
https://s9.postimg.org/azoif6vgf/2016_10_15_11_12_31.png

What's wrong?

**Comment by 0xDubas** [comment]
Text on the button also not view.

**Comment by caprica** [comment]
Work out what's different between your two environments. Maybe it's a font issue or something.

Anyway, it's clearly not a vlcj issue.

**Comment by 0xDubas** [comment]
I tried change fonts, but it didn't work!  

Earlier this worked on my home PC. But i reinstall system and now it not work too. Maybe need intall some package? I have installed libvlccore-dev, libvlc-dev, browser-plugin-vlc, libvdpau-va-gl1 and them dependences.
What kind the dependences need vlcj?

**Comment by caprica** [comment]
vlcj has no such dependencies.

Your problem is more fundamental than vlcj. All that overlay test is doing is using Java2D to render text. If you removed vlcj most likely you would still have the same problem.

I can't see any way in which this a vlcj problem.

**Comment by 0xDubas** [comment]
I thought so too. But i write test application that drawing on form. And it works!
The same code with vlcj don't worked.

Can you take me bit sourcecode of  setOverlay method. Maybe i can understand what influence on my problem.

**Comment by caprica** [comment]
>The same code with vlcj don't worked.
It did work, before you reinstalled your system. You said so yourself. So how can it be a vlcj issue?

**Comment by 0xDubas** [comment]
Becouse somthing in system influence on lib work. But i don't kwow what.

**Comment by 0xDubas** [comment]
I want know what need vlcj in system.

**Comment by caprica** [comment]
vlcj does not need anything like that.

**Comment by Remonell** [comment]
@0xDubas Did you figure this out?
