### ISSUE TITLE
how to add "EmbeddedMediaPlayerComponent" object  to JPanal

### ISSUE THREAD

**Issue by akash19ku** [caprica/vlcj#520]
i am creating a javafx project in which i want to l do live streaming of IPCamera through  Rtsp protocol. using vlcj.
when i am using normal java project with jframe its working fine
when i am trying javafx project its note working so i am using swingnode component to integrate jcomponent inside my fxml project

but how to attach EmbeddedMediaPlayerComponent with JPanal .
 
Here is my code- 

package javafxapplication3;

import javafx.application.Application;
import javafx.embed.swing.SwingNode;
import javafx.scene.Scene;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import uk.co.caprica.vlcj.component.EmbeddedMediaPlayerComponent;
import uk.co.caprica.vlcj.discovery.NativeDiscovery;
import uk.co.caprica.vlcj.mrl.RtspMrl;

 public class SwingFx extends Application {

         @Override
         public void start(Stage stage) {
             final SwingNode swingNode = new SwingNode();
             createAndSetSwingContent(swingNode);

             StackPane pane = new StackPane();
             pane.getChildren().add(swingNode);

             stage.setScene(new Scene(pane, 100, 50));
             stage.show();
         }

         private void createAndSetSwingContent(final SwingNode swingNode) {
             SwingUtilities.invokeLater(new Runnable() {
                 @Override
                 public void run() {
                     
                     
                     
        
       EmbeddedMediaPlayerComponent mediaPlayerComponent = new EmbeddedMediaPlayerComponent();
    //    frame.setContentPane(mediaPlayerComponent);
    //    frame.setVisible(true); String address;
       JPanel p = new JPanel();
       p.add(mediaPlayerComponent);
        String address = new RtspMrl().host("@192.162.27.223").value();
        System.out.println(address);
        mediaPlayerComponent.getMediaPlayer().playMedia(address);
                     
                     
                     swingNode.setContent(p);
                 }
             });
         }
 
         public static void main(String[] args) {
             new NativeDiscovery().discover();
             launch(args);
         }
     }

[SwingFx.txt](https://github.com/caprica/vlcj/files/587671/SwingFx.txt)

**Comment by caprica** [comment]
http://stackoverflow.com/questions/40507922/add-a-vlcj-media-player-to-a-canvas-in-javafx
