### ISSUE TITLE
how execute StreamHttp.java?

### ISSUE THREAD

**Issue by Dizzman** [caprica/vlcj#533]
## I what to redirect TV stream to http://localhost:8081/TNT.mp3

> # errors

000000000025ae70] core stream output error: stream chain failed for `transcode{vcodec=none,acodec=mp3,ab=128,channels=2,samplerate=44100}:http{dst=127.0.0.1:8081/TNT.mp3} :sout-keep'
[000000001a31e1d0] core input error: cannot start stream output instance, aborting

> **CODE**

`
 public static void main(String[] args) throws Exception {
        boolean found = new NativeDiscovery().discover();
        System.out.println(found);
        System.out.println(args[0]);
        String media=args[0];
        String options "";
        MediaPlayerFactory mediaPlayerFactory = new MediaPlayerFactory(args);
        HeadlessMediaPlayer mediaPlayer = mediaPlayerFactory.newHeadlessMediaPlayer();
        mediaPlayer.playMedia(media,options);
        Thread.currentThread().join();
    }
    private static String formatHttpStream(String serverAddress, int serverPort) {
        StringBuilder sb = new StringBuilder(60);        sb.append(":sout=#transcode{vcodec=none,acodec=mp3,ab=128,channels=2,samplerate=44100}:http{dst=127.0.0.1:8081/TNT.mp3} :sout-keep");
        return sb.toString();
    }`

> **Output**

0 [main] INFO uk.co.caprica.vlcj.Info  - vlcj: 3.10.1
2 [main] INFO uk.co.caprica.vlcj.Info  - java: 1.8.0_111 Oracle Corporation
2 [main] INFO uk.co.caprica.vlcj.Info  - java home: C:\Program Files\Java\jdk1.8.0_111\jre
2 [main] INFO uk.co.caprica.vlcj.Info  - os: Windows 7 6.1 amd64
4 [main] DEBUG uk.co.caprica.vlcj.discovery.NativeDiscovery  - discover()
4 [main] DEBUG uk.co.caprica.vlcj.discovery.NativeDiscovery  - jnaLibraryPath=null
4 [main] DEBUG uk.co.caprica.vlcj.discovery.NativeDiscovery  - discoveryStrategy=uk.co.caprica.vlcj.discovery.linux.DefaultLinuxNativeDiscoveryStrategy@2b05039f
4 [main] DEBUG uk.co.caprica.vlcj.discovery.NativeDiscovery  - supported=false
4 [main] DEBUG uk.co.caprica.vlcj.discovery.NativeDiscovery  - discoveryStrategy=uk.co.caprica.vlcj.discovery.windows.DefaultWindowsNativeDiscoveryStrategy@61e717c2
4 [main] DEBUG uk.co.caprica.vlcj.discovery.NativeDiscovery  - supported=true
4 [main] DEBUG uk.co.caprica.vlcj.discovery.AbstractNativeDiscoveryStrategy  - discover()
5 [main] DEBUG uk.co.caprica.vlcj.runtime.windows.WindowsRuntimeUtil  - getVlcInstallDir()
62 [main] DEBUG uk.co.caprica.vlcj.discovery.AbstractNativeDiscoveryStrategy  - directoryNames=[d:\Program Files\VideoLAN\VLC, D:\#PRJ2\streamer_1, C:\ProgramData\Oracle\Java\javapath, D:\Program Files (x86)\Embarcadero\Studio\17.0\bin, C:\Users\Public\Documents\Embarcadero\Studio\17.0\Bpl, C:\Program Files (x86)\Embarcadero\Studio\16.0\bin, C:\Users\Public\Documents\Embarcadero\Studio\16.0\Bpl, C:\Program Files (x86)\Intel\Compiler\11.1\054\tbb\intel64\vc9\bin, C:\Program Files (x86)\Intel\Compiler\11.1\054\ipp\em64t\bin, C:\Program Files (x86)\Intel\Compiler\11.1\054\lib\Intel64, C:\Program Files (x86)\Intel\Compiler\11.1\054\lib\ia32, C:\Program Files (x86)\Intel\Compiler\11.1\054\mkl\em64t\bin, C:\Windows\system32, C:\Windows, C:\Windows\System32\Wbem, C:\Windows\System32\WindowsPowerShell\v1.0\, C:\Program Files (x86)\Microsoft SQL Server\90\Tools\binn\, C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common, C:\Program Files\TortoiseSVN\bin, C:\Program Files\TortoiseGit\bin, C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\, C:\Program Files\Microsoft SQL Server\130\Tools\Binn\, C:\Program Files\Git\cmd, C:\Program Files (x86)\Skype\Phone\, d:\Program Files\MATLAB\R2016b\runtime\win64, d:\Program Files\MATLAB\R2016b\bin, d:\Program Files\MATLAB\R2016b\polyspace\bin, D:\Users\SCHWARZ\AppData\Local\Programs\Python\Python35-32\Scripts\, D:\Users\SCHWARZ\AppData\Local\Programs\Python\Python35-32\, C:\Program Files\Java\jdk1.8.0_111\bin\]
62 [main] DEBUG uk.co.caprica.vlcj.discovery.AbstractNativeDiscoveryStrategy  - directoryName=d:\Program Files\VideoLAN\VLC
62 [main] DEBUG uk.co.caprica.vlcj.discovery.AbstractNativeDiscoveryStrategy  - Matched 'libvlc.dll' in 'd:\Program Files\VideoLAN\VLC'
62 [main] DEBUG uk.co.caprica.vlcj.discovery.AbstractNativeDiscoveryStrategy  - Matched 'libvlccore.dll' in 'd:\Program Files\VideoLAN\VLC'
63 [main] DEBUG uk.co.caprica.vlcj.discovery.AbstractNativeDiscoveryStrategy  - Matched all required files
63 [main] DEBUG uk.co.caprica.vlcj.discovery.AbstractNativeDiscoveryStrategy  - result=d:\Program Files\VideoLAN\VLC
63 [main] DEBUG uk.co.caprica.vlcj.discovery.NativeDiscovery  - path=d:\Program Files\VideoLAN\VLC
63 [main] INFO uk.co.caprica.vlcj.discovery.NativeDiscovery  - Discovery found libvlc at 'd:\Program Files\VideoLAN\VLC'
true
http://178.162.218.85:8081/liveg/tnt.stream/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9Mi8xMC8yMDE3IDM6MDg6MTIgUE0maGFzaF92YWx1ZT1rcnFtNWtiNE81RTNlNEMvU3loR1h3PT0mdmFsaWRtaW51dGVzPTIwMA==
135 [main] DEBUG uk.co.caprica.vlcj.player.MediaPlayerFactory  - initX=null
136 [main] INFO uk.co.caprica.vlcj.binding.LibVlcFactory  - vlc: 2.2.4 Weatherwax, changeset 2.2.4-0-g888b7e89
136 [main] INFO uk.co.caprica.vlcj.binding.LibVlcFactory  - libvlc: d:\Program Files\VideoLAN\VLC\libvlc.dll
136 [main] DEBUG uk.co.caprica.vlcj.player.MediaPlayerFactory  - MediaPlayerFactory(libvlc=Proxy interface to Native Library <d:\Program Files\VideoLAN\VLC\libvlc.dll@1890779136>,libvlcArgs=[http://178.162.218.85:8081/liveg/tnt.stream/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9Mi8xMC8yMDE3IDM6MDg6MTIgUE0maGFzaF92YWx1ZT1rcnFtNWtiNE81RTNlNEMvU3loR1h3PT0mdmFsaWRtaW51dGVzPTIwMA==])
136 [main] DEBUG uk.co.caprica.vlcj.player.MediaPlayerFactory  - jna.library.path=null
136 [main] DEBUG uk.co.caprica.vlcj.player.MediaPlayerFactory  - VLC_PLUGIN_PATH=null
425 [main] DEBUG uk.co.caprica.vlcj.player.MediaPlayerFactory  - instance=native@0x5ac350 (uk.co.caprica.vlcj.binding.internal.libvlc_instance_t@5ac350)
425 [main] DEBUG uk.co.caprica.vlcj.player.MediaPlayerFactory  - equalizerAvailable=true
425 [main] DEBUG uk.co.caprica.vlcj.player.MediaPlayerFactory  - createEqualizerBandFrequencies()
425 [main] DEBUG uk.co.caprica.vlcj.player.MediaPlayerFactory  - numBands=10
426 [main] DEBUG uk.co.caprica.vlcj.player.MediaPlayerFactory  - result=[31.25, 62.5, 125.0, 250.0, 500.0, 1000.0, 2000.0, 4000.0, 8000.0, 16000.0]
426 [main] DEBUG uk.co.caprica.vlcj.player.MediaPlayerFactory  - createEqualizerPresetNames()
426 [main] DEBUG uk.co.caprica.vlcj.player.MediaPlayerFactory  - numPresets=18
427 [main] DEBUG uk.co.caprica.vlcj.player.MediaPlayerFactory  - result=[Flat, Classical, Club, Dance, Full bass, Full bass and treble, Full treble, Headphones, Large Hall, Live, Party, Pop, Reggae, Rock, Ska, Soft, Soft rock, Techno]
427 [main] DEBUG uk.co.caprica.vlcj.player.MediaPlayerFactory  - newHeadlessMediaPlayer()
438 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - DefaultMediaPlayer(libvlc=Proxy interface to Native Library <d:\Program Files\VideoLAN\VLC\libvlc.dll@1890779136>, instance=native@0x5ac350 (uk.co.caprica.vlcj.binding.internal.libvlc_instance_t@5ac350))
438 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - createInstance()
439 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - mediaPlayerInstance=native@0x1a349690 (uk.co.caprica.vlcj.binding.internal.libvlc_media_player_t@1a349690)
439 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - mediaPlayerEventManager=native@0x1a36dbb0 (uk.co.caprica.vlcj.binding.internal.libvlc_event_manager_t@1a36dbb0)
439 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - registerEventListener()
441 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerMediaChanged
467 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
467 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerNothingSpecial
467 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
467 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerOpening
467 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
467 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerBuffering
467 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
467 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerPlaying
467 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
467 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerPaused
467 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
467 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerStopped
468 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
468 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerForward
468 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
468 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerBackward
468 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
468 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerEndReached
468 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
468 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerEncounteredError
468 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
468 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerTimeChanged
468 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
468 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerPositionChanged
468 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
468 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerSeekableChanged
468 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
468 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerPausableChanged
468 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
468 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerTitleChanged
469 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
469 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerSnapshotTaken
469 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
469 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerLengthChanged
469 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
469 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerVout
469 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
469 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerScrambledChanged
469 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
471 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - playMedia(mrl=http://178.162.218.85:8081/liveg/tnt.stream/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9Mi8xMC8yMDE3IDM6MDg6MTIgUE0maGFzaF92YWx1ZT1rcnFtNWtiNE81RTNlNEMvU3loR1h3PT0mdmFsaWRtaW51dGVzPTIwMA==,mediaOptions=[:sout=#transcode{vcodec=none,acodec=mp3,ab=128,channels=2,samplerate=44100}:http{dst=127.0.0.1:8081/TNT.mp3} :sout-keep])
472 [main] DEBUG uk.co.caprica.vlcj.player.MediaResourceLocator  - encodeMrl(mrl=http://178.162.218.85:8081/liveg/tnt.stream/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9Mi8xMC8yMDE3IDM6MDg6MTIgUE0maGFzaF92YWx1ZT1rcnFtNWtiNE81RTNlNEMvU3loR1h3PT0mdmFsaWRtaW51dGVzPTIwMA==)
472 [main] DEBUG uk.co.caprica.vlcj.player.MediaResourceLocator  - MRL does not contain any Unicode characters
472 [main] DEBUG uk.co.caprica.vlcj.player.MediaResourceLocator  - result=http://178.162.218.85:8081/liveg/tnt.stream/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9Mi8xMC8yMDE3IDM6MDg6MTIgUE0maGFzaF92YWx1ZT1rcnFtNWtiNE81RTNlNEMvU3loR1h3PT0mdmFsaWRtaW51dGVzPTIwMA==
472 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - playMedia(media=SimpleMedia[mrl=http://178.162.218.85:8081/liveg/tnt.stream/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9Mi8xMC8yMDE3IDM6MDg6MTIgUE0maGFzaF92YWx1ZT1rcnFtNWtiNE81RTNlNEMvU3loR1h3PT0mdmFsaWRtaW51dGVzPTIwMA==,mediaOptions=[Ljava.lang.String;@39ba5a14])
472 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - prepareMedia(media=SimpleMedia[mrl=http://178.162.218.85:8081/liveg/tnt.stream/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9Mi8xMC8yMDE3IDM6MDg6MTIgUE0maGFzaF92YWx1ZT1rcnFtNWtiNE81RTNlNEMvU3loR1h3PT0mdmFsaWRtaW51dGVzPTIwMA==,mediaOptions=[Ljava.lang.String;@39ba5a14])
472 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - setMedia(media=SimpleMedia[mrl=http://178.162.218.85:8081/liveg/tnt.stream/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9Mi8xMC8yMDE3IDM6MDg6MTIgUE0maGFzaF92YWx1ZT1rcnFtNWtiNE81RTNlNEMvU3loR1h3PT0mdmFsaWRtaW51dGVzPTIwMA==,mediaOptions=[Ljava.lang.String;@39ba5a14])
472 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - createMediaInstance(media=SimpleMedia[mrl=http://178.162.218.85:8081/liveg/tnt.stream/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9Mi8xMC8yMDE3IDM6MDg6MTIgUE0maGFzaF92YWx1ZT1rcnFtNWtiNE81RTNlNEMvU3loR1h3PT0mdmFsaWRtaW51dGVzPTIwMA==,mediaOptions=[Ljava.lang.String;@39ba5a14])
472 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - Treating mrl as a location
473 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - mediaInstance=native@0x1a36dcd0 (uk.co.caprica.vlcj.binding.internal.libvlc_media_t@1a36dcd0)
473 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - mediaOption=:sout=#transcode{vcodec=none,acodec=mp3,ab=128,channels=2,samplerate=44100}:http{dst=127.0.0.1:8081/TNT.mp3} :sout-keep
473 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - registerMediaEventListener()
473 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaMetaChanged
473 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
473 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaSubItemAdded
473 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
473 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaDurationChanged
473 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
473 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaParsedChanged
473 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
473 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaFreed
473 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
474 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaStateChanged
474 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
474 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaSubItemTreeAdded
474 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
480 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - mrl(mediaInstance=native@0x1a36dcd0 (uk.co.caprica.vlcj.binding.internal.libvlc_media_t@1a36dcd0))
482 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=true
482 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - play()
494 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - after play
494 [pool-1-thread-1] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - mediaChanged(mediaPlayer=uk.co.caprica.vlcj.player.headless.DefaultHeadlessMediaPlayer@1e4f99df,media=native@0x1a36dcd0 (uk.co.caprica.vlcj.binding.internal.libvlc_media_t@1a36dcd0),mrl=http://178.162.218.85:8081/liveg/tnt.stream/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9Mi8xMC8yMDE3IDM6MDg6MTIgUE0maGFzaF92YWx1ZT1rcnFtNWtiNE81RTNlNEMvU3loR1h3PT0mdmFsaWRtaW51dGVzPTIwMA==)
494 [pool-1-thread-1] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - Raising event for new media
[000000000025ae70] core stream output error: stream chain failed for `transcode{vcodec=none,acodec=mp3,ab=128,channels=2,samplerate=44100}:http{dst=127.0.0.1:8081/TNT.mp3} :sout-keep'
[000000001a31e1d0] core input error: cannot start stream output instance, aborting

**Comment by caprica** [comment]
It is not my job to troubleshoot your code. As per your other issue, try your stream in one of the vlcj example projects first.

**Comment by Dizzman** [comment]
Ok. Thank you for answer.
oops... i have just saw it. sorry.

but code was so.... that cleary code from 
[https://github.com/caprica/vlcj/blob/master/src/test/java/uk/co/caprica/vlcj/test/streaming/StreamHttp.java](url)

( only ### sb.append(":sout=#transcode{vcodec=none,acodec=mp3,ab=128,channels=2,samplerate=44100}:http{dst=127.0.0.1:8081/TNT.mp3} :sout-keep");  
)
i changed.



public static void main(String[] args) throws Exception {
 boolean found = new NativeDiscovery().discover(); 
System.out.println(found); 
System.out.println(args[0]); 
String media=args[0]; 
String options ""; 
MediaPlayerFactory mediaPlayerFactory = new MediaPlayerFactory(args); HeadlessMediaPlayer mediaPlayer = mediaPlayerFactory.newHeadlessMediaPlayer(); mediaPlayer.playMedia(media,options); Thread.currentThread().join();
 } 

private static String formatHttpStream(String serverAddress, int serverPort) { StringBuilder sb = new StringBuilder(60); sb.append(":sout=#transcode{vcodec=none,acodec=mp3,ab=128,channels=2,samplerate=44100}:http{dst=127.0.0.1:8081/TNT.mp3} :sout-keep"); 
return sb.toString();
 }

**Comment by caprica** [comment]
Honestly, I don't know. There is probably something wrong with your "sout" string, but that is really outside of the scope of vlcj.

It may be something as simple as not having a space character before " :sout-keep", or it may be a problem because you've removed the mux option, or it may be something else - I really don't know.

These "sout" strings are all internal to VLC, vlcj does not care about them nor does vlcj do anything at all with them other than pass them directly to VLC.

**Comment by Dizzman** [comment]
Thank you, for your explanation.

My task - to get audio mp3 stream from some internet straning TV (.m3u8)
bellow about where i got the string;

![default](https://cloud.githubusercontent.com/assets/25510074/22847975/02963494-f002-11e6-9aad-04599ae95d86.png)


and when i start new VLC Player with url : http://localhost:8081/TNT.mp3 i listen only audio

**Comment by caprica** [comment]
I can only suggest that wherever you see a space character in the sout string, that's actually a separate option, so maybe you need something like this to pass as options to play():

    String[] options = {"your first sout string here", ":sout-keep"};

Failing that, create your MediaPlayerFactory with "-vvv" and have a look at the native logs to see if there's anything that can help you.

This type of thing really is nothing specifically to do with vlcj itself so it's kind of out of my scope to help on this.

**Comment by caprica** [comment]
Also, it's still not clear to me specifically what you're using vlcj for here.

Are you using vlcj to redirect your TV stream to a local http port?

Or are you using vlcj to play your local http stream?

Because those are two separate things.

**Comment by Dizzman** [comment]
I need analyze of audio stream from TV streaming.
task is extraction audio and analyze it in online not from dowloaded audio file.
Not necessarily only from port

![default](https://cloud.githubusercontent.com/assets/25510074/22857791/4eec1168-f0bd-11e6-903d-366a53b17325.png)

**Comment by Dizzman** [comment]
But. if i take StreamHttp.java from src

see below...

`public class StreamHttp extends VlcjTest {

    public static void main(String[] args) throws Exception {
        boolean found = new NativeDiscovery().discover();
        System.out.println(found);
        System.out.println(args[0]);
        String media=args[0];
        //media = "http://178.162.218.85:8081/liveg/tnt.stream/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9Mi8xMC8yMDE3IDM6MDg6MTIgUE0maGFzaF92YWx1ZT1rcnFtNWtiNE81RTNlNEMvU3loR1h3PT0mdmFsaWRtaW51dGVzPTIwMA==";
        media = "http://178.162.218.85:8081/liveg/tnt.stream/chunks.m3u8?nimblesessionid=211102004&wmsAuthSign=c2VydmVyX3RpbWU9Mi8xMS8yMDE3IDEwOjIyOjQ3IFBNJmhhc2hfdmFsdWU9WU1MK2FzQnJSRkdLL29vNzc4cTlIdz09JnZhbGlkbWludXRlcz0yMDA=";
        String options = formatHttpStream("127.0.0.1", 8081);
        MediaPlayerFactory mediaPlayerFactory = new MediaPlayerFactory(args);
        HeadlessMediaPlayer mediaPlayer = mediaPlayerFactory.newHeadlessMediaPlayer();
        mediaPlayer.playMedia(media,options);
        Thread.currentThread().join();
    }

    private static String formatHttpStream(String serverAddress, int serverPort) {
        StringBuilder sb = new StringBuilder(60);
        sb.append(":sout=#duplicate{dst=std{access=http,mux=ts,");
        sb.append("dst=");
        sb.append(serverAddress);
        sb.append(':');
        sb.append(serverPort);
        sb.append("}}");
        return sb.toString();
    }`

and when I start VLC Player with url http://127.0.0.1:8081 I see video stream. That is working
with some errors in output 
**### [000000002018fb00] ts demux: MPEG-4 descriptor not found for pid 0x101 type 0xf
[00000000200f2ec0] packetizer_mpeg4audio decoder: AAC channels: 2 samplerate: 48000
[000000002018fb00] ts demux error: libdvbpsi error (PSI decoder): TS duplicate (received 0, expected 1) for PID 0
[000000002018fb00] ts demux error: libdvbpsi error (PSI decoder): TS duplicate (received 0, expected 1) for PID 4095**

but  I need audio streaming!

**Comment by caprica** [comment]
I can't help much with problems like this, they're not vlcj problems. vlcj simply passes your URL/MRL to VLC and asks VLC to play it.

**Comment by caprica** [comment]
If you want to analyse the audio stream, consider looking at the `DirectAudioPlayer`, it will give you direct access to the native audio samples.

**Comment by Dizzman** [comment]
I need just extract audio stream from TV stream

**Comment by Dizzman** [comment]
and aftre  that   analyze audio

**Comment by caprica** [comment]
I'm sorry, it's just not clear precisely what the real issue is here.

What are you trying to do by consuming the remote stream and sending it to a *local* http service?

If you want access to the audio stream as it is playing, use a `DirectAudioPlayer` to play the remote stream - no local http involved.

If you want to access the audio stream off-line, use a regular vlcj media player to play and capture the remote stream to disk so you can process it later.

**Comment by Dizzman** [comment]
Thank you for anser. 
I try finding way -  how get audio online stream from online TV stream. Not for save to file. I need get audio stream and read it online. Like a radio. I found that (http VLC player   can do TV stream->local http mp3 stream). And i try do  the same thing with captica API.

I dont need play  audio from TV online streaming....it i did for check

I need getting audio online stream from online TV streaming for  online reading and analyze it.

Why  do i send to local http service?
because i found that VLC player can to extract audio and build localhost:port/audiofilename.mp3 and after this i can read this stream and analyze it.
it's not necessary....it only one way what i found....(TV streaming to local mp3 streaming) using by VLC player.... now i trying do it in caprica API

May be  you know how i can extract online  audio from online TV stream without building streaming mp3 to localhost  stream?

**Comment by caprica** [comment]
I already suggested this: 

>If you want access to the audio stream as it is playing, use a DirectAudioPlayer to play the remote stream - no local http involved.

**Comment by Dizzman** [comment]
Can DircetAudioPlayer  plays   m3u8 link?

**Comment by Dizzman** [comment]
Thank you for anwer.  But it not easier....
How to get audio from TV streaming by DirectAudioPlayer?

1 - Where notes that it can to get video  stream?
http://caprica.github.io/vlcj/javadoc/3.10.1/index.html

from DirectAudioPlayerTest.java 
Where i can find some example? in caprica ..//test/... i see only audio 
test converts an mp3 to a "raw" PCM file.
.....
audioPlayer = factory.newDirectAudioPlayer("S16N", 44100, 2, new TestAudioCallbackAdapter(new File("test.raw")));???
.....


from 
MediaPlayerFactory.java 

    /**
     * Create a new direct audio media player.
     *
     * @param format decoded audio format
     * @param rate decoded audio sample rate
     * @param channels decoded audio channels
     * @param audioCallback callback
     * @return media player instance
     */
    public DirectAudioPlayer newDirectAudioPlayer(String format, int rate, int channels, AudioCallback audioCallback) {
        logger.debug("newDirectAudioPlayer(format={},rate={},channels={},audioCallback={}", format, rate, channels, audioCallback);
        return new DefaultDirectAudioPlayer(libvlc, instance, format, rate, channels, audioCallback);
    }

Where i can read about format....and somthing about how i can do it?

Thank a lot! I hope that i will find it!

**Comment by caprica** [comment]
I don't think I can help you any further. You are not being clear and you are changing your requirements. You said you were only interested in getting the audio stream so you could process it, and now your latest comment is asking about video too.

**Comment by Dizzman** [comment]
I need get video TV stream and extract audio.
not change my  requirements!!!!
always talking about get video TV stream and extract audio!
I got VLC player for readig m3u8 Video TV and use options for extract audio.

**Comment by Dizzman** [comment]
Mark. 
I never tolking that i need video. Where you read it? 
all I can say about I need audio stream from video TV stream.
And DirectAudioPlayer i see can't get audio from vidoe.

**Comment by caprica** [comment]
Arguing the point is worthless, but I was referring to a comment like this:

>I try finding way - how get audio online stream from online TV stream. Not for save to file. I need get audio stream and read it online.

Anyway, the level of help you need unfortunately is way outside of the scope of the help that this project can provide, sorry.

**Comment by Dizzman** [comment]
Ok, I found how get it by VLCPlayer. I showed it you. And I trying do it by vlcj. it may not be possible. But i see only errors.
Or can can you show what is my worng, or show anyway how it can make by vlcj.

**Comment by Dizzman** [comment]
Ok. 
But. I used VLC Player for extraction audio from video online TV. And redirect it to local http audio stream. 
I found olny this way for extract audio. And all working how i need. I have only audio stream.

Now i'm here for make it by vlcj. That all what i need.

**Comment by Dizzman** [comment]
![02963494-f002-11e6-9aad-04599ae95d86](https://cloud.githubusercontent.com/assets/25510074/22903561/16661c74-f24a-11e6-9dff-395dab658ebd.png)

**Comment by Dizzman** [comment]
I have done it!  mediaPlayer.playMedia(media,":sout=#transcode{vcodec=none,acodec=mp3,ab=128,channels=2,samplerate=44100}:http{dst=:172.0.0.1:8081/stream.mp3}");

**Comment by tehseenvirk** [comment]
14 [main] DEBUG uk.co.caprica.vlcj.discovery.NativeDiscovery  - discover()
14 [main] DEBUG uk.co.caprica.vlcj.discovery.NativeDiscovery  - jnaLibraryPath=null
14 [main] DEBUG uk.co.caprica.vlcj.discovery.NativeDiscovery  - discoveryStrategy=uk.co.caprica.vlcj.discovery.linux.DefaultLinuxNativeDiscoveryStrategy@181eb93
16 [main] DEBUG uk.co.caprica.vlcj.discovery.NativeDiscovery  - supported=false

How i set JNA path ? i set it into enviromental varibal but its not working.

**Comment by tehseenvirk** [comment]
How Run a video Using Vlcj source code ? In Which java  class we pass Video path to play that video?
