### ISSUE TITLE
How i can check status of connection with http stream?

### ISSUE THREAD

**Issue by Dizzman** [caprica/vlcj#534]
Do you have any interface for this?
for exanple interception of http access error: cannot connect vlc.
Thank you.

**Comment by caprica** [comment]
The only thing you can do is listen for events provided by the `MediaPlayerEventListener`. LibVLC generally does *not* provide the type of errors you are asking about.

It is theoretically possible to use the `NativeLog` and search for error messages, but this is clearly sub-optimal.

**Comment by Dizzman** [comment]
Thank you!
