### ISSUE TITLE
Access to RTP packet NTP time stamp in RTSP client

### ISSUE THREAD

**Issue by ryantheseer** [caprica/vlcj#536]
I am building an RTSP client in Java. I need to be able to synchronize the video stream from a server with another set of data being streamed from the same remote computer on another stream. I need access to the NTP time stamp that is packaged with each RTP video packet (in my case, expected fragmented H264 units) so that I can find the actual time the packet was created. Is there a way to modify the VLCJ source to give access to this time stamp through the API?

I have found this question posted in 2014 on the LibVLC forum: https://forum.videolan.org/viewtopic.php?f=32&t=123056&p=413729&hilit=rtp+time+stamp#p413729

**Comment by caprica** [comment]
LibVLC simply does not expose that data.

So there's no way to modify vlcj source to get access to data that can't be provided by LibVLC.

Maybe you can find a way to modify VLC source first :-/

**Comment by ryantheseer** [comment]
In that case, yes, I will have to modify the libVLC code first. I found in their code, the modules/access/rtp/session.c contains a method (rtp_decode) that calculates the PTS and DTS time of the packet and adds them to a "block_t" type of object. If I were to modify this type (include/vlc_block.h) and possibly the modules/access/rtp/rtp.h file where the block is passed into for decoding, how could I access this block object through both APIs? Any ideas?

**Comment by caprica** [comment]
You would have to find a way to expose it via LibVLC. I'm afraid what you're asking about is way beyond the scope of what I can help with or advise on.

I usually add any official LibVLC API to vlcj quite quickly. But if I'm brutally honest with you, you're in for a tough ride if you want to try and such a thing to the official VLC source.

**Comment by ryantheseer** [comment]
Thanks anyway! :)
