### ISSUE TITLE
Win 64-bit LibVLC attempts to open RTSP MRL using libdvdnav plugin

### ISSUE THREAD

**Issue by ryantheseer** [caprica/vlcj#538]
I have installed the 64-bit Windows VLC on my PC (from http://download.cnet.com/VLC-Media-Player-64-bit/3000-13632_4-75761094.html), and am using a 64-bit JDK in my Eclipse Java project. I am trying to create an RTSP streaming client, but when I run the program I get the following error output (below) relating to libdvdnav plugin (instead of the librtp plugin I believe it should be using).
When I set up the project to run with the 32-bit Windows install of VLC (same version number) and 32-bit JDK, it works fine, but I want to be using 64-bit version of the binaries for other reasons. Could this be related to differences in the 64-bit libvlc API, or another JNI problem?

<pre>
VLCJ is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

VLCJ is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with VLCJ.  If not, see <http://www.gnu.org/licenses/>.

Copyright 2009, 2010, 2011, 2012 Caprica Software Limited.

vlcj: (Info.java:103)                                | INFO  | vlcj: 2.1.0
vlcj: (Info.java:104)                                | INFO  | java: 1.8.0_74 Oracle Corporation
vlcj: (Info.java:105)                                | INFO  | java home: C:\home\dev\code\tools\jdk\windows\jre
vlcj: (Info.java:106)                                | INFO  | os: Windows 7 6.1 amd64
vlcj: (LibVlcFactory.java:164)                       | INFO  | vlc: 2.2.4 Weatherwax, changeset 2.2.4-0-g888b7e89
vlcj: (LibVlcFactory.java:165)                       | INFO  | libvlc: C:\home\dev\code\install\jrelibs\extras\windows\bin\libvlc.dll
libdvdnav: Using dvdnav version 5.0.3
libdvdread: Could not open C:\home\dev\code\apps\VideoAlignment\rtsp:\\192.168.1.10:554\video with libdvdcss.
libdvdread: Can't open C:\home\dev\code\apps\VideoAlignment\rtsp:\\192.168.1.10:554\video for reading
libdvdnav: vm: failed to open/read the DVD
</pre>

The approximate Java code I'm using:
<pre>
static final int RTSP_VIDEO_PORT = 554;
EmbeddedMediaPlayerComponent mediaPlayerComponent;
String[] _mediaOptions = new String[]{ "network-caching=1000" };
String _videoFile = new RtspMrl().host(hostName)
					.port(RTSP_VIDEO_PORT)
					.path("/video")
					.value();
mediaPlayerComponent = new EmbeddedMediaPlayerComponent();
VideoPanel.this.add(mediaPlayerComponent, BorderLayout.CENTER);
mediaPlayerComponent.getMediaPlayer().setStandardMediaOptions(_mediaOptions);
mediaPlayerComponent.getMediaPlayer().playMedia(_videoFile);
</pre>

**Comment by caprica** [comment]
There is no difference between LibVLC whether it's 32bit or 64bit. There's no JNI difference either, nor vlcj for that matter.

What version of VLC are you using for 32bit and 64bit, are they actually the same?

If you print out the "_videoFile" (btw why do you prefix with underscore, that's kinda odd) value what is it?

Something changed with VLC with regards to URL vs local path handling (I don't recall exactly which version it changed) but maybe this is what you are encountering. vlcj, at least current versions, accommodate this change by checking if the MRL you are playing "looks like" a URL or a local file and picks the appropriate native LibVLC API function to use accordingly.

It looks to me from your log that it thinks an MRL is actually a local path.

Also, look how old your vlcj version is!

**Comment by ryantheseer** [comment]
64-bit VLC version: 2.2.4 Weatherwax
32-bit VLC version: 2.2.4 Weatherwax
VLCJ jar version: 3.10.1
64-bit Java version: 1.8.0_111
32-bit Java version: 1.8.0_111
_videoFile is rtsp://192.168.1.10:554/video when passed to the playMedia() method.
(the prepended underscore is because in our code it's actually declared as a private global member variable, and we tend to prepend those with underscores)

**Comment by ryantheseer** [comment]
The full debug code:
<pre>
vlcj: (Info.java:103)                                | INFO  | vlcj: 2.1.0
vlcj: (Info.java:104)                                | INFO  | java: 1.8.0_74 Oracle Corporation
vlcj: (Info.java:105)                                | INFO  | java home: C:\home\dev\code\tools\jdk\windows\jre
vlcj: (Info.java:106)                                | INFO  | os: Windows 7 6.1 amd64
vlcj: (LibVlcFactory.java:164)                       | INFO  | vlc: 2.2.4 Weatherwax, changeset 2.2.4-0-g888b7e89
vlcj: (LibVlcFactory.java:165)                       | INFO  | libvlc: C:\home\dev\code\install\jrelibs\extras\windows\bin\libvlc.dll
vlcj: (MediaPlayerFactory.java:189)                  | DEBUG | MediaPlayerFactory(libvlc=Proxy interface to Native Library <C:\home\dev\code\install\jrelibs\extras\windows\bin\libvlc.dll@1772748800>,libvlcArgs=[--no-plugins-cache, --no-video-title-show, --no-snapshot-preview, --quiet, --quiet-synchro, --intf, dummy])
vlcj: (MediaPlayerFactory.java:191)                  | DEBUG | jna.library.path=C:\home\dev\code\install\jrelibs\extras\windows\bin
vlcj: (MediaPlayerFactory.java:214)                  | DEBUG | instance=native@0x3dc9e0
vlcj: (MediaPlayerFactory.java:413)                  | DEBUG | newEmbeddedMediaPlayer(fullScreenStrategy=null)
vlcj: (DefaultMediaPlayer.java:167)                  | DEBUG | DefaultMediaPlayer(libvlc=Proxy interface to Native Library <C:\home\dev\code\install\jrelibs\extras\windows\bin\libvlc.dll@1772748800>, instance=native@0x3dc9e0)
vlcj: (DefaultMediaPlayer.java:1500)                 | DEBUG | createInstance()
vlcj: (DefaultMediaPlayer.java:1503)                 | DEBUG | mediaPlayerInstance=native@0x422f80
vlcj: (DefaultMediaPlayer.java:1506)                 | DEBUG | mediaPlayerEventManager=native@0x24a3c920
vlcj: (DefaultMediaPlayer.java:1553)                 | DEBUG | registerEventListener()
vlcj: (DefaultMediaPlayer.java:1557)                 | DEBUG | event=libvlc_MediaPlayerMediaChanged
vlcj: (DefaultMediaPlayer.java:1559)                 | DEBUG | result=0
vlcj: (DefaultMediaPlayer.java:1557)                 | DEBUG | event=libvlc_MediaPlayerNothingSpecial
vlcj: (DefaultMediaPlayer.java:1559)                 | DEBUG | result=0
vlcj: (DefaultMediaPlayer.java:1557)                 | DEBUG | event=libvlc_MediaPlayerOpening
vlcj: (DefaultMediaPlayer.java:1559)                 | DEBUG | result=0
vlcj: (DefaultMediaPlayer.java:1557)                 | DEBUG | event=libvlc_MediaPlayerBuffering
vlcj: (DefaultMediaPlayer.java:1559)                 | DEBUG | result=0
vlcj: (DefaultMediaPlayer.java:1557)                 | DEBUG | event=libvlc_MediaPlayerPlaying
vlcj: (DefaultMediaPlayer.java:1559)                 | DEBUG | result=0
vlcj: (DefaultMediaPlayer.java:1557)                 | DEBUG | event=libvlc_MediaPlayerPaused
vlcj: (DefaultMediaPlayer.java:1559)                 | DEBUG | result=0
vlcj: (DefaultMediaPlayer.java:1557)                 | DEBUG | event=libvlc_MediaPlayerStopped
vlcj: (DefaultMediaPlayer.java:1559)                 | DEBUG | result=0
vlcj: (DefaultMediaPlayer.java:1557)                 | DEBUG | event=libvlc_MediaPlayerForward
vlcj: (DefaultMediaPlayer.java:1559)                 | DEBUG | result=0
vlcj: (DefaultMediaPlayer.java:1557)                 | DEBUG | event=libvlc_MediaPlayerBackward
vlcj: (DefaultMediaPlayer.java:1559)                 | DEBUG | result=0
vlcj: (DefaultMediaPlayer.java:1557)                 | DEBUG | event=libvlc_MediaPlayerEndReached
vlcj: (DefaultMediaPlayer.java:1559)                 | DEBUG | result=0
vlcj: (DefaultMediaPlayer.java:1557)                 | DEBUG | event=libvlc_MediaPlayerEncounteredError
vlcj: (DefaultMediaPlayer.java:1559)                 | DEBUG | result=0
vlcj: (DefaultMediaPlayer.java:1557)                 | DEBUG | event=libvlc_MediaPlayerTimeChanged
vlcj: (DefaultMediaPlayer.java:1559)                 | DEBUG | result=0
vlcj: (DefaultMediaPlayer.java:1557)                 | DEBUG | event=libvlc_MediaPlayerPositionChanged
vlcj: (DefaultMediaPlayer.java:1559)                 | DEBUG | result=0
vlcj: (DefaultMediaPlayer.java:1557)                 | DEBUG | event=libvlc_MediaPlayerSeekableChanged
vlcj: (DefaultMediaPlayer.java:1559)                 | DEBUG | result=0
vlcj: (DefaultMediaPlayer.java:1557)                 | DEBUG | event=libvlc_MediaPlayerPausableChanged
vlcj: (DefaultMediaPlayer.java:1559)                 | DEBUG | result=0
vlcj: (DefaultMediaPlayer.java:1557)                 | DEBUG | event=libvlc_MediaPlayerTitleChanged
vlcj: (DefaultMediaPlayer.java:1559)                 | DEBUG | result=0
vlcj: (DefaultMediaPlayer.java:1557)                 | DEBUG | event=libvlc_MediaPlayerSnapshotTaken
vlcj: (DefaultMediaPlayer.java:1559)                 | DEBUG | result=0
vlcj: (DefaultMediaPlayer.java:1557)                 | DEBUG | event=libvlc_MediaPlayerLengthChanged
vlcj: (DefaultMediaPlayer.java:1559)                 | DEBUG | result=0
vlcj: (DefaultMediaPlayer.java:1557)                 | DEBUG | event=libvlc_MediaPlayerVout
vlcj: (DefaultMediaPlayer.java:1559)                 | DEBUG | result=0
vlcj: (MediaPlayerFactory.java:482)                  | DEBUG | newVideoSurface(canvas=java.awt.Canvas[canvas0,0,0,0x0,invalid])
vlcj: (MediaPlayerFactory.java:497)                  | DEBUG | videoSurface=uk.co.caprica.vlcj.player.embedded.videosurface.CanvasVideoSurface@68c93cc3
vlcj: (DefaultEmbeddedMediaPlayer.java:142)          | DEBUG | setVideoSurface(videoSurface=uk.co.caprica.vlcj.player.embedded.videosurface.CanvasVideoSurface@68c93cc3)
vlcj: (DefaultMediaPlayer.java:173)                  | DEBUG | addMediaPlayerEventListener(listener=uk.co.caprica.vlcj.component.EmbeddedMediaPlayerComponent[panel0,0,0,0x0,invalid,layout=java.awt.BorderLayout])
vlcj: (DefaultEmbeddedMediaPlayer.java:222)          | DEBUG | setOverlay(overlay=null)
vlcj: (DefaultEmbeddedMediaPlayer.java:238)          | DEBUG | enableOverlay(enable=false)
vlcj: (DefaultEmbeddedMediaPlayer.java:304)          | DEBUG | removeOverlay()
vlcj: (DefaultEmbeddedMediaPlayer.java:284)          | DEBUG | addOverlay(overlay=null)
vlcj: (DefaultMediaPlayer.java:193)                  | DEBUG | setStandardMediaOptions(options=[network-caching=1000])
vlcj: (DefaultMediaPlayer.java:199)                  | DEBUG | playMedia(mrl=rtsp://192.168.1.10:554/video,mediaOptions=[])
vlcj: (DefaultMediaPlayer.java:213)                  | DEBUG | prepareMedia(mrl=rtsp://192.168.1.10:554/video,mediaOptions=[])
vlcj: (DefaultMediaPlayer.java:1638)                 | DEBUG | setMedia(media=rtsp://192.168.1.10:554/video,mediaOptions=[])
vlcj: (DefaultMediaPlayer.java:1651)                 | DEBUG | mediaInstance=native@0x24a3ca40
vlcj: (DefaultMediaPlayer.java:1656)                 | DEBUG | standardMediaOption=network-caching=1000
vlcj: (DefaultMediaPlayer.java:1584)                 | DEBUG | registerMediaEventListener()
vlcj: (DefaultMediaPlayer.java:1590)                 | DEBUG | event=libvlc_MediaMetaChanged
vlcj: (DefaultMediaPlayer.java:1592)                 | DEBUG | result=0
vlcj: (DefaultMediaPlayer.java:1590)                 | DEBUG | event=libvlc_MediaSubItemAdded
vlcj: (DefaultMediaPlayer.java:1592)                 | DEBUG | result=0
vlcj: (DefaultMediaPlayer.java:1590)                 | DEBUG | event=libvlc_MediaDurationChanged
vlcj: (DefaultMediaPlayer.java:1592)                 | DEBUG | result=0
vlcj: (DefaultMediaPlayer.java:1590)                 | DEBUG | event=libvlc_MediaParsedChanged
vlcj: (DefaultMediaPlayer.java:1592)                 | DEBUG | result=0
vlcj: (DefaultMediaPlayer.java:1590)                 | DEBUG | event=libvlc_MediaFreed
vlcj: (DefaultMediaPlayer.java:1592)                 | DEBUG | result=0
vlcj: (DefaultMediaPlayer.java:1590)                 | DEBUG | event=libvlc_MediaStateChanged
vlcj: (DefaultMediaPlayer.java:1592)                 | DEBUG | result=0
vlcj: (DefaultMediaPlayer.java:1452)                 | DEBUG | mrl(mediaInstance=native@0x24a3ca40)
vlcj: (DefaultMediaPlayer.java:1796)                 | DEBUG | mediaChanged(mediaPlayer=uk.co.caprica.vlcj.player.embedded.DefaultEmbeddedMediaPlayer@38f2b81e,media=native@0x24a3ca40,mrl=file:///C:/home/dev/code/apps/VideoAlignment/rtsp%3A%2F%2F192.168.1.10%3A554%2Fvideo)
vlcj: (DefaultMediaPlayer.java:1800)                 | DEBUG | Raising event for new media
vlcj: (DefaultMediaPlayer.java:664)                  | DEBUG | play()
vlcj: (DefaultEmbeddedMediaPlayer.java:314)          | DEBUG | onBeforePlay()
vlcj: (DefaultEmbeddedMediaPlayer.java:151)          | DEBUG | attachVideoSurface()
vlcj: (CanvasVideoSurface.java:67)                   | DEBUG | attach()
vlcj: (WindowsVideoSurfaceAdapter.java:41)           | DEBUG | attach(componentId=10225058)
</pre>

**Comment by caprica** [comment]
You're using vlcj 2.1.0, not vlcj 3.10.1 like you say.

**Comment by caprica** [comment]
I suspect you are using an incompatible vlcj + VLC combination for the reasons I mentioned above (i.e. MRL vs local file).

**Comment by caprica** [comment]
See https://github.com/caprica/vlcj/commit/f6a7313aae48cff1f5aa7a64c39c4e6c691e687c
and https://github.com/caprica/vlcj/commit/1fb3caa810c1cc15cbaa6fcbae400d2f8d8b920f

Those commits became part of vlcj 2.2.0 release, which is after your release used according to your posted log.

Prior to that 2.2.0 release, libvlc_media_new_path was used whether it was a local file or URL. For the version of VLC that was contemporary at the time, this actually worked correctly. This commit calls either libvlc_media_new_path or libvlc_media_new_location as appropriate.

**Comment by caprica** [comment]
Solution: use current version of vlcj and latest official release version of VLC.

**Comment by ryantheseer** [comment]
Thanks, I found out that I had the 2.1.0 version available on the classpath, so it didn't load the 3.10.1 jar that I had just built from source. I had to use the JVM command -verbose:class to find that out.
Good spot of the version number mismatch!

**Comment by caprica** [comment]
Yep, it's the first line of your log! :-D
