### ISSUE TITLE
Stream Volume

### ISSUE THREAD

**Issue by xtechgamer735** [caprica/vlcj#539]
Hello!

Is is possible to detect the current volume of the stream that is playing? I want to detect whether the stream is silent you see.

Many thanks

**Comment by caprica** [comment]
Short answer: no.

Longer answer:, you would have to process the audio samples in some way to detect silence, so you could use a DirectAudioPlayer (it gives you direct access to the audio samples) and implement your silence algorithm.

**Comment by xtechgamer735** [comment]
Thanks! I will give this a go.
