### ISSUE TITLE
DefaultDirectMediaPlayer DisplayCallback pointers always null

### ISSUE THREAD

**Issue by ryantheseer** [caprica/vlcj#541]
I'm using an extension of the player.direct.DefaultDirectMediaPlayer to play a video stream (branching from tag "vlcj-3.10.1"). But every time I  get the DisplayCallback, the Pointer opaque and the Pointer picture are both "null". I want to get the picture's details - such as its time stamp - but the pointer is always null. What might be going wrong?
Using Windows 64-bit, custom VLC cross-compiled from a branch from VLC git tag "2.2.4".

**Comment by caprica** [comment]
This is somewhat explained in the LibVLC native header file, but it's not abundantly clear I suppose.

The "opaque" 'pointer' is some private LibVLC application-specific value (it could be an integer, or a 'pointer' to some "user data"). The idea is you can use it to associate your own data with a particular media player callback so you can differentiate them if you have multiple ones. 

In vlcj's direct media player implementation the "opaque" value is not used and so will always be null.

The "picture" pointer is also a private pointer "used to identify the picture buffers". It is a value returned by the native callback.

Again, vlcj does not need that picture pointer.

The raw picture data is accessible in the Java callback via the "nativeBuffers" reference.

Why do you think there are "details" there, like a timestamp?

**Comment by ryantheseer** [comment]
If there is no information in either of these pointers, and only pixel data in the nativeBuffers, I will need to modify the LibVLC API (and VLCJ accordingly) to get the time stamp. Is it in the LockCallback where the nativeBuffers are populated from the planes PointerByReference? So if I modified the Lock callback in VLC and VLCJ, I could add a NativeLongByReference (for example) argument that could pass the time stamp?

**Comment by ryantheseer** [comment]
The way I understand it now: the Lock callback allows VLCJ to tell VLC where to write the new frame of data, and the Display callback tells VLCJ that the data has been written. Is this correct?

**Comment by caprica** [comment]
You're first question is some that that is outside the scope of what I can help you with, sorry.

I suspect the type of change you're proposing will not make it into any official LibVLC API either if I'm honest.

Is displaying the timecode enough for you? Maybe look at https://github.com/caprica/vlcj/blob/a3637da2bf3d552f71a9f3cce9942da03c8aef34/src/test/java/uk/co/caprica/vlcj/test/timecode/TimecodeTest.java

**Comment by caprica** [comment]
To answer your second question...

The native callbacks go lock -> display -> unlock and the meaning is pretty apparent I think.

lock means VLC has a frame of data in the native buffer ready for display.
display means render it
unlock means my application has finished rendering the frame so VLC can prepare the next one

**Comment by ryantheseer** [comment]
The Timecode Track won't work for my purposes, since I want to have access to the time when the frame was captured (or encoded into RTP in my case), not the elapsed time since the beginning of the video playing. I think I will have to continue looking for ways to pass the time stamp through callbacks from VLC - probably through the Lock or Display native callbacks.
