### ISSUE TITLE
logo problem

### ISSUE THREAD

**Issue by xiaolong3000** [caprica/vlcj#544]
why my logo isn't show?just follow the teach of home page,I can play media.

**Comment by caprica** [comment]
What code are you using to show the logo?

Did you look at the vlcj examples in the test sources, and also the vlcj-player project, because a working logo is demonstrated there.

**Comment by xiaolong3000** [comment]
File f=new File("vlcj-logo.png")
mediaPlayerComponent.getMediaPlayer().setLogoFile(f);
mediaPlayerComponent.getMediaPlayer().setLogoPosition(libvlc_logo_position_e.top_left);
mediaPlayerComponent.getMediaPlayer().setLogoOpacity(0.3f);
mediaPlayerComponent.getMediaPlayer().enableLogo(true);


I use myeclipse to build it,when i print the logo.getX,the result is null.And can't find logo.But the file is exist.

**Comment by caprica** [comment]
Have a look at the TestPlayer class in the vlcj test sources. It uses a logo. I just tested it. It works.

Compare that code with your own code and work out what's different.

Since you are using a relative path for your logo File object, are you sure that your "vlcj-logo.png" is actually in the "current directory" when you run you Java application?

**Comment by xiaolong3000** [comment]
I'm sorry,I do that follow you,But I can't find logo.Then I use web url for file,It also can't show.The whole code is here.
`package vlc;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

import uk.co.caprica.vlcj.component.EmbeddedMediaPlayerComponent;
import uk.co.caprica.vlcj.discovery.NativeDiscovery;
import uk.co.caprica.vlcj.player.Logo;

public class testvlc {
	private final EmbeddedMediaPlayerComponent media;
	private final JButton pauseButton;
	private final JButton rewindButton;
	private final JButton skipButton;
	
	/**
	 * @param args
	 */
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		//NativeLibrary.addSearchPath(RuntimeUtil.getLibVlcLibraryName(), "E:\\Program Files\\VideoLAN\\VLC\\");
		//Native.loadLibrary(RuntimeUtil.getLibVlcLibraryName(),LibVlc.class);
		new NativeDiscovery().discover();
		//System.out.println(LibVlc.INSTANCE.libvlc_get_version());
		
            SwingUtilities.invokeLater(new Runnable() {
			
				@Override
				public void run() {
					// TODO Auto-generated method stub
					
					new testvlc();
				}
			});
             
	}
	private testvlc(){
		JFrame frame=new JFrame("123");
		media=new EmbeddedMediaPlayerComponent();
		
		JPanel contentPane=new JPanel();
		contentPane.setLayout(new BorderLayout());
		
		//frame.setLocation(100,100);
		frame.setSize(800,600);
		frame.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
		frame.addWindowListener(new WindowAdapter() {
			@Override
			public void windowClosing(WindowEvent arg0) {
				// TODO Auto-generated method stub
				media.release(true);
			    System.exit(0);
			}
			
		});
//		ImageIcon ii=new  ImageIcon("images/logo.png");
//		JLabel logolabel=new JLabel("imageicon",ii,SwingConstants.LEFT);
//	
//		
//		contentPane.add(logolabel,BorderLayout.NORTH);
	
	        
		
		contentPane.add(media,BorderLayout.CENTER);
	
		JPanel controlsPane=new JPanel();
		pauseButton=new JButton("Pause");
		controlsPane.add(pauseButton);
	
		rewindButton=new JButton("rewind");
	    controlsPane.add(rewindButton);
	    
	    skipButton=new JButton("skip");
	    controlsPane.add(skipButton);
	    
	    contentPane.add(controlsPane,BorderLayout.SOUTH);
	 //   contentPane.add(new ImagePane(ImagePane.Mode.CENTER,getClass().getResource("images/logo.png"),0.3f));
	    
	    pauseButton.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent arg0) {
				// TODO Auto-generated method stub
				media.getMediaPlayer().pause();
			}
		});
	    
	    rewindButton.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent arg0) {
				// TODO Auto-generated method stub
				media.getMediaPlayer().skip(-10000);
			}
		});
		
	    skipButton.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent arg0) {
				// TODO Auto-generated method stub
			        media.getMediaPlayer().skip(10000);	
			}
		});
	    
	    
		
		
		
		frame.setContentPane(contentPane);
		frame.setVisible(true);
     
		Logo logo=Logo.logo()
			     .file("http://10.103.18.28/Article/zxzxx/zhongxin.jpg")
			     .location(10,10)
				//.position(libvlc_logo_position_e.centre)
				.opacity(0.3f)
				.enable(true);
		
		
		
		//logo.apply(media.getMediaPlayer());
		media.getMediaPlayer().playMedia("C:\\1.3gp");//http://10.103.18.194/tlj_cms/PushServer/upload/265914785236938/VID_20170309_225209.3gp
	//
		media.getMediaPlayer().setLogo(logo);
	
	                  
	}

}
`

**Comment by caprica** [comment]
Does that posted code look properly formatted to you? If you want someone to help you, you should make it easier for them not harder to read your code.

Anyway, you can NOT specify a URL for the logo file - it expects a local file.

So this (in your code) will never work:

    Logo logo=Logo.logo()
		     .file("http://10.103.18.28/Article/zxzxx/zhongxin.jpg")

In the code that you first posted you had this:

    File f=new File("vlcj-logo.png");

This has a relative path and will resolve the file to your application's "current" directory, so you need to make sure that file is available in whatever that "current" directory is.

The simplest test here is:

    System.out.println(f.getAbsolutePath());

Also:

    System.out.println(f.exists());

If that prints false, then your logo file can't be found, so at least try that.

I know for sure that the logo in vlcj works, so your problem is in your own code or your own environment.

**Comment by xiaolong3000** [comment]
`     File f=new File("C:\\1.jpg");
     System.out.println(f.getAbsolutePath());
     System.out.println(f.exists());
		Logo logo=Logo.logo()
			     .file(f)
			     .location(10,10)
				//.position(libvlc_logo_position_e.centre)
				.opacity(0.3f)
				.enable(true);
		
		
		
		
		media.getMediaPlayer().playMedia("C:\\1.3gp");

		media.getMediaPlayer().setLogo(logo);

`

The Console is :+1: 

`

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
C:\1.jpg
true
[0366fd0c] core vout display error: Failed to set on top

`

**Comment by xiaolong3000** [comment]
File f=new File("C:\\1.jpg");
 System.out.println(f.getAbsolutePath());
 System.out.println(f.exists());
Logo logo=Logo.logo()
.file(f)
.location(10,10)
.opacity(0.3f)
.enable(true);
media.getMediaPlayer().playMedia("C:\\1.3gp");
media.getMediaPlayer().setLogo(logo);

the console is

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
C:\1.jpg
true
[0366fd0c] core vout display error: Failed to set on top


Then always can't find logo.

**Comment by caprica** [comment]
Well, the vlcj example code that I already told you about works. You will need to compare the differences between your own code.

Here's a screenshot of the vlcj "TestPlayer" class:

![vlcj-logo-screenshot](https://cloud.githubusercontent.com/assets/1385879/24093619/a6369640-0d4c-11e7-9310-e3479c04febf.png)

**Comment by xiaolong3000** [comment]
Well,I know how to show it.
In my opinton,I will show logo by initing the media,But it may couldn't work.
Then I try buttonActionListener  for it,In that method  using `media.getMediaPlayer.setLogo(logo)` can work!

Thank you~

**Comment by caprica** [comment]
Ah, yes, I should have spotted that. The logo can only be set after the video is playing and a video output has been created.

The vlcj `TestPlayer` I referred to sets the logo in a listener, so something like:

    mediaPlayer.addMediaPlayerEventListener(new MediaPlayerEventAdapter() {

        @Override
        public void videoOutput(MediaPlayer mediaPlayer, int newCount) {
            if (newCount == 0) {
                return;
            }

            File logoFile = new File("./etc/vlcj-logo.png");
            if (logoFile.exists()) {
                mediaPlayer.setLogoFile(logoFile.getAbsolutePath());
                mediaPlayer.setLogoOpacity(0.5f);
                mediaPlayer.setLogoLocation(10, 10);
                mediaPlayer.enableLogo(true);
            }
        }

    });

**Comment by adamish** [comment]
We're using a really old version of VLCJ on a legacy project before videoOutput() was added to MediaPlayerEventListener. Is there an equivalent of the videoOutput() callback provided elsewhere?
