### ISSUE TITLE
Logo Implementation & MediaPlayerEventAdapter goals

### ISSUE THREAD

**Issue by Iwerzhon** [caprica/vlcj#546]
Hello, I was implementing a logo over my video and faced some problem with the documentation I felt unclear : 

To sum up the situation, there is 3 ways explained in the doc [here](http://caprica.github.io/vlcj/javadoc/3.0.0/uk/co/caprica/vlcj/player/MediaPlayer.html) to show a logo over the `MediaPlayer`.

```java
// 1
String[] standardMediaOptions = {"video-filter=logo", "logo-file=vlcj-logo.png", "logo-opacity=25"}; 
mediaPlayer.setStandardMediaOptions(standardMediaOptions);

// 2
String[] mediaOptions = {"video-filter=logo", "logo-file=vlcj-logo.png", "logo-opacity=25"};
mediaPlayer.playMedia(mediaPath, mediaOptions);
 
// 3
mediaPlayer.setLogoFile("vlcj-logo.png");
mediaPlayer.setLogoOpacity(25);
mediaPlayer.setLogoLocation(10, 10);
mediaPlayer.enableLogo(true);
```

I didn't find any documentation implementing the two first methods and I focused on the 3rd one which has one default : 
> it is not possible to enable the logo until after the video has started playing.

I created a `MediaPlayerEventListener` and tried to enable it after the video started, however it seems that none of those listeners work : `newMedia, opening, playing`. I discovered in #544 that `videoOutput` worked well but asked myself why the others (especially `playing`, it's normal for `opening` to be happening before the video actually starts) happened before the true beginning of the video.
I looped the video and typed the different Listeners and it gave me this :

```
[AWT-EventQueue-0] INFO uk.co.caprica.vlcj.binding.LibVlcFactory - libvlc: C:\Program Files\VideoLAN\VLC\libvlc.dll
mediaPlayer.play()
newMedia
opening
TagLib: MP4: No audio tracks
playing
[000000001c405800] core vout display error: Failed to set on top
videoOutput
newMedia
newMedia
opening
TagLib: MP4: No audio tracks
playing
videoOutput
```
The only acceptable comportment with enabling the logo is with `videoOutput` here. I was wondering then : 

 - what is the goal of the other Listeners (we can assume that "playing" is a smart choice to name the Listener of the start of the video) and by extension is the usage `videoOutput` a best practice or a workaround ? 
 - is there any example of an actual implementation of one of the 2 first methods which adds directly the logo on the video ?

[Source](https://wiki.videolan.org/Documentation:Modules/logo/) of the VLC documentation concerning the logo

This message follows the digression made on [stackoverflow](http://stackoverflow.com/questions/42832693/using-mouselistener-with-vlcj) some days ago.

**Comment by caprica** [comment]
So that should probably say "it is not possible to enable the logo until after a video output has been created".

The listeners you question are named *exactly in correspondence with their native event counterparts*. So when a playing event is received in Java, that means LibVLC sent a playing event.

Playing need not necessarily mean a video output has been created, e.g. playing audio media.

The first two options in your original post should ideally NOT be used because they are not using an API, they are relying on video output plugin options which may or may not be supported and/or work in the future. They were offered at the time the documentation was written as a workaround to problems with the logo filter being enabled at the right time.

**Comment by caprica** [comment]
Even if the documentation is a little unclear, or imprecise I suppose, the code examples provided work and should be followed. The ultimate documentation is the working code.

**Comment by Iwerzhon** [comment]
Thanks ! I'll stay with the third implementation then, which works fine. I just wanted to know which way was the best way to do it and you answered my question.
