### ISSUE TITLE
setAudioOutput

### ISSUE THREAD

**Issue by xtechgamer735** [caprica/vlcj#547]
Hello!

I am trying to set the audio output of the MediaPlayer however its not working. I am passing the name and id of it and before and after it returns null when I attempt to output current settings. Do you know why this might be?

Also, is it possible to increase the buffer time at all?

**Comment by caprica** [comment]
Did you try setting the audio output in the vlcj-player reference project?

**Comment by xtechgamer735** [comment]
I seem to be unable to find the example. Here is the code I'm using:

`for (AudioDevice a : primary.getAudioOutputDevices())
        {
            if (a.getLongName().equals(name))
            {
                id = a.getDeviceId();
            }
        }

        System.out.println("OLD: " + primary.getAudioOutputDevice());
        primary.setAudioOutputDevice(name, id);
        statusLabel.setText("RESTART");
        if (primary.isPlaying())
        {
            end();
            start();
        }
        System.out.println("NEW: " + primary.getAudioOutputDevice());`

**Comment by caprica** [comment]
You realise everything is pretty much async, right? That may be a factor.

The vlcj-player example has a menu option that sets the audio output, it should be simple for you to see if that works. Run it, change the audio output. If it works, compare it with your own code.

https://github.com/caprica/vlcj-player

I can't debug a partial code fragment where I can't see all of the code, and I don't generally debug other people's code anyway.
