### ISSUE TITLE
Access extra data in Transport Stream of a video

### ISSUE THREAD

**Issue by ryantheseer** [caprica/vlcj#548]
Is there any way to access extra data in a MPEG-2 .TS video file through the VLC/VLCJ API? When I run the test.info.MediaInfoTest, I don't see a way to access it, even when I add a line to check the "spu count", but using GStreamer, I can pipe the data to a text file.

The code I use to stream with GStreamer:
`C:\gstreamer\1.0\x86_64\bin\gst-launch-1.0 filesrc location=metademo.ts ! tsdemux name=mux mux. ! queue ! meta/x-klv ! filesink sync=true location=metadata.txt async=false mux. ! queue ! h264parse ! avdec_h264 ! autovideosink async=false mux. ! queue ! mpegaudioparse ! avdec_mp3 ! autoaudiosink async=false`

The output of MediaInfoTest.java:
`0 [main] DEBUG uk.co.caprica.vlcj.player.MediaPlayerFactory  - initX=null
6 [main] INFO uk.co.caprica.vlcj.Info  - vlcj: 3.10.1
6 [main] INFO uk.co.caprica.vlcj.Info  - java: 1.8.0_74 Oracle Corporation
6 [main] INFO uk.co.caprica.vlcj.Info  - java home: [Path-to-jre-8]
6 [main] INFO uk.co.caprica.vlcj.Info  - os: Windows 7 6.1 amd64
41 [main] INFO uk.co.caprica.vlcj.binding.LibVlcFactory  - vlc: 2.2.4 Weatherwax, changeset 2.2.4-0-g888b7e89
41 [main] INFO uk.co.caprica.vlcj.binding.LibVlcFactory  - libvlc: C:\Program Files\VideoLAN\VLC\libvlc.dll
41 [main] DEBUG uk.co.caprica.vlcj.player.MediaPlayerFactory  - MediaPlayerFactory(libvlc=Proxy interface to Native Library <C:\Program Files\VideoLAN\VLC\libvlc.dll@1768030208>,libvlcArgs=[])
41 [main] DEBUG uk.co.caprica.vlcj.player.MediaPlayerFactory  - jna.library.path=C:\Program Files\VideoLAN\VLC
41 [main] DEBUG uk.co.caprica.vlcj.player.MediaPlayerFactory  - VLC_PLUGIN_PATH=null
335 [main] DEBUG uk.co.caprica.vlcj.player.MediaPlayerFactory  - instance=native@0x5ec6e0 (uk.co.caprica.vlcj.binding.internal.libvlc_instance_t@5ec6e0)
335 [main] DEBUG uk.co.caprica.vlcj.player.MediaPlayerFactory  - equalizerAvailable=true
335 [main] DEBUG uk.co.caprica.vlcj.player.MediaPlayerFactory  - createEqualizerBandFrequencies()
335 [main] DEBUG uk.co.caprica.vlcj.player.MediaPlayerFactory  - numBands=10
338 [main] DEBUG uk.co.caprica.vlcj.player.MediaPlayerFactory  - result=[31.25, 62.5, 125.0, 250.0, 500.0, 1000.0, 2000.0, 4000.0, 8000.0, 16000.0]
338 [main] DEBUG uk.co.caprica.vlcj.player.MediaPlayerFactory  - createEqualizerPresetNames()
338 [main] DEBUG uk.co.caprica.vlcj.player.MediaPlayerFactory  - numPresets=18
339 [main] DEBUG uk.co.caprica.vlcj.player.MediaPlayerFactory  - result=[Flat, Classical, Club, Dance, Full bass, Full bass and treble, Full treble, Headphones, Large Hall, Live, Party, Pop, Reggae, Rock, Ska, Soft, Soft rock, Techno]
339 [main] DEBUG uk.co.caprica.vlcj.player.MediaPlayerFactory  - newHeadlessMediaPlayer()
347 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - DefaultMediaPlayer(libvlc=Proxy interface to Native Library <C:\Program Files\VideoLAN\VLC\libvlc.dll@1768030208>, instance=native@0x5ec6e0 (uk.co.caprica.vlcj.binding.internal.libvlc_instance_t@5ec6e0))
347 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - createInstance()
353 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - mediaPlayerInstance=native@0x1f35c9d0 (uk.co.caprica.vlcj.binding.internal.libvlc_media_player_t@1f35c9d0)
353 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - mediaPlayerEventManager=native@0x1f3723c0 (uk.co.caprica.vlcj.binding.internal.libvlc_event_manager_t@1f3723c0)
353 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - registerEventListener()
355 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerMediaChanged
374 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
374 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerNothingSpecial
375 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
375 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerOpening
375 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
375 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerBuffering
375 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
375 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerPlaying
375 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
375 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerPaused
375 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
375 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerStopped
375 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
375 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerForward
375 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
375 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerBackward
375 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
375 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerEndReached
375 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
375 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerEncounteredError
375 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
375 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerTimeChanged
375 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
375 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerPositionChanged
375 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
375 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerSeekableChanged
376 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
376 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerPausableChanged
376 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
376 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerTitleChanged
376 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
376 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerSnapshotTaken
376 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
376 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerLengthChanged
376 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
376 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerVout
376 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
376 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerScrambledChanged
376 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
378 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - setStandardMediaOptions(options=[--quiet])
381 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - addMediaPlayerEventListener(listener=uk.co.caprica.vlcj.test.info.MediaInfoTest$1@3712b94)
381 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - prepareMedia(mrl=C:\Users\User1\Downloads\metademo.ts,mediaOptions=[])
382 [main] DEBUG uk.co.caprica.vlcj.player.MediaResourceLocator  - encodeMrl(mrl=C:\Users\User1\Downloads\metademo.ts)
382 [main] DEBUG uk.co.caprica.vlcj.player.MediaResourceLocator  - MRL does not contain any Unicode characters
382 [main] DEBUG uk.co.caprica.vlcj.player.MediaResourceLocator  - result=C:\Users\User1\Downloads\metademo.ts
382 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - prepareMedia(media=SimpleMedia[mrl=C:\Users\User1\Downloads\metademo.ts,mediaOptions=[Ljava.lang.String;@1b68ddbd])
382 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - setMedia(media=SimpleMedia[mrl=C:\Users\User1\Downloads\metademo.ts,mediaOptions=[Ljava.lang.String;@1b68ddbd])
382 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - createMediaInstance(media=SimpleMedia[mrl=C:\Users\User1\Downloads\metademo.ts,mediaOptions=[Ljava.lang.String;@1b68ddbd])
383 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - Treating mrl as a path
383 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - mediaInstance=native@0x1f3724e0 (uk.co.caprica.vlcj.binding.internal.libvlc_media_t@1f3724e0)
383 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - standardMediaOption=--quiet
384 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - registerMediaEventListener()
384 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaMetaChanged
384 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
384 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaSubItemAdded
384 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
384 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaDurationChanged
384 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
384 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaParsedChanged
384 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
384 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaFreed
384 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
384 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaStateChanged
384 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
384 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaSubItemTreeAdded
385 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=0
387 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - mrl(mediaInstance=native@0x1f3724e0 (uk.co.caprica.vlcj.binding.internal.libvlc_media_t@1f3724e0))
389 [pool-1-thread-1] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - mediaChanged(mediaPlayer=uk.co.caprica.vlcj.player.headless.DefaultHeadlessMediaPlayer@4ecc4d6d,media=native@0x1f3724e0 (uk.co.caprica.vlcj.binding.internal.libvlc_media_t@1f3724e0),mrl=file:///C:/Users/User1/Downloads/metademo.ts)
389 [pool-1-thread-1] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - Raising event for new media
389 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - result=true
389 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - parseMedia()
420 [main] DEBUG uk.co.caprica.vlcj.player.MediaPlayerLatch  - play()
421 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - addMediaPlayerEventListener(listener=uk.co.caprica.vlcj.player.MediaPlayerLatch$LatchListener@30a3107a)
421 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - play()
436 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - after play
436 [main] DEBUG uk.co.caprica.vlcj.player.MediaPlayerLatch  - Waiting for media playing or error...
484 [main] DEBUG uk.co.caprica.vlcj.player.MediaPlayerLatch  - Finished waiting.
484 [main] DEBUG uk.co.caprica.vlcj.player.MediaPlayerLatch  - started=true
484 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - removeMediaPlayerEventListener(listener=uk.co.caprica.vlcj.player.MediaPlayerLatch$LatchListener@30a3107a)
531 [pool-1-thread-1] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - getTrackInfo(types=[])
531 [pool-1-thread-1] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - getTrackInfo(media=native@0x1f3724e0 (uk.co.caprica.vlcj.binding.internal.libvlc_media_t@1f3724e0),types=[])
531 [pool-1-thread-1] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - newGetTrackInfo(media=native@0x1f3724e0 (uk.co.caprica.vlcj.binding.internal.libvlc_media_t@1f3724e0),types=null)
532 [pool-1-thread-1] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - numberOfTracks=2
536 [pool-1-thread-1] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - getCodecDescription(type=libvlc_track_video,codec=875967080)
537 [pool-1-thread-1] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - getCodecDescription(type=libvlc_track_audio,codec=1634168941)
     Track Information: [VideoTrackInfo[codec=0x34363268,codecName=h264,originalCodec=0x34363268,originalCodecName=h264,id=0,profile=-1,level=-1,bitRate=0,language=null,description=null,codecDescription=][width=0,height=0,sampleAspectRatio=0,sampleAspectRatioBase=0,frameRate=0,frameRateBase=0], AudioTrackInfo[codec=0x6167706d,codecName=mpga,originalCodec=0x6167706d,originalCodecName=mpga,id=1,profile=-1,level=-1,bitRate=0,language=en,description=null,codecDescription=][channels=0,rate=0]]
537 [pool-1-thread-1] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - getTitleDescriptions()
537 [pool-1-thread-1] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - getTrackDescriptions()
    Title Descriptions: []
537 [pool-1-thread-1] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - getVideoDescriptions()
538 [pool-1-thread-1] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - getTrackDescriptions()
    Video Descriptions: [TrackDescription[id=-1,description=Disable], TrackDescription[id=66,description=Track 1]]
539 [pool-1-thread-1] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - getAudioDescriptions()
539 [pool-1-thread-1] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - getTrackDescriptions()
    Audio Descriptions: [TrackDescription[id=-1,description=Disable], TrackDescription[id=67,description=Track 1 - [English]]]
539 [pool-1-thread-1] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - getSpuCount()
 Sub-pics or Subtitles: 0
539 [pool-1-thread-1] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - getTitleDescriptions()
539 [pool-1-thread-1] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - getTrackDescriptions()
539 [pool-1-thread-1] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - getExtendedTitleDescriptions()
       Extended Titles: []
539 [pool-1-thread-1] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - getExtendedChapterDescriptions()
539 [pool-1-thread-1] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - getTitle()
539 [pool-1-thread-1] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - getExtendedChapterDescriptions(title=0)
     Extended Chapters: []
3484 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - getTrackInfo(types=[])
3484 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - getTrackInfo(media=native@0x1f3724e0 (uk.co.caprica.vlcj.binding.internal.libvlc_media_t@1f3724e0),types=[])
3484 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - newGetTrackInfo(media=native@0x1f3724e0 (uk.co.caprica.vlcj.binding.internal.libvlc_media_t@1f3724e0),types=null)
3484 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - numberOfTracks=2
3484 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - getCodecDescription(type=libvlc_track_video,codec=875967080)
3485 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - getCodecDescription(type=libvlc_track_audio,codec=1634168941)
Track Information before end: [VideoTrackInfo[codec=0x34363268,codecName=h264,originalCodec=0x34363268,originalCodecName=h264,id=0,profile=0,level=0,bitRate=0,language=null,description=null,codecDescription=][width=1024,height=768,sampleAspectRatio=1,sampleAspectRatioBase=1,frameRate=60,frameRateBase=1], AudioTrackInfo[codec=0x6167706d,codecName=mpga,originalCodec=0x6167706d,originalCodecName=mpga,id=1,profile=0,level=0,bitRate=224000,language=null,description=null,codecDescription=][channels=1,rate=44100]]
3485 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - getTrackInfo(types=[UNKNOWN])
3485 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - getTrackInfo(media=native@0x1f3724e0 (uk.co.caprica.vlcj.binding.internal.libvlc_media_t@1f3724e0),types=[UNKNOWN])
3485 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - newGetTrackInfo(media=native@0x1f3724e0 (uk.co.caprica.vlcj.binding.internal.libvlc_media_t@1f3724e0),types=[UNKNOWN])
3485 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - numberOfTracks=2
    UNKNOWN: []
3485 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - getTrackInfo(types=[AUDIO])
3485 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - getTrackInfo(media=native@0x1f3724e0 (uk.co.caprica.vlcj.binding.internal.libvlc_media_t@1f3724e0),types=[AUDIO])
3486 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - newGetTrackInfo(media=native@0x1f3724e0 (uk.co.caprica.vlcj.binding.internal.libvlc_media_t@1f3724e0),types=[AUDIO])
3486 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - numberOfTracks=2
3486 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - getCodecDescription(type=libvlc_track_audio,codec=1634168941)
      AUDIO: [AudioTrackInfo[codec=0x6167706d,codecName=mpga,originalCodec=0x6167706d,originalCodecName=mpga,id=1,profile=0,level=0,bitRate=224000,language=null,description=null,codecDescription=][channels=1,rate=44100]]
3486 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - getTrackInfo(types=[VIDEO])
3486 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - getTrackInfo(media=native@0x1f3724e0 (uk.co.caprica.vlcj.binding.internal.libvlc_media_t@1f3724e0),types=[VIDEO])
3486 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - newGetTrackInfo(media=native@0x1f3724e0 (uk.co.caprica.vlcj.binding.internal.libvlc_media_t@1f3724e0),types=[VIDEO])
3486 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - numberOfTracks=2
3486 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - getCodecDescription(type=libvlc_track_video,codec=875967080)
      VIDEO: [VideoTrackInfo[codec=0x34363268,codecName=h264,originalCodec=0x34363268,originalCodecName=h264,id=0,profile=0,level=0,bitRate=0,language=null,description=null,codecDescription=][width=1024,height=768,sampleAspectRatio=1,sampleAspectRatioBase=1,frameRate=60,frameRateBase=1]]
3487 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - getTrackInfo(types=[TEXT])
3487 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - getTrackInfo(media=native@0x1f3724e0 (uk.co.caprica.vlcj.binding.internal.libvlc_media_t@1f3724e0),types=[TEXT])
3487 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - newGetTrackInfo(media=native@0x1f3724e0 (uk.co.caprica.vlcj.binding.internal.libvlc_media_t@1f3724e0),types=[TEXT])
3487 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - numberOfTracks=2
       TEXT: []
3487 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - getTrackInfo(types=[AUDIO, VIDEO])
3487 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - getTrackInfo(media=native@0x1f3724e0 (uk.co.caprica.vlcj.binding.internal.libvlc_media_t@1f3724e0),types=[AUDIO, VIDEO])
3487 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - newGetTrackInfo(media=native@0x1f3724e0 (uk.co.caprica.vlcj.binding.internal.libvlc_media_t@1f3724e0),types=[AUDIO, VIDEO])
3487 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - numberOfTracks=2
3488 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - getCodecDescription(type=libvlc_track_video,codec=875967080)
3488 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - getCodecDescription(type=libvlc_track_audio,codec=1634168941)
AUDIO+VIDEO: [VideoTrackInfo[codec=0x34363268,codecName=h264,originalCodec=0x34363268,originalCodecName=h264,id=0,profile=0,level=0,bitRate=0,language=null,description=null,codecDescription=][width=1024,height=768,sampleAspectRatio=1,sampleAspectRatioBase=1,frameRate=60,frameRateBase=1], AudioTrackInfo[codec=0x6167706d,codecName=mpga,originalCodec=0x6167706d,originalCodecName=mpga,id=1,profile=0,level=0,bitRate=224000,language=null,description=null,codecDescription=][channels=1,rate=44100]]
3488 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - stop()
3565 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - release()
3565 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - destroyInstance()
3565 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - Detach media events...
3565 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - deregisterMediaEventListener()
3565 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaMetaChanged
3565 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaSubItemAdded
3565 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaDurationChanged
3565 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaParsedChanged
3565 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaFreed
3565 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaStateChanged
3565 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaSubItemTreeAdded
3565 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - Media events detached.
3566 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - Release media...
3566 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - Media released.
3566 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - Detach media player events...
3566 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - deregisterEventListener()
3566 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerMediaChanged
3566 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerNothingSpecial
3566 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerOpening
3566 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerBuffering
3566 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerPlaying
3566 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerPaused
3566 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerStopped
3567 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerForward
3567 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerBackward
3567 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerEndReached
3567 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerEncounteredError
3567 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerTimeChanged
3567 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerPositionChanged
3567 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerSeekableChanged
3567 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerPausableChanged
3567 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerTitleChanged
3567 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerSnapshotTaken
3567 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerLengthChanged
3567 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerVout
3567 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - event=libvlc_MediaPlayerScrambledChanged
3567 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - Media player events detached.
3567 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - Release media player...
3568 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - Media player released.
3568 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - Shut down listeners...
3568 [main] DEBUG uk.co.caprica.vlcj.player.DefaultMediaPlayer  - Listeners shut down.
3568 [main] DEBUG uk.co.caprica.vlcj.player.MediaPlayerFactory  - release()
`

**Comment by caprica** [comment]
Media info in vlcj is exactly the video/audio/spu track information provided by the native LibVLC API. No more, no less.

I don't see what relevance there is mentioning gstreamer quite honestly - a different tool/library has different capabilities :-/

Getting SPU count does work, but because playing media works asynchronously complete track data may not be available immediately, you're supposed to wait for events before you can access that. This is what the vlcj-player reference application does.
