### ISSUE TITLE
Facing issue to Stream screen using HTTP

### ISSUE THREAD

**Issue by kdubey007** [caprica/vlcj#549]
I am trying to stream my desktop  using http from past few days. 
but it throws Java Result: -1073741676 and strops working.

```
public class StreamHttp extends VlcjTest {
static MediaPlayerFactory mediaPlayerFactory;
    public static void main(String[] args) throws Exception {
        new NativeDiscovery().discover();     

        String options = formatHttpStream("127.0.0.1", 5555);       

        mediaPlayerFactory = new MediaPlayerFactory(args);
        HeadlessMediaPlayer mediaPlayer = mediaPlayerFactory.newHeadlessMediaPlayer();
        mediaPlayer.playMedia("screen://", options);


        Thread.currentThread().join();
    }

    private static String formatHttpStream(String serverAddress, int serverPort) {
        StringBuilder sb = new StringBuilder(60);
        sb.append(":sout=#transcode{vcodec=mp4v,vb=800,scale=0,acodec=mpga,ab=128,channels=2,samplerate=44100}:duplicate{dst=std{access=http,mux=ts,");
        sb.append("dst=");
        sb.append(serverAddress);
        sb.append(':');
        sb.append(serverPort);
        sb.append("}}");
        return sb.toString();
    }
}
```

**Comment by caprica** [comment]
Impossible to help you with such limited information.

**Comment by kdubey007** [comment]
Kindly let me know what more details should I provide. I will provide those.

**Comment by caprica** [comment]
I have no idea. What have you tried/investigated so far? Is there anything in the console. Turn on VLC logging and read that. You've basically just posted "my app doesn't work, please help". It's too vague.

**Comment by kdubey007** [comment]
I debugged the code but there was no specific error. Even tried to do the same with vlc player but when I started the stream it suddenly got closed. The code which i have posted works fine for "dshow://". But when I replace it with "screen://" it gives Java Result: -1073741676. I don't know if I am taking wrong approach or if the code has bug. I didn't found any specific code or help on google.
Please suggest

**Comment by kdubey007** [comment]
Okay so the code on which I was working for was correct. VLC player 2.2.4 had the issue. I installed 2.1.3 and every thing was back to normal.
Thank You

**Comment by caprica** [comment]
Awesome!
