### ISSUE TITLE
Does vlcj reverse playback and increase/decrese video playback?

### ISSUE THREAD

**Issue by nvkaymanov** [caprica/vlcj#552]
If Yes, how it can be implemented?

**Comment by caprica** [comment]
VLC does not allow to play in reverse.

Increase/decrease playback speed is achieved by setting the "rate". vlcj's MediaPlayer has API for setting the rate, i.e. mediaPlayer.setRate(value) where value is e.g. 0.5 for half speed, 2.0 for double speed.

**Comment by nvkaymanov** [comment]
I found a workaround for play in reverse - http://stackoverflow.com/a/31882421/6781737
It works.
