### ISSUE TITLE
How can i put a transparent JPanel on top of the EmbeddedMediaPlayerComponent?

### ISSUE THREAD

**Issue by clayandgithub** [caprica/vlcj#553]
I have tried OverlayLayout and setOpaque with another JPanel, but neither of them could work.
There alway exists a background on top of the EmbeddedMediaPlayerComponent.

**Comment by caprica** [comment]
http://capricasoftware.co.uk/#/projects/vlcj/tutorial/overlay

**Comment by clayandgithub** [comment]
Didn't see this tutorial.
Thanks a lot!

**Comment by caprica** [comment]
Also https://github.com/caprica/vlcj/tree/master/src/test/java/uk/co/caprica/vlcj/test/overlay
