### ISSUE TITLE
Trim videos with vlcj

### ISSUE THREAD

**Issue by andrea-bologna** [caprica/vlcj#556]
Hi, is it possible to cut a video part using vlcj and export it as a new file (eg an MP4)? 

Thanks

**Comment by caprica** [comment]
It is *possible* by using VLC command-line switches, and "sout" strings, and passing those to the media player and/or factory.

However, it is very much NOT recommended to use LibVLC/vlcj for doing this since there's no actual API for it.

You are much better off using dedicated utilities instead.
