### ISSUE TITLE
EmbeddedMediaPlayerComponent class not found error in raspberry pi

### ISSUE THREAD

**Issue by anscorpion** [caprica/vlcj#557]
I am using java code to run video through vlc player on raspberry pi. Code is developed in Intellij. I can compile it on windows but when i actually use on raspberry pi it throws an exception as -
`AWT-eventque-0: java.lang.NoClassDefFoundError uk/co/caprica/vlcj/Component/EmbeddedMediaPlayerComponent....
.
.
.
.
.
.
.
.
`
              i am using jna-4.1.0.jar, vlcj-3.0.0.jar
Can you please suggest me the correction.

**Comment by caprica** [comment]
`NoClassDefFoundError` means that the JVM can't find the class on the classpath. Simple as that.

**Comment by anscorpion** [comment]
Thank you very much for reply.
Can you please tell me how can i check the class is there in classpath or not, as i am relatively new in this field.

**Comment by caprica** [comment]
Your problem is a general problem and not specifically related to vlcj. I can't offer you the level of support you need. I can only suggest you find a good tutorial on launching Java applications and setting the Java classpath.

**Comment by anscorpion** [comment]
Ok. No problem.
Still Thank you very much for your time. 
Really appreciate your help.
