### ISSUE TITLE
Streaming http VLCJ

### ISSUE THREAD

**Issue by Palak92** [caprica/vlcj#561]
I am trying to stream a video via vlcj to local host by using this code: 

~~~~
public class StreamHttp extends VlcjTest {
static MediaPlayerFactory mediaPlayerFactory;
    public static void main(String[] args) throws Exception {
        new NativeDiscovery().discover();     

        String options = formatHttpStream("127.0.0.1", 5555);       

        mediaPlayerFactory = new MediaPlayerFactory(args);
        HeadlessMediaPlayer mediaPlayer = mediaPlayerFactory.newHeadlessMediaPlayer();
        mediaPlayer.playMedia("screen://", options);


        Thread.currentThread().join();
    }

    private static String formatHttpStream(String serverAddress, int serverPort) {
        StringBuilder sb = new StringBuilder(60);
        sb.append(":sout=#transcode{vcodec=mp4v,vb=800,scale=0,acodec=mpga,ab=128,channels=2,samplerate=44100}:duplicate{dst=std{access=http,mux=ts,");
        sb.append("dst=");
        sb.append(serverAddress);
        sb.append(':');
        sb.append(serverPort);
        sb.append("}}");
        return sb.toString();
    }
}
~~~~
But when I type IP address and port number in my browser nothing comes up.

**Comment by caprica** [comment]
First, please take the time to format your code in markdown correctly if you expect any help.

Second, what do you expect me to do with this limited information and without logs. Enable logs, look at the logs, if you're still stuck, post the logs.

**Comment by Palak92** [comment]
1. The code is :**[https://github.com/caprica/vlcj/blob/master/src/test/java/uk/co/caprica/vlcj/test/streaming/StreamHttp.java**]

2. The logs:

 ### _--- exec-maven-plugin:1.2.1:exec (default-cli) @ ScreenCapture ---
247 [main] INFO uk.co.caprica.vlcj.Info - vlcj: 3.10.1
248 [main] INFO uk.co.caprica.vlcj.Info - java: 1.8.0_121 Oracle Corporation
248 [main] INFO uk.co.caprica.vlcj.Info - java home: C:\Program Files\Java\jdk1.8.0_121\jre
248 [main] INFO uk.co.caprica.vlcj.Info - os: Windows 7 6.1 amd64
316 [main] INFO uk.co.caprica.vlcj.binding.LibVlcFactory - vlc: 2.1.3 Rincewind, changeset 2.1.3-0-ge6a71cc
316 [main] INFO uk.co.caprica.vlcj.binding.LibVlcFactory - libvlc: libvlc.dll
TagLib: MP4: No audio tracks
TagLib: MP4: No audio tracks
TagLib: MP4: No audio tracks
TagLib: MP4: No audio tracks_


the Program runs but I am not able to see streamed video at this IP

**Comment by caprica** [comment]
I see markdown formatting escapes you.

Probably something wrong with your transcoding "sout" string.

**Comment by Palak92** [comment]
I checked the string containing "sout" with vlc media player ( in streaming option ) and copied it down in my program.  I rechecked the string by executing it on cmd window. It works there too.
The logs dont show any issue with the string.

**Comment by caprica** [comment]
Enable verbose _native_ logging in vlcj using "-vvv" in MediaPlayerFactory arguments.
Play your media.

Enable verbose logging in VLC using "-vvv" on the command-line.
Play your media.

Compare differences in the logs.

**Comment by caprica** [comment]
Put it this way, there can only be a few things that are wrong.

Either it's your MRL, "screen://" - now this on its own looks OK, but you may need to set other options.

Or it's your sout string.

Or it's some other option you need to set on the MediaPlayerFactory.
