### ISSUE TITLE
stream webcam+mic to rtsp

### ISSUE THREAD

**Issue by salvo19881** [caprica/vlcj#562]
Hello, i'm trying to stream my webcam to rtsp.
With VLC i've no problem , but when try to do it with vlcj in javacode vlc can't read mrl
this is my code

`String mediaURL= "dshow://";`
`MediaPlayerFactory mediaPlayerFactory = new MediaPlayerFactory();`
`String input=" :dshow-vdev=HP Truevision HD :dshow-adev=Array microfono interno (IDT High Definition Audio CODEC) ";`
`String out=":sout=#transcode{vcodec=h264,acodec=mpga,ab=128,channels=2,samplerate=44100}:rtp{sdp=rtsp://192.168.88.241:8554/prva.mp4} :sout-keep";`
`HeadlessMediaPlayer mediaPlayer = mediaPlayerFactory.newHeadlessMediaPlayer();`
`mediaPlayer.playMedia(mediaURL,input+out);`
`Thread.currentThread().join();`

**Comment by caprica** [comment]
Please format that code properly.

**Comment by salvo19881** [comment]
Sorry, i didn't see preview

**Comment by caprica** [comment]
Looks just the same unformatted to me right now.

**Comment by salvo19881** [comment]
Now? i insert code tag for each line

**Comment by caprica** [comment]
https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

**Comment by caprica** [comment]
Don't use spaces in a long media options string. Wherever you have a space, that's a separate string you pass in an array.

Also, look at the vlcj test examples like https://github.com/caprica/vlcj/blob/master/src/test/java/uk/co/caprica/vlcj/test/capture/CaptureTest.java and maybe https://github.com/caprica/vlcj/blob/master/src/test/java/uk/co/caprica/vlcj/test/screen/ScreenTestPlayer.java for an example of how to pass options.

**Comment by salvo19881** [comment]
I try without spaces but not work.
I see an jframe with webcam video and audio, but if i go in vlc and try rtsp url, not work.
I don't know how work , but i think that i set wrong output

**Comment by caprica** [comment]
Enable native logging and check the logs.

**Comment by salvo19881** [comment]
Ok, solved.
I delete input and   `  :sout-keep ` in out string.
Now problem is delay, on start about 20 sec,
After first frame about 5 second.
It's net problem?
PS 
Thanks for answer

**Comment by caprica** [comment]
The things you are asking about pertain to VLC itself, not vlcj.

Having said that, maybe try reducing caching.

**Comment by salvo19881** [comment]
I try, but not solve.
Thanks a lot for help. 
I will try to found a solution. 
Bye
