### ISSUE TITLE
Adding 'edit options' in streaming 

### ISSUE THREAD

**Issue by Palak92** [caprica/vlcj#564]
I want to stream a particular area of my desktop. In vlc I am able to do it by using '**edit options= :screen-top=150 :screen-left=150 :screen-width=300 :screen-height=200**'. How can I use it in my code?
 

```
public static void main(String[] args)  throws Exception {  
        if(args.length != 1) {
            System.out.println("Specify a single MRL to stream");
            System.exit(1);
        }
 String media = "screen://";
String[] options = { :sout=#transcode{vcodec=mp2v,vb=800,acodec=mpga,ab=128,channels=2,samplerate=44100} :http{mux=ts,dst=:8081" }
      MediaPlayerFactory mediaPlayerFactory = new MediaPlayerFactory("-vvv");
        
        HeadlessMediaPlayer mediaPlayer = mediaPlayerFactory.newHeadlessMediaPlayer();
        mediaPlayer.playMedia(media, options);
        // Don't exit
       Thread.currentThread().join();
    }
```

**Comment by caprica** [comment]
The options array does not accept strings separated by spaces. Each space is a separate option, so must be a separate item in the array.

I have no idea what "edit options ..." is, but I see no reason why those e.g. ":scree-left=150" would not work as separate strings in the options array, either on the factory or when you invoke mediaPlayer.playMedia(mrl, options).
