### ISSUE TITLE
Error NativeLibrary.addSearchPath Win Xp Java 8

### ISSUE THREAD

**Issue by Tsyklop** [caprica/vlcj#565]
I have probmel. 
I made a program. And run it on Windows XP x32. VLC x32 and Java 8 x32.

But when the program reaches the moment when the library is searched for vlc - `NativeLibrary.addSearchPath`, it closes. In this case, no errors occur.

What wrong?

**Comment by caprica** [comment]
This problem description is way too vague, seriously.

There must be error messages, logs. Did you try the vlcj tutorials?

**Comment by Tsyklop** [comment]
@caprica I would gladly give you logs. But the fact of the matter is that they do not exist. My program writes a log file (log4J), but there is no error.

No, I have not tried it. Tell me that there?

**Comment by caprica** [comment]
Well then, I'm afraid it is pretty much impossible to help you given your problem statement.

**Comment by caprica** [comment]
In your other issue #563 you already got past the code where it does NativeLibrary.addSearchPath.

**Comment by Tsyklop** [comment]
@caprica There is another computer and everything is working fine.

**Comment by caprica** [comment]
So you need to compare the differences in your working vs non-working environments, I can't do that for you.
