### ISSUE TITLE
Linebreaking the videofile

### ISSUE THREAD

**Issue by MS-Tech** [caprica/vlcj#568]
Hi, 

i am currently programming a JavaFX application and have problems with the internal media player, since this does not play files larger than 1920x1080 (it´s a limitation of the h.264 codec). Now I would like to integrate the VLC Player with vlcj, but have a few question. Can I wrap the video with vlcj? I have a send window with a size of 1000 pixels. The video is 3000 pixels wide. I would therefore have to wrap the video in 3 lines. With the MediaView of JavaFX is not a problem, because I can set as a ViewPort. Can I do this with vlcj? Then it may happen that I have to play several videos at the same time. These videos must start and end synchronously.

Thanks for the answers.
MS-Tech

**Comment by caprica** [comment]
I don't know what you mean by "wrapping".

LibVLC/vlcj allows you to crop, pan and zoom the video. That's about it.

Be aware that hi-resolution video using vlcj with JavaFX will be *very* resource intensive (software rendering).

**Comment by MS-Tech** [comment]
Hello. Thanks for the quick response. What i mean with wrapping. So... I have a View with a width of 1000px and a height of 300px. The Video has a width of 3000px and a height of 100px. I must crop the videofile after 1000px (the end of the first line). In the next line i have to continue at the crop point of the first line. in the third line is the same. is this possible? Its hard to explain. I´ve attatched a example. Is this possible with vlcj?
[github.pdf](https://github.com/caprica/vlcj/files/1160509/github.pdf)

**Comment by caprica** [comment]
I'm not going to open a random PDF, sorry.

What you're doing is likely not possible with LibVLC/vlcj. By that, I mean there's no API support in LibVLC or vlcj to help you do that.
