### ISSUE TITLE
buffer newCache indicator is not updated

### ISSUE THREAD

**Issue by Abu-Abdullah** [caprica/vlcj#569]
Hi,

i just notice that in the latest version the buffer cache is not updated in the buffering() method. it throws 2 numbers with 0.0 value (at the beginning and at the end)

```
public void buffering(MediaPlayer mediaPlayer, float newCache)
{
	System.out.println(newCache);
}
```
it was working on 3.6.0

**Comment by caprica** [comment]
Are you playing the same media now as you did when it was on 3.6.0?

Are you using the same VLC version now as you did when it worked?

Because that implementation has not changed in vlcj at all, it just sends whatever LibVLC tells it.

**Comment by Abu-Abdullah** [comment]
i just retest  it with exactly the same vlc version, i got the same result. the only change was in my application, i migrated my code from swing to fully native JavaFX without any swing classes.

**Comment by caprica** [comment]
Nothing has changed in vlcj in the area of native events for quite some time.

**Comment by Abu-Abdullah** [comment]
ok i will do more tests and update this case later. i will try to have sample test.

**Comment by Abu-Abdullah** [comment]
it turns out to be a mistake from my side. i have been updating UI inside buffering() which is not in the FX application thread. wrapping all the UI calls inside Platform.runLater solved it (even though there was no errors shown).
it seems javaFX is very sensitives on this
