### ISSUE TITLE
how to use vlcj with socket, i cant't found any example, .hope some help...

### ISSUE THREAD

**Issue by kaixuanluo** [caprica/vlcj#572]
`private void socketTest() {

		try {
			socket2 = new Socket(server, ip);
			dis = new DataInputStream(socket2.getInputStream());
			dos = new DataOutputStream(socket2.getOutputStream());
			br = new BufferedReader(new InputStreamReader(socket2.getInputStream()));
		} catch (UnknownHostException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		new Thread(new Runnable() {

			@Override
			public void run() {
				// TODO Auto-generated method stub

				MediaPlayerFactory mediaPlayerFactory = new MediaPlayerFactory();
				EmbeddedMediaPlayer mediaPlayer = mediaPlayerFactory.newEmbeddedMediaPlayer();

				Canvas canvas = new Canvas();
				canvas.setBackground(Color.black);
				CanvasVideoSurface videoSurface = mediaPlayerFactory.newVideoSurface(canvas);
				mediaPlayer.setVideoSurface(videoSurface);

				// Creating a JFrame to display stream ( duplicate)
				JFrame f = new JFrame("vlcj duplicate output test");
				f.add(canvas);
				f.setSize(800, 600); 
				f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
				f.setVisible(true);

				while (true) {
					try {
						 int read = dis.read();
						String mrl = dis.readLine();
		
						System.out.println("get mrl : " + mrl);
						if (mrl == null) {
							return;
						}
						 mediaPlayer.playMedia(mrl);
					} catch (IOException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
				}
				
			}
		}).start();
	}`

> this code is incorrect, the log like this .

> get mrl : RâïÝRäB

**Comment by kaixuanluo** [comment]
log info 

get mrl : RâïÝRäB
libdvdnav: Using dvdnav version 5.0.3
libdvdread: Could not open D:\MyEclipseWorkSpace3\vlcjExample\?a???.!hBa???.!`??t!q QHG��??k1��a?A`?1(?1%T��|%|$1}����?..yD?.D)p5@ with libdvdcss.
libdvdread: Can't open D:\MyEclipseWorkSpace3\vlcjExample\?a???.!hBa???.!`??t!q QHG��??k1��a?A`?1(?1%T��|%|$1}����?..yD?.D)p5@ for reading
libdvdnav: vm: failed to open/read the DVD
libdvdnav: Using dvdnav version 5.0.3
libdvdread: Could not open D:\MyEclipseWorkSpace3\vlcjExample\?a???.!hBa???.!`??t!q QHG��??k1��a?A`?1(?1%T��|%|$1}����?..yD?.D)p5@ with libdvdcss.
libdvdread: Can't open D:\MyEclipseWorkSpace3\vlcjExample\?a???.!hBa???.!`??t!q QHG��??k1��a?A`?1(?1%T��|%|$1}����?..yD?.D)p5@ for reading
libdvdnav: vm: failed to open/read the DVD
[000000001addc820] filesystem access error: cannot open file D:\MyEclipseWorkSpace3\vlcjExample\�����.!hB����.!`���!q QHG�ƌk1���A`�1(�1%���%�$�}�ȅ..�Ѕ.D)p5@ (Invalid argument)
[000000001addc820] core access error: File reading failed
[000000001addc820] core access error: VLC could not open the file "D:\MyEclipseWorkSpace3\vlcjExample\�����.!hB����.!`���!q QHG�ƌk1���A`�1(�1%���%�$�}�ȅ..�Ѕ.D)p5@" (Invalid argument).
[000000001addc820] filesystem access error: cannot open file D:\MyEclipseWorkSpace3\vlcjExample\�����.!hB����.!`���!q QHG�ƌk1���A`�1(�1%���%�$�}�ȅ..�Ѕ.D)p5@ (Invalid argument)
[000000001addc820] core access error: File reading failed
[000000001addc820] core access error: VLC could not open the file "D:\MyEclipseWorkSpace3\vlcjExample\�����.!hB����.!`���!q QHG�ƌk1���A`�1(�1%���%�$�}�ȅ..�Ѕ.D)p5@" (Invalid argument).
[000000001ac83f00] core input error: open of `file:///D:/MyEclipseWorkSpace3/vlcjExample/%C3%B6%C3%A2%17%10%C2%B8%C2%85%C3%84.%21hB%C3%A2%17%10%C2%B8%C2%85%C3%84.%21%60%C2%8F%C2%92%C3%BE%21q%0B%20QHG%C3%BC%C3%86%C2%8Ck1%C2%A3%1A%C3%A2%14%C2%84A%60%C2%851%28%C2%851%25%C3%9E%C3%BA%10%C2%A6%25%10%C2%A6%24%C2%B9%7D%07%10%C2%A5%C3%88%C2%85..%C3%BD%C3%90%C2%85.D%29p%015%40' failed
[000000001ac83f00] core input error: Your input can't be opened
[000000001ac83f00] core input error: VLC is unable to open the MRL 'file:///D:/MyEclipseWorkSpace3/vlcjExample/%C3%B6%C3%A2%17%10%C2%B8%C2%85%C3%84.%21hB%C3%A2%17%10%C2%B8%C2%85%C3%84.%21%60%C2%8F%C2%92%C3%BE%21q%0B%20QHG%C3%BC%C3%86%C2%8Ck1%C2%A3%1A%C3%A2%14%C2%84A%60%C2%851%28%C2%851%25%C3%9E%C3%BA%10%C2%A6%25%10%C2%A6%24%C2%B9%7D%07%10%C2%A5%C3%88%C2%85..%C3%BD%C3%90%C2%85.D%29p%015%40'. Check the log for details.

**Comment by caprica** [comment]
This is not a vlcj problem. This is a problem related to reading data (seemingly garbage data) from your network socket.

**Comment by kaixuanluo** [comment]
here is my android code, it as the video source.

`  private void startScreenCapture(int resultCode, Intent resultData) {

        this.mediaProjection = ((MediaProjectionManager) getSystemService(Context.MEDIA_PROJECTION_SERVICE)).getMediaProjection(resultCode, resultData);

      ServerSocket serverSocket = new ServerSocket(port);
                    socket = serverSocket.accept();
                    socketOutputStream = socket.getOutputStream();
                    dataOutputStream = new DataOutputStream(socketOutputStream);

        Log.d(TAG, "startRecording...");

        this.videoBufferInfo = new MediaCodec.BufferInfo();
        MediaFormat mediaFormat = MediaFormat.createVideoFormat("video/avc", 640, 360);

        mediaFormat.setInteger(MediaFormat.KEY_BIT_RATE, 1024000);
        mediaFormat.setInteger(MediaFormat.KEY_FRAME_RATE, 30);
        mediaFormat.setInteger(MediaFormat.KEY_CHANNEL_COUNT, 0);
        mediaFormat.setInteger(MediaFormat.KEY_I_FRAME_INTERVAL, 1);

        try {
                    // AVC
                    mediaFormat.setInteger(MediaFormat.KEY_COLOR_FORMAT, MediaCodecInfo.CodecCapabilities.COLOR_FormatSurface);

                    this.encoder = MediaCodec.createEncoderByType("video/avc");
                    this.encoder.setCallback(new MediaCodec.Callback() {
                        @Override
                        public void onInputBufferAvailable(MediaCodec codec, int inputBufferId) {
                        }

                        @Override
                        public void onOutputBufferAvailable(MediaCodec codec, int outputBufferId, MediaCodec.BufferInfo info) {
                            ByteBuffer outputBuffer = codec.getOutputBuffer(outputBufferId);
                            if (info.size > 0 && outputBuffer != null) {
                                outputBuffer.position(info.offset);
                                outputBuffer.limit(info.offset + info.size);
                                byte[] b = new byte[outputBuffer.remaining()];
                                outputBuffer.get(b);
                                   new Thread(new Runnable() {
                                  @Override
                                  public void run() {
                                  dataOutputStream.write(b);    //here is data output
                                 }});
                            }
                            if (encoder != null) {
                                encoder.releaseOutputBuffer(outputBufferId, false);
                            }
                            if (videoBufferInfo != null && (videoBufferInfo.flags & MediaCodec.BUFFER_FLAG_END_OF_STREAM) != 0) {
                                Log.i(TAG, "End of Stream");
                                stopScreenCapture();
                            }
                        }

                        @Override
                        public void onError(MediaCodec codec, MediaCodec.CodecException e) {
                            e.printStackTrace();
                        }

                        @Override
                        public void onOutputFormatChanged(MediaCodec codec, MediaFormat format) {
                            Log.i(TAG, "onOutputFormatChanged. CodecInfo:" + codec.getCodecInfo().toString() + " MediaFormat:" + format.toString());
                        }
                    });`

**Comment by caprica** [comment]
Your problems are nothing to do with vlcj specifically. I can't help you.

**Comment by kaixuanluo** [comment]
Hello, I've Changed my code to this 
`String mrl = "tcp://192.168.3.3:9005";
mediaPlayer.playMedia(mrl, new String[] { ":demux=h264" });`
It worked, But the video delay is so large, 
Thanks All.

**Comment by caprica** [comment]
I actually had no idea, or had long since forgotten, about "tcp://" as a valid MRL for VLC. Wow.

For the delay, you can try and hunt around for network caching options to reduce them, if you find something relevant you can pass such options via the vlcj MediaPlayerFactory.

**Comment by kaixuanluo** [comment]
Excuse i can't input super link, 
Yes, I've passed those options "--network-caching=0",  "--file-caching=0",to MediaPlayerFactory.
But throw those logs.
'[000000001aa6bb80] core input error: ES_OUT_SET_(GROUP_)PCR  is called too late (jitter of 5379 ms ignored)
[h264 @ 000000001ab58740] decode_slice_header error
[000000001ab55660] core decoder error: Could not get display date for timestamp 0
[000000001ab55660] core decoder error: Could not convert timestamp 0'

I can't sure it is work or not ,  My first think, When my h264 data is too small (around 1kb/s) , vlcj will throw those error
It's not network delay, Is android MediaCodec https://developer.android.google.cn/reference/android/media/MediaCodec.html
I recoded phone screen data and out put it to vlcj, When the screen content not change ,
It will output very small h264 data, so cased this.

Here is the play video https://youtu.be/oh5mWOV-FcE
And Here is the Android play video https://youtu.be/k8aRI_4r9wk
They all used the  same one server data source

**Comment by kaixuanluo** [comment]
Yes, I found it, If i  always output data(data out put enough) , the error log never appear, And then , i think i should to set or ignore this ([000000001a15c900] core input error: ES_OUT_SET_(GROUP_)PCR  is called too late (jitter of 5652 ms ignored))

**Comment by kaixuanluo** [comment]
Here is vlc source code https://github.com/videolan/vlc/blob/7f69c2d5f1161b7ad3eddfe4afd2b64aa087bf24/src/input/es_out.c
 '  if( i_pts_delay > __MIN( i_pts_delay_base + i_jitter_max, INPUT_PTS_DELAY_MAX ) )
                {
                    msg_Err( p_sys->p_input,
                             "ES_OUT_SET_(GROUP_)PCR  is called too late (jitter of %d ms ignored)",
                             (int)(i_pts_delay - i_pts_delay_base) / 1000 );
                    i_pts_delay = p_sys->i_pts_delay;

                    /* reset clock */
                    for( int i = 0; i < p_sys->i_pgrm; i++ )
                      input_clock_Reset( p_sys->pgrm[i]->p_clock );
                }
                else
                {
                    msg_Err( p_sys->p_input,
                             "ES_OUT_SET_(GROUP_)PCR  is called too late (pts_delay increased to %d ms)",
                             (int)(i_pts_delay/1000) );

                    /* Force a rebufferization when we are too late */

                    /* It is not really good, as we throw away already buffered data
                     * TODO have a mean to correctly reenter bufferization */
                    es_out_Control( out, ES_OUT_RESET_PCR );
                };'

**Comment by caprica** [comment]
This is the wrong place for these types of sprawling questions. If you have vlcj problem, feel free to create a new issue here, but VLC source code is out-of-scope for this project.
