### ISSUE TITLE
Start-Time of Media

### ISSUE THREAD

**Issue by MS-Tech** [caprica/vlcj#574]
Hello,

how can i set the start-time of a media-file before the media-file is playing? at the moment i start the mediaplayer (start playing media) and after that i set the star-time. 
This has the effect that the video is already played before setting the start time. This will already play the first half second (or less) before jumping to the start time.

Greetings
MS-Tech

**Comment by caprica** [comment]
Pass ":start-time=whatever" in options parameter when you invoke playMedia.

**Comment by MS-Tech** [comment]
Hello,

i´ve set the start-time in the playMedia method, but the file played from the beginning. In the first case the starttime is -1 and the file begins to play from the start position. in the second case the starttime is 9345 millicseonds, but the file begins to play again from the start position. The starttime is a class variable.

`	@Override
	public void play(String media) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
            	player.playMedia(media, ":start-time=" + startTime);
            }
        });
	}`

Greetings
MS-Tech

**Comment by MS-Tech** [comment]
Hello,

can only seconds be given as start time and no milliseconds? I have tested your answer, but here, too, the first frames are played, until the start time is jumped.

Greetings
MS-Tech

**Comment by caprica** [comment]
See also https://stackoverflow.com/questions/34793016/do-milliseconds-have-any-effect-when-vlcj-is-playing-a-video-segment

**Comment by caprica** [comment]
What has been described so far is all you can do. There is nothing more.

**Comment by caprica** [comment]
There is no perfect solution here, if anything only awkward workarounds.

You can try something like: put a black panel in place of your video player, play the video with the start-time option, wait for a time changed event reporting a time equal to or greater than your start time, remove the black panel and show the video player. Maybe mute the volume until ready too.

**Comment by MS-Tech** [comment]
Thank you for the suggestion. I will try it.

Greetings
MS-Tech
