### ISSUE TITLE
raspberry pi 3 vout argument not working

### ISSUE THREAD

**Issue by ssoulDeveloper** [caprica/vlcj#576]
Hi there,

I have checked issues about problems with raspberry pi and i would like to repost one of the problems since it's still exists:

When i use EmbeddedMediaPlayerComponent inside a JFrame, "--vout" argument is clearly ignore once i start playing media. This problem can be extended to general case when you try to set VideoSurface to EmbeddedMediaPlayer. If this VideoSurface (which usually is a canvas) isn't placed inside a JFrame you will get an exception (which i think is normal).But when you place it inside a JFrame you will get the problem i described (and no exception) 

Here some cases:

1. Extend EmbeddedMediaPlayerComponent class and override onGetMediaPlayerFactoryArgs
2. Extend EmbeddedMediaPlayerComponent class and override onGetMediaPlayerFactoryExtraArgs
3. Extend EmbeddedMediaPlayerComponent class and override onGetMediaPlayerFactory
4. Use directly MediaPlayerFactory:
    I. Create MediaPlayerFactory (with args)
   II. Create VideoSurface (using MediaPlayerFactory)
  III. Create EmbeddedMediaPlayer (using the same MediaPlayerFactory)
  IV. Set VideoSurface
   V. Add VideoSurface to JFrame
  VI. Play Media -> Get problems

**Comment by caprica** [comment]
I do not understand what you say about the general case. There is clearly no problem using a Canvas as a video surface using EmbeddedMediaPlayer inside a JFrame in the general case, since it's what I do all the time.

The only thing vlcj does here is to pass the native window handle to LibVLC - that either works or it doesn't, there is nothing else that can be done in vlcj other than to pass that native window handle.

The RPi video output might not support being embedded in another application for all I know.

**Comment by caprica** [comment]
Relates to #518 and other issues I suppose.

**Comment by ssoulDeveloper** [comment]
My bad, by "general cases" i mean all these i tested (both EmbeddedMediaPlayerComponent and EmbeddedMediaPlayer). I don't think it's a "general problem" since i have no problem with playing media on Windows 10.
It is related to #518 though it was closed without any proper solution. Now the most important part:

I started with [this](http://capricasoftware.co.uk/#/projects/vlcj/tutorial/my-first-media-player) tutorial and changed:

`mediaPlayerComponent = new EmbeddedMediaPlayerComponent();`

into 
```
mediaPlayerComponent = new EmbeddedMediaPlayerComponent(){
            @Override
            protected String[] onGetMediaPlayerFactoryExtraArgs() {
                return new String[] { "--vout=omxil_vout", "--aout=alsa"};
            }
        }
```

This should "pass extra arguments to vlc player". I tested these arguments with vlc from command line though the result i got was different from the one i get after calling:

`mediaPlayerComponent.getMediaPlayer().playMedia(args[0]);`

When i run vlc from command line (`vlc --vout=omxil_vout --aout=alsa /home/pi/Videos/1.mp4`) i get a clear image and good quality audio, but when i run the code from tutorial i get almost fixed image and good quality audio running in background. It's almost like the player updates frame once every `x seconds`.

Yet, when this code:
```
    String[] libvlcArgs = new String[] {"--vout=omxil_vout","--aout=alsa"};
    MediaPlayerFactory mpf = new MediaPlayerFactory(libvlcArgs);
    EmbeddedMediaPlayer mp = mpf.newEmbeddedMediaPlayer();
    mp.playMedia("vid.mp4");
```

is still working.

**Comment by caprica** [comment]
For anyone coming across this issue, as of February 2019 vlcj should just work with up-to-date software - I just tested VLC 3.0.6, Raspbian GNU/Linux 9 (stretch) with all other packages up-to-date and it worked just fined.

There was no need to set audio outputs/video outputs or anything else.
