### ISSUE TITLE
How to get on external class the value of positionPane

### ISSUE THREAD

**Issue by cahernanz** [caprica/vlcj#577]
Hi!, my question is how to acces to value or get the value o newTime to see how it increases and use it in an external class. Do you know othe method to get the time of the video in oher class??. 

This is the function to see the time
            @Override
            public void timeChanged(MediaPlayer mediaPlayer, long newTime) {
                SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        positionPane.setTime(newTime);
                        statusBar.setTime(newTime);
                    }
                });
            }

Thanks in advance

**Comment by caprica** [comment]
The class that wants to know the time should add itself as a MediaPlayerEventListener.

That is a pretty standard Java concept, and not particular to vlcj.

**Comment by cahernanz** [comment]
thanks a lot!, ill check it
