### ISSUE TITLE
vlcj crashes on win64

### ISSUE THREAD

**Issue by happy3014** [caprica/vlcj#579]
I cloned this project and ran it on my pc, it crashed, and below is my log file.
[debug.log](https://github.com/caprica/vlcj/files/1393321/debug.log)
I have found what is wrong. Because vlc only has a 32-bit version, when it is installed on win64, the location of it in the register is "HKEY_LOCAL_MACHINE->SOFTWARE->WOW6432Node->VideoLAN->VLC", not "HKEY_LOCAL_MACHINE->SOFTWARE->VideoLAN->VLC". So this will fail when the function "getVlcInstallDir" in the class uk.co.caprica.vlcj.runtime.windows.WindowsRuntimeUtil runs.

I know what is wrong, but I don't know how to fixed it, Could you help to solve it?Thanks

**Comment by caprica** [comment]
You could write your own implementation of a vlcj native discovery strategy class that looks for the other registry key.

Eventually the existing code in vlcj will probably be patched to search that additional key I suppose.

**Comment by caprica** [comment]
You can also simply not use those vlcj classes, and instead add the LibVLC path manually as described in the tutorial or the JNA documentation.

**Comment by happy3014** [comment]
Thanks for your reply. I've solved this by install a 64-bit version on my pc.(sorry, the link on the official website only points to a 32-bit version, so I thought there wasn't 64-bit version. Later I found a 64-bit version on this website http://download.videolan.org/pub/videolan/vlc/).

But I still advise to patch this to improve the usability. Thanks again for your share.
