### ISSUE TITLE
How to get the length of a HLS video?

### ISSUE THREAD

**Issue by happy3014** [caprica/vlcj#581]
I want to play a HLS video by vlcj, it plays normally, but I can't get the length of the video by the function <kbd>player.getLength()</kbd>, it returns 0. And the function <kbd>player.setTime()</kbd> doesn't work. Below is my m3u8 file content. This a bug of vlcj or there is something wrong with my code? I'm confused about this. If this is a bug, could you please give me some advice to solve it? Thanks.
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:64
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-KEY:METHOD=AES-128,URI="http://localhost:12345/hlss/en1.key"
#EXTINF:60.375000,
output0.ts
#EXTINF:60.291667,
output1.ts
#EXTINF:60.833333,
output2.ts
#EXTINF:60.208333,
output3.ts
#EXTINF:58.791667,
output4.ts
#EXTINF:63.791667,
output5.ts
#EXTINF:56.125000,
output6.ts
#EXTINF:43.875000,
output7.ts
#EXT-X-ENDLIST
```

**Comment by caprica** [comment]
For some media types, VLC does not know the media duration (length) until some time after it has started playing. So you must listen for a "length changed" event.

For setTime, some media does not allow you to skip I suppose.

**Comment by caprica** [comment]
Also, with a "playlist" file like your m3u8 file you likely will need to wait until a sub-item has started playing (there is an event for this).

**Comment by happy3014** [comment]
Thanks for your reply. Later I found that function <kbd>player.setPosition()</kbd> worked normally.
