### ISSUE TITLE
Video Stream is played in separate new window instead of intended canvas

### ISSUE THREAD

**Issue by nullpointer01** [caprica/vlcj#582]
![capture](https://user-images.githubusercontent.com/33321673/32329676-c3c89ff0-bfee-11e7-9beb-0a7aadc56bb0.JPG)

In my project I create like 4 - 9 canvas and assign libvlc instances to each one of them.
Program needs to be able to redo this process frequently.
For example I close a mediaPlayer and dismiss its related canvas, and start creation from the start.

Most of the time program works just fine. Problem is that, sometimes (specially when CPU usage of the PC is high) media player plays the video stream in a separate video window (as can be seen in the attached photo) with the title VLC (hardware YUV DirectX output) instead of playing it on the assigned canvas.

I know there may be a problem with my coding, but:

1. Is there an obvious reason to get this result ? Should I check something ?

2. I'm thinking this may be because windows can not find and give libvlc the canvas with the given canvasId. Is there a way to tell media player not to play in  a separate window ? Like, "If you are not able to play in the desired canvas, just dont play the stream".  or "Continue trying to get the canvas you are given the link for"

3. Can I catch (realize) this result inside coding ? Like, with a return value, or in a state (like in MediaPlayerEventAdapter) Because when this happens, media player is in playing state like nothing is wrong. If my program can now there is a problem with canvas, I can close/open or do something to correct this.

I'm sorry that I can not create a working example, Code is scattered to multiple classes etc. So I tried to make a list of the lines responsible in my player creation process:

```
LibVlc libvlc = LibVlcFactory.factory().create();

libvlc_instance_t vlcInstance = LibVlcFactory.factory().synchronise().log().create().libvlc_new(1, new String[]{"--no-video-title"});
vlcInstance = libvlc.libvlc_new(parameterSize, args);

EmbeddedMediaPlayer mediaPlayer = new DefaultEmbeddedMediaPlayer(libvlc, vlcInstance);
Pointer ptr = Pointer.createConstant(Long.parseLong(remp.getCanvasId()))

libvlc.libvlc_media_player_set_hwnd(mediaPlayer.mediaPlayerInstance(), ptr);

vlcInstance.getMediaPlayer().prepareMedia(mediaLink, otherparameters);
vlcInstance.getMediaPlayer().play();
```

**Comment by caprica** [comment]
Why are you doing this?

> libvlc.libvlc_media_player_set_hwnd(mediaPlayer.mediaPlayerInstance(), ptr);

**Comment by nullpointer01** [comment]
Whole layout (panels for 4-9 player) are created in my main program.
But the players for each panel is created out of the main program with ProcessBuilder. (code you see in previous post is from this outer program)  

Therefore I put 4-9 EmbeddedMediaPlayerComponent in my main program.
These are used as playing locations for the outer video players.

I learn their component ids : 
`canvasId = String.valueOf(Native.getComponentID(mediaPlayerComponent.getVideoSurface()));`
(remp.getCanvasId() in the previous post contains this value)
Then I create a Pointer object with this value.

**Finally (the line you asked): I give this pointer to the libvlc instance, so it can know where (which panel) to play the video stream**

**Comment by caprica** [comment]
I know what the LibVLC API call does, I was trying to understand more why you were using it as what you're doing is not at all how vlcj was intended to be used.

The fact of the matter is that VLC will open up a video window if the native window handle you've passed via the API is "invalid" - invalid might mean more than one thing here, not "ready" or "realised" in some way, or there's some race condition of multi-threading issue, it's impossible to say specifically.

There is simply no way via the LibVLC API to "handle" or "catch" VLC deciding that that window handle is invalid.

**Comment by maxrave-dev** [comment]
Still have this issue in 2026, anyway to fix it sir @caprica ?

**Comment by cumhurkilic01** [comment]
> Still have this issue in 2026, anyway to fix it sir [@caprica](https://github.com/caprica) ?

Hello. 
Before we were able to solve this issue, I left that company. But afterwards, I heard that they solved this problem. I'm not %100 sure but:

Reason for this problem was like caprica suggested. Somehow sometimes video window was not valid or ready when we are giving its pointer to the libvlc. Some guy even said we were giving a null reference.

**Comment by caprica** [comment]
@maxrave-dev if you are using vlcj as intended, you should never see a problem like this, so it's not like this issue existed since 2017 to 2026 with no resolution.

I can only reiterate, if VLC is opening its own window, it means your Java UI is not "realised" yet, you must ensure that is it least packed if you have not made it visible yet, before you start playback.

So check that first, and if you're still seeing a problem, post a minimal code example that demonstrates the problem - either a single class here, or create your own github repo and I will see if I can take a look.
