### ISSUE TITLE
How to make the player automatically play 5 video files?

### ISSUE THREAD

**Issue by wroxman** [caprica/vlcj#583]
Hi!, my question is how to make the player automatically play 5 video files?
is there any examples??
Thanks in advance

**Comment by caprica** [comment]
That's a bit unclear what you're asking.

Do you mean a sequential playlist? Look in the vlcj test sources for MediaListPlayer examples.

**Comment by wroxman** [comment]
I need to do an ad player, let the player automatically play, do not need to manually operate。

I tried to use MediaListPlayer, but need to listen for finished events, etc., I feel EmbeddedMediaPlayerComponent better, is there other ways to achieve it?

this is my way,so bad
`			@Override
			public void finished(MediaPlayer mediaPlayer) {
				
				SwingUtilities.invokeLater(new Runnable() {
					@Override
					public void run() {
						playerComponent.requestFocus();
						try {
							Thread.sleep(300);
						} catch (InterruptedException e) {
							// TODO 自动生成的 catch 块
							e.printStackTrace();
						}
						
//						mediaPlayer.setPlaySubItems(true);
						robot.keyPress(KeyEvent.VK_F7);
						robot.keyRelease(KeyEvent.VK_F7);
						robot.delay(500);

						}
				});
	`

`	public void keyBordListner() {
		Toolkit.getDefaultToolkit().addAWTEventListener(new AWTEventListener() {
			@Override
			public void eventDispatched(AWTEvent event) {
				// TODO Auto-generated method stub
				if (((KeyEvent) event).getID() == KeyEvent.KEY_PRESSED) {//监听到事件后播放，同时存数据到播放列表
					switch (((KeyEvent) event).getKeyCode()) {
					case KeyEvent.VK_F7: {
//						playerComponent.getMediaPlayer().release();
						if(PlayerMain.playNum < (PlayerMain.listPlay.size()-1)) {
							PlayerMain.playNum++;
							System.out.println(PlayerMain.playNum);
						}
						else {
							PlayerMain.playNum = 0;
							System.out.println(PlayerMain.playNum);
							
						}
						playerComponent.getMediaPlayer().playMedia("video\\"+PlayerMain.listPlay.get(PlayerMain.playNum));
						//PlayerMain.sql.InsertPlayRecord(PlayerMain.list.get(PlayerMain.playNum));
					}
						break;
					}
				}
			}
		}, AWTEvent.KEY_EVENT_MASK);
	}
`

**Comment by caprica** [comment]
MediaListPlayer will play an entire playlist without you having to listen to events.

**Comment by wroxman** [comment]
OK，I need to record the result when the player finished

**Comment by caprica** [comment]
There is an event raised for when the end of the playlist is reached.

**Comment by wroxman** [comment]
thank you ！！
But when I play in full screen, the nextItem only can  catch the first event but can not catch afterwards
why？？
this is the code :
`	  public static void main(String[] args) throws Exception {
		  
	        MediaPlayerFactory mediaPlayerFactory = new MediaPlayerFactory();

	        Canvas canvas = new Canvas();
	        canvas.setBackground(Color.black);
	        CanvasVideoSurface videoSurface = mediaPlayerFactory.newVideoSurface(canvas);

	        EmbeddedMediaPlayer mediaPlayer = mediaPlayerFactory.newEmbeddedMediaPlayer();
	        mediaPlayer.setVideoSurface(videoSurface);

	        MediaListPlayer mediaListPlayer = mediaPlayerFactory.newMediaListPlayer();
	        
	        mediaListPlayer.addMediaListPlayerEventListener(new MediaListPlayerEventAdapter() {
	            @Override
	            public void nextItem(MediaListPlayer mediaListPlayer, libvlc_media_t item, String itemMrl) {
	                System.out.println("nextItem()"+item+" mmm" + itemMrl);
	            }
	        });

	        mediaListPlayer.setMediaPlayer(mediaPlayer); // <--- Important, associate the media player with the media list player

	        JPanel cp = new JPanel();
	        cp.setBackground(Color.black);
//	        cp.setBorder(new EmptyBorder(0, 0, 0, 0));
	        cp.setLayout(new BorderLayout(0,0));
	        cp.add(canvas, BorderLayout.CENTER);

	        JFrame f = new JFrame("vlcj embedded media list player test");
//	        f.setIconImage(new ImageIcon(TestMediaListEmbeddedPlayer.class.getResource("/icons/vlcj-logo.png")).getImage());
	        f.setContentPane(cp);
//	        f.setSize(800, 600);
	        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
	        f.setAlwaysOnTop(true);
	        f.setUndecorated(true);
//	        f.getGraphicsConfiguration().getDevice().setFullScreenWindow(f);
	        f.setVisible(true);

	        MediaList mediaList = mediaPlayerFactory.newMediaList();
	        String[] options = {};
	        mediaList.addMedia("/Wildlife.wmv", options);
	        mediaList.addMedia("/qcwy.wmv", options);
	        mediaList.addMedia("/pepsi.flv", options);


	        mediaListPlayer.setMediaList(mediaList);
	        mediaListPlayer.setMode(MediaListPlayerMode.LOOP);

	        mediaListPlayer.play();`

**Comment by wroxman** [comment]
annother way,when i use 
`f.setSize(800, 600);`
the nextItem is ok
but when i use
`f.setBounds(400, 300, 600, 400);` whithout other change,
the nextItem can only  catch the first event

**Comment by wroxman** [comment]
thank you for all .
i know the reason .
doing this :
`Thread.currentThread().join();`
