### ISSUE TITLE
Play many files sequentially

### ISSUE THREAD

**Issue by MS-Tech** [caprica/vlcj#584]
Hello,

i have a question regarding the playback of several files sequentially. I have a playlist (Java List) where I manage files. These files are played one after another. This will create a player, play the file and close the player again. The problem is that between closing the player and playing the next file, the player disappears and then reopens. But I would like that the player is permanently available and I can play each file in succession. Finally, it should be as if the many individual files are a large file with no break between each file. Can this be implemented?

Best regards

MS-Tech

**Comment by caprica** [comment]
You could use a MediaListPlayer.

There is no need for you to close a player and create it again, just re-use the same player.

Unfortunately you will probably not be able to achieve 100% seamless playback with no break between each file - using a MediaListPlayer here is probably the best you can get.

**Comment by MS-Tech** [comment]
Hello,

thank you for the support. 

I have just tested it in the VLC and played there a list of files. In the VLC i saw a seamless playback is possible. I will try to use one player and reuse it.

Best regards
MS-Tech

**Comment by caprica** [comment]
I think you must use a MediaListPlayer for this.

**Comment by MS-Tech** [comment]
Hello,

your solution was great. I can play files seamless, but i have another question. How can I exchange a complete list while the player is playing a file? I also want to jump seamlessly from list to list.

Best regards
MS-Tech

**Comment by caprica** [comment]
If you want seamless, you add them to the same list.

**Comment by MS-Tech** [comment]
Hello,

okay then I will try that. In my current programming I use the function finished from the MediaPlayerEventListener. But this listener does not exist in MediaListPlayer. How can I do that in MediaListPlayer?

Best regards
MS-Tech

**Comment by caprica** [comment]
You were asking about seamless playback. Just add everything to the same list. Why do you need to know if it finished or not?

As for potential alternative events to use, look at the API documentation.

I would also add, github issues are not a discussion forum, please don't mix up different questions in the same issue. Nevertheless to answer your tangential question, get the media player from the list player and call set time.
