### ISSUE TITLE
Can't get hardware acceleration / Vout to work at all?

### ISSUE THREAD

**Issue by Joannou1** [caprica/vlcj#586]
I've been trying to get VLCJ to play an RTMP stream for a little camera monitoring project.
The problem is that I've decided to limit myself to a tiny low-power device similar to a Raspberry Pi (Orange Pi Lite).

Installed Armbian on the device and got VLC 4.0.0-rc1 installed. (2.2.2 on mainline ppa doesn't play RTMP for some reason)
When I play the RTMP stream normally through VLC with video out set to "VDPAU output", it's butter smooth and the CPU usage is extremely low (~10%). 
Automatic / OpenGL results in 100% CPU usage and extremely choppy video output of around 1 frame per second.

I've tried the EmbeddedMediaPlayerComponent with launch options and DirectMediaPlayer with no luck. Hours and hours were spent trying all sorts of combinations of launch options and different implementations.
I even tried telling VLCJ / LibVLC to use the normal VLC config file (--no-ignore-config", "--config=/home/joan/.config/vlc/vlcrc") but it mostly ignored the config options and very little changed.

Tried display out stuff like: "--vout=vdpau_chroma" and "--vout=vdpau_display"

I can't figure this one out. Any idea how to get a VLCJ output that just plays video like normal VLC would, butter smooth with the vdpau stuff?

Infact, I don't think vout works at all. Setting vout to dummy/none/caca/ascii does absolutely nothing on both Embedded and Direct players.

Similar to #576 

Through VLCJ (1 FPS / 100% CPU):
[vlc-log.txt](https://github.com/caprica/vlcj/files/1594954/vlc-log.txt)
![screenshot](https://user-images.githubusercontent.com/997747/34458853-1dad3678-ed96-11e7-9a1c-831043c6b80d.png)

Through VLC (60 FPS / 10-15% CPU):
[vlc-log-direct.txt](https://github.com/caprica/vlcj/files/1594969/vlc-log-direct.txt)
![screenshot2](https://user-images.githubusercontent.com/997747/34458971-e508703c-ed98-11e7-87a8-bb2aa39d4d90.png)

**Comment by caprica** [comment]
Are you passing your video output options to a `MediaPlayerFactory` and using that factory to create your media player?

In any case, according to your CPU graph it looks like your JVM is consuming the CPU and you appear to have ten instances of your application running?!

**Comment by Joannou1** [comment]
I'm doing it this way:

```
        rotatingPlayer = new EmbeddedMediaPlayerComponent() {
            protected String[] onGetMediaPlayerFactoryArgs() {
                return new String[] {"--vout=vdpau_display"};
            }
        };
```

I tried the MediaPlayerFactory route, but it crashed the JVM each time VLC was opened. (Only on the linux device for some reason)

I can tell my method passes the args, when I specify --no-ignore-config and a config file, I get a log file output, which is because my normal VLC is configured to output a log.

As far as multiple instances, I'm guessing there's some sort of Multithreading going on?
I'm definitely only opening one instance.
If I stop the stream but leave the player open, the CPU returns to an idle level (with as many threads/instances open)

**Comment by caprica** [comment]
For things like setting vout, you need to use the `MediaPlayerFactory`. The fact that it crashed when you tried it is some other problem.

**Comment by caprica** [comment]
The other thing I would point out is this, you are using a low power device which usually does not go well with using a JVM. vlcj hosts an instance of a VLC media player, but it also has callbacks from the native code back into the JVM to notify your Java application of media player events, like time-changed, position-changed and so on.

You can get a LOT of those events, meaning that VLC is near constantly triggering callbacks from native code to the JVM. This will have a CPU cost which is negligible on powerful desktop devices, but may be simply too much for your low power device.

You can maybe try the media player enableEvents API (search the Javadoc for this) to disable all the events and see if it helps.

**Comment by Joannou1** [comment]
Appreciate the info!

I used a stripped down version of the TestPlayer code, (https://github.com/caprica/vlcj/blob/master/src/test/java/uk/co/caprica/vlcj/test/basic/TestPlayer.java), which uses `MediaPlayerFactory`, but had no luck.

Made sure to use the vlcArgs list, but vout still doesn't seem to want to work.
A quick and easy way to check if it works is to set vout to caca (for ascii art)
`vlcArgs.add("--vout=caca");`

Also tried the enableEvents thing, I believe this is the right way, but it may not be.
`mediaPlayer.enableEvents(MediaPlayerEventType.NONE.value());`

However, CPU usage is still near 100%.
