### ISSUE TITLE
Issues with Logo Overlay

### ISSUE THREAD

**Issue by JohanJarvi** [caprica/vlcj#588]
I'm not sure what the issue is, no error messages, no stacktrace, just no logo. I followed the tutorial to what I'm thinking is an adequate standard. Here's my code:		
                
            frame.setContentPane(contentPane);
        	frame.setVisible(true);

		String[] options = { ":network-caching=100 :clock-jitter=0 :clock-synchro=0" };
		
		Logo logo = Logo.logo()
				.file("ControllerGreen.png")
				.position(libvlc_logo_position_e.top_left)
				.opacity(1.0f)
				.enable();
		mediaPlayerComponent.getMediaPlayer().setLogo(logo);
		mediaPlayerComponent.getMediaPlayer().playMedia("rtsp:/"IPADDRESS"/h264", options);

Can you see why the logo wouldn't work here?

**Comment by caprica** [comment]
Check if the logo works in the vlcj-player application and compare what you did differently.

Logo has been finnicky in the past, in that it required you to enable certain video filters to make it work properly. But the last time I checked vlcj-player with a contemporary VLC version, it worked just fine.

**Comment by caprica** [comment]
A side note: your options string is wrong I think.

The API requires an array of options, not a string delimited by space characters.

```
String[] options = {
    ":network-caching=100",
    ":clock-jitter=0",
    ":clock-synchro=0" 
};
```

**Comment by JohanJarvi** [comment]
Thanks I'll check that, and the options string appears to work the way it is I believe, but I can change it so thanks for that as well.
