### ISSUE TITLE
Volume setting incorrect when starting new media

### ISSUE THREAD

**Issue by hjohn** [caprica/vlcj#59]
I'm basically playing a Media, and reduce the volume to say 50%.  I then stop playing, and I play a new Media.  The volume is now set to full, however mediaPlayer.getVolume() still reports 50.

Only when I change the volume again is the volume changed to the correct level.

It does not help to add a mediaOption like this to the playMedia call either:

"volume=" + (512 \* mediaPlayer.getVolume() / 100)

Setting the volume explicitely after a playMedia call, or even a prepareMedia/play combination has no effect -- it really needs to be set a few milliseconds later apparently for it to work.

**Comment by Joe-Schmo** [comment]
I am using vlcj4.2 (with JavaFX) and I am having issues setting the volume.  In an earlier comment you said "mediaPlayer.startMedia() instead - this call blocks until the media player receives a playing or error event callback; "
I think that call is now MediaAPI start(String mrl).  But this doesn't work.  Should it?  Should I be able to set the volume after calling that method?
