### ISSUE TITLE
Video stutter & lag

### ISSUE THREAD

**Issue by cassiohoffmann** [caprica/vlcj#592]
Hello friends!

I am playing a video using EmbeddedMediaPlayerComponent on a netbook with windows7
observed in the following link when using via vlcj happens some locked with the course of the reproduction and sometimes the screen is squared
is this some kind of bug or is there any action or parameter that can be passed ap vlc to minimize this problem?

link to demonstrate:

https://youtu.be/1Dyl0BN1t78

sample code:

public class BasicEmbeddedMediaPlayerComponentTest {
    public static void main(String[] args) {
        new NativeDiscovery().discover();

        final String mrl = args[0];
        new BasicEmbeddedMediaPlayerComponentTest(mrl);
    }

    private BasicEmbeddedMediaPlayerComponentTest(String mrl) {
        JFrame frame = new JFrame();
        frame.setLocation(100, 100);
        frame.setSize(720, 480);
        frame.setLayout(null);

        final JPanel jPanel = new JPanel();
        jPanel.setVisible(true);
        jPanel.setBounds(0, 0, 720, 480);
        jPanel.setLayout(new BorderLayout());

        java.util.List<String>  vlcArgs = new ArrayList<>();
        vlcArgs.add("--no-plugins-cache");
        vlcArgs.add("--no-video-title-show");
        vlcArgs.add("--quiet-synchro");
        vlcArgs.add("--file-caching=1000");

        Canvas videoSurface = new Canvas();
        EmbeddedMediaPlayer mediaPlayer = createPlayer(vlcArgs, videoSurface);

        jPanel.add(videoSurface);
        frame.add(jPanel);

        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);

        new Thread(new Runnable() {
            @Override
            public void run() {
                mediaPlayer.playMedia(mrl);
            }
        }).start();
    }

    private EmbeddedMediaPlayer createPlayer(final java.util.List<String> vlcArgs, final Canvas videoSurface) {
        EmbeddedMediaPlayerComponent mediaPlayerComponent = new EmbeddedMediaPlayerComponent();
        EmbeddedMediaPlayer embeddedMediaPlayer = mediaPlayerComponent.getMediaPlayer();
        MediaPlayerFactory mediaPlayerFactory = new MediaPlayerFactory(vlcArgs.toArray(new String[vlcArgs.size()]));
        mediaPlayerFactory.setUserAgent("vlcj test player");
        embeddedMediaPlayer.setVideoSurface(mediaPlayerFactory.newVideoSurface(videoSurface));
        embeddedMediaPlayer.setPlaySubItems(true);
        return embeddedMediaPlayer;
    }
}

**Comment by caprica** [comment]
As far as I can tell, the problem exhibited in your video relates to your OS and is nothing that can be "fixed" in application code.

**Comment by caprica** [comment]
As an aside, your vlcj code is not optimal. The idea using EmbeddedMediaPlayerComponent is that you simply add the component to your frame/layout and let it manage its own video surface.

So in your case:

```
    jPanel.add(mediaPlayer)
```

...is all you need. You don't need to create your own Canvas.

**Comment by cassiohoffmann** [comment]
a question of having used the canvas was to pass access to the MediaPlayerFactory to pass parameters.
Is there any parameter to be used for minimizing? some type of buffering before reproducing, something that can improve?

**Comment by caprica** [comment]
How you are using the factory in createPlayer is wrong.

When you create a new EmbeddedMediaPlayerComponent with the default constructor, like you are doing, it is using it's OWN MediaPlayerFactory, not the one you create later to create the video surface.

You need to look at the Javadoc for EmbeddedMediaPlayerComponent and decide whether you want to use a different constructor that takes a factory parameter, or instead you override the method that provides the factory arguments.

For the main problem you are having, there may well be parameters you can set or there may not, but they would be outside the scope of vlcj and I don't know what they might be.

**Comment by caprica** [comment]
To find out all of the available options, usually you can do this from a command-prompt/shell:

```
vlc -h
```

**Comment by cassiohoffmann** [comment]
thanks for your return. Suggest an advanced translation for the method to force some parameters for testing.
I realized that pure vlc is normal. only when using it via vlcj which presents
these squares and gray checkered canvases. only for that reason I opened the question here to know if with your experiment already had seen something seemed.

**Comment by cassiohoffmann** [comment]
Another strange thing is the question that you raised about the way I passed the parameters. If I do something wrong, the palication does not go up. so I assumed I would be sending the parameters correctly.

**Comment by caprica** [comment]
Go check the source code for EmbeddedMediaPlayerComponent. It will be clear that your factory, and therefore your parameters, are not being used.
