### ISSUE TITLE
Can't load vlcj

### ISSUE THREAD

**Issue by nvkaymanov** [caprica/vlcj#599]
NativeLibrary.addSearchPath(RuntimeUtil.getLibVlcLibraryName(), "/Applications/VLC.app/Contents/MacOS/lib");

            Native.loadLibrary(RuntimeUtil.getLibVlcLibraryName(), LibVlc.class);

            LibC.INSTANCE._putenv("VLC_PLUGIN_PATH=" + "/Applications/VLC.app/Contents/MacOS/plugins/");`

Ger errors:

Caused by: java.lang.UnsatisfiedLinkError: dlopen(/Users/ae/Desktop/vplayer/out/production/vplayer/libvlc.dylib, 9): Library not loaded: @rpath/libvlccore.dylib
  Referenced from: /Users/ae/Desktop/vplayer/out/production/vplayer/libvlc.dylib
  Reason: image not found

**Comment by caprica** [comment]
You should search existing issues https://github.com/caprica/vlcj/search?q=dylib&type=Issues

And, although the code you posted is similar to that used by vlcj, that code is actually entirely JNA and standard Java, not vlcj at all.

I'm going to close this issue as there is nothing new that can be said on it, that has not already been said on the other related issues.

**Comment by valnaumov** [comment]
@nvkaymanov which VLC version are you using? I used 3.0.1 and got the same error. Downgraded to 2.2.8, and all went fine.

**Comment by caprica** [comment]
For anyone coming across this issue, please see #643, you do NOT need to do anything with rpath, otool or any other such nasty workaround. If you use the latest vlcj this issue should be gone.
