### ISSUE TITLE
Content bit rate using vlcj playing rtsp stream

### ISSUE THREAD

**Issue by rcarele** [caprica/vlcj#600]
Hi,
I have a java application playing rtsp stream using vlcj 2.4.1. 
I have 2 questions:

- How  can I get statistics media information **CONTENT BIT RATE** using vlcj?
![image](https://user-images.githubusercontent.com/20105253/37662465-62579df4-2c57-11e8-93ae-ecde01bca144.png)
-Why are readBytes (mediaPlayer.getMediaPlayer().getMediaStatics().i_read_bytes)  always 0?
The code I'm using is this:
```
package streamplayer;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import sun.awt.EmbeddedFrame;
import uk.co.caprica.vlcj.component.EmbeddedMediaPlayerComponent;


public class StreamPlayer {

    /**
     * @param args the command line arguments
     */
    private final JFrame frame;
    private final EmbeddedMediaPlayerComponent mediaPlayerComponent;
    private float lostFrames=0;
    private float i_lost_pictures;
    public static void main(String[] args) {
        // TODO code application logic here
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
               new StreamPlayer();
            }
        });
    }
    public StreamPlayer(){
        frame =new JFrame("Test Media Player");
        frame.setBounds(100, 100, 600, 400);
        mediaPlayerComponent = new EmbeddedMediaPlayerComponent();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setContentPane(mediaPlayerComponent);
        frame.setVisible(true);
        mediaPlayerComponent.getMediaPlayer().playMedia("rtsp://admin:admin@xxxxxxxx/cam/realmonitor?channel=1&subtype=0");
        while(true){
            float readBytes=mediaPlayerComponent.getMediaPlayer().getMediaStatistics().i_read_bytes;
            System.err.println("Read bytes: "+readBytes);
            
        }
    }
    
}



```

**Comment by caprica** [comment]
Some stats only get delivered through the API for some media types.

What VLC has access to is not necessarily the same as what is made available through LibVLC.

I am pretty sure I've seen that read_bytes field populated before, but I can not remember what the media type was, it may have been a local file.

**Comment by caprica** [comment]
By the way, I appreciate that your code is likely just test code, but your tight loop polling the stats is a really bad idea. At least sleep 50 ms or something.
