### ISSUE TITLE
hardware acceleration with vlcj

### ISSUE THREAD

**Issue by sjaiswal25** [caprica/vlcj#604]
embedded media player component automatically takes gpu into account while displaying but same is not the case with direct media player component. Is there any way to integrate hardware acceleration with direct media player component.

Regards

**Comment by sjaiswal25** [comment]
Thank you

**Comment by iyyapparajm** [comment]
i am trying to enable the hardware accelration programatically in java. kindly help me on doing this. i am using direct media player.

**Comment by caprica** [comment]
What do you mean? Rendering? Decoding?

Rendering: Use an OpenGL texture, VolatileImage, whatever else you can think of.
Decoding: VLC 3.x uses hardware decoding by default

**Comment by iyyapparajm** [comment]
Thanks for your reply

How to get the logs of hardware acceleration in VLCJ embedded media player. Is there any documentations available for that?

**Comment by caprica** [comment]
Create a MediaPlayerFactory with "-vv" as arguments, create the media player from that factory, run your code.

It is VLC logs that you are looking at.

In my case I would see messages about VDPAU being used since I have an nVidia GPU.

**Comment by iyyapparajm** [comment]
thanks a lot for your reply. 

how to use the Embedded media player without installing VLC player on windows?. kindly consider the 32 bit and 64bit versions compatibility.
