### ISSUE TITLE
Cpu usage

### ISSUE THREAD

**Issue by sanitsingh** [caprica/vlcj#605]
10 instance of EmbeddedMediaPlayerComponent using13-15% cpu for playing rtsp stream,
while 16 instance consuming 45-53% cpu.
Is any way to optimize it.

**Comment by caprica** [comment]
No.

You want 16 media players in the same app?! Invest in CPU and GPU I suppose!

**Comment by sanitsingh** [comment]
How about using vlcj pro ? Is it going to help us in any way ?

**Comment by caprica** [comment]
vlcj pro is more about isolation and robustness, it can not magically give you more hardware resources.

You have to be realistic about your goals, playing 16 streams concurrently on the same PC is hardware intensive.

You may be able to reduce some CPU load by disabling the vlcj media player events that you're not interested in, but this will give you marginal benefit only I think.

**Comment by caprica** [comment]
With vlcj pro, I have played 12+, 16+ videos concurrently in a test project, so it is possible. But I can not remember the CPU load.

vlcj pro has a free trial and a demo project that you could try.
