### ISSUE TITLE
RTSP vlc unable to open MRL

### ISSUE THREAD

**Issue by hypothermic** [caprica/vlcj#606]
I'm getting an error when connecting to my IP camera, similar to #362.
I'm using the _AnimationTimerJavaFXDirectRenderingTest.java_ sample from one of your repo's. (long name btw!)

```java
String addr = "rtsp://192.168.0.203:65534/videoMain";
mediaPlayerComponent.getMediaPlayer().playMedia(addr, new String[] {"--sout-rtsp-user=xx", "--sout-rtsp-pwd=xx"});
```
returns the following error:
```
Created new TCP socket 38 for connection
[00007fc1f0001068] live555 demux error: Failed to connect with rtsp://192.168.0.203:65534/videoMain
[00007fc22c389628] core input error: open of `rtsp://192.168.0.203:65534/videoMain' failed
[00007fc22c389628] core input error: Your input can't be opened
[00007fc22c389628] core input error: VLC is unable to open the MRL 'rtsp://192.168.0.203:65534/videoMain'. Check the log for details.
```
The error indicates that there are connection issues, however I can confirm that the camera works fine, because `vlc rtsp://192.168.0.203:65534/videoMain --rtsp-user=xx --rtsp-pwd=xx` successfully connects to the camera and loads the stream. Any idea what might cause it?

OS: Ubuntu 17.10

**Comment by caprica** [comment]
IIRC instead of passing the username/password when you invoke mediaPlayer.playMedia() you must instead pass the username/password as arguments for the MediaPlayerFactory, from which you create the media player.

This is just how LibVLC works, I think, in that the credentials are associated with the LibVLC instance rather than the native media player instance.

**Comment by hypothermic** [comment]
No success with passing the params into the MediaPlayerFactory. Here's the full error log I've generated with `-vvv`: https://gist.github.com/hypothermic/7ccf665b143fcf9e14f7b0155ee5962f. 
From what I can see, it seems that authentication went wrong. This is strange, because I'm using the exact same user/pass combo as on the command line. Do you notice anything that could be wrong in the log?

**Comment by caprica** [comment]
Also, it was you stripped the username from this?
```
Authorization: Digest username="", realm="xxxx", nonce="e7e5a182e8f45f2e31734dc177c31c60", uri="rtsp://192.168.0.203:65534/videoMain", response="59dd9c90f72298ac6da35459252a68f3"
```

**Comment by hypothermic** [comment]
Unfortunately I could not resolve the issue. Downgrading VLC is not an option either, since the application has to be cross-compatible, and my university uses VLC3.0. Thank you for your effort and good luck with the project.
