### ISSUE TITLE
Audio recording

### ISSUE THREAD

**Issue by preetamsikdar** [caprica/vlcj#608]
Is it possible to add audio from microphone in the video.Can you please provide some support in it. As video is working fine ...

**Comment by caprica** [comment]
It can work, you have to add an "input slave". Currently this can only be done using command-line switches, so that means passing them via the media player factory, or maybe as options when you invoke playMedia on the media player.

I don't have a specific example unfortunately.

**Comment by preetamsikdar** [comment]
package com.exprimentalqa.screenrecorder;

import java.io.File;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.sun.jna.NativeLibrary;

import uk.co.caprica.vlcj.player.MediaPlayer;
import uk.co.caprica.vlcj.player.MediaPlayerFactory;
import uk.co.caprica.vlcj.runtime.RuntimeUtil;

public class ScreenRecorder  {
	private final Logger logger =  LoggerFactory.getLogger(ScreenRecorder.class);
	private static final String[] OPTIONS = {
			"--quiet",
			"--quiet-synchro",
			"--intf",
			"dummy",
			"input slave"
	};

	private static final String RECORDINGFORMAT = ".mp4";
	private static final String SOUT    = ":sout=#transcode{vcodec=h264,vb=%d,scale=%f}:duplicate{dst=file{dst=%s}}";
	private static final String MRL     = "screen://";
	private static final String FPS     = ":screen-fps=%d";
	private static final String CACHING = ":screen-caching=%d";

	private static final int    fps     = 20;
	private static final int    caching = 500;
	private static final int    bits    = 1024;
	private static final float  scale   = 0.5f;

	private final MediaPlayerFactory mediaPlayerFactory;
	private final MediaPlayer mediaPlayer;

	public ScreenRecorder() {
		NativeLibrary.addSearchPath(RuntimeUtil.getLibVlcLibraryName(), System.getProperty("user.dir")+"/lib");
		System.setProperty("VLC_PLUGIN_PATH",  System.getProperty("user.dir")+"/lib/plugins");
		mediaPlayerFactory = new MediaPlayerFactory(OPTIONS);
		mediaPlayer = mediaPlayerFactory.newHeadlessMediaPlayer();
	}

	public static void main(String[] args) {
		ScreenRecorder scr = new ScreenRecorder();
		scr.startRecording("test");
		// wait for 10 sec to test
		try {
			Thread.sleep(10000);
		} catch (Exception e) {
			scr.logger.error("wait failed", e);
		}
		scr.stopRecording();
	}

	public void startRecording(String testName) {
		String mp4FileName = getFile(testName);
		logger.info("start recording, "+ mp4FileName);
		mediaPlayer.playMedia(MRL, getMediaOptions(mp4FileName));
		
	}

	public void stopRecording() {
		logger.info("stop recording ");
		mediaPlayer.stop();
	}
	
	public void releaseRecordingResources() {
		mediaPlayer.release();
		mediaPlayerFactory.release();
	}

	private String getFile(String testName) {
		File dir = new File(System.getProperty("user.dir"), "mp4Result");
		dir.mkdirs();
		DateFormat df = new SimpleDateFormat("yyyyMMdd-HHmmss");
		return dir.getAbsolutePath() + "/" + testName + "-" + df.format(new Date()) + RECORDINGFORMAT;
	}
	
	private String[] getMediaOptions(String destination) {
		return new String[] {
				String.format(SOUT, bits, scale, destination),
				String.format(FPS, fps),
				String.format(CACHING, caching)
		};
	}
}


//With this I am able to record video but need to add options so that we can record audio along with the video

**Comment by caprica** [comment]
Search for "VLC input slave microphone" or something. I am sorry but I do not know the specific options. Once you find the options, then you can add them via the factory or the media player like I mentioned above.
