### ISSUE TITLE
How can I get snapshot with vlcj while I'm getting video from encoder with RTP?

### ISSUE THREAD

**Issue by benttu** [caprica/vlcj#609]
I'm getting video from encoder with RTP using vlcj and I'm recording this video file into the my directory. However I need get snapshot at specific time intervals. I searched about this topic, I found some information but these are not working.

issue #261 answer not satisfactory for me because my sout options include "duplicate" like this;

String[] options = {:duplicate{dst = file{dst =" + fileName + "},dst=display}};
I record video flewlessly, but I don't get snapshot. I'm waiting for your help. Thanks.

**Comment by caprica** [comment]
I don;t know. It looks exactly like the problem described in #261 which unfortunately has no solution.

**Comment by benttu** [comment]
I use these codes. Maybe you can help me with these codes.
```
MediaPlayerFactory mediaPlayerFactory = new MediaPlayerFactory();
EmbeddedMediaPlayer mediaPlayer = factory.newEmbeddedMediaPlayer();
File dir = new File("C:\\testCam");
dir.mkdirs();
DateFormat df = new SimpleDateFormat("ddMMyyyy-HHmmss");
String fileName = dir.getAbsolutePath() + "Record - " + df.format(new Date()) + ".mpg";
String[] options = {":sout=#transcode{vcodec=mp2v,vb=1024,acodec=mpga,ab=128,channels=2,samplerate=48000}:duplicate{dst=file{dst=" + fileName + "},dst=display}", ":input-slave=alsa://hw:0,0"}; 
mediaPlayer.startMedia("rtp://@10.0.0.100:10000",options);
File file = new File("C:\\testCam\\snapshot-test.png")
mediaPlayer.saveSnapshot(file);
System.out.println(mediaPlayer.getSnapshot()); // return null
```
I'm getting video flewlessly. However getSnapshot methot returns null everytime. I need snapshot. Is there any suggestion about snapshot.

**Comment by benttu** [comment]
I tried some methods for this problem and I got a result. However, I have a new problem.

```
MediaPlayerFactory mediaPlayerFactory = new MediaPlayerFactory();
HeadlessMediaPlayer mediaPlayer = mediaPlayerFactory.newHeadlessMediaPlayer();
mediaPlayer.prepareMedia("rtp://@10.0.0.100:10000");
mediaPlayer.play();
try{
     Thread.sleep(4000);
} catch(InterruptedException e) {
     e.printStackTrace();
}

BufferedImage img = mediaPlayer.getSnapshot();
File file = new File("C:\\testCam\\snapshot-test.png");
try{
     ImageIO.write(img,"png",file);
} catch(InterruptedException e) {
     e.printStackTrace();
}
```
This code is working but while I run this code, new frame are openning on the screen which title is "VLC(Direct3D9 output)". How can I prevent this frame? Actually, I don't want to see anything on the screen. I only want to save snapshot.

**Comment by benttu** [comment]
I add VLC_ARGS into the MediaPlayerFactory like this;

```
String[] VLC_ARGS = {"--vout","dummy"};
MediaPlayerFactory mediaPlayerFactory = new MediaPlayerFactory(VLC_ARGS);
```

and then I'm preventing Direct3D9 frame but I have new problems.
```
[000000005b9b7320] mpeg4audio packetizer: AAC channels: 2 samplerate: 48000
[000000005b962f50] d3d11va generic error: D3D11CreateDevice failed. (hr = 0x80004001)
[000000005b9c1200] avcodec decoder: Using DXVA2 (NVIDIA GeForce GTX 1050, vendor NVIDIA, device 7231, revision 160) for hardware decoding
[000000005ba4e8c0] main filter error: option chain-level does not exist
[000000005bb4b830] chain filter error: Too high level of recursion (3)
...
```
I think, this problems occur because of options. Can I help me?

**Comment by caprica** [comment]
This is not a discussion forum. If you fixed your initial issue it would be awesome if you would post the resolution here, and then open a fresh issue for your new problem.
