### ISSUE TITLE
Example using HeadlessMediaPlayer with callback 

### ISSUE THREAD

**Issue by noahf19** [caprica/vlcj#613]
I'm looking for a code example similar to the well-known DirectMediaPlayer example with callbacks so I can access and manipulate frame images in a headless client reading data off an rtsp source. Can you please point me in the right direction?

**Comment by caprica** [comment]
I really don't know what more you're asking for than is already demonstrated by the DirectMediaPlayer example.

Either that or I don't really understand what you're asking for.

Perhaps you could clarify.

**Comment by caprica** [comment]
HeadlessMediaPlayer is just a MediaPlayer with no API relevant to actually displaying the video in an embedded control.

**Comment by noahf19** [comment]
I was able to modify the Direct Media Player example to do what I want. My concern is whether the example will still work when I run it on a server that does not have X windows.

**Comment by caprica** [comment]
Well, you won't know until you try I guess. There's no other code example available related to that.
