### ISSUE TITLE
Version can't parse Java version 10 in Linux

### ISSUE THREAD

**Issue by smay4finger** [caprica/vlcj#615]
When MediaPlayerFactory is instanciated in Linux with a Java version >= 10 it will fail with a parse error in Version.

```
Caused by: java.lang.IllegalArgumentException: Can't parse version from '10'
	at uk.co.caprica.vlcj.version.Version.<init>(Version.java:85)
	at uk.co.caprica.vlcj.player.MediaPlayerFactory.<clinit>(MediaPlayerFactory.java:144)
```

In Java 10 the version information in system property "java.version" is not 1.10.0 anymore, but just 10.

**Comment by caprica** [comment]
Why do Oracle developers do such things... srsly... :-(

**Comment by caprica** [comment]
Ugly temporary fix at cb99774ad6f2040d77fd96251529e4abff879f9b

**Comment by caprica** [comment]
Fix will be included as part of the next release.

**Comment by smay4finger** [comment]
Your ugly temporary fix should change the "10" to something like "1.10.0", which is closer to the old version number style. I suggest the following:

```java
private static String getJavaVersion() {
    String result = System.getProperty("java.version");
    if (!result.contains(".")) {
        // I know, it's not great, but change e.g. "10" to "10.0.0"
        result = "1." + result + ".0"
    }
    return result;
}
```

But anyway, thanks for the ugly fix.
