### ISSUE TITLE
After updating to the 64-bit version of 3.0.3 the mute() does nothing.

### ISSUE THREAD

**Issue by lordarnoud** [caprica/vlcj#617]
I have used your library for a very long time now with no problems so far, but this new update seems to be messing things up :( I use the library to play 2-3 videos at the same time, and then I mute all videos except for the first one. This has worked for as long as I can remember, but with the new version this doesn't work? The mute() function does not crash and still returns "true", except that it doesn't actually mute the video.

**Comment by caprica** [comment]
The new version of VLC you mean? Well then, I suspect that's where the problem lies.

But let's be clear first, you mean mute is not working _at all_ for any of your 3 videos, or it only works on one of them, or what?

**Comment by lordarnoud** [comment]
That was fast! Well I do think that's where the problem lies, mute still works if I try it in VLC itself.
The mute function does not work for ANY video that I try it on. BEFORE it worked on the selected videos while other videos kept their audio. AFTER all videos keep their audio and none of them get muted :(

**Comment by caprica** [comment]
Keep a look out for VLC 3.0.4 and hope for a fix I suppose!

**Comment by lordarnoud** [comment]
Will do, fingers crossed!

**Comment by caprica** [comment]
Similar to #611 I suppose

**Comment by lordarnoud** [comment]
Thanks for the update :) Will patiently wait for a real fix or the VLC fix, we're managing atm ^^  Thanks!

**Comment by caprica** [comment]
I just tested this with VLC 3.0.4 and it is working (at least on Linux).
