### ISSUE TITLE
I still have problems creating a project with vlc 3.0.x (UnsatifiedLinkError libvvlc.dylib).

### ISSUE THREAD

**Issue by HagiBlickle** [caprica/vlcj#619]
I use:
 vlci 3.10.1
Jna 4.5.2
vlc 3.0.3
Mac OS 10.11.6

I have read the article #602 etc., but nothing leads to the goal. 

NativeLibrary.addSearchPath(RuntimeUtil.getLibVlcLibraryName(), "/Applications/VLC.app/Contents/MacOS/lib/");
does not help and is used by NativeDiscovery.discover() anyway!

Is there a guide to the error UnsatisfiedLinkError: Unable to load library 'vlc'... can be avoided?
At the moment I only have the possibility to install VLC 2.2.8.

Thanks in advance.

**Comment by caprica** [comment]
The sum total of what is currently known about this problem is in #602. Creating another issue is not going to provide any more answers I'm afraid.

**Comment by valnaumov** [comment]
@HagiBlickle you have to patch the dylib file.

**Comment by caprica** [comment]
Everything known about this problem is in #602.

**Comment by caprica** [comment]
Maybe see #643, this might be fixed for you in the next version of vlcj (if it's the same problem).
