### ISSUE TITLE
An error when trying to open a video file on 32 bit Ubuntu

### ISSUE THREAD

**Issue by ghost** [caprica/vlcj#62]
Hello, my name is Lee, studying Computer Science in South Korea and trying to use vlcj project for some reason.
After conducting many tests and searching Google hours, I figured out this problem has never happened to others.
I need to run vlcj in both Windows and Ubuntu.
I have no problem running it in Windows while in Ubuntu it always terminates with a SIGSEGV error.
The exact moment programs terminate is right after I open a video file with a provided example, TestPlayer(in package uk.co.caprica.vlcj.test.basic)
(Of course, the TestPlayer with the video file worked completely fine in Windows)
I've tried to run the TestPlayer in both command-line and eclipse with as many combination of the following Ubuntu, vlc, and vlcj versions as possible.
I even tried some on my friend's laptop and ended up in the same situation.

Details of my tests and a log file are as in the following
OS  Ubuntu 10.04 (Linux 2.6.32-21-generic) in VMWare
    Ubuntu 12.04 (linux 3.2.0-23-generic-pae) in VMWare and in direct installation
JDK 1.7.0_05
Eclipse Juno 20120614-1722
Path to the
vlc libraries   /home/prosopher/vlc/lib (I gave it when I typed configure command)
vlc version 1.1.10 / 2.0.2 (I mannually installed these in the above path)
vlcj version    1.1.5 / 1.2.2 / 2.1.0

I tried every combination of the above Ubuntu, vlc, and vlcs versions.
In command-line I typed the following line.
java –jar –Djna.library.path=”/home/prosopher/vlc/lib” vlcj-1.1.5-test.jar
In eclipse I gave the VM arguments –Djna.library.path.

Let me know if you need more information or don’t understand anything in my writing.
Sincerely,

**Comment by caprica** [comment]
Seems related: http://stackoverflow.com/questions/13821854/strange-crashes-while-calling-jni-code-on-linux-am-i-compiling-my-shared-librar

**Comment by caprica** [comment]
This also seems similar: https://bugs.launchpad.net/ubuntu/+source/firefox/+bug/810214

**Comment by caprica** [comment]
After more research I still don't see a way forward on this issue.

If the _IO_STDIN_USED export is the right track, which can not be confirmed, then it implies something like a mismatch between versions of libc/glibc and/or libio somewhere. But diving deeper into this is way outside the scope of this project.
