### ISSUE TITLE
Unable to Automatically play a track after current track is Finished

### ISSUE THREAD

**Issue by JoshuaD84** [caprica/vlcj#620]
I am writing an audio player that uses VLCJ to handle audio output. 

I am able to get audio to play, and I am able to jump to a different track while the current track is playing (using `next()` in the example below).

However, if I call `next()` after the current track finishes. It will load the track, but the track won't make any noise.

If I manually skip to another track (again, using `next()`) after that, it works. 

Here is a minimum working example:
	
```

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;

import com.sun.jna.NativeLibrary;

import uk.co.caprica.vlcj.component.AudioMediaPlayerComponent;
import uk.co.caprica.vlcj.player.MediaPlayer;
import uk.co.caprica.vlcj.player.MediaPlayerEventAdapter;
import uk.co.caprica.vlcj.runtime.RuntimeUtil;

public class VLCJFinishedBug {

	String[] trackList = new String[] {
		"D:\\test\\1.mp3",
		"D:\\test\\2.mp3",
		"D:\\test\\3.mp3",
		"D:\\test\\4.mp3",
		"D:\\test\\5.mp3",
		"D:\\test\\6.mp3",
		"D:\\test\\7.mp3",
		"D:\\test\\8.mp3",
		"D:\\test\\9.mp3",
	};
	
	int trackIndex = 0;
	
	private AudioMediaPlayerComponent vlcComponent;
	private MediaPlayer mediaPlayer;
	private static final String NATIVE_LIBRARY_SEARCH_PATH = "stage\\lib\\vlc";
	
	public VLCJFinishedBug( ) {
		NativeLibrary.addSearchPath( RuntimeUtil.getLibVlcLibraryName(), NATIVE_LIBRARY_SEARCH_PATH );
		vlcComponent = new AudioMediaPlayerComponent();
		mediaPlayer = vlcComponent.getMediaPlayer();
		
		mediaPlayer.addMediaPlayerEventListener(new MediaPlayerEventAdapter() {
			public void finished ( MediaPlayer player ) {
				next();
			}
		});
	}
	
	private void playTrack( String trackLocation ) {
		System.out.println ( "Playing track: " + trackLocation );
		mediaPlayer.playMedia( trackLocation );
	}
	
	private String nextTrackString() {
		trackIndex++;
		if ( trackIndex >= trackList.length ) {
			System.out.println( "Reach end of track list." );
			System.exit( 0 );
		}

		return ( trackList [ trackIndex ] );
	}
	
	public void start() {
		trackIndex = 0;
		playTrack ( trackList[ 0 ] );
	}
	
	public void next() {
		playTrack ( nextTrackString() );
	}
	
	public void goToNearEnd() {
		mediaPlayer.setPosition( .98f );
	}
	
	public static void main ( String[] args ) {
		VLCJFinishedBug player = new VLCJFinishedBug();
		
		JButton start = new JButton ( "Start" );
		start.addActionListener( e -> player.start() );
		
		JButton next = new JButton ( "Next" );
		next.addActionListener( e -> player.next() );
		
		JButton goToNearEnd = new JButton ( "Go To Near End" );
		goToNearEnd.addActionListener( e -> player.goToNearEnd() );
		
		JPanel content = new JPanel();
		content.add( start );
		content.add( next );
		content.add( goToNearEnd );
		
		JFrame frame = new JFrame( "VLC Play Test" );
		frame.setDefaultCloseOperation( JFrame.EXIT_ON_CLOSE );
		frame.setContentPane( content );
		frame.pack();
		frame.setVisible( true );
	}
}
```

I am on Windows 7 using:

jna-3.5.2.jar
platform-3.5.2.jar
slf4j-api-1.7.10.jar
vlcj-3.10.1.jar

VLC DLLs from VLC Version 3.0.3 Vetinari

**Comment by caprica** [comment]
This may be because you are calling next() from the VLC callback thread - generally it is not allowed to call back into LibVLC from that callback thread. You may try scheduling a task to run later (so it's on a different thread) to invoke your next() method. It may even be enough to use SwingUtilities here, I'm not 100% sure.

The real issue here is that if you want to use play-lists, you are supposed to use a MediaListPlayer.

**Comment by JoshuaD84** [comment]
I was able to confirm that. But can be closed, it was my ignorance about how to use the library, not the library's fault.

**Comment by caprica** [comment]
Well, it's not always obvious so it's easy to get tripped up.

There is a general rule with LibVLC that you must not callback into LibVLC from an event callback thread. A lot of complications and unexpected behaviours follow from that simple assertion.

Did you try SwingUtilities.invokeLater(...)? I expect that would be enough.

Or really, as I stated in an earlier comment, consider using a MediaList.

**Comment by caprica** [comment]
If you don't want a pause, use a MediaList. There is nothing else you can do.

**Comment by JoshuaD84** [comment]
That's very helpful to know, thank you. 

Am I able to append to the media list during finished()?
