### ISSUE TITLE
Cannot Load VLC Native Libraries in Ubuntu unless they are installed to the system

### ISSUE THREAD

**Issue by JoshuaD84** [caprica/vlcj#623]
I am able to run my program on Ubuntu if the vlc native libraries are installed via apt-get. 

However, I am looking to bundle the libraries with my program, since I am packaging it as an AppImage, and that is how AppImages are supposed to be distributed -- all non-system libraries included with the program.

When I download the libvlc libraries from the Ubuntu website directly and unpack them, and then try to load them with NativeLibrary.addSearchPath(), it doesn't work. 

I have confirmed that the correct directory for the libraries is being added to the search path. I used this exact same method for windows, and this code works there. For some reason, it does not work on Ubuntu -- I cannot get vlcj to see the standalone libraries.

**Any suggestions on how to fix this problem?**

**I used the native libraries in the following three packages:**
https://packages.ubuntu.com/bionic/video/vlc-plugin-base
https://packages.ubuntu.com/bionic/libs/libvlc5
https://packages.ubuntu.com/bionic/libs/libvlccore9

**I have confirmed that:**
1. The code works in windows using windows native libraries. 
2. There are no path errors -- I am adding the right directory to the search path. 
3. There are no permission issues
4. Both the libraries and java are 64 bit. 

**Here is the error:** 

SEVERE: class java.lang.RuntimeException:  Exception caught at top level of Hypnos. Exiting.
java.lang.RuntimeException: Failed to load the native library.

The error was "Unable to load library 'vlc': JNA native support (linux-amd64/libvlc.so) not found in resource path (/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/resources.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jsse.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jce.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/charsets.jar:/usr/share/java/openjfx/jre/lib/ext/jfxrt.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/dnsns.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/localedata.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/jaccess.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/sunec.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/icedtea-sound.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/zipfs.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/cldrdata.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/nashorn.jar:/usr/share/java/java-atk-wrapper.jar:/d/programming/workspace/MusicPlayer/stage/bin:/d/programming/workspace/MusicPlayer/stage/lib/commons-cli-1.4.jar:/d/programming/workspace/MusicPlayer/stage/lib/fuzzywuzzy-1.1.8.jar:/d/programming/workspace/MusicPlayer/stage/lib/jaudiotagger-2.2.6-SNAPSHOT.jar:/d/programming/workspace/MusicPlayer/stage/lib/commons-io-2.5.jar:/d/programming/workspace/MusicPlayer/stage/lib/jsoup-1.11.2.jar:/d/programming/workspace/MusicPlayer/stage/lib/commons-text-1.1.jar:/d/programming/workspace/MusicPlayer/stage/lib/commons-lang3-3.7.jar:/d/programming/workspace/MusicPlayer/stage/lib/jnativehook-2.0.2.jar:/d/programming/workspace/MusicPlayer/stage/lib/jlastfm.jar:/usr/lib/jvm/java-8-openjdk-amd64/lib/javafx-mx.jar:/d/programming/workspace/MusicPlayer/stage/lib/jna-3.5.2.jar:/d/programming/workspace/MusicPlayer/stage/lib/platform-3.5.2.jar:/d/programming/workspace/MusicPlayer/stage/lib/slf4j-api-1.7.10.jar:/d/programming/workspace/MusicPlayer/stage/lib/vlcj-3.10.1.jar)".

The required native libraries are named "libvlc.so" and "libvlccore.so".

In the text below <libvlc-path> represents the name of the directory containing "libvlc.so" and "libvlccore.so"...

There are a number of different ways to specify where to find the native libraries:
 1. Include NativeLibrary.addSearchPath("vlc", "<libvlc-path>"); at the start of your application code.
 2. Include System.setProperty("jna.library.path", "<libvlc-path>"); at the start of your application code.
 3. Specify -Djna.library.path=<libvlc-path> on the command-line when starting your application.
 4. Add <libvlc-path> to the system search path (and reboot).

If this still does not work, then it may be necessary to explicitly add the native library directory to the operating
system configuration - e.g. on Linux this might mean setting the LD_LIBRARY_PATH environment variable, or adding
configuration to the "/etc/ld.so.conf" file or the "/etc/ld.so.conf.d" directory. Of these options, setting
LD_LIBRARY_PATH is the only one that would not require root privileges.

Finally, it is not possible to mix CPU architectures - it is not possible for a 64-bit Java Virtual Machine to load
32-bit native libraries.

More information may be available in the log.

	at uk.co.caprica.vlcj.binding.LibVlcFactory.create(LibVlcFactory.java:198)
	at uk.co.caprica.vlcj.player.MediaPlayerFactory.<init>(MediaPlayerFactory.java:259)
	at uk.co.caprica.vlcj.component.AudioMediaPlayerComponent.onGetMediaPlayerFactory(AudioMediaPlayerComponent.java:177)
	at uk.co.caprica.vlcj.component.AudioMediaPlayerComponent.<init>(AudioMediaPlayerComponent.java:109)
	at net.joshuad.hypnos.audio.VLCAudioPlayer.<init>(VLCAudioPlayer.java:77)
	at net.joshuad.hypnos.audio.AudioSystem.<init>(AudioSystem.java:85)
	at net.joshuad.hypnos.Hypnos.start(Hypnos.java:726)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$7(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$5(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)

**Comment by caprica** [comment]
This is normal behaviour if you don't install the native libraries "properly". It's related to things like "rpath", and as such this is not a vlcj problem per se.

**Comment by mdecorde** [comment]
Hi,

What about a VLC installed with snap ? 

Can this be solved if we add the "/snap/vlc/current/usr/lib" path to the DefaultLinuxNativeDiscoveryStrategy class discovery paths ?

thx

**Comment by caprica** [comment]
Did you try?
