### ISSUE TITLE
Stuttering with HTTP streaming

### ISSUE THREAD

**Issue by heftylou** [caprica/vlcj#625]
Hello, I'm currently trying to make an application that can display a live stream from a URL using HTTP. The actual stream is represented as a .ts file.

An example URL would be: "http://host.me:9999/streams/snek.ts"

I'm writing my program in Java, using vlcj and so far, this is the code I have so far: https://pastebin.com/dnqQ6Yt9

The thing is, it pauses... alot. 

Now, I know I can change my code to be something like this:

`
        
        //play the StreamMedia object I've created
        //Play the URL directly instead of creating my own Media class
        mediaPlayer.getMediaPlayer().playMedia("MY URL");
 
`

And that in-fact fixes my stuttering/pausing problem because VLC handles all the network stuff. 

However, I also want to record the stream itself and by going this route, I won't be able to customize how VLC reads from the stream.

What am I missing in my original code that's preventing from having the smooth playback as passing in the URL directly?
I've tried buffered inputstreams, but things are read to quickly and it's back to square one with the stuttering. 

I'm pretty new to the vlc community and vlcj so apologies if I'm missing obvious things. I also don't have much experience with http. 

Thanks.

**Comment by caprica** [comment]
In my opinion there is simply no way you will be able to use Java to record the stream *and* play it quickly enough at the same time, hence the stuttering you are seeing.

I mean, if you want to try something at least use a buffer size bigger than 512 bytes.

**Comment by caprica** [comment]
The reality is that vlcj and LibVLC may not suit your particular use-case.
