### ISSUE TITLE
Screenshot size does not match video resolution

### ISSUE THREAD

**Issue by klib009** [caprica/vlcj#629]
Hi
I have a video file (MPEG2 720x576). When playing the file the actual size is 768x576. AFAIK this is because of different size ratios for the PAL resolution (720 would be 5:4 whereas 768 is 4:3).
This sreenshot shows 1:1 Video output:
![2018-09-03_10h33_30](https://user-images.githubusercontent.com/42930869/44976759-73418980-af66-11e8-9026-384b8f48d782.png)

Now I try making a screenshot by calling
`mediaPlayerComponent.getMediaPlayer().getSnapshot();`

This gives me a Screenshot with size 720x576px. Since the dispayed width is 768px, the screenshot is squeezed horizontally. In order to get the screenshot right, I'd have to set the width parameter when calling getSnapshot(int, int). Can you tell me how to obtain the aspect ratio of the video that is currently played s.t. I could calculate the width?

Or is there a simpler way I didn't get?

Thanks for your help

**Comment by caprica** [comment]
It is LibVLC/VLC itself (i.e. the native code) that is creating the screenshot, vlcj does nothing here.

This sounds similar to #616.

**Comment by klib009** [comment]
I am no expert with video formats but I don't think it's the same issue as #616. 
My problem should only arise with PAL resolution. Please see this image from Wikipedia
[https://de.wikipedia.org/wiki/Videoaufl%C3%B6sung#/media/File:Vector_Video_Standards4.svg](url).

All other video formats have fixed ratios and should therefore be displayed correctly. 

I have already tried (but not mentioned in the prev. message, sorry)
getAspectRation() -> NULL
getMediaDetails() -> Nothing useful
getMetaData() -> NULL

When creating a screenshot directly from VLC, the size is the same as the video (768*576).

**Comment by caprica** [comment]
It sounded similar to the other issue in that VLC had some strange handling of resolutions in certain versions. But fair enough it may be irrelevant.

For those other methods you tried, is your video actually playing when you invoke them - did you *after* you received a "playing" event.

Also you should try the methods that return Track information, a video track should have the resolution.

But again, sometimes this information is not available until *after* the video has started playing.

**Comment by klib009** [comment]
`getTrackInfo(TrackType.VIDEO);` indeed returned some info about the video:
[VideoTrackInfo[codec=0x34363268,codecName=h264,originalCodec=0x31637661,originalCodecName=avc1,id=0,profile=0,level=0,bitRate=0,language=null,description=null,codecDescription=][width=720,height=576,sampleAspectRatio=16,sampleAspectRatioBase=15,frameRate=25,frameRateBase=1]]

The resolution is again not the displayed one. 
SampleAspectRation and SampleAspectRatioBase do return some value, but I don't know what the numbers stand for. In the Javadoc there is no explanation for it. Do you know where to get more information about these numbers?

**Comment by caprica** [comment]
All I can tell you is 720 x 16 / 15 = 768, which matches the behaviour you're seeing doesn't it?

**Comment by klib009** [comment]
Thank you so much for your Support! I have checked TrackInfo for other resolutions and it is as expected (usually 1). 

So for anyone encountering the same problem in the future:
The correct width for PAL-Screenshots is TrackInfo.width x TrackInfo.sanmpleAspectRation / sampleAspectRatioBase

Kind regards
Hannes
