### ISSUE TITLE
Unable to enable hardware acceleration on libvlc 3.0.2

### ISSUE THREAD

**Issue by zuinqstudio** [caprica/vlcj#630]
Hi!
we're trying integrating vlcj in a java Swing application. We're trying to enable hardware acceleration (**--avcodec-hr=vaapi_drm**) but it seems the library is ignoring it; checking the gpu usage rate, we get near 0%, but when launching vlc from a terminal with the very same config, gpu is used as expected. May we missing something obvious or is it a bug? 

Please, find vlc and vlcj logs attached to the issue.

Thanks in advance!

[vlcj-log-debug.txt](https://github.com/caprica/vlcj/files/2358024/vlcj-log-debug.txt)
[libvlc-log-debug.txt](https://github.com/caprica/vlcj/files/2358025/libvlc-log-debug.txt)

**Comment by caprica** [comment]
When doing the same thing in VLC, grab the VLC log and compare the differences.
