### ISSUE TITLE
Video on Demand RTP Server Connection Failed

### ISSUE THREAD

**Issue by lukasHoel** [caprica/vlcj#631]
Hi, 
I tried to setup an RTP-server as described in `test/manager/VodTest.java`: 

`MediaPlayerFactory factory = new MediaPlayerFactory("--rtsp-host=127.0.0.1", "--rtsp-port=5004");`
`MediaManager manager = factory.newMediaManager();`
`manager.addVideoOnDemand("Movie1", "videos/Video 1.mp4", true, vodMux);`
`Thread.currentThread().join();`

`videos/Video 1.mp4` is the path where an example video can be found on my system.

Then I tried to show that video on a client as described in `test/streaming/StreamRtp.java`:

`EmbeddedMediaPlayerComponent playerComp = new EmbeddedMediaPlayerComponent();`
`MediaPlayer player = playerComp.getMediaPlayer();`
`String media = "rtsp://@127.0.0.1:5004/Movie1";`
`String options = formatRtpStream("127.0.0.1", 5004);`

`player.playMedia(media, options,`
				`":no-sout-rtp-sap", `
				`":no-sout-standard-sap", `
				`":sout-all",` 
				`":sout-keep");`

`public static String formatRtpStream(String serverAddress, int serverPort) { `
`		StringBuilder sb = new StringBuilder(60); `
`		sb.append(":sout=#rtp{dst="); `
`		sb.append(serverAddress); `
`		sb.append(",port="); `
`		sb.append(serverPort); `
`		sb.append(",mux=ts}"); `
`		return sb.toString(); `
`	} `

The video stays black and when closing the player I get the error:

`[000000005b2fd610] live555 demux error: Failed to connect with rtsp://127.0.0.1:5004/Movie1`
`[0000000000466870] satip stream error: Failed to setup RTSP session`
`[000000005b15f190] main input error: Your input can't be opened`
`[000000005b15f190] main input error: VLC is unable to open the MRL 'rtsp://@127.0.0.1:5004/Movie1'. Check the log for details.`

Is this even the right way to setup an RTP-Server and RTP-Client? 
Thanks for your help!

**Comment by caprica** [comment]
Check the native (VLC) log and see what it says.

**Comment by caprica** [comment]
The VoD stuff is historically very difficult to set up, you may need to consult (possible outdated) pages in the VideoLAN WIKI.

**Comment by lukasHoel** [comment]
What RTP Server Implementation in Java can you suggest using instead of VLCJ that works with a VLCJ Client? 

Among others, the native log is saying:

`file:///[...]/videos/Video 1.mp4' successfully opened`
`[stream_out_rtp      ] (vod server          )   DEBUG: media 'Movie1' has 1 declared ES`
`[stream_out_rtp      ] (vod server          )   DEBUG:   - added ES 33 MP2T (mp2t)`
`[stream_out_rtp      ] (vod server          )   DEBUG: adding media 'Movie1'`
`[stream_out_rtp      ] (vod server          )   DEBUG: RTSP stream at 127.0.0.1/Movie1`
`[main                ] (vod server          )   DEBUG: net: listening to * port 5004`
`[stream_out_rtp      ] (vod server          )   DEBUG: RTSP: adding 127.0.0.1/Movie1/trackID=0`

After that nothing more appears until I close the video-player and then the errors are printed.
