### ISSUE TITLE
vlcj linux error

### ISSUE THREAD

**Issue by benttu** [caprica/vlcj#632]
I get some errors when I trying to record video. I recorded video and get snapshot on Windows but I can't doing these on Linux. Can you help me?

`ps mux: Open`
`mpeg4audio decoder: AAC channels: 2 samplerate: 48000`
`avcodec encoder error: Unknown option "rc_buffer_aggressivity`

**Comment by caprica** [comment]
Those errors are coming from VLC. I can't help you with that.

**Comment by benttu** [comment]
> Those errors are coming from VLC. I can't help you with that.

Maybe you're right but can you guide for me?
