### ISSUE TITLE
Failed to load the native library - Windows 10, 64 bit

### ISSUE THREAD

**Issue by Alphagen2901** [caprica/vlcj#634]
Hey Community, 

I get an error when i try to run on Windows 10 64 bit. At Linux Debian my Project is running without any Problem. I figgured out, that the problem is the "EmbeddedMediaPlayerComponent".
If i remove this part in my Code, "true" and "2.2.8 Weatherwax" is printed to console.
I also tryed with vlc 3.0.3 and 3.0.4. without any changes.

You can find my code underneath the Error.

I hope someone can help me. :-)

**Error:**
> "C:\Program Files\Java\jdk1.8.0_181\bin\java.exe" "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.2.2\lib\idea_rt.jar=59075:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.2.2\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_181\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_181\jre\lib\rt.jar;P:\Martin\SignagePlayer\target\classes;C:\Users\martin\.m2\repository\uk\co\caprica\vlcj\3.10.1\vlcj-3.10.1.jar;C:\Users\martin\.m2\repository\net\java\dev\jna\jna-platform\4.1.0\jna-platform-4.1.0.jar;C:\Users\martin\.m2\repository\org\slf4j\slf4j-api\1.7.10\slf4j-api-1.7.10.jar;C:\Users\martin\.m2\repository\ch\qos\logback\logback-classic\1.1.2\logback-classic-1.1.2.jar;C:\Users\martin\.m2\repository\ch\qos\logback\logback-core\1.1.2\logback-core-1.1.2.jar;C:\Users\martin\.m2\repository\net\java\dev\jna\jna\4.5.2\jna-4.5.2.jar" signagePlayer.SignagePlayerMain
> 12:10:53.157 [JavaFX Application Thread] DEBUG u.c.c.v.c.EmbeddedMediaPlayerComponent - args=[--video-title=vlcj video output, --no-snapshot-preview, --quiet-synchro, --sub-filter=logo:marq, --intf=dummy]
> 12:10:53.174 [JavaFX Application Thread] DEBUG u.c.c.vlcj.player.MediaPlayerFactory - initX=null
> 12:10:53.321 [JavaFX Application Thread] INFO  uk.co.caprica.vlcj.Info - vlcj: 3.10.1
> 12:10:53.322 [JavaFX Application Thread] INFO  uk.co.caprica.vlcj.Info - java: 1.8.0_181 Oracle Corporation
> 12:10:53.322 [JavaFX Application Thread] INFO  uk.co.caprica.vlcj.Info - java home: C:\Program Files\Java\jdk1.8.0_181\jre
> 12:10:53.322 [JavaFX Application Thread] INFO  uk.co.caprica.vlcj.Info - os: Windows 10 10.0 amd64
> 12:10:53.325 [JavaFX Application Thread] ERROR u.c.c.vlcj.binding.LibVlcFactory - Failed to load native library
> Exception in Application constructor
> java.lang.reflect.InvocationTargetException
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
> 	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
> Caused by: java.lang.RuntimeException: Unable to construct Application instance: class signagePlayer.SignagePlayerMain
> 	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:907)
> 	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$154(LauncherImpl.java:182)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.reflect.InvocationTargetException
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> 	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$160(LauncherImpl.java:819)
> 	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$174(PlatformImpl.java:326)
> 	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
> 	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
> 	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
> 	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
> 	... 1 more
> Caused by: java.lang.RuntimeException: Failed to load the native library.
> 
> The error was "Unable to load library 'libvlc': Native library (win32-x86-64/libvlc.dll) not found in resource path ([file:/C:/Program%20Files/Java/jdk1.8.0_181/jre/lib/charsets.jar, file:/C:/Program%20Files/Java/jdk1.8.0_181/jre/lib/deploy.jar, file:/C:/Program%20Files/Java/jdk1.8.0_181/jre/lib/ext/access-bridge-64.jar, file:/C:/Program%20Files/Java/jdk1.8.0_181/jre/lib/ext/cldrdata.jar, file:/C:/Program%20Files/Java/jdk1.8.0_181/jre/lib/ext/dnsns.jar, file:/C:/Program%20Files/Java/jdk1.8.0_181/jre/lib/ext/jaccess.jar, file:/C:/Program%20Files/Java/jdk1.8.0_181/jre/lib/ext/jfxrt.jar, file:/C:/Program%20Files/Java/jdk1.8.0_181/jre/lib/ext/localedata.jar, file:/C:/Program%20Files/Java/jdk1.8.0_181/jre/lib/ext/nashorn.jar, file:/C:/Program%20Files/Java/jdk1.8.0_181/jre/lib/ext/sunec.jar, file:/C:/Program%20Files/Java/jdk1.8.0_181/jre/lib/ext/sunjce_provider.jar, file:/C:/Program%20Files/Java/jdk1.8.0_181/jre/lib/ext/sunmscapi.jar, file:/C:/Program%20Files/Java/jdk1.8.0_181/jre/lib/ext/sunpkcs11.jar, file:/C:/Program%20Files/Java/jdk1.8.0_181/jre/lib/ext/zipfs.jar, file:/C:/Program%20Files/Java/jdk1.8.0_181/jre/lib/javaws.jar, file:/C:/Program%20Files/Java/jdk1.8.0_181/jre/lib/jce.jar, file:/C:/Program%20Files/Java/jdk1.8.0_181/jre/lib/jfr.jar, file:/C:/Program%20Files/Java/jdk1.8.0_181/jre/lib/jfxswt.jar, file:/C:/Program%20Files/Java/jdk1.8.0_181/jre/lib/jsse.jar, file:/C:/Program%20Files/Java/jdk1.8.0_181/jre/lib/management-agent.jar, file:/C:/Program%20Files/Java/jdk1.8.0_181/jre/lib/plugin.jar, file:/C:/Program%20Files/Java/jdk1.8.0_181/jre/lib/resources.jar, file:/C:/Program%20Files/Java/jdk1.8.0_181/jre/lib/rt.jar, file:/P:/Martin/SignagePlayer/target/classes/, file:/C:/Users/martin/.m2/repository/uk/co/caprica/vlcj/3.10.1/vlcj-3.10.1.jar, file:/C:/Users/martin/.m2/repository/net/java/dev/jna/jna-platform/4.1.0/jna-platform-4.1.0.jar, file:/C:/Users/martin/.m2/repository/org/slf4j/slf4j-api/1.7.10/slf4j-api-1.7.10.jar, file:/C:/Users/martin/.m2/repository/ch/qos/logback/logback-classic/1.1.2/logback-classic-1.1.2.jar, file:/C:/Users/martin/.m2/repository/ch/qos/logback/logback-core/1.1.2/logback-core-1.1.2.jar, file:/C:/Users/martin/.m2/repository/net/java/dev/jna/jna/4.5.2/jna-4.5.2.jar, file:/C:/Program%20Files/JetBrains/IntelliJ%20IDEA%20Community%20Edition%202018.2.2/lib/idea_rt.jar])".
> 
> The required native libraries are named "libvlc.dll" and "libvlccore.dll".
> 
> In the text below <libvlc-path> represents the name of the directory containing "libvlc.dll" and "libvlccore.dll"...
> 
> There are a number of different ways to specify where to find the native libraries:
>  1. Include NativeLibrary.addSearchPath("libvlc", "<libvlc-path>"); at the start of your application code.
>  2. Include System.setProperty("jna.library.path", "<libvlc-path>"); at the start of your application code.
>  3. Specify -Djna.library.path=<libvlc-path> on the command-line when starting your application.
>  4. Add <libvlc-path> to the system search path (and reboot).
> 
> If this still does not work, then it may be necessary to explicitly add the native library directory to the operating
> system configuration - e.g. on Linux this might mean setting the LD_LIBRARY_PATH environment variable, or adding
> configuration to the "/etc/ld.so.conf" file or the "/etc/ld.so.conf.d" directory. Of these options, setting
> LD_LIBRARY_PATH is the only one that would not require root privileges.
> 
> Finally, it is not possible to mix CPU architectures - it is not possible for a 64-bit Java Virtual Machine to load
> 32-bit native libraries.
> 
> More information may be available in the log.
> 
> 	at uk.co.caprica.vlcj.binding.LibVlcFactory.create(LibVlcFactory.java:198)
> 	at uk.co.caprica.vlcj.player.MediaPlayerFactory.<init>(MediaPlayerFactory.java:259)
> 	at uk.co.caprica.vlcj.component.EmbeddedMediaPlayerComponent.onGetMediaPlayerFactory(EmbeddedMediaPlayerComponent.java:349)
> 	at uk.co.caprica.vlcj.component.EmbeddedMediaPlayerComponent.<init>(EmbeddedMediaPlayerComponent.java:217)
> 	at signagePlayer.SignagePlayerMain.<init>(SignagePlayerMain.java:48)
> 	... 13 more
> Exception running application signagePlayer.SignagePlayerMain

**Code:**
package signagePlayer;

import javafx.application.Application;
import javafx.stage.Stage;
import uk.co.caprica.vlcj.binding.LibVlc;
import uk.co.caprica.vlcj.component.EmbeddedMediaPlayerComponent;
import uk.co.caprica.vlcj.discovery.NativeDiscovery;

import javax.swing.*;

public class SignagePlayerMain extends Application {

    private final JFrame frame;
    private final EmbeddedMediaPlayerComponent mediaPlayerComponent;

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) {
        boolean found = new NativeDiscovery().discover();
        System.out.println(found);
        System.out.println(LibVlc.INSTANCE.libvlc_get_version());

        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                new SignagePlayerMain();
            }
        });
    }

    public SignagePlayerMain() {

        frame = new JFrame("My First Media Player");
        frame.setBounds(100, 100, 600, 400);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        mediaPlayerComponent = new EmbeddedMediaPlayerComponent();
        //frame.setContentPane(mediaPlayerComponent);
        frame.setVisible(true);
        //mediaPlayerComponent.getMediaPlayer().playMedia(System.getProperty("user.home") + "/Signage/Videos/Test.mp4");
    }
}

**Comment by caprica** [comment]
Did you try following the suggestions/explanation in the error message?

**Comment by Alphagen2901** [comment]
I will try 

> Include System.setProperty("jna.library.path", ""); at the start of your application code.

Do i have to download jna in that case in a maven project manualy and add the path as show above?
