### ISSUE TITLE
Get BufferedImage and sound stream (RTSP:\\)

### ISSUE THREAD

**Issue by josephbriguet01** [caprica/vlcj#638]
Sometimes _EmbeddedMediaPlayerComponent_ is not enough. Because we need to collect the _sound stream_ and _BufferedImage objects_ from the video stream. But everything is hidden. Would it be possible to create an _Object Interface_ allowing the _redirection_ of sound streams and BufferedImage to the application that we develop ?

Il arrive parfois que _EmbeddedMediaPlayerComponent_ ne suffise pas. Parce que nous avons besoin de récupérer le _flux son_ et les _objets BufferedImage_ du flux vidéo. Or tout est masqué. Serait-il possible de créer une _interface_ permettant la _redirection_ des flux sonores et les BufferedImage vers l'application que l'on développe ?

**Comment by caprica** [comment]
There is the DirectAudioPlayer and associated component to grab the audio streams, but at the moment there is no easy way to get both audio and video streams directly.

The BufferedImage API exists to get a single video snapshot/screenshot, it is not intended for any other use.
