### ISSUE TITLE
JNA 5.0.0 seems to be unsupported

### ISSUE THREAD

**Issue by berry120** [caprica/vlcj#639]
V. low priority (for me at least) as I have no need to use the latest 5.x branch of JNA - but a heads up that when I tried using JNA 5.0.0 as an experiment, VLCJ was unable to find the native libraries.

Haven't looked into this at a technical level in the slightest, so no idea what's changed that might be causing this. I can do some digging when I get the time if that'd be helpful.

**Comment by Xerus2000** [comment]
Sure it is related to the JNA update? For example, for me it can't discover VLC because #612 is not merged.

**Comment by berry120** [comment]
This appears unrelated to #612 - I'm on a windows machine, and with an older version of JNA (and nothing else that's changed ) it finds the native libraries no problem.

**Comment by berry120** [comment]
Ah, I did a little more digging, and it turns out this was caused by the fact I had two different major versions of JNA on the classpath that weren't playing nicely together.

Nothing to do with VLCJ. Apologies. Rather embarassing for yours truly.
