### ISSUE TITLE
Spinning wheel of death on macos with DirectMediaPlayer

### ISSUE THREAD

**Issue by eitzenbe** [caprica/vlcj#640]
I am implementing a video player for linux, win and mac where as the first two work flawlessly.

On MacOS using installed VLC3.0.4 on JDK 10.0.2 (and JDK 11) I experience **reproducable** hangs of the vlcj lib calls.

[source.zip](https://github.com/caprica/vlcj/files/2490942/source.zip)

I have reduced the code to two classes being attached and the pom file if you want to build it.
You will also need two video files (video1.flv and video2.mp4) to reproduce the bug

AND you will need to change the dylib of vlc in order for java / JNI to find it

install_name_tool -change @rpath/libvlccore.dylib @loader_path/../lib/libvlccore.dylib ./libvlc.dylib

One more env var

export VLC_PLUGIN_PATH=/Applications/VLC.app/Contents/MacOS/plugins

and run it to see the error

java -Dvlcj.log=DEBUG -Djna.library.path=/Applications/VLC.app/Contents/MacOS/lib  -jar /Applications/GoldFinder.app/Contents/Java/vlcjmacos-0.1.0-shaded.jar 

after startup switch between the videos in the JLIST right side. I have it reproducable on EVERY switch (alas I am running macOS in Virtualbox without sound). A friend of mine has two real mac books and on both (Sierra and High Sierra) the same effect happens

Here is the log:
WARNING: GL pipe is running in software mode (Renderer ID=0x1020400)
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[00007f9fd92a1350] auhal audio output error: No audio output devices found.
[00007f9fd92a1350] auhal audio output error: AudioObjectAddPropertyListener failed, device id 0, prop: [nvil], OSStatus: 560947818
[00007f9fd92a1350] auhal audio output error: AudioObjectGetPropertyDataSize failed, device id: 0, prop: [cntl], OSStatus: 560947818
[h264 @ 0x7f9fdb0c3200] get_buffer() failed
[h264 @ 0x7f9fdb0c3200] thread_get_buffer() failed
[h264 @ 0x7f9fdb0c3200] decode_slice_header error
[h264 @ 0x7f9fdb0c3200] no frame!

**Comment by caprica** [comment]
I don't know, but there are some misconceptions in your playVideo code.

```
  void playVideo(final String videofile) {
    try {
      boolean playing = getMediaPlayer().isPlaying();
      if (playing) {
        getMediaPlayer().stop();
      }
      if (!getMediaPlayer().prepareMedia(videofile)) {
        System.out.println("Unable to start media " + videofile);
      }
      getMediaPlayer().setTime(0);
      getMediaPlayer().play();
    } catch (Throwable t) {
      t.printStackTrace();
    }
  }
```
After you call mediaPlayer.stop() the video may still be playing, because it is an asynchronous call you are supposed to wait for an event callback to tell you it has actually stopped. I suppose you could do a sleep loop and poll, but events would be better.

Call mediaPlayer.setTime(0) here will do nothing as far as I can remember.

You really should just call mediaPlayer.playMedia() IMO.

As to the hang, if you are suggesting that the posted log pertains to the hang, then those errors are native errors coming from VLC itself.

**Comment by caprica** [comment]
Similarly your togglePlayPause() implementation is suspect for the same reasons. There is already functionality in the media player to handle the toggle, and the status of playing vs pausing (e.g. to update the UI) should be detected by listening for playing/paused/stopped/error events.

You need to be aware that just about every such media player call that "mutates" the native media player will operate asynchronously.

**Comment by eitzenbe** [comment]
Thanx for the feedbac, i will adapt the code and will check if it still hangs

**Comment by caprica** [comment]
I suspect it will still hang, but at least eliminating these small issues might help get to the real problem.

**Comment by eitzenbe** [comment]
Hi Mark,

I have adapted the player widget code to a poor mans event handler :)
BUT it still hangs in stop(). 

First click on JList, plays video (as stop is not called) as boolean playing is false
Second click the console says:

Play video2.mp4
waiting for pause
STOPPING
waiting for stop
waiting for stop
waiting for stop
waiting for stop
....

this goes on and on, clearly indicating that the stop() call never returns. I am confused as to what else I could do. I would expect that I can call stop() at any time or?

Regarding the event driven approach, it is clear that will have to rewrite my code, but I am talking about TWO clicks here which cause the vlcj lib to hang on mac os...

Attached are the sources and the pom.xml. I can also provide a shaded jar containing all classes/libs
[source.zip](https://github.com/caprica/vlcj/files/2491263/source.zip)


Below is the relvant code excerpt

 int state = 2;
  // 1 playing
  // 2 stopped
  // 3 paused
  void playVideo(final String videofile) {
    System.out.println("Play " + videofile);
    new Thread(new Runnable() {
      @Override
      public void run() {
        try {
          boolean playing = getMediaPlayer().isPlaying();
          if (playing) {
            getMediaPlayer().pause();
            while (state != 3) {
              Thread.sleep(500);
              System.out.println("waiting for pause");
            }
            System.out.println("STOPPING");
            getMediaPlayer().stop();
            System.out.println("STOP returned");
          }

          while (state != 2) {
            Thread.sleep(500);
            System.out.println("waiting for stop");
          }
          System.out.println("preparing media");
          if (!getMediaPlayer().prepareMedia(videofile)) {
            System.out.println("Unable to start media " + videofile);
          }
          getMediaPlayer().setTime(0);
          getMediaPlayer().play();
        } catch (Throwable t) {
          t.printStackTrace();
        }
      }
    }, "playvideo").start();
  }

  private MediaPlayerEventListener listener = new MediaPlayerEventAdapter() {
    public void playing(MediaPlayer mp) {
      System.out.println("playing");
      state = 1;
    }
    public void paused(MediaPlayer mp) {
      System.out.println("paused");
      state = 3;
    }
    public void stopped(MediaPlayer mp) {
      System.out.println("stopped");
      state = 2;
    }
  };

**Comment by eitzenbe** [comment]
Tried to format the code but md fails :(

**Comment by caprica** [comment]
There may also be finished() and error() events happening, in which case you will not see stop().

**Comment by caprica** [comment]
Your code is also not threadsafe with respect to your "state" variable. The event handlers run in a different thread to the rest of your application.

Honestly I think you're going down a wrong path here with your use of the Runnable and your state management. It should not be this complicated to stop one video and play another.

**Comment by eitzenbe** [comment]
I completely agree with your analysis, but the point is that the stop() hang is NOT related to this
I have added the following code on startup of frame:

  if (!pw.getMediaPlayer().prepareMedia("video2.mp4")) {
      System.out.println("Unable to start media");
    }
    pw.getMediaPlayer().setTime(0);
    pw.getMediaPlayer().play();
    Thread.sleep(3000);
    System.out.println("PAUSING");
    pw.getMediaPlayer().pause();
    Thread.sleep(3000);
    System.out.println("STOPPING");
    pw.getMediaPlayer().stop();
    System.out.println("STOPPED");

The console last line is "STOPPING"

There is no event thread involved, I wait 3 seconds after pause before stopping so clearly its not related to mediaplayer still sending events ....

I also did not find ANY Directmediaplayer example for mac os only the embeddedplayer variants not working with JDK > 6

I spent two nights now trying to trace this down. Please also note that the same code works flawlessly on linux AND windows, so I really think there is something within vlcj that causes the hang and not within my code....

I am lost as how to proceed here. Worst case scenario currently is to switch to gstreamer-java but that would be a major rewrite..... Any help/hint on how to proceed appreciated. If desired I could also provide the intellij project as zip.....

**Comment by eitzenbe** [comment]
BTW: added callbacks for finished and error and as expected no calls to these

**Comment by caprica** [comment]
So your code works flawlessly on Linux and Windows and yet you somehow conclude that there is something in vlcj that cases the hang? You know Java is cross-platform, right? You know that vlcj is Java, with no platform-specific code of its own? Your conclusion is not sound IMO.

**Comment by eitzenbe** [comment]
well it actually hangs within the call to native libvlc stop method and please I dont want to blame anyone. I am trying to work together to fix this issue. Do you have a running demo of Directmediaplayer jar for mac os? I would be happy to try this out it should allow to play a video stop it and play another video....

**Comment by eitzenbe** [comment]
I'd be also happy to modify my test code if you give me any hints on what to change (as outlined in the last modification I have no more events, just call once prepareMedia, play it, wait 3 secs, pause, wait another 3 secs and try to stop, so I am lost as to what I could make it even more simple to locate the error)

**Comment by eitzenbe** [comment]
I have removed the stop() method and directly preparedMedia (calling pause(), waiting 3 secs...)

Debugger attached to process remotely returns

invokeVoid:-1, Native {com.sun.jna}
invoke:367, Function {com.sun.jna}
invoke:315, Function {com.sun.jna}
invoke:212, Library$Handler {com.sun.jna}
libvlc_media_player_set_media:-1, $Proxy0 {com.sun.proxy}
setMedia:2105, DefaultMediaPlayer {uk.co.caprica.vlcj.player}
prepareMedia:282, DefaultMediaPlayer {uk.co.caprica.vlcj.player}
prepareMedia:276, DefaultMediaPlayer {uk.co.caprica.vlcj.player}
main:52, Main {mm}
in the main thread

All thread states
"AppKit Thread"@1.253: RUNNING
"AWT-EventQueue-0"@2.281 in group "main": WAIT
"AWT-Shutdown"@1.256: WAIT
"Common-Cleaner"@418 in group "InnocuousThreadGroup": WAIT
"Finalizer"@2.991: WAIT
"Java2D Disposer"@1.517: WAIT
"Java2D Queue Flusher"@1.310: WAIT
"main"@1 in group "main": RUNNING
"pool-1-thread-1"@2.557 in group "main": WAIT
"Reference Handler"@2.990: RUNNING
"Signal Dispatcher"@2.992: RUNNING
"TimerQueue"@2.615: WAIT

No clue if this is of help....

**Comment by eitzenbe** [comment]
Nope sorry, switched to gstreamer lib due to more supportive community (No offense intended here)

**Comment by caprica** [comment]
In my experience, anyone that says "no offense intended" is being disingenuous.
