### ISSUE TITLE
Video statistics not available when recording network stream 

### ISSUE THREAD

**Issue by andrey2good** [caprica/vlcj#644]
When calling 
``embeddedMediaPlayer.playMedia(streamURL)`` I am able to get an output like

Decoded video blocks: 550 (embeddedMediaPlayer.getMediaStatistics().i_decoded_video)
Displayed frames: 267 (embeddedMediaPlayer.getMediaStatistics().i_displayed_pictures)
Lost frames: 0 (embeddedMediaPlayer.getMediaStatistics().i_lost_pictures)

but when I am calling
``embeddedMediaPlayer.playMedia(streamURL, new String[]{":sout=#duplicate{dst=file{dst=video.avi},dst=display}"})`` the output is 

Decoded video blocks: 0 (embeddedMediaPlayer.getMediaStatistics().i_decoded_video)
Displayed frames: 0 (embeddedMediaPlayer.getMediaStatistics().i_displayed_pictures)
Lost frames: 0 (embeddedMediaPlayer.getMediaStatistics().i_lost_pictures)

Notes:
 - My Jframe content is as expected, the stream is playing. (as I want to: allow display & record network stream)
 - The video.avi is successfully saved with the expected content.
 - Other statistics like i_read_bytes or demux info is correctly shown. 

Am I missing something ? The vlcj version which I am using is 2.4.1.

**Comment by caprica** [comment]
Most likely LibVLC does not support that when you duplicate the output.

**Comment by andrey2good** [comment]
Thank you for your response. Do you know if this can be achieved somehow? The only way I see here is to replay the recorded file and get those video statistics.

**Comment by caprica** [comment]
I guess you would have to look at the VLC sources and try and figure it out.

There is nothing that can be changed in vlcj to make that work, vlcj is giving you the statistics that VLC is sending.

**Comment by andrey2good** [comment]
Hey, I will just leave a question here. 

Why i_read_bytes, i_demux_read_bytes and maybe i_decoded_video are considered as be int types (binding.internal.libvlc_media_stats_t) ?

I am running a test on a network stream for... let's say 72 hours and I am trying to get the stream statistics. All goes fine until one of the abovementioned parameters exceed their maximum value (Integer.MAX_VALUE = 2,147,483,647). Maybe you should update them as BigInteger. 

For now I've workaround this by counting how many times the int values goes in negative/positive range. I will let here the workaround solution as well in case there is someone else who is concerned about a long network stream statistics. 
```
// list where "+" or "-" will be added when the int max/min value will be achieved (only once - the result will be a list like {"+", "-", "+", "-", "+"} )
static List<String> mediaSizeSigns = Stream.of("+").collect(Collectors.toList());


// method that will be called while stream is playing (I decided to call it after each minute)
    private void checkIntExceedsItsType(int i_read_bytes, List<String> signs){
        if(i_read_bytes< 0 && signs.get(signs.size() - 1).equals("+")){
            System.out.println("Value exceeds its positive type limit. Going with negative numbers.");
            signs.add("-");
        } else if(i_read_bytes > 0 && signs.get(signs.size() - 1).equals("-")){
            System.out.println("Value exceeds its negative type limit. Going back with positive.");
            signs.add("+");
        }
    }


// current size is the value of i_read_bytes at the end of the stream
// this is how you get the final statistic, by calling this method over the i_read_bytes  and the list of signs
static BigInteger intToBigInteger(int currentSize, List<String> mediaSizeSigns) {
        BigInteger completeTrack = BigInteger.valueOf(Integer.MAX_VALUE)
                .multiply(BigInteger.valueOf(2));
        if (currentSize > 0)
            return completeTrack
                    .multiply(BigInteger.valueOf(Collections.frequency(mediaSizeSigns, "+") - 1))
                    .add(BigInteger.valueOf(currentSize));

        return completeTrack
                .multiply(BigInteger.valueOf(Collections.frequency(mediaSizeSigns, "-") - 1))
                .add(BigInteger.valueOf(Integer.MAX_VALUE)
                        .add(BigInteger.valueOf(Integer.MAX_VALUE)
                                .add(BigInteger.valueOf(currentSize))));
    }
```

**Comment by caprica** [comment]
The reason it's the way it is is because the JNA mapping from a native int is to a Java int.

```
typedef struct libvlc_media_stats_t
{
    /* Input */
    int         i_read_bytes;
    float       f_input_bitrate;

    /* Demux */
    int         i_demux_read_bytes;
    float       f_demux_bitrate;
    int         i_demux_corrupted;
    int         i_demux_discontinuity;

    /* Decoders */
    int         i_decoded_video;
    int         i_decoded_audio;

    /* Video Output */
    int         i_displayed_pictures;
    int         i_lost_pictures;

    /* Audio output */
    int         i_played_abuffers;
    int         i_lost_abuffers;

    /* Stream output */
    int         i_sent_packets;
    int         i_sent_bytes;
    float       f_send_bitrate;
} libvlc_media_stats_t;
```
So, VLC itself is sending a 32-bit integer value.
