### ISSUE TITLE
Adding a folder to NativeDiscovery on every platform

### ISSUE THREAD

**Issue by Xerus2000** [caprica/vlcj#646]
I have a cross-platform application where I want to be able to call the Discovery with a specific directory and then have it do its default Discovery plus look into that directory.

As I see it right now, I have to extend all three NativeDiscoveryStrategies and add the folder in `onGetDirectoryNames`, which is super annoying. What if the constructor of every DefaultDiscoveryStrategy had a varargs parameter that would take additional directories? Is super easy to implement and would this usecase a lot easier.

**Comment by Xerus2000** [comment]
template method?
But then I'd also have to implement `getFilenamePatterns`, and I want to leave such granular stuff to the library.

**Comment by Xerus2000** [comment]
That's why I proposed #647 - a very simple solution that fixes this problem and makes it a bit more convenient. 

The reason is that we considered optionally shipping the application with VLC so it's a fully deployable package, so we want to add the application directory to the Discovery. Right now, that's about 20 extra lines of code, with the PR merged I'd need no extra lines ;)

**Comment by caprica** [comment]
Maybe your solution should be a one-liner, something like:

```
NativeLibrary.addSearchPath(RuntimeUtil.getLibVlcLibraryName(), "your application directory name");
```

**Comment by caprica** [comment]
Closing this, as it is superceded by work done under #697.

**Comment by Xerus2000** [comment]
Thank you :)
