### ISSUE TITLE
Media information output failure

### ISSUE THREAD

**Issue by HarperCuiXin** [caprica/vlcj#649]
Media information output failure.

java.lang.Error: Structure.getFieldOrder() on class uk.co.caprica.vlcj.binding.internal.libvlc_video_track_t does not provide enough names [6] ([i_frame_rate_den, i_frame_rate_num, i_height, i_sar_den, i_sar_num, i_width]) 
to match declared fields [12] ([f_fov_degrees, f_pitch_degrees, f_roll_degrees, f_yaw_degrees, i_frame_rate_den, i_frame_rate_num, i_height, i_orientation, i_projection, i_sar_den, i_sar_num, i_width])

**Comment by caprica** [comment]
You have some sort of classpath problem, maybe a mismatch between vlcj and JNA.

**Comment by caprica** [comment]
Indeed this is a bug, thanks.

**Comment by caprica** [comment]
Fixed by f3c8a69cffc68d62708fe8581e14f19fc07aa61d.
