### ISSUE TITLE
Extract frames

### ISSUE THREAD

**Issue by HarperCuiXin** [caprica/vlcj#651]
Is there a function in the project to extract a frame in video based on the number of frames?

**Comment by HarperCuiXin** [comment]
And get the video screenshot

**Comment by caprica** [comment]
The answer to your first question is no. With VLC/LibVLC, it is not possible to address individual video frames by their number.

For your second question, the mediaPlayer object has a method to capture a screenshot, consult the Javadoc or use your IDE to find it. Note however that the screenshot is captured to disk first, it is not possible to directly capture it to memory - this is a limitation of LibVLC.

**Comment by HarperCuiXin** [comment]
Capture screenshots can you set the frame number to capture screenshots? For example, if the preset frame number =1000, then output video screenshots with 1000 frames and save them to the hard disk

**Comment by caprica** [comment]
No.

**Comment by caprica** [comment]
Simply put: you can not do *anything* with individual frames using VLC/LibVLC/vlcj since it is not possible to address any specific frame, there is no "seek-to-frame" API.
