### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by implementt** [caprica/vlcj#653]
hi,there is a question:
There this a new computer,once you start playing video other programs will be slow,but cpu and mem is normal.(20%,15%)
This is a 1080P video,i try use virtual machine to Recurring problems
Because,this computer is not with me,1 core cpu and 1g mem,playing same video,but It works very well.
use vlc media player  very well too.
Can you give me some ideas?

4g memory
Intel(R) Core(TM) i3-4330TE CPU @ 2.40GHz 
root@kylin-ECS-1819:~# dpkg -l | grep intel
ii  libdrm-intel1:i386                         2.4.56-1                                 i386         Userspace interface to intel-specific kernel DRM services -- runtime
ii  xserver-xorg-video-intel                   2:2.99.914-1~exp1ubuntu4                 i386         X.Org X server -- Intel i8xx, i9xx display driver
root@kylin-ECS-1819:~# lspci | grep -i vga
00:02.0 VGA compatible controller: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller (rev 06)
root@kylin-ECS-1819:~# dmidecode | grep "Product Name"
        Product Name: ECS-1819
        Product Name: ECS-1819
root@kylin-ECS-1819:~# dmidecode |grep -A16 "System Information$"
System Information
        Manufacturer: EVOC
        Product Name: ECS-1819
        Version: BIOS Name:09200000 BIOS Version:C03 Build Date:03/22/2018 09:06:50
        Serial Number: To be filled by O.E.M.
        UUID: 03000200-0400-0500-0006-000700080009
        Wake-up Type: Power Switch
        SKU Number: To be filled by O.E.M.
        Family: To be filled by O.E.M.

Handle 0x0002, DMI type 2, 15 bytes
Base Board Information
        Manufacturer: EVOC
        Product Name: ECS-1819
        Version: C03
        Serial Number: To be filled by O.E.M.
        Asset Tag: To be filled by O.E.M.

**Comment by caprica** [comment]
Impossible to say, really.

Make sure you use hardware accelerated decoding if possible, see "vlc -H" and  --avcodec-hw option.

**Comment by implementt** [comment]
look this.
slow computer:
[mas.txt](https://github.com/caprica/vlcj/files/2659789/mas.txt)
virtual machine:
[xnj.txt](https://github.com/caprica/vlcj/files/2659790/xnj.txt)

I tried the same code and video with a machine in the lab, but it worked very well.
Genuine Intel(R) CPU           T2600  @ 2.16GHz
2g mem

**Comment by implementt** [comment]
I am trying to compare the output of these two machines

**Comment by caprica** [comment]
Performance problems related to video playback can not be "fixed" in vlcj's Java code, it's as simple as that.

vlcj does not play your video. Rather, vlcj gives an AWT window handle to the LibVLC native library and it is LibVLC/VLC that plays your video directly into that AWT window.

So unfortunately if you have video playback performance issues in one of your environments, the onus is on you to do the necessary work (such as using a native profiler) to work out where the problem is. You're certainly better placed to investigate such problems than I am, frankly.

**Comment by caprica** [comment]
A quick skim of your logs shows one uses this video output:

`[6b0dc648] core vout display debug: using vout display module "xcb_x11"`

And the other this:

`[737f36d0] core vout display debug: using vout display module "xcb_glx"`

Presumably GLX is faster since it will benefit from hardware acceleration, I assume.

**Comment by implementt** [comment]
thanks.i trying

**Comment by implementt** [comment]
use xcb_x11:
Run VLC media player and my program at the same time. Video plays normally and the program runs normally.it fast

I tried using --vout=xcb_glx, but the log indicated that my GLX version was too low, but I couldn't rush to upgrade it

vlc_media_player:
[mas_glx_vlc_media_player.log](https://github.com/caprica/vlcj/files/2659858/mas_glx_vlc_media_player.log)
my program:
[mas_glx.log](https://github.com/caprica/vlcj/files/2659859/mas_glx.log)

**Comment by implementt** [comment]
my lab computer use xcb_x11 too.but it is fast

vlc_media_player:
[lab_vlc_media_player.log](https://github.com/caprica/vlcj/files/2659874/lab_vlc_media_player.log)

**Comment by implementt** [comment]
i always use remote screen,may be slow is normal,
I'll try again tomorrow.Thank you.

**Comment by caprica** [comment]
I don't know what you expect me to do quite honestly. It is extremely unlikely that anything can be done in vlcj to address your performance problem.
