### ISSUE TITLE
marquee new line

### ISSUE THREAD

**Issue by implementt** [caprica/vlcj#656]
https://wiki.videolan.org/Documentation:Play_HowTo/Format_String/

i cant't format marquee  char.
such as:
--marq-marquee=hello:$_judy
video show text:hello:$_judy
not format.
why?

**Comment by caprica** [comment]
Your question is too minimalist and not clear, what exactly are you doing here? Are you using the VLC command-line? Did you try those options with the VLC command first? Is it vlcj media options when you call mediaPlayer.playMedia()? What are all your other options?

**Comment by implementt** [comment]
Marquee marquee = Marquee.marquee();
                    marquee.location(0, 0);
                    marquee.size(60);
                    marquee.text("hello:$_judy");
                    mediaPlayerComponent.getMediaPlayer().setMarquee(marquee);
                    mediaPlayerComponent.getMediaPlayer().enableMarquee(true);
$_ not work
![image](https://user-images.githubusercontent.com/11623035/49751561-a1aecd80-fce8-11e8-8163-b4893990c273.png)

**Comment by implementt** [comment]
soory

**Comment by caprica** [comment]
Try the same options on the VLC command-line to make sure it works.

What vlcj does is to take the string you set on marquee.text(...) and send it directly to LibVLC via the native method call libvlc_video_set_marquee_string. It may be the case that it simply is not possible to use those marquee formatting options via this LibVLC API call.

If you try those same options on the command-line it would be useful to know if it worked there or not.

**Comment by implementt** [comment]
same
Probably because of VLC

**Comment by caprica** [comment]
If you look at the VLC command-line help for marquee (VLC -H | grep marquee) it gives a hint that you can use things like %Y %M %D and so on, but it does not list all possible options, nor does it say anywhere that you can use any "$" formatters.

In fact, if you look again at the page you linked in your first post, it is not completely clear but...

--marq-marquee is under the section named "Time" and there it says you can use %Y %m %H and so on.

The $ format strings are in the next section named "Input Meta". That section does NOT say you can use those $ format string with --marquee-marq - they can only be used with --input-title-format, --snapshot-path and so on.

So the answer is simply that you can not use the $ format strings with marquee. There's no bug.

**Comment by caprica** [comment]
However, there is some good news...
![marquee-test](https://user-images.githubusercontent.com/1385879/49753328-ee73b380-fcaa-11e8-8845-76be77146fef.png)
Here my marquee is A then a newline then B.

The trick is to simply to use "\r\n" in your string where you want the newline. Note that "\n" by itself does NOT work, at least not on Linux.

So, in this case...

`marquee.text("hello:\r\njudy");`

...works!

**Comment by implementt** [comment]
When line breaks differ in length, they are not aligned,
Use Spaces to solve this problem
but sometimes the length of each line of content is different,
Spaces don't solve this problem perfectly

https://forum.videolan.org/viewtopic.php?f=32&t=147340

**Comment by implementt** [comment]
thanks,Let me think of something else

**Comment by caprica** [comment]
I don't know, it looks to me like if you use a combination of the x-offset, y-offset, position (center, top-left etc) you can get good results *without* padding with spaces.

![marquee-2](https://user-images.githubusercontent.com/1385879/49788561-88764300-fd21-11e8-95a3-385c0c01d6e8.png)

Marquee is intended for small amounts of simple text, it is not a complex or extensive text-layout and formatting system.

**Comment by caprica** [comment]
You could also think about using a heavyweight window overlay and do your own Java2D rendering into that. But be warned, that approach may have critical limitations (if you need to move the video window around, the overlay window will lag the position of the video window while dragging, for example, but it would work really well for full-screen).

**Comment by implementt** [comment]
hi
thanks very much.
please show your code,

**Comment by implementt** [comment]
![image](https://user-images.githubusercontent.com/11623035/49796679-4d532e80-fd78-11e8-8df3-c5c32530ac47.png)

**Comment by caprica** [comment]
You should probably set the "position" attribute on the marquee to be top-left and maybe adjust the x and y location a little bit. It's as simple as that. There's no magic code to show, I simply used the vlcj MarqueeTest example with a fixed string.

I suppose it's something like:

```
    marquee()
        .text("This\r\nLooks\r\nNicely Lined Up\nTo me!")
        .location(0, 50)
        .position(libvlc_marquee_position_e.top_left)
        .enable(true)
```
Depending on which "position" you use, the text will be aligned/justified that way. So, if you use top, centre or bottom the text will be centre-aligned horizontally and if you use left it will be left-aligned and so on.

You should probably play around with position, and x,y to get the effect you want.

**Comment by implementt** [comment]
use linux and vlcj MarqueeTest success.

**Comment by implementt** [comment]
but same code
windows os no change.
how every,my program run on linux

**Comment by implementt** [comment]
Windows
![image](https://user-images.githubusercontent.com/11623035/49800434-71b40880-fd82-11e8-904f-b38539eb4ec8.png)
Linux:
![image](https://user-images.githubusercontent.com/11623035/49800453-7ed0f780-fd82-11e8-8cd5-efaf162eb5d7.png)
