### ISSUE TITLE
Update Javadoc on marquee to show how to do newlines

### ISSUE THREAD

**Issue by caprica** [caprica/vlcj#657]
It is not actually obvious how to get VLC to render newlines in the marquee text, even though the answer is very simple.

So, update the Javadoc with a mention on how to properly do this.

See #656.

**Comment by implementt** [comment]
Please check my new reply
https://github.com/caprica/vlcj/issues/656

**Comment by caprica** [comment]
Reminder in the Marquee Javadoc to remove the $ formatting comment.

**Comment by caprica** [comment]
Done at cb6b764c3b940a6eb3d872f5417150988793c504
