### ISSUE TITLE
rotate each image ?

### ISSUE THREAD

**Issue by ivanooi** [caprica/vlcj#661]
Hi,

  Is there any way that I can rotate each of the images using options?

I had tried 
        String[] options = { "--transform-type={90}"};

        mediaPlayer.playMedia( file, options);        
 
but not working..

Thanks

**Comment by caprica** [comment]
Maybe try the suggestions here http://stackoverflow.com/questions/36227391/how-to-rotate-a-video-placed-on-a-jframe-vlcj, it's possible that you can set the same media options when you invoke playMedia but sometimes these things must be set on the MediaPlayerFactory instead.

**Comment by ivanooi** [comment]
Rotating using playMedia option, no, cannot...
The example that you gave me, it using Factory to do the job... so, I'm stuck

**Comment by ivanooi** [comment]
Anyway, I had changed my mind. Loading image using VLC for Windows speed not so appealing. 
so, I just used back SWT to display images. almost is the same speed.
