### ISSUE TITLE
MediaPlayerFactory with SwtEmbeddedMediaPlayer

### ISSUE THREAD

**Issue by ivanooi** [caprica/vlcj#662]
Anyway that SwtEmbeddedMediaPlayer can be use in MediaPlayerFactory ?

Thanks and happy new year :-D

**Comment by caprica** [comment]
So the good news is that with vlcj-4 this will become trivial to use.

In fact, there will be no need for an SwtEmbeddedMediaPlayer at all - you will only need an implementation of a CompositeVideoSurface and it will work with the normal EmbeddedMediaPlayer.

I will be updating the https://github.com/caprica/vlcj-swt-swing project accordingly in due course, and eventually it should become a separate artefact deployed to Maven Central.

The only real blocker will be getting the SWT dependencies integrated into the pom for all OS and architectures.

**Comment by ivanooi** [comment]
great! thx!

**Comment by caprica** [comment]
When vlcj 4.0.0 is released, this project will follow: https://github.com/caprica/vlcj-swt

Demo projects https://github.com/caprica/vlcj-swt-demo and https://github.com/caprica/vlcj-swt-swing
