### ISSUE TITLE
javadoc option -html5 not available with java8

### ISSUE THREAD

**Issue by HorstFiedler** [caprica/vlcj#695]
pom.xml  line 216
`        <additionalOptions>-html5</additionalOptions>`
creates maven error 
> cd /home/xxx/git/vlcj-4.x; JAVA_HOME=/opt/jdk1.8.0_121 /opt/netbeans-8.2/java/maven/bin/mvn install
> Scanning for projects...
>                                                                       
>------------------------------------------------------------------------
>Building vlcj 3.12.1-SNAPSHOT
>------------------------------------------------------------------------
> ........
> Unable to parse configuration of mojo org.apache.maven.plugins:maven-javadoc-plugin:3.0.1:jar for parameter additionalOptions: Cannot assign configuration entry 'additionalOptions' with value '-html5' of type java.lang.String to property of type java.lang.String[]

The parsing error can be fixed by using
`                <additionalOptions>
                      <additionalOption>-html5</additionalOption>
                  </additionalOptions>
`
instead, but then build fails with
> Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.1:jar (attach-javadocs) on project vlcj: MavenReportException: Error while generating Javadoc:
Exit code: 1 - javadoc: error - invalid flag: -html5

**Comment by caprica** [comment]
So... right now I need to build vlcj with OpenJDK 10 and cross-compile to 1.6. It looks like the -html5 option was introduced some time after OpenJDK 8 which is what you're compiling with.

Obviously if you're building vlcj yourself just remove that option from the pom.

I'm not sure what to do about it going forward, I don't really want to bother with per-JDK profiles in the pom.

**Comment by caprica** [comment]
Or you could just use the libraries from Maven Central of course.

**Comment by caprica** [comment]
I'm going to close this, for the "official" vlcj build I'll just say that option is required.

If I put in multiple profiles then in theory I don't get a guaranteed repeatable build for the same vlcj version, and I don't want different qualified versions of the Javadoc artefact

Not ideal, I know.

I also question how many people really need to be building vlcj themselves, is it enough to warrant cluttering the pom and complicating the build, I doubt it.

This can be reopened if it becomes a significant problem.
