### ISSUE TITLE
Get video dimensions

### ISSUE THREAD

**Issue by mjgmarcio** [caprica/vlcj#70]
hello,

I want to get the video dimensions, but when I do:  System.out.println(mediaPlayerComponent.getMediaPlayer().getVideoDimension());
gives me a "null".

And when I do:         System.out.println(mediaPlayerComponent.getPreferredSize());
gives me the size of the painel instead of the real video resolution.

Here is the code:

```
    private JFrame frame;
    private final EmbeddedMediaPlayerComponent mediaPlayerComponent;

  public static void main(String[] args) {
  //  NativeLibrary.addSearchPath( RuntimeUtil.getLibVlcLibraryName(), "C:\\Program Files\\VideoLAN\\VLC" );
  //  Native.loadLibrary(RuntimeUtil.getLibVlcLibraryName(), LibVlc.class);
    new vlcPlayer().start("D:\\Documents\\Escola\\Tese\\AVIs\\MobileECalendar_768x432_50.avi"); //712testclipNTSC
  }

  private vlcPlayer() {

        mediaPlayerComponent = new EmbeddedMediaPlayerComponent();
        JButton b= new JButton("b");
        JPanel cp = new JPanel();
        cp.setLayout(new BorderLayout());
        cp.add(mediaPlayerComponent, BorderLayout.CENTER);
        cp.add(b, BorderLayout.EAST);

        frame = new JFrame("vlcj Media Statistics");
        frame.setLocation(100, 100);
        frame.setSize(1000, 400);
        frame.setContentPane(cp);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);

  }
    private void start(String mrl) {
        mediaPlayerComponent.getMediaPlayer().playMedia(mrl);
       System.out.println(mediaPlayerComponent.getMediaPlayer().getVideoDimension());
           System.out.println(mediaPlayerComponent.getPreferredSize());
    } 
```

Can you help me on  this subject?
many thanks in advance.

**Comment by atripp601** [comment]
In case anyone is interested, here is some code to resize and display the frame once we get the video size:
`        mediaPlayer.events().addMediaEventListener(new MediaEventAdapter() {
            @Override
            public void mediaParsedChanged(Media media, MediaParsedStatus mediaParsedStatus) {
                Dimension videoDimension = mediaPlayer.video().videoDimension();
                if (videoDimension != null) {
                    System.out.println("parsed:" + videoDimension);
                    mediaPlayerComponent.setPreferredSize(videoDimension);
                    frame.pack();
                    frame.setVisible(true);
                }
            }
        });`

**Comment by caprica** [comment]
That is OK, but, IMO it is better to use the elementary stream selected event.
