### ISSUE TITLE
EmbeddedMediaPlayer with a Window should work on OSX

### ISSUE THREAD

**Issue by caprica** [caprica/vlcj#718]
Get this working if possible.

In theory, the sticking point is getting the native window handle from the java.awt.Window.

This solution is still not optimal as the ideal is to play in a java.awt.Canvas, but playing in a java.awt.Window should be possible on OSX and might be good enough for some use-cases (e.g. having a dedicated Window for video output and having other UI components arrange themselves in relation to that Window).

Related to #594, and made possible by #412.

**Comment by caprica** [comment]
Need to be mindful of JDK 1.6 on OSX, because 1.6 still has heavyweight AWT the "normal" approach of using a Canvas will work.

There is currently nothing in vlcj-4 that would require JDK 1.7, so it would be nice to still have option of supporting 1.6.

**Comment by caprica** [comment]
Confirmed an EmbeddedMediaPlayer with a ComponentVideoSurface using a Window works on OSX with contemporary JDKs.

So, with certain limitations, we can have optimal heayweight media player rendering working on OSX again.

Hooray!

**Comment by caprica** [comment]
Regarding the limitations...

It seems that if you resize the Window containing the video, the video does not resize to match - instead it renders at the original size.

So whilst a lot of progress has been made here to get optimal media playback on OSX, this is still a crippling limitation.

**Comment by caprica** [comment]
Currently the implementation as written should support 1.6.

**Comment by caprica** [comment]
For the resize failure, enabling the VLC native log shows that VLC receives a resize event but the values it receives are those for the original window size when the video started playing - these values do not change as the java.awt.Window changes size.

**Comment by acely** [comment]
Run into the same resize issue here.
Seems like that vlc can only render to that "window surface", but can't alter that surface, since that surface is still controlled by jvm.

So maybe when resizing, detach the surface from vjc and when resize is done, re-attach it to vlc will work? (I'm just guessing here)

**Comment by acely** [comment]
Oh dear..

**Comment by caprica** [comment]
Well, right now using a fixed-sized Window, or some other nasty workarounds like stopping/restarting on a resize is perhaps a better solution than existed before. At least it gives applications the option of embedding a heavyweight media player solution.

The changes described in this ticket will be delivered with vlcj 4.0.0.

I'll close this ticket now as I expect to do no further work on it. A new ticket can be opened if a viable solution or workaround is found.

**Comment by caprica** [comment]
The last possible chance for this I think may lie with Apple EAWT's CocoaComponent.

The purpose of the class is to embed a native NSView into an AWT application. The handle of that NSView is then used in the call to libvlc_media_player_set_nsobject. Some special message passing is also required.

Implementing CocoaComponent needs some native code and JNI.

In theory, I think it is possible.

In practice, I think I have already looked into this a long, long, long, long, time ago and didn't get far. The main problem is that web-searches don't return much of any use on this subject, and I did not find any example code.

I am also unsure as to whether the resize issue mentioned above would still be a problem.

Speaking personally, it just isn't worth the time and effort involved to pursue this.

Probably for OSX, the OpenGL solution will be best, I don't know.

The CallbackVideoSurface stuff does work quite well now and is probably as efficient as it can be, so that too is an option.

**Comment by caprica** [comment]
In fact, EAWT CocoaComponent is gone for good, supposedly this leaves the only possible vain hope in  CALayer-based JAWT embedding.

**Comment by caprica** [comment]
I have seen some hints in the VLC mailing list that some work on resize notifications may be being looked at, so this situation may improve in the future.

On the other hand, the "best" solution on OSX may end up being the OpenGL callbacks in an LWJGL or JOGL or similar application.
