### ISSUE TITLE
apply normvol

### ISSUE THREAD

**Issue by Will021193** [caprica/vlcj#721]
I'm trying to use the volume normalizer via mediafactory but nothing happened... Am I missing something? I tested the parameters in the cmd and work as intended. ("--rate=2" just 2x speed the video, I'm using that for test the string and that parameter work fine)

This is the way I'm calling the parameters

`public class MediaPlayer {
	
    // We created public instances of Embedded MediaPlayer since we use it in other classes
    public EmbeddedMediaPlayer embeddedMediaPlayer;
    public EmbeddedMediaPlayer embeddedMediaPlayerMp3;

    public String pathSongs;
    protected static final String[] standardMediaOptions = {
               "--rate=2",
                "--audio-filter=normvol",
                "--norm-buff-size=10",
                "--norm-max-level=1"};

    // We created a JPanel container for our player
    private JPanel mediaPlayerContainer;

    // In the constructor we start our variables
    public MediaPlayer(String pathVLC, String pathSongs) {
        System.out.println("entra al media para cargar argumentos");
        this.pathSongs = pathSongs;

        // We call the native libraries of VLC, passing them as parameters the path where VLC is installed
        try {

            NativeLibrary.addSearchPath(RuntimeUtil.getLibVlcLibraryName(),pathVLC);
            Native.loadLibrary(RuntimeUtil.getLibVlcLibraryName(),LibVlc.class);

            // A Canvas is created
            Canvas canvas = new Canvas();
            canvas.setBackground(Color.WHITE);
            mediaPlayerContainer = new JPanel();
            mediaPlayerContainer.setLayout(new BorderLayout());
            mediaPlayerContainer.add(canvas,BorderLayout.CENTER);
            

            // Instantiating a MediaPlayerFactory. Create an embedded player and add our canvas
            //System.out.println(DEFAULT_FACTORY_ARGUMENTS);
            MediaPlayerFactory mediaPlayerFactory = new MediaPlayerFactory(standardMediaOptions);
            embeddedMediaPlayer = mediaPlayerFactory.newEmbeddedMediaPlayer();
            embeddedMediaPlayer.setVideoSurface(mediaPlayerFactory.newVideoSurface(canvas));
            embeddedMediaPlayerMp3 = mediaPlayerFactory.newEmbeddedMediaPlayer();
        } catch(UnsatisfiedLinkError error) {
            // If there is an exception is that the VLC directory is not found
            JOptionPane.showMessageDialog(null,"No se encuentran las librerias de VLC, intente reinstalar VLC y configure el directorio correctamente. Si el problema persiste y su version de Java es de 64Bits pruebe instalando VLC de 64 Bits.");
            System.exit(1);
        }
    }`

**Comment by caprica** [comment]
When you say nothing happened, what specifically do you mean?

First thing to do is add "-vv" or "-vvv" to your factory arguments and grab the console output.

Then pass those same options to VLC via the command line and grab the console output.

Compare the differences in the output.

**Comment by caprica** [comment]
You can also try passing the filter options when you invoke playMedia on your media player. Sometimes those options need to be set differently.

To be clear I mean the "norm" options only, leave the audio-filter option on the factory.

**Comment by Will021193** [comment]
Nothing happened mean that the volume normalization it's no applying to the audio on videos and mp3 files. Basically with that setting on my code the audio should sound lower, works fine with command line but no results with the code. The console output look the same between factory arguments and command line, I'm going to try what you said about the norms via playmedia and the audio filter via factory

**Comment by Will021193** [comment]
I passed the audio-filter parameters on the factory and the "norm" on playmedia and same result, settings not applying

**Comment by caprica** [comment]
In the vlcj version, when you check the native log, do you see any messages related to this filter or not?

You really need to carefully study those native logs.

The thing is, and I say this a LOT on problems like this, vlcj doesn't care about these filters. It passes your arguments unchanged to LibVLC and that's all. So, if it doesn't work via the factory, you likely missed some other required argument.

The answer is always the same, either pass the arguments via the factory, or pass them via playMedia. There's literally nothing else that can be done.

**Comment by caprica** [comment]
I should also add, that VLC themselves make no guarantee that *any* of those command-line options will work when using LibVLC.

**Comment by caprica** [comment]
So indeed I tried this and saw the same.

The native output from VLC shows the normvol filter being applied, but the same thing is missing from the LibVLC version.

A google search "VLC --audio-filter" yields this very similar issue: https://forum.videolan.org/viewtopic.php?t=143056

You can see the response there from the VLC dev that says LibVLC sets up audio filters internally and what you're trying is not supported.

So I suppose someone needs to write some API to expose the normvol filter in VLC, unfortunately.

I think you will get nowhere with this, I'm afraid.

**Comment by caprica** [comment]
Closing the issue since there is nothing that can be done.
