### ISSUE TITLE
Play audio and video

### ISSUE THREAD

**Issue by runegame** [caprica/vlcj#733]
Hello people of Caprica.

I have a Rockola program widely used in Colombia and one of the options your users ask me is that the audio files have a video without background audio. I made a version that with two instances of the player embedded to this, in one reproduces the audio, and in the other the video without sound.

Is this the best option? or is there a way to reproduce both in the same instance?

**Comment by caprica** [comment]
I'm sorry, but I don't quite understand the question.

**Comment by caprica** [comment]
Closing due to lack of follow-up.
