### ISSUE TITLE
Getting rid of the black frames when loading a new video

### ISSUE THREAD

**Issue by Remonell** [caprica/vlcj#760]
Hi caprica, 
may I ask for another advice from you? I am having issues to draw on a canvas, that is invisible. The whole problem I posted on stackoverflow but sadly did not get any answers yet.
[https://stackoverflow.com/questions/54517331/playing-4k-videos-with-vlcj-one-after-the-other-without-black-frames-inbetween](https://stackoverflow.com/questions/54517331/playing-4k-videos-with-vlcj-one-after-the-other-without-black-frames-inbetween)

I already wasted 3 days to find a way to solve my problem. Maybe you have done something similar before and you can hint me in the right direction.

Kind regards

**Comment by caprica** [comment]
If you want me to look at an issue here, you should post it here.

In any case, your posted link is broken. I did see your stackoverflow post the other day, but your problem statement was not clear to me.

**Comment by Remonell** [comment]
Sorry about the broken link. I fixed it. I can copy the contents here anyways and also say a few more words what the problem exactly is.

For the last few days I have been trying to play multiple 4k videos, with the java vlcj library, after each other without the black (buffering?) frames inbetween them.

My idea was, that I place a JLabel over the canvas for the EmbeddedVideoPlayer. When I click the button for next video, I will pause the ongoing video -> make an image of the frame in that moment -> draw that image on the JLabel -> make JLabel visible. When the next video actually started, I will make the JLabel invisible again. Ideally the user will never have to look at black frames.

```
public class FullscreenPlayer {
    public final EmbeddedMediaPlayerComponent mediaPlayerComponent;
    public final EmbeddedMediaPlayer mediaPlayer;
    public JFrame frame;

    public JLabel overlayLabel;

    boolean posChanged = false;
    String fhdVideoPath;

public FullscreenPlayer(int screen) {
    System.setProperty("sun.awt.noerasebackground", "true");

    GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
    GraphicsDevice[] gs = ge.getScreenDevices();
    Rectangle bounds = gs[screen].getDefaultConfiguration().getBounds();

    final String[] VLC_ARGS = { "--intf", "dummy", /* no interface */
            /*"--vout", "dummy",  we don't want video (output) */
            "--no-audio", /* we don't want audio (decoding) */
            "--no-snapshot-preview", /* no blending in dummy vout */
    };


    MediaPlayerFactory mediaPlayerFactory = new MediaPlayerFactory(VLC_ARGS);

    Canvas videoCanvas = new Canvas();
    videoCanvas.setBounds(0, 0, bounds.width, bounds.height);
    videoCanvas.setIgnoreRepaint(true);

    overlayLabel = new JLabel();
    overlayLabel.setBounds(0, 0, bounds.width, bounds.height);
     overlayLabel.setBackground(Color.black);
    overlayLabel.setVisible(true);
    overlayLabel.setIgnoreRepaint(true);

    Panel p = new Panel();

    p.setLayout(null);
    p.setBackground(Color.black);
    p.setIgnoreRepaint(true);

    p.add(overlayLabel);
    p.add(videoCanvas);

    frame = new JFrame();

    mediaPlayerComponent = new EmbeddedMediaPlayerComponent() {
        private static final long serialVersionUID = 1L;

        @Override
        protected FullScreenStrategy onGetFullScreenStrategy() {
            return new Win32FullScreenStrategy(frame);
        }
    };

    // mediaPlayer = mediaPlayerComponent.getMediaPlayer();
    mediaPlayer = mediaPlayerFactory.newEmbeddedMediaPlayer();

    mediaPlayer.setVideoSurface(mediaPlayerFactory.newVideoSurface(videoCanvas));

    mediaPlayer.addMediaPlayerEventListener(new MediaPlayerEventAdapter() {

        @Override
        public void positionChanged(MediaPlayer mediaPlayer, float newPosition) {
            super.positionChanged(mediaPlayer, newPosition);

            if (!posChanged) {
                System.out.println("Position changed!");
                posChanged = true;
                overlayLabel.setVisible(false);
            }
        }
    });

    // frame.add(videoCanvas);
    frame.setLayout(new BorderLayout());
    frame.add(p, BorderLayout.CENTER);
    frame.setSize(bounds.width, bounds.height);
    frame.setLocation(bounds.x, bounds.y);
    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    frame.setBackground(Color.black);
    frame.setVisible(true);
    frame.setLocationRelativeTo(null);
    frame.setIgnoreRepaint(true);
    frame.addWindowListener(new WindowAdapter() {
        @Override
        public void windowClosing(WindowEvent e) {
            mediaPlayer.release();
            mediaPlayerFactory.release();
            System.exit(0);
        }
    });

    frame.addKeyListener(new KeyAdapter() {
        @Override
        public void keyPressed(KeyEvent e) {
            switch (e.getKeyChar()) {
            case 'q':
                overlayLabel.setVisible(!overlayLabel.isVisible());
                break;
            case 'w':
                BufferedImage img = mediaPlayer.getSnapshot();
                overlayTest(img);
                break;
            }
        }
    });

    mediaPlayer.setFullScreenStrategy(new Win32FullScreenStrategy(frame));
    mediaPlayer.setFullScreen(true);
}

public void start(String uhdPath, String fhdPath) {
    fhdVideoPath = fhdPath;
    mediaPlayer.pause();

    try {
        BufferedImage img = mediaPlayer.getSnapshot();

        if (mediaPlayer.getTime() > 0 || mediaPlayer.getTime() != -1) {
            overlayTest(img);
        }
        PresentationStarter.fhdInstance.mediaPlayer.pause();
        mediaPlayer.playMedia(uhdPath);
        posChanged = false;
    } catch (Exception e) {
        e.printStackTrace();
    }

}

public void overlayTest(BufferedImage image) {
    double i_h = image.getHeight(null);
    double i_w = image.getWidth(null);
    double c_w = frame.getWidth();

    int imgHeight = (int) (i_h / (i_w / c_w));
    int imgWidth = (int) c_w;

    BufferedImage resizedImage = PresentationStarter.resize(image, imgWidth, imgHeight);
    ImageIcon imgIcon = new ImageIcon(resizedImage);

    overlayLabel.setIcon(imgIcon);
    overlayLabel.setVisible(true);

    // The repaint happens after this point.
}

}
```

I do not see any vlcj debug messages when I play the videos. Only when I close the application. But that might be because I am not garbage collecting properly.

I am thankful for any kind of help.

Kind regards

**Further simplified informations:** Basically I have a canvas over another canvas (inspired by your nontransparent overlay test class). And I want to draw on the overlay canvas first and then make it visible, because if its visible first, then you will see a black canvas for the fraction of a second, before the image appears that I want to draw on the canvas. I am not sure if it is possible at all the to draw on a canvas that is invisible.

**Comment by caprica** [comment]
I'm still unclear on this, honestly. 

If I understood your problem, this might work...

The simplest solution is to paint into a JPanel, and swap the JPanel for your video Canvas.

I've done this using a CardLayout before, the vlcj-player project does something like this.

Have a CardLayout with two "views", one is a JPanel that you paint your image into, the other is the Canvas for your video. One view in the layout is called "picture", one view is called "video".

When you get a media player finished (or stopped, I suppose) event, paint your picture and tell the card layout to swap to the "picture" view.

When you get your media player ready event, tell the card layout to swap to the "video" view.

This would be much easier than messing around with overlays (which are always problematic).

And yes, you can render/paint a component that is not currently "visible" on the screen.

**Comment by caprica** [comment]
Remember to update your components from the Swing EDT, especially if you see strange things happening.

**Comment by caprica** [comment]
Another approach... (this depends on any potential audio clashes)

When your first video gets to position > 0.98% (or whatever you decide), play your next video in another media player and when you get the playing event, immediately pause that video. Actually you could start playing your next video immediately, I guess it doesn't matter.

Then, wait for your first media player to raise "finished", then you unpause your other video.

So you have two media players working one after the other.

The drawback of this approach is that you might get a click or burst of sound from the next video.

**Comment by Remonell** [comment]
Your first approach is exactly what I was looking for. I will try it out. 
Your second approach sounds even better. No frozen images. How would you achieve your second approach? Also with CardLayout and two canvas?

**Comment by caprica** [comment]
I don't know, that's the fine detail of the solution, I can't give you everything :)

I have to add, I have been doing quite a bit of work with vlcj recently, and what I am noticing is without me doing *anything* special, if I let a video play to the end it *will* stop on the last frame.

**Comment by Remonell** [comment]
Yes I experience the same. That is not the issue. When I play a 4K Video on the mediaplayer and tell him at 30% of the video to play another 4K video. Then the viewer will see black frames in between the 2 videos that do not belong to any of those videos. I will make a quick video of the phenomenon.

**Comment by caprica** [comment]
You don't need to make a video, I think I understand now. Hopefully I gave you some ideas to help.

**Comment by Remonell** [comment]
[https://youtu.be/vSUk4L0VGMI](https://youtu.be/vSUk4L0VGMI)

I have diffrent buttons that load diffrent 4K  videos in the same player.

**Comment by caprica** [comment]
OK, from what I can tell on that video, this is what I would do...

Two media players, working one after the other.
Use a card layout but this time one for each video player, you don't need a picture view.
Play video in first media player.
Press button to play second video.
Start the video in the second media player.
When you got a media player ready event in the second media player, swap the card layout and stop the first media player.

**Comment by caprica** [comment]
Be warned if you try my latest idea that there can sometimes be problems with multiple media players simultaneously in the same app. In which case the previous ideas would be better.

**Comment by Remonell** [comment]
That sounds good! I will try that the very first :) Thank you very much, caprica!

**Comment by caprica** [comment]
Please report back if you have success. I'm on a quest to close these issue... :)

**Comment by Remonell** [comment]
Yeeeees! Thanks a lot caprica. I tested your approach with a simple test case in[ it works out perfectly](https://www.youtube.com/watch?v=_VsEG4kPJ7c&feature=youtu.be). 
At first I tried to add the 2 canvases directly to the CardLayout-Panel(not a JPanel). When I tried to play media on the canvas that was not visible it gave me again the error message, that I cannot draw on a surface that is not visible. After I put both canvases in a separate JPanel, it worked. 
I am little surprised, because everywhere you get warned not to mix AWT and Swing components.

Anyways, thanks again. I will implement that approach fully into my project now and hope there will be no more problems.

**Comment by caprica** [comment]
People who warn you to not mix AWT and Swing components are lazy or ignorant, frankly.

There are some small limitations when you mix AWT and Swing, but fundamentally there is nothing "wrong" about doing it.

A brief suggestion on why it might not have worked without JPanel, you may have had to a preferred size on the component - by default, without a LayoutManager, its size may be (0,0) and that can cause a failure. But honestly, I would have used a JPanel too, use heavyweight components only when you need them, and here a Panel was not necessary at all.

Anyway, glad your code is working now.
