### ISSUE TITLE
libvlc swallows last few frames when video finished

### ISSUE THREAD

**Issue by Remonell** [caprica/vlcj#786]
Hi caprica,
the frame that the embeddedMediaPlayer shows when the video is finished should be the last frame but it is not. It is 5 or 6 frames before the end of the video. I tested it with a short videos where every frame shows its frame number.
This seems not to be an issue with the java library but probably with libvlc since it happens in the VLC Windows Application as well.
But maybe you know a way how to fix that. 

Kind regards

**Comment by caprica** [comment]
If it works like that with VLC, I think you're out of luck.

**Comment by Remonell** [comment]
Okay :/ Thanks for your quick reply.
