### ISSUE TITLE
XFullScreenStrategy not work in Ubuntu (with XFCE) in VLCJ 4.0.0

### ISSUE THREAD

**Issue by NatanielBR** [caprica/vlcj#817]
My uname result:

``
natan@natan-POSITIVO-MOBILE:~$ uname -a
Linux natan-POSITIVO-MOBILE 4.18.0-15-generic #16~18.04.1-Ubuntu SMP Thu Feb 7 14:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
``

My computer info:

CPU: I3 2330M
RAM: 4GB
Graphics: 1440x900 Mesa DRI Intel Sandybridge Mobile

![image](https://user-images.githubusercontent.com/22733502/53431544-83936800-39cf-11e9-80b1-dd4c3aadb1db.png)

**Comment by caprica** [comment]
In what way does it not work?

Is there an exception? Or is it simply nothing happens when you try?

**Comment by NatanielBR** [comment]
Not happens nothing

**Comment by caprica** [comment]
What happens if you run this test: https://raw.githubusercontent.com/caprica/vlcj/master/src/test/java/uk/co/caprica/vlcj/test/fullscreen/FullScreenTest.java

And you're sure there are no exceptions in your console?

**Comment by NatanielBR** [comment]
I will try

**Comment by NatanielBR** [comment]
It works, sorry for anything.

**Comment by NatanielBR** [comment]
was fail in my code

**Comment by caprica** [comment]
That's OK. Glad it's working!
