### ISSUE TITLE
DiscoveryDirectoryProvider isn't been loaded

### ISSUE THREAD

**Issue by abpthunder** [caprica/vlcj#822]
The file placed in 'services' directory must be renamed in order to work properly.

ServiceLoader will not found 'uk.co.caprica.vlcj.uk.co.caprica.vlcj.factory.discovery.provider.DiscoveryDirectoryProvider' class. The file must be called 'uk.co.caprica.vlcj.factory.discovery.provider.DiscoveryDirectoryProvider'.

**Comment by caprica** [comment]
Damn my IDE and its automatic refactoring.

Thanks for the report.

**Comment by caprica** [comment]
Fixed at 211e8c9ff52a8621cb6b35a2ab53102545413528.

I'll push a 4.0.3 release out soon enough.
