### ISSUE TITLE
Assertion failed in vlc_mutex_marked when creating a new EmbeddedMediaPlayerComponent

### ISSUE THREAD

**Issue by Nicofisi** [caprica/vlcj#824]
Hello,

I'm porting my old project to vlcj 4.0.3, and I have this Kotlin code:
```kotlin
var mediaPlayerComponent = object : EmbeddedMediaPlayerComponent() {}
```
which is the equivalent of Java's
```java
EmbeddedMediaPlayerComponent mediaPlayerComponent = new EmbeddedMediaPlayerComponent()
```
and I get this:
```
> Task :client:run
Assertion failed!

Program: C:\Program Files\Java\jdk1.8.0_172\bin\java.exe
File: ../../extras/package/win32/../../../lib/media_list_player.c, Line 110

Expression: vlc_mutex_marked(&p_mlp->mp_callback_lock)

> Task :client:run FAILED
```

I added a println before and after the mentioned line, that's how I know it's the one causing the problem I'm on Windows 10 Pro. Am I doing something wrong or is it a bug?

Here is my code: https://github.com/Nicofisi/SatisfyingPlayer/blob/dcef6b915c922fd1417db8a6a4ed34e5095704a4/client/src/main/kotlin/me/nicofisi/satisfyingplayer/PlayerFrame.kt#L80

**Comment by caprica** [comment]
You're using a pre-release of VLC 4.0.0, right?

**Comment by Nicofisi** [comment]
```gradle
dependencies {
    implementation project(':shared')
    implementation group: 'uk.co.caprica', name: 'vlcj', version: '4.0.3'
}
```

**Comment by caprica** [comment]
Please read carefully!

VLC version, not vlcj version.

**Comment by Nicofisi** [comment]
Oh, sorry, yeah I completely forgot I have installed it yesterday.

Yes I am. I assume it's not supported at all?
![image](https://user-images.githubusercontent.com/12614053/53695691-0301ac80-3dbf-11e9-8c20-920ab9aa8c31.png)

**Comment by caprica** [comment]
Well, it's a pre-release not even alpha version, so no, I'm not going to support it in vlcj (yet).

Coincidentally, I raised this ticket a few days ago:

https://trac.videolan.org/vlc/ticket/21985

**Comment by caprica** [comment]
If you want to stick with your pre-release of VLC, and you are happy to change your own copy of the vlcj source code, you should check out the vlcj-5.x branch, find the SubitemApi class and make the following changes:

 - comment out line 49 and 51, where the media list player is created
 - comment out all of the implementation in the changeMedia method in the same class

If you do this, *most* things in vlcj will work, but automatic playing of e.g. YouTube MRL's etc will NOT work anymore.

You will also get access to thumbnails and OpenGL rendering if you use the dev branch of vlcj-5.x.

**Comment by Nicofisi** [comment]
Thank you, I just downgraded to 3.0.6 for now to see if it fixes the problem and it did.

I don't really think I need the pre-release support that badly, since I installed it only to test whether it fixes some minor issue with VLC itself that it didn't. But in case I change my mind or someone else needs it, thanks for the instructions :) 

*Should I/you close the issue?*

**Comment by caprica** [comment]
No worries.

**Comment by caprica** [comment]
This has now been fixed in VLC master git, so eventually it will make its way into a build.

**Comment by Nicofisi** [comment]
Great, good to hear!
