### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by abpthunder** [caprica/vlcj#829]
Hi Mark,

I just added the dependency to vlcj 4.0.4, and downloaded its dependencies, and when i try to open a video connection I have the problem below. If i download the code and compile myself a 4.0.5-SNAPSHOT version, it works properly. 

I'm working with JDK8 in a Win10 computer.

Is there any incompatibility between openjdk10 (you used to compile) and jdk8?

```
[com.sun.jna.Native] WARNING JNA: Callback uk.co.caprica.vlcj.player.embedded.videosurface.CallbackVideoSurface$SetupCallback@8f7b7 threw the following exception 
                  java.lang.NoSuchMethodError: java.nio.ByteBuffer.limit(I)Ljava/nio/ByteBuffer;                                                                                    
                     at uk.co.caprica.vlcj.player.embedded.videosurface.ByteBufferFactory.allocateAlignedBuffer(ByteBufferFactory.java:86)                                          
                     at uk.co.caprica.vlcj.player.embedded.videosurface.ByteBufferFactory.allocateAlignedBuffer(ByteBufferFactory.java:52)                                          
                     at uk.co.caprica.vlcj.player.embedded.videosurface.NativeBuffers.allocate(NativeBuffers.java:74)                                                               
                     at uk.co.caprica.vlcj.player.embedded.videosurface.CallbackVideoSurface$SetupCallback.format(CallbackVideoSurface.java:87)
```

**Comment by caprica** [comment]
That's odd. ByteBuffer.limit(int) is in Java 1.6.

**Comment by caprica** [comment]
You're not using that "compact" profiles mechanism with 1.8 are you?

**Comment by caprica** [comment]
Just confirmed the same behaviour with 1.8.

This is so stupid.

Same as this I suppose: https://jira.mongodb.org/browse/JAVA-2559

**Comment by caprica** [comment]
Essentially, because of new covariant return types in Java 9, cross-compiling to earlier Java versions has these problems.

In the case of vlcj, it is ByteBuffer's limit() and position() methods that cause the problem. The solution is to downcast the ByteBuffer reference to Buffer:
```
if ((address & (alignment - 1)) == 0) {
    // Stupid cast required see #829
    ((Buffer) buffer).limit(capacity);
    result = buffer.slice().order(ByteOrder.nativeOrder());
} else {
    int newPosition = (int) (alignment - (address & (alignment - 1)));
    // Stupid casts required see #829
    ((Buffer) buffer).position(newPosition);
    ((Buffer) buffer).limit(newPosition + capacity);
    result = buffer.slice().order(ByteOrder.nativeOrder());
}
```
Alternatively don't use any compiler after 1.8.

**Comment by caprica** [comment]
1b4528bb8c55efad01834b26fd8db82968647573
