### ISSUE TITLE
JavaFX FileChooser

### ISSUE THREAD

**Issue by sghpjuikit** [caprica/vlcj#834]
Not an issue, only a question.

I noticed comment in 0c904e3 mentioning JavaFX FileChooser causing JVM crashes. I actually experienced this on Linux with vlcj3 (didnt realize it was vlcj related and maybe it wasnt). I think the issue went away at some point (I'll check with my contributor). Is there any more details about the issue you can share with me?

**Comment by caprica** [comment]
See #607 and the other related issues referenced therein.

**Comment by sghpjuikit** [comment]
That was quick! Thx.

I will monitor my circumstances and update the issues if anything notable pops up.
