### ISSUE TITLE
How to pause/resume a media player which is playing rtsp live source? 

### ISSUE THREAD

**Issue by VanMesure** [caprica/vlcj#836]
I try to pause it with the function player.pause(),  10 scond later I called player.play() to resume the player,  I want the plyer to play the live right now,  But it still played the video 10 scond ago.   I want to know how to skip these frames.
I'm sorry for my poor english, wish u can understand what I'm saying， thank u very mach。O(∩_∩)O

**Comment by caprica** [comment]
VLC has this option:
```
--live-caching <integer [0 .. 60000]> 
                                 Live capture caching (ms)
```

So you can try setting this value to zero.

There are two ways you can try this.

1. As a media option when you play media
2. As a LibVLC argument when you create the MediaPlayerFactory

Have a look here to see how you can set options such as that:

If you're using vlcj-3.x, http://capricasoftware.co.uk/projects/vlcj-3/tutorials/options-arguments

Or If you're using vlcj-4.x, http://capricasoftware.co.uk/projects/vlcj-4/tutorials/options-arguments

If that doesn't work, use "VLC -H" in a shell/command window and see if there's any other options there that might be relevant.
