### ISSUE TITLE
Seeking mp3 playback in rapid succession affects playback rate

### ISSUE THREAD

**Issue by sghpjuikit** [caprica/vlcj#846]
Seeking playback multiple times (+-5) very fast (every 30ms) very often results in a change of what I assume is the playback rate, responsible in a clearly discernible and incredibly annoying change in pitch, that returns to normal after several seconds after seeking. Rapid seeking like this is rare, but possible when user uses (and holds) seek hotkeys.

Reproduced with at least 2 unrelated mp3 files. Could not reproduce with several flac files.

Running on 4.0.6, very recent (month) 64-bit VLC. I haven't noticed this issue before (and I definitely would by now), but unfortunately my migration to vlcj4 was accompanied with VLC upgrade as well.

This could be VLC bug. I have also noticed some mentions of "fast" vs "precise" seeking in recent commits. I'm mentioning that also because while adopting vlcj4 I tried to use `player.controls().setTime()` only to find out it produced so incorrect seek times (off by seconds) as to be unusable. I'm using `player.controls().setPosition` now, which works.

I will try vanilla VLC playback to see if I can reproduce it in VLC. If I have time, I will also try different VLC versions with the vlcj project I encountered this in.

**Comment by caprica** [comment]
It's not just mp3 files. Video files sometimes show the same issue. I noticed this very thing just yesterday in fact with some video files.

The reality of the situation is, however, that it is extremely unlikely that anything could be changed in vlcj to mitigate this. The only thing vlcj does here is to invoke the native setTime or setPosition method as often as you tell it to.

If you can't reproduce the problem with a different format audio file, that looks much more like a problem with that particular native audio decoder module doesn't it?

By the way, the fast vs precise seeking relates to VLC 4.x, not VLC 3.x.

**Comment by sghpjuikit** [comment]
I see. I will monitor the situation and try VLC playback/versions.

> can't reproduce the problem with a different format audio file

My testing was not conclusive yet. My gut tells me this affects all formats and the fact that you reproduced this with video points there as well, right?

> By the way, the fast vs precise seeking relates to VLC 4.x, not VLC 3.x.

I am using 4.0.6 so I was right to point this as possible cause of the problem no?

PS: Once again you respond blazing fast! Respect!

**Comment by sghpjuikit** [comment]
I can confirm this affecting VLC (3.0.6) playback itself. This can be closed.

**Comment by caprica** [comment]
I respond fast because I'm working here right now, and I like to keep the issues list clear. :)

It's interesting that you found such an old bug, because I've done shed-loads of development with VLC, as you might expect, and I never noticed this happen before yesterday.

**Comment by sghpjuikit** [comment]
I never noticed this before either, which is not unbelievable, but it is strange.
