### ISSUE TITLE
Question: way to control left/right volume balance?

### ISSUE THREAD

**Issue by sghpjuikit** [caprica/vlcj#847]
I'm wondering if it is possible to do this, I was unable to find this in the code.

**Comment by caprica** [comment]
Not possible. No native LibVLC API to do it. In fact, I don't think you can even do this in the VLC application.

**Comment by sghpjuikit** [comment]
Ok. At least I am certain.

**Comment by caprica** [comment]
In theory you could some other native API to interact with the OS volume mixer.

**Comment by sghpjuikit** [comment]
That would not be per process but system wide I believe. And it would involve too much work and trickery, so I'm not going to do that. Thx for the tip though.
