### ISSUE TITLE
Native.load bug

### ISSUE THREAD

**Issue by AleksandrGurtovoy** [caprica/vlcj#848]
When i trying to start an application i had a exception 
java.lang.NoSuchMethodError: com.sun.jna.Native.load(Ljava/lang/String;Ljava/lang/Class;)Lcom/sun/jna/Library;

In the library Native uses a method called load, but there is no such method. Perhaps should be replaced by loadLibrary

**Comment by caprica** [comment]
You have wrong (outdated) JNA dependencies somewhere.

Native.loadLibrary is deprecated in contemporary versions of JNA, and Native.load is the correct replacement, so no, Native.load should not be replaced - rather, your classpath should be fixed :)
