### ISSUE TITLE
Problem with JNA on MacOS: Native.getComponentID always return 0

### ISSUE THREAD

**Issue by acely** [caprica/vlcj#851]
I'm testing the new 4.1 branch of vlcj on MacOS (Apple-Java 6, using Canvas as video surface, VLC 3.0.4), I noticed some strange thing: When using Canvas as video surface, vlc prints lots of these errors:

> [00007fd828c86570] macosx vout display error: No drawable-nsobject nor vout_window_t found, passing over.
> [00007fd8270bcef0] main video output error: video output creation failed
> [00007fd828d80650] main decoder error: failed to create video output
> [h264 @ 0x7fd82590e200] get_buffer() failed
> [h264 @ 0x7fd82590e200] thread_get_buffer() failed
> [h264 @ 0x7fd82590e200] decode_slice_header error
> [h264 @ 0x7fd82590e200] no frame!
> 
At first I thought I might got something wrong, but then I looked at the component id, it was zero! Then I created a completely new project, to test different versions of jna.
The new project only has an awt-canvas in an awt-window,:
```
Window window = new Window(null);
window.setBounds(100, 100, 500, 300);
window.setLayout(new BorderLayout());
				
Canvas canvas = new Canvas();
window.add(canvas, BorderLayout.CENTER);
window.setVisible(true);
				
System.out.println("window-id="+Native.getComponentID(window));
System.out.println("canvas-id="+Native.getComponentID(canvas));
```
And the result is:

Jna version | Java 1.6 | Java 1.8
-- | -- | --
4.1.0 | ok | x (java.lang.UnsatisfiedLinkError: Can't load JAWT)
4.5.1 | x id=0 | x id=0
4.5.2 | x id=0 | x id=0
5.2.0 | x id=0 | x id=0

(For comparison, I also tested using 1.8)

I'm so confused, what could we do for this?

**Comment by caprica** [comment]
As far as I know, it should always work on Java 1.6, even on OSX. So the reason for later JNA versions not working on Java 1.6 is an issue for the JNA project - or you can implement your own version of Native.getComponentID, have a look at the OsxComponentId class in vlcj-4.x.

It will not work on OSX on Java 1.7+ because there is no longer any heavyweight AWT on OSX - this is documented extensively in other issues in this project, and you can see it failing in your UnsatisfiedLinkError above.

**Comment by caprica** [comment]
By the way, it should make no difference which version of vlcj you're using for this - other than different versions of vlcj pull in different versions of JNA.

What I mean is, there's nothing intrinsic to vlcj code that would cause this issue.

**Comment by acely** [comment]
Say if someone must use java 1.6 on MacOS for some reason, after failed to use canvas as video surface, he might move to test the awt window as window surface. And sadly he will fail again, he will run into this error:

> Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: java.lang.NoSuchMethodException: apple.awt.CWindow.getPlatformWindow()
> 	at uk.co.caprica.vlcj.binding.OsxComponentId.getOsxComponentId(OsxComponentId.java:64)
> 	at uk.co.caprica.vlcj.player.embedded.videosurface.ComponentVideoSurface.getComponentId(ComponentVideoSurface.java:74)
> 	at uk.co.caprica.vlcj.player.embedded.videosurface.ComponentVideoSurface.attach(ComponentVideoSurface.java:62)

(In my opinion)Because the underlying GUI framework was different from java 1.6 and 1.8, and our OsxComponentId use reflect to get the component id. The root component implementation is different, so the reflect cannot find those methods.

In this case, he will only have to use a CallbackMediaPlayer.

**Comment by caprica** [comment]
Yes that is exactly correct, but someone could implement similar reflection-based code to find the native heavyweight component ID - probably by looking at the JNA 4.1.0 source code where it worked.

If you had that code, all you need to do is provide a bespoke video surface implementation for OSX and use that - and if that code was generic enough it could be added to vlcj's default video surface for OSX.

But someone else will have to do that, frankly I've spent enough time chasing ghosts on OSX to make me utterly sick of that platform.

**Comment by acely** [comment]
> By the way, it should make no difference which version of vlcj you're using for this - other than different versions of vlcj pull in different versions of JNA.
> 
> What I mean is, there's nothing intrinsic to vlcj code that would cause this issue.

That's true, there's nothing intrinsic to vlcj code.
Just let you know, and keep this documented in case someone else runs into same problem.

**Comment by caprica** [comment]
Absolutely, I am just tired of this problem of no heavyweight AWT on OSX - I have spent many, many, many hours looking at this.

On Linux and Windows the only consideration is a single native method call, on OSX the fact that we can't get an NSObject handle through Java is just crippling. I even tried using Apple's ancient EAWT classes (I forget the name of the specific class you're supposed to use, but there was basically no documentation on the web anywhere describing how to use it) and writing some bespoke Objective-C code accessed via JNI to try and embed an NSObject-based native component in Java, but I couldn't make it work. If I remember correctly I did manage to get an NSView embedded inside a Canvas, but I couldn't get the native window handle in the Java application.

LibVLC doesn't help much either, as the only API they provide for OSX is libvlc_media_player_set_nsobject.

With LibVLC 4.0.0 at least there is the option of using a native OpenGL solution which should give good performance, but it would mean building your application with a Java OpenGL library.

The other thing to note is that Eclipse SWT appears to have a solution to embedded an NSView into a Java SWT application. I did try and pick it apart to see if I could do something similar but SWT source is not easy to dive into and I never found any secret sauce in there.

I know you've been involved in these issues before so I'm glad you're still trying to make it work!

**Comment by caprica** [comment]
For completeness sake, the name of the class I couldn't remember was CocoaComponent, and I could find no useful documentation on the web anywhere for it - I found some old, old, old stuff that was not too helpful.

But in later versions of Apple's EAWT library the CocoaComponent class was removed anyway!

**Comment by acely** [comment]
Lmao, I'm also sick of the "Heavyweight-Free" Java on OSX.
But I'm also sick of one thing in Apple-Java6: very slow swing render. Seems it just use cpu to render the gui. As a result, if I use CallbackMediaPlayer, the CPU usage rises, and my laptop can cook eggs.
So CallbackMediaPlayer isn't good enough for Apple-Java6 neither.

Basically this is driving developers mad, and move to Java8, which at least has a fast render on gui, and also can use awt window surface.

**Comment by acely** [comment]
Yeah, maybe using an OpenGL library is a good way to go.

**Comment by caprica** [comment]
I just don't know what can be done.

To try and get back on point and summarise...

For the immediate problem described by this issue, look into the source code for Native.getComponentID in JNA 4.1, that should still work now on 1.6 on OSX. In theory similar code could even be added to vlcj's OSX video surface implementation so that we could still support running on 1.6 on OSX.

For the wider problem, there really is no drop-in replacement. NSObject is *gone* from AWT on OSX, so unless we can do something similar to what SWT do, or I think JOGL also has a bespoke solution for OSX, we're stuck with software rendering on OSX.

With vlcj-5 and VLC 4, we should get native performance using the new OpenGL video callbacks - but the price of this is having to build an OpenGL application to play your video rather than using JavaFX/Swing and so on. IMO OpenGL applications are kinda nasty, and it seems like a square peg and a round hole building a desktop GUI with OpenGL, but I am far from being an expert with OpenGL.

**Comment by caprica** [comment]
If you can build VLC git yourself, and the vlcj-5 branch, you can try those OpenGL callbacks now.

I even added a demo project at https://github.com/caprica/vlcj-lwjgl-demo

**Comment by caprica** [comment]
Another aside, I was really hopeful of that fix we made to at least render to a Window rather than a Canvas - but the fact the resizes aren't handled was very disappointing.

**Comment by caprica** [comment]
One more thing while I remember, isn't creating an SWT application or embedding an SWT Composite in a Swing application still a reasonable possibility on OSX? If that still works I think it would be a reasonable compromise solution, not ideal, but reasonable.

**Comment by caprica** [comment]
For anyone else reading, #205 relates.

**Comment by acely** [comment]
After a lot of digging and testing, I finally worked out a solution for this.
In short, we don't rely on jna to get the component id, here's the method I use:
```
/**
 * Component can be awt Canvas,Panel,Window,Frame,Dialog
 * This method is only for apple java 6 on MacOSX, which uses
 * apple.awt.CComponent and it's subclasses.
 * @param c must be awt component
 * @return heavyweight component id
 */
public static long getComponentNativeID(Component c) {
	try {
		Method getPeer = Component.class.getMethod("getPeer");
		Object peer = getPeer.invoke(c);
		Method getViewPtr = peer.getClass().getMethod("getViewPtr");
		Object ptr = getViewPtr.invoke(peer);
		return (Long) ptr;
	} catch (Exception e) {}
    return 0;
}
```

Detail informations: In apple's jdk6 they use CCanvas,CPanel,CWindow,CFrame,CDialog... as underlying implementation of awt's Canvas,Panel,Window... And the CComponents provides a method called `getViewPtr` which is what we looking for.

So for the OsxComponentId class you may need to deal with the `java.vendor` as well, if the vendor is apple, use this method.

**Comment by caprica** [comment]
Good work, thanks. This is something that probably should be included in vlcj. I'll add a milestone for it soon enough.

**Comment by caprica** [comment]
Actually, I don't think there is any need to bother checking JDK version or java.vendor or anything else, simply try the code heuristically and it either works or it doesn't.

**Comment by caprica** [comment]
https://github.com/caprica/vlcj-natives/commit/5bf24e2ab693bdd424f6baa9681d92404f7a8d7d

**Comment by caprica** [comment]
This will be included in the vlcj release, timescale unknown at the moment.
