### ISSUE TITLE
LibVlc seems not respecting the args that pass though MediaPlayerFactory

### ISSUE THREAD

**Issue by acely** [caprica/vlcj#853]
I'm using vlcj in my subtitle editing tool, so I use these args to prevent vlc from auto loading any subtitles, the args workd fine back when I use vlcj 3.10.1, but with vlcj 4.1 it doesn't respond to them. That means vlc still auto load subtitles after I pass these args.
The issue exists in both macosx and windows, here is my code:

```
NativeDiscovery nd = new NativeDiscovery(new MyOsxDS(),new MyWinDS(),new MyLinuxDS());
boolean found = nd.discover();
if (found) {
	String[] vlcargs = {
		"--quiet-synchro",
		"--sub-type=ass",
		"--sub-autodetect-fuzzy=0",
		"--no-sub-autodetect-file",
		"--sub-filter=logo:marq",
		"--intf=dummy"};
	MediaPlayerFactory pf = new MediaPlayerFactory(nd,vlcargs);
	Canvas videocanvas = new Canvas();
	getPlayerComponentContainer().add(videocanvas,BorderLayout.CENTER);

	long cid = MyUtil.getComponentNativeID(videocanvas);
	ComponentIdVideoSurface wvs = pf.videoSurfaces().newVideoSurface(cid);
	wvs.attach(pf.mediaPlayers().newMediaPlayer());
}
```
Am I doing anything wrong or there's indeed an issue?

**Comment by acely** [comment]
I also checked the latest vlc doc to confirm these args are still valid to vlc itself.

**Comment by caprica** [comment]
First an aside... you don't need the logo:marq sub-filter argument anymore, and intf=dummy isn't needed either.

Second, I just tried your vlcargs when creating a new MediaPlayerFactory and it works for me - the sub-titles get suppressed/not-detected/whatever.

**Comment by acely** [comment]
After I cleaned the project and rebuilt it, things just worked.
Maybe my eclipse kept an odd cache of the classes.
Thanks dude.
