### ISSUE TITLE
CallbackMediaPlayer does not render subtitles

### ISSUE THREAD

**Issue by acely** [caprica/vlcj#854]
The CallbackMediaPlayer only shows video content, subtitles won't show up.
Im using vlcj 4.1, the result is the same both in java 1.6 and 1.8.
I think it's about how vlc renders the output: my guess is that vlc renders video to a "base-layer" and then renders the subtitle(maybe also something else) to another "overlay-layer", then stack them together as a whole output. If my guess is right, then the CallbackMediaPlayer only gets it's buffered content from the "base-layer", so the subtitle is not visible.

To verify this idea, I created a 4x4 black video, and prepared an ass subtitle file. If vlc directly renders the subtitle to the video, we'll not be able to see any text, because the canvas is too small. I open this 4x4 video with vlc, and resize the player window up, guess what? The subtitle displayed sharply in the player! And even fits the resolution of my retina display.
![image](https://user-images.githubusercontent.com/5640723/56083000-138f5300-5e52-11e9-90a9-f841f665f730.png)

So I'm convinced that vlc is using more than one rendering buffer. With heavyweight components vlc can directly manipulate the component so it can add the "overlay-layer" itself. But with a callback player, maybe some code is needed to deal with this.

**Comment by caprica** [comment]
Subtitles *are* rendered by the video callbacks.

But they're not a separate "layer" in the UI, they are I suppose you could say effectively "burned in" to the video frames.

But the net effect is the same isn't it? I'm not quite sure what the actual problem is here.

**Comment by caprica** [comment]
Any follow-up?

**Comment by acely** [comment]
I'm not sure what the problem is, just create a minimal callback player and set subtitle file:
```
CallbackMediaPlayerComponent cbp = new CallbackMediaPlayerComponent();
cbp.mediaPlayer().subpictures().setSubTitleFile(sf);
```
The subtitle file is indeed loaded by vlc, because vlc prints the following log:
```
[ass] Shaper: FriBidi 0.19.7 (SIMPLE) HarfBuzz-ng 1.7.6 (COMPLEX)
[ass] Using font provider coretext
[ass] Shaper: FriBidi 0.19.7 (SIMPLE) HarfBuzz-ng 1.7.6 (COMPLEX)
[ass] Using font provider coretext
[ass] fontselect: (Hiragino Sans GB, 400, 0) -> /System/Library/Fonts/Hiragino Sans GB W3.ttc, -1, HiraginoSansGB-W3
```
But the callback media player doesn't show the subtitles.

Have you try it on windows or linux? Maybe this is another mac-shit-thing?

**Comment by caprica** [comment]
The callback player does, in normal use-cases, show sub-titles.

But if your video size is 4x4 I guess it has nowhere to render the subtitles to - clearly it tries to render subtitles within either the video surface or the constraints of the video geometry itself.

**Comment by acely** [comment]
Oh, that 4x4 video is just for the first test.
Today I'm testing using a normal 720p video, no subs shown.

**Comment by caprica** [comment]
I don't know, then!

I have a version of the vlcj-player project that uses a CallbackMediaPlayerComponent and this screenshot shows working subtitles.

![Screenshot from 2019-04-23 20-53-52](https://user-images.githubusercontent.com/1385879/56611594-0f112a00-660a-11e9-9c08-f92f519ddd40.png)

So... I dunno...

**Comment by caprica** [comment]
Closing this for now, it can be reopened if any significant update is provided.
