### ISSUE TITLE
Mute audio code that worked before but after update doesn't work anymore(multiple instances).

### ISSUE THREAD

**Issue by lordarnoud** [caprica/vlcj#858]
Hello!

We have multiple mediaPlayerComponents that we use to play multiple video's at the same time. To make this not a living hell for our users we mute all videos except for the first video. This code worked flawlessly until we updated to the newest versions of VLCJ and VLC. Now when we use the mute, it mutes all instances of the mediaPlayerComponents. Same for setting volumes to 0.
But things like skipping to a time still works for individual video's.

Code as such:
mediaPlayerComponent.mediaPlayer().audio().setMute(!firstVideo);

Hope to hear from you soon! :)

**Comment by caprica** [comment]
I am surprised you say it was working in previous versions, because as far as I'm aware volume controls have *never* been independent on any version of VLC when using multiple in-process media players.

**Comment by lordarnoud** [comment]
This is VERY odd then, maybe we had some glitch or issue with audio drivers then I guess? Is there any way to get around this issue that you are already aware of? I saw you mentioned VLCJ Pro somewhere once during my searches? Ty for the fast reply btw!

**Comment by caprica** [comment]
With multiple in-process media players there is no workaround.

Maybe you can see if VLC is using a different audio output with the newer version but it's doubtful.

vlcj-pro is a commercial only product that can help, but it's not just a drop in replacement for vlcj, you need to write your code differently. There's a free trial and user guide you're welcome to download and try from the commercial website.

**Comment by lordarnoud** [comment]
In what way would it be able to help? And after that I will close this issue btw :)

**Comment by caprica** [comment]
Rather than in-process media players they are all isolated in their own process and consequently they have their own independent audio controls. But there are limitations, I suggest you go to the commercial project page and read what's there, it's all explained.

**Comment by lordarnoud** [comment]
Ok will do, thanks! Issue closed :)
