### ISSUE TITLE
vljc v4.1: EmbeddedMediaPlayerComponent.getMediaPlayer()

### ISSUE THREAD

**Issue by hanneshorn** [caprica/vlcj#860]
Prior to vlcj v4.1 I used to call getMediaPlayer() on EmbeddedMediaPlayerComponent.
Now getMediaPlayer() is missing.

**Comment by caprica** [comment]
It's just "mediaPlayer()" now.

Personally, I prefer this style of method naming rather than having everything be a getter.

**Comment by hanneshorn** [comment]
Thanks Mark.

now I get:

The method playMedia(String) is undefined for the type EmbeddedMediaPlayer
The method stop() is undefined for the type EmbeddedMediaPlayer

**Comment by caprica** [comment]
Please have a look at the documentation. All significant API changes were documented in issues linked from the project home page, and there is Javadoc of course. And your IDE should be helping you.

**Comment by caprica** [comment]
https://github.com/caprica/vlcj/issues/681
