### ISSUE TITLE
Drop support for Java 1.6 with vlcj 5.0.0+

### ISSUE THREAD

**Issue by caprica** [caprica/vlcj#862]
Java 6 is very old.
Java 7 seems entrenched in enterprises at the moment.
At the very least we should move to Java 7, but even Java 7 is old by now.
Feedback welcome on this issue from any vlcj application developers.

**Comment by caprica** [comment]
Official Java 7 support ended in 2015.

Java 8 is the LTS release, so probably that is a reasonable target.

**Comment by s-frei** [comment]
> 
> Java 8 is the LTS release, so probably that is a reasonable target.
> 

I completely agree with this.

**Comment by scholzi100** [comment]
A lot of projects have adopted Java 11, maybe its the way to go.

**Comment by caprica** [comment]
It's tricky, I still have clients on Java 7, mostly Java 8. At the moment I doubt there's any compelling reason to jump all the way to 11 as a minimum. Currently I've not made any decision and still 1.6 is supported :-)

**Comment by xinyingho** [comment]
Most applications have moved at least to Java 8. But you can generate multi-release jar files that still supports Java 6-8 and have a proper support for Java 9+ with modules. Particularly when VLCj has bugs like this one with Java 9+: https://github.com/caprica/vlcj/issues/924

**Comment by caprica** [comment]
I would not call #924 a "bug" per se. There's something to be resolved there, but it can't be a reason for preventing the project moving to a modern JDK.

There is likely no prospect of me doing multi-release jar files.

I don't see the point to target as a baseline any release other than a LTS, so right now that's 8 or 11, right?

Anyway, this is targeted for v5.x, and that will be out when LibVLC 4.x is out, and that cold still be some considerable time away so there's no need to make the decision just yet.

**Comment by caprica** [comment]
Referencing here: https://en.wikipedia.org/wiki/Java_version_history

Java 11 is the latest LTS, the next LTS won't be until Java 17 in September 2021.

I think bumping to Java 11 for vlcj 5.x+ is reasonable, so that's what will be done.

**Comment by caprica** [comment]
With this caveat...

There are Javadoc errors when building with Java 11 - this appears to be caused by bugs in the Javadoc tool in JDK11.

I build the project using the latest JDK, but target the release at version 11.

**Comment by frankdog-dev** [comment]
Why does vlcj 5.0 stop supporting Java 8? Java 11 versions and higher are still not very popular, besides they are not on java.com
Discontinuing Java 8 will make it difficult for the user to install an application written using vlcj 5.0.

**Comment by caprica** [comment]
There are a bunch of reasons:

Java 8 general availability was 2014. Six years ago. It's in its end of life phase, at least as far as free public updates are concerned.

Java 11 LTS general availability was 2018, around 1.5 years ago. By the time VLC 4.0 is released along with vlcj 5.x that is likely to be 3+ years ago with Java 8 approaching *ten years*. If you look at the VLC 4.x milestone in their bug tracker there are many, many tickets still to do.

Modern versions of JavaFX require Java 11.
oracle.com has all JDK's up to 14 available, although I prefer AdoptOpenJDK myself because I despise Oracle licensing practices.


I also think with the new Java packaging efforts with the new JDKs it will be come much easier to bundle a contemporary JVM with your application.

Ultimately, the burden of maintaining legacy is onerous and I want to move on. 

This project is a labour of love, not my day job and time is valuable. Commercial support for maintaining legacy versions may be a possibility.

**Comment by caprica** [comment]
I would also add, the vlcj-4.4.0 API will be almost exactly the same as the vlcj-5 API. There are not that many new features for LibVLC coming with VLC 4.x.

Perhaps the most notable is new video engine callbacks (for OpenGL).

The other useful change I suppose is native generation of video thumbnails, but this can be done in vlcj-4.x already with some work.

So my point is, vlcj-4.4.0 is still viable for the foreseeable future, no one forces you to upgrade.

**Comment by caprica** [comment]
Changed my mind on all this. 1.8 and no modules is the result.

**Comment by ivanooi** [comment]
Hopefully, Java8 is the minimum requirement for VLCJ5

**Comment by caprica** [comment]
@ivanooi yes, I flirted with the module system and Java 11 but back-pedalled due to how onerous it was, so the baseline for vlcj-5 is Java8. This was the vlcj-4.5.x release stream which is now abandoned.

A side note: even at the present time there is no Java8-specific code in the vlcj-5 master branch.

**Comment by caprica** [comment]
Thinking past vlcj 5.0.0 and what will *eventually* come after that, it could very well be the case that a huge leap to Java 17 will be required as I want to drop JNA and use Panama FFI instead.

But that would be quite some considerable time in the future.

It is almost certain that any significant changes made for probably vlcj 6.0.0+FFI will where possible be backported to vlcj 5.0.0+JNA.

See #1041.
