### ISSUE TITLE
Spelling mistake in javadocs

### ISSUE THREAD

**Issue by MGlolenstine** [caprica/vlcj#871]
In the [docs](http://caprica.github.io/vlcj/javadoc/4.1.0/index.html?uk/co/caprica/vlcj/media/OptionsApi.html), the name of the method is `newNediaList`, even tho it should be `newMediaList`

**Comment by caprica** [comment]
Well spotted, thanks!

Fixed by 7be0bbd8ea7027b9cfa0bd6ad3b46d907200ce9d

It will be included in the next release.

**Comment by MGlolenstine** [comment]
You're welcome!
