### ISSUE TITLE
How to obtain audio-only MediaPlayer

### ISSUE THREAD

**Issue by sghpjuikit** [caprica/vlcj#873]
I'm attempting to avoid rendering video for video files, but I was unable to find a way.

This is how I obtain a MediaPlayer:
```
new MediaPlayerFactory(...).mediaPlayers().newMediaPlayer()
```

I read in one of the earlier issues that MediaListPlayer can achieve that so I was trying to use:
```
new MediaPlayerFactory(...).mediaPlayers().newMediaListPlayer()
```
but it appears MediaListPlayer requires do invoke:
```
...newMediaListPlayer().mediaPlayer().setMediaPlayer(...)
```
to avoid NullPointerException, which puts me right at the start.

What MediaPlayer should I use to achieve audio only playback?

**Comment by caprica** [comment]
Uhm... your latter comment sounds like a MedialistPlayer bug, if you're sure it's the case you could please raise a separate issue.

**Comment by caprica** [comment]
For audio only, use mediaPlayerFactory.newMediaPlayer() - but you also need to pass "--novideo" when you create your media player factory, see https://stackoverflow.com/questions/56312019/is-there-a-way-to-only-play-audio-from-a-video

**Comment by sghpjuikit** [comment]
Thx, the `--novideo` flag solved my issue.
This can be closed.
