### ISSUE TITLE
Show logo without playing video

### ISSUE THREAD

**Issue by hassanrazakhalid** [caprica/vlcj#874]
I am able to show logo using following code
```
Logo logo = Logo.logo()
			    .file("assests/sample-logo.png")
			    .position(LogoPosition.CENTRE)
			    .opacity(1.0f)
			    .enable();
		logo.apply(mediaPlayerComponent.mediaPlayer());
```
But it only show when video is played, can i show logo in the start when no video is played.

**Comment by caprica** [comment]
Unfortunately that can't be done. 
Nothing stops you showing a different component that displays your logo when the video is not playing, but this may not be what you want.

**Comment by hassanrazakhalid** [comment]
alright thanks
