### ISSUE TITLE
Remove "final" from MediaPlayer

### ISSUE THREAD

**Issue by CalziferFire** [caprica/vlcj#876]
I wanted to ask if it is possible to remove the final keyword from the "uk.co.caprica.vlcj.player.base.MediaPlayer" api methods (e.g. controls() or audio() ), member variables and the API classes itself?

I have an application where multiple threads are accessing the MediaPlayer simultaneously causing deadlocks. (e.g one threads executes the control commands like play or stop, another thread polls the current time)

My workaround is to use a lock object but since all api methods are final I'm forced to create something like customControls() returning my own  CustomControlsApi which isn't really a Api because also all the Api classes itself are final but a wrapper class for the MediaPlayer.
So calling play() at my CustomControlsApi will lock the monitor, delegate the call to mediaPlayer.controls().play() and finally unlock the monitor.

**Comment by caprica** [comment]
I'm not convinced it's a good idea to loosen the API design for this atypical use case.

I would instead recommend other solutions, maybe bytecode manipulation/aspects of some sort, or a simple task queue to serialise access to the media player.

For example you could quite easily use a bytecode manipulation library to dynamically create a proxy for all those API methods that did your locking.
