### ISSUE TITLE
MediaListPlayer NullPointerException

### ISSUE THREAD

**Issue by sghpjuikit** [caprica/vlcj#877]
As I reported earlier, the following
```
new MediaPlayerFactory(...).mediaPlayers().newMediaListPlayer().mediaPlayer().mediaPlayer()
```
returns null, unless

```
new MediaPlayerFactory(...).mediaPlayers().newMediaListPlayer().mediaPlayer().setMediaPlayer(...)
```
is called.

**Comment by caprica** [comment]
This is actually not as straightforward as it may seem.
I may, for vlcj-4.x at least, add a note on the Javadoc and a more useful exception if a media player instance has not been set.

**Comment by caprica** [comment]
Closing for now, may re-open in the future.
