### ISSUE TITLE
Play file within jar

### ISSUE THREAD

**Issue by hassanrazakhalid** [caprica/vlcj#881]
I am trying to read image from with in jar. i am getting the path but VLCj4 not showing it
![Screenshot from 2019-06-06 07-30-23](https://user-images.githubusercontent.com/15266641/58992179-6de2d980-882d-11e9-8cb5-ee960c811ea4.png)
File structure of my file is  in the image. The path i am getting when i run runnable jar is 
 VLC is unable to open the MRL 'file:///home/hassan/Documents/file%3A/home/hassan/eclipse-workspace/nuc-client/target/FxMaven-0.0.1-SNAPSHOT-jar-with-dependencies.jar%21/logo.png'. Check the log for details

Can some one please how to play file with in the jar and is my method is corrct

**Comment by caprica** [comment]
In your file path use zip:// instead of file://

**Comment by hassanrazakhalid** [comment]
Will i need to handle this differently when deploying build and while running with Eclipse as normal execution via eclipse the image works fine.

**Comment by caprica** [comment]
If you want to load the image from the jar, you must use the zip:// protocol whether you run from inside Eclipse or not.

If you use the file:// protocol you are not loading the image from the jar, you're loading it from probably some unpacked directory, especially if you're on Windows.

**Comment by caprica** [comment]
Actually I may be mis-remembering. I was sure this was possible but I can't get it working right now.

Anyway, this is a feature of VLC and the "MRL"s it can open. It's not specifically a problem with vlcj.

**Comment by hassanrazakhalid** [comment]
i tried with zip:/{filePath} but its still not working. Did you managed to make it work

**Comment by caprica** [comment]
I was completely sure it was possible using something like "zip://filename.zip!file.mp4", but no, I can't get it to work.

**Comment by hassanrazakhalid** [comment]
is there a way i can use relative path from root of runnable jar so VLCJ wont have to come into JAR from outside. The structure of jar is in the image
![Screenshot from 2019-06-07 05-08-19](https://user-images.githubusercontent.com/15266641/59059499-7812df80-88e2-11e9-9c01-6c9d485adaaf.png)

**Comment by hassanrazakhalid** [comment]
also will zip:// will work .jar as well ?

**Comment by caprica** [comment]
Zip and jar is exactly the same.

But it works for neither, or so it seems.

**Comment by caprica** [comment]
Honestly, just have your application at run-time unpack the logo from the jar to a temporary file and load it from the filesystem.

Then all this becomes moot.

**Comment by hassanrazakhalid** [comment]
alright thank you for help going with alternate way. I thought there is some way reading image within the JAR

**Comment by caprica** [comment]
I thought so too, but seems I was wrong!
