### ISSUE TITLE
jump back does not work properly

### ISSUE THREAD

**Issue by sense42** [caprica/vlcj#882]
when media is playing and a jumpback is called with:
embeddedMediaListPlayerComponent.mediaPlayer().controls().skipTime((long) (-10000 / ratio));

the jump back does not work every now and then. 
This can be reproduced with: 

1. pause the video
2. call jumpback
3. play video 

The Video will play without a jumbpack, even when a single frame is shown like a jumpback was done properly. 

The VLC Media Player has the same issue. If "fast seek" is selected in the codec settings this probem is solved. 
Is there any way to enable "fast seek" vlcj ?

**Comment by caprica** [comment]
Only if the fast seek setting can be made in the VLC command line.

As an aside, fast seek is coming on the LibVLC 4.0.0 API but that is likely a long way in the future.

**Comment by sense42** [comment]
mediaPlayerFactory = new MediaPlayerFactory("--input-fast-seek");

solved my problem so far. Thanks for your help!

**Comment by caprica** [comment]
Glad to hear that worked.
I might be able to use it in my own projects in fact :-)
