### ISSUE TITLE
Error shows but video playing

### ISSUE THREAD

**Issue by hassanrazakhalid** [caprica/vlcj#884]
Some times while playing video from HTTP i see following error. video continue to play. What the meaning of these errors and should i worry about these?
Envirnoment:
Ubuntu: 18.04
Ram: 8GB
INTEL Nuc Device

```
ES_OUT_SET_(GROUP_)PCR  is called too late (pts_delay increased to 5857 ms)
[00007fd4f4f3a690] main decoder error: Timestamp conversion failed for 3435001: no reference clock
[00007fd4f4f3a690] main decoder error: Could not get display date for timestamp 0
[00007fd50c34cf80] main input error: ES_OUT_SET_(GROUP_)PCR  is called too late (pts_delay increased to 5656 ms)
[00007fd504007250] prefetch stream error: cannot seek (to offset 1831564)
[h264 @ 0x7fd50480c700] Invalid NAL unit size (18968 > 6592).
[h264 @ 0x7fd50480c700] Error splitting the input into NAL units.
[00007fd50c34cf80] main input error: ES_OUT_SET_(GROUP_)PCR  is called too late (pts_delay increased to 3278 ms)
[00007fd4e000d730] prefetch stream error: cannot seek (to offset 1831564)
[h264 @ 0x7fd4e0166d40] Invalid NAL unit size (18968 > 3816).
[h264 @ 0x7fd4e0166d40] Error splitting the input into NAL units.
[00007fd50c34cf80] main input error: ES_OUT_SET_(GROUP_)PCR  is called too late (pts_delay increased to 2750 ms)
[00007fd4e020ad40] main decoder error: Timestamp conversion failed for 3535001: no reference clock
[00007fd4e020ad40] main decoder error: Could not get display date for timestamp 0
[00007fd4e020ad40] main decoder error: Timestamp conversion failed for 3535001: no reference clock
```

**Comment by caprica** [comment]
Those are native messages from VLC and can be ignored.

**Comment by caprica** [comment]
They are reporting something like network errors, I don't know what they specifically mean.

**Comment by hassanrazakhalid** [comment]
more than 5 seconds of late video -> dropping frame (computer too slow ?)
[00007f813c1c2560] main input error: ES_OUT_SET_(GROUP_)PCR  is called too late (jitter of 12262 ms ignored)
The Video im trying to play has following info. I have corei5 NUC 8GB ram

```
ffmpeg version 2.8.15 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 4.8.5 (GCC) 20150623 (Red Hat 4.8.5-36)
configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --arch=x86_64 --optflags='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic' --extra-ldflags='-Wl,-z,relro ' --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-version3 --enable-bzlib --disable-crystalhd --enable-gnutls --enable-ladspa --enable-libass --enable-libcdio --enable-libdc1394 --enable-libfdk-aac --enable-nonfree --disable-indev=jack --enable-libfreetype --enable-libgsm --enable-libmp3lame --enable-openal --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvorbis --enable-libv4l2 --enable-libx264 --enable-libx265 --enable-libxvid --enable-x11grab --enable-avfilter --enable-avresample --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib64 --enable-runtime-cpudetect
libavutil 54. 31.100 / 54. 31.100
libavcodec 56. 60.100 / 56. 60.100
libavformat 56. 40.101 / 56. 40.101
libavdevice 56. 4.100 / 56. 4.100
libavfilter 5. 40.101 / 5. 40.101
libavresample 2. 1. 0 / 2. 1. 0
libswscale 3. 1.101 / 3. 1.101
libswresample 1. 2.101 / 1. 2.101
libpostproc 53. 3.100 / 53. 3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '3d37f3241e942.mp4':
Metadata:
major_brand : mp42
minor_version : 1
compatible_brands: mp41mp42isom
creation_time : 2019-02-27 19:12:59
Duration: 00:01:14.14, start: 0.000000, bitrate: 20064 kb/s
Stream #0:0(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 125 kb/s (default)
Metadata:
creation_time : 2019-02-27 19:12:59
handler_name : Core Media Audio
Stream #0:1(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 19931 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 60k tbc (default)
Metadata:
creation_time : 2019-02-27 19:12:59
handler_name : Core Media Video
```

**Comment by caprica** [comment]
You're playing over HTTP too, right?
So network problems/congestion may be a factor.
In any case, VLC is reporting those errors, there's nothing you can do in vlcj to resolve them.

If playback is OK, I would just make sure you create your media player factory with "--quiet" and or "--quiet-synchro" and forget about them.

**Comment by hassanrazakhalid** [comment]
Yes you are right im over HTTP. 
1. Is there any option of buffering before i actually start playing video.
2. Since im using JavaFX with VLCJ4 is there any performance difference between VLCJ4 with Swing and VLCJ4 with JavaFX

**Comment by caprica** [comment]
There are buffering options for VLC, go to a command line and type "vlc -H" and have a look there.

Using the Swing approach is definitely going to have better performance than the JavaFX approach - with the Swing approach VLC is rendering you native, with the JavaFX you are rendering each frame in software.

**Comment by hassanrazakhalid** [comment]
thank you response. I decided to give JWT one more try. I am sharing the code via google drive please have look.
https://drive.google.com/file/d/1c73Z0QxQej6UsXQB3Wv6pp-GeowJmmoP/view?usp=sharing
The problem is same, after a few videos are played in full screen mode only JWT frame stops updating and then i press ALT + TAB and toggle back java application then i see the updated video, although VLC4 is already instructed to play the video by SignalR. One way you can test is like send random HTTP links of videos after some interval like 6s 10s 12s with a timer and you should be able to reproduce the error.

**Comment by caprica** [comment]
I did try and have a look at your project, but frankly it's just too complex for me to be able to pick up quickly.

If you can provide a simple standalone test-case to demonstrate your problem, and most importantly **_that I can easily run_** (without doing any work myself!) then I can maybe help you.

**Comment by hassanrazakhalid** [comment]
https://drive.google.com/file/d/1B-60yU_NfRqqIHGkHRBrdphg5xOh2W_W/view?usp=sharing
Hi i have added Unit test just goto class
VideoTest is under com.hardtone.test. Run the testcase there are 3 videos 16s, 10s, under 10s. Once all three are played they will loop back but you will notice that there will black screen randomly and UI is not updated although video is played on backend, but as soon as ALT + TAB is pressed video show.
I am using Ubuntu 18. Please let me know you need any further information.

**Comment by hassanrazakhalid** [comment]
i just did another scenario. I even tried to play files locally. Even then after playing for 2-3 minutes, then between video change, black screen is displayed and again ALT + TAB is need to refresh the UI. You can easily replace the videos path to local. Just add short duration videos to play and you will get scenario.

```
contents.add(GetVideoObject("file:///home/hassan/Downloads/sun", "-1"));
		contents.add(GetVideoObject("file:///home/hassan/Downloads/xtheia-start", "-1"));
		contents.add(GetVideoObject("file:///home/hassan/Downloads/3d37f3241e942.mp4", "-1"));
```

**Comment by hassanrazakhalid** [comment]
@caprica Were you able to reproduce scenario ?.

**Comment by caprica** [comment]
So, the first time I ran it it was fine. I let it play your streams and I reckon it played each video about three times total without any problems.

On subsequent runs it didn't seem to run so well, but it looked like network/server/streaming errors to me.

In short, I don't see the problem you described requiring ALT+TAB.

**Comment by caprica** [comment]
I just ran it again, the network problems seem to have subsided. It's running just fine here.

**Comment by caprica** [comment]
I mean it looks to me like the any problems are just network/streaming related rather than client/vlcj related.

I did see stuttering and pauses at some points, but it just looks like typical network/congestion/capacity problems.

**Comment by hassanrazakhalid** [comment]
@caprica Can you please try playing locally instead of network

contents.add(GetVideoObject("file:///home/hassan/Downloads/sun", "-1"));
contents.add(GetVideoObject("file:///home/hassan/Downloads/xtheia-start", "-1"));
contents.add(GetVideoObject("file:///home/hassan/Downloads/3d37f3241e942.mp4", "-1"));

just replace these in VideoTest.java. And play short video like 10s, 15s etc. You need to provide you own path. Let them loop 3,4 times. And are you testing in ubuntu ?. In that these will no network lag. I can share a small recording as well

**Comment by caprica** [comment]
I play local videos *all the time* and never see the problem you describe.

To answer your question, I use Linux Mint (latest version), which is a derivative of Ubuntu.

I suspect the problem is in your hardware/drivers/network-stack or your own application or your streaming server or something.

I think the onus is on you to try different hardware at your side.

I already spent quite a bit of time supporting you on this.

**Comment by caprica** [comment]
I tried a playlist of 3 local files, each one is a 5-second clip.
It's played 50+ times using your application without any problems whatsoever.

**Comment by caprica** [comment]
I watched pretty much the whole time for 10 minutes:
```
Playing Video: file:///home/mark/test1.mp4
Playing Video: file:///home/mark/test2.mp4
Playing Video: file:///home/mark/test3.mp4
Playing Video: file:///home/mark/test1.mp4
Playing Video: file:///home/mark/test2.mp4
Playing Video: file:///home/mark/test3.mp4
Playing Video: file:///home/mark/test1.mp4
Playing Video: file:///home/mark/test2.mp4
Playing Video: file:///home/mark/test3.mp4
Playing Video: file:///home/mark/test1.mp4
Playing Video: file:///home/mark/test2.mp4
Playing Video: file:///home/mark/test3.mp4
Playing Video: file:///home/mark/test1.mp4
Playing Video: file:///home/mark/test2.mp4
Playing Video: file:///home/mark/test3.mp4
Playing Video: file:///home/mark/test1.mp4
Playing Video: file:///home/mark/test2.mp4
Playing Video: file:///home/mark/test3.mp4
Playing Video: file:///home/mark/test1.mp4
Playing Video: file:///home/mark/test2.mp4
Playing Video: file:///home/mark/test3.mp4
Playing Video: file:///home/mark/test1.mp4
Playing Video: file:///home/mark/test2.mp4
Playing Video: file:///home/mark/test3.mp4
Playing Video: file:///home/mark/test1.mp4
Playing Video: file:///home/mark/test2.mp4
Playing Video: file:///home/mark/test3.mp4
Playing Video: file:///home/mark/test1.mp4
Playing Video: file:///home/mark/test2.mp4
Playing Video: file:///home/mark/test3.mp4
Playing Video: file:///home/mark/test1.mp4
Playing Video: file:///home/mark/test2.mp4
Playing Video: file:///home/mark/test3.mp4
Playing Video: file:///home/mark/test1.mp4
Playing Video: file:///home/mark/test2.mp4
Playing Video: file:///home/mark/test3.mp4
Playing Video: file:///home/mark/test1.mp4
Playing Video: file:///home/mark/test2.mp4
Playing Video: file:///home/mark/test3.mp4
Playing Video: file:///home/mark/test1.mp4
Playing Video: file:///home/mark/test2.mp4
Playing Video: file:///home/mark/test3.mp4
Playing Video: file:///home/mark/test1.mp4
Playing Video: file:///home/mark/test2.mp4
Playing Video: file:///home/mark/test3.mp4
Playing Video: file:///home/mark/test1.mp4
Playing Video: file:///home/mark/test2.mp4
Playing Video: file:///home/mark/test3.mp4
Playing Video: file:///home/mark/test1.mp4
Playing Video: file:///home/mark/test2.mp4
Playing Video: file:///home/mark/test3.mp4
Playing Video: file:///home/mark/test1.mp4
Playing Video: file:///home/mark/test2.mp4
Playing Video: file:///home/mark/test3.mp4
Playing Video: file:///home/mark/test1.mp4
Playing Video: file:///home/mark/test2.mp4
Playing Video: file:///home/mark/test3.mp4
Playing Video: file:///home/mark/test1.mp4
Playing Video: file:///home/mark/test2.mp4
Playing Video: file:///home/mark/test3.mp4
Playing Video: file:///home/mark/test1.mp4
Playing Video: file:///home/mark/test2.mp4
Playing Video: file:///home/mark/test3.mp4
Playing Video: file:///home/mark/test1.mp4
Playing Video: file:///home/mark/test2.mp4
Playing Video: file:///home/mark/test3.mp4
Playing Video: file:///home/mark/test1.mp4
Playing Video: file:///home/mark/test2.mp4
Playing Video: file:///home/mark/test3.mp4
Playing Video: file:///home/mark/test1.mp4
Playing Video: file:///home/mark/test2.mp4
Playing Video: file:///home/mark/test3.mp4
Playing Video: file:///home/mark/test1.mp4
Playing Video: file:///home/mark/test2.mp4
Playing Video: file:///home/mark/test3.mp4
Playing Video: file:///home/mark/test1.mp4
Playing Video: file:///home/mark/test2.mp4
Playing Video: file:///home/mark/test3.mp4
Playing Video: file:///home/mark/test1.mp4
Playing Video: file:///home/mark/test2.mp4
Playing Video: file:///home/mark/test3.mp4
Playing Video: file:///home/mark/test1.mp4
Playing Video: file:///home/mark/test2.mp4
Playing Video: file:///home/mark/test3.mp4
Playing Video: file:///home/mark/test1.mp4
Playing Video: file:///home/mark/test2.mp4
Playing Video: file:///home/mark/test3.mp4
Playing Video: file:///home/mark/test1.mp4
Playing Video: file:///home/mark/test2.mp4
Playing Video: file:///home/mark/test3.mp4
Playing Video: file:///home/mark/test1.mp4
Playing Video: file:///home/mark/test2.mp4
Playing Video: file:///home/mark/test3.mp4
Playing Video: file:///home/mark/test1.mp4
Playing Video: file:///home/mark/test2.mp4
Playing Video: file:///home/mark/test3.mp4
Playing Video: file:///home/mark/test1.mp4
Playing Video: file:///home/mark/test2.mp4
Playing Video: file:///home/mark/test3.mp4
Playing Video: file:///home/mark/test1.mp4
Playing Video: file:///home/mark/test2.mp4
Playing Video: file:///home/mark/test3.mp4
Playing Video: file:///home/mark/test1.mp4
Playing Video: file:///home/mark/test2.mp4
Playing Video: file:///home/mark/test3.mp4
Playing Video: file:///home/mark/test1.mp4
Playing Video: file:///home/mark/test2.mp4

Process finished with exit code 0
```
No problems whatsoever were apparent.

**Comment by hassanrazakhalid** [comment]
k i have 2 questions
1. I tried vlc -H to see what should i pass while playing to enable like to buffer the video for 20s of total length or 50% of total file size and then start playing. I see a whole alot of details a little difficult to find
2. Secondly if i download the file and lets say its 25% completed, will vlc play that video file even though its 20% completed and then video is playing along with more file is downloading. Will this approach work.

**Comment by caprica** [comment]
These follow up questions are out of scope really. I can help with things specifically related to vlcj, that's it.

**Comment by hassanrazakhalid** [comment]
@caprica thank you for help. I tried on Linux Mint and it is working fine. I will try updating ubuntu or switch to Mint. Closing this one
