### ISSUE TITLE
Video options not working as expected

### ISSUE THREAD

**Issue by hassanrazakhalid** [caprica/vlcj#889]
I am trying to follow  vlc -H to hide the mouse but its not working. What am i missing
Also is this correct way to use thse,
Rotate is working fine
also VLC is not saving stream from HTTP to documents
```
	MediaPlayerFactory factory = new MediaPlayerFactory(
//				"--video-filter", "rotate",
				"--mouse-hide-timeout=1500"
				,"--sout", "sout-record-dst-prefix=~/Documents"
				,"--sout", "sout-mux-caching=2500"
		
				);
		
				);
```
And if i wil play using the below line will it override all the above options or just the one i passed as param
`mediaPlayerComponent.mediaPlayer().media().play(url, "image-duration=-1 ");`

**Comment by caprica** [comment]
Well for the mouse it's a Java/AWT/Swing mouse isn't it? So you need to set your own cursor.
For your other question, this page shows how to set arguments:
http://capricasoftware.co.uk/projects/vlcj-4/tutorials/options-arguments

**Comment by caprica** [comment]
You also need to be aware that not all VLC filters will actually work through LibVLC, even if you find the right options.

Some will work, but some will only work when you create the factory and you can not dynamically change the options while your video is playing.

Those are LibVLC/VLC limitations, not vlcj limitations.

**Comment by hassanrazakhalid** [comment]
yes im using JWT for hiding mouse i'm referencing following doc. Since there is nothing in round braces like mentioned in document (rotate) no module is required to be enabled for this. I m passing this in MediaPlayerFactory
```
   --mouse-hide-timeout <integer> 
                                 Hide cursor and fullscreen controller after x
                                 milliseconds
          Hide mouse cursor and fullscreen controller after n milliseconds.
```
```
String[] options = {
//				"--video-filter", "--grayscale",
				"--mouse-hide-timeout=1000",
				"--sout", "sout-record-dst-prefix=~/Documents",
				"--sout", "sout-mux-caching=2500"};
		MediaPlayerFactory factory = new MediaPlayerFactory(options);
		mediaPlayerComponent = new EmbeddedMediaPlayerComponent(
			    factory,
			    null,
			    null,
			    null,
			    null
			);
```

but still it is not working. I tried passing it at like below as well
```
String[] options = {
							"--mouse-hide-timeout=1500",
							};
							mediaPlayerComponent.mediaPlayer().media().play(url, options);
```
Is there some anything i need to do to make it work.

**Comment by caprica** [comment]
I'm saying to set an AWT/Swing mouse, forget about the VLC mouse options because that is for the native pointer.

The mouse pointer in your application is associated with your Java JFrame, so use Java code to set an empty Cursor on your JFrame. Traditionally this is done by setting a 1x1 transparent pixel cursor.

But again, that question is nothing to do with vlcj, it's a general Java/AWT/Swing question.

**Comment by hassanrazakhalid** [comment]
Got it thanks and what about buffering option i am passing these in factory. These are also not  working as expected i am expecting sout-record-dst-prefix to save buffered video so that next time when it plays it will play locally and sout-mux-caching to buffer video for 2.5s then start playing the video.
 ```
"--sout", "sout-record-dst-prefix=/home/hassan/Documents",
"--sout", "sout-mux-caching=2500"
```

**Comment by caprica** [comment]
Those are VLC options, nothing at all to do with vlcj. You will have tondo some research or experiments.
