### ISSUE TITLE
How to disable native discovery

### ISSUE THREAD

**Issue by Vodes** [caprica/vlcj#893]
So. My Program downloads a ZIP with the libs from my server and extracts them. If you have VLC installed and try to launch a video in my program **main libvlc error: stale plugins cache: modified** comes up for every plugin. Because of all those errors, it takes for ever to start a video. If you dont have VLC installed nothing happens and everything works fine. 

**TL;DR:** Is there a way to disable Discovery and directly use a single path for Libs?

**Comment by caprica** [comment]
The Javadoc for MediaPlayerFactory covers this.

```
    /**
     * Create a new media player factory with default native discovery.
     * <p>
     * If you do not want to use native discovery, use the {@link #MediaPlayerFactory(NativeDiscovery, String...)}
     * constructor instead, passing <code>null</code>.
     *
     * @param libvlcArgs array of options/arguments to pass to LibVLC for initialisation of the native library
     */
```
So you can pass `null`, or you can create your own bespoke implementation that does whatever you want.
