### ISSUE TITLE
Argument --vout ignored in MediaPlayerFactory

### ISSUE THREAD

**Issue by ThomasPhilipp** [caprica/vlcj#895]
Hey everybody,

I have troubles with setting the `xcb_vw` module for the (global) `--vout` argument in VLCJ.

I've switched to Linux (Lubuntu) with my PC and now I can't display my UDP stream anymore. The video freezes after 1-3 seconds but the sound is still playing. This was also a problem in VLC, but I could solve it by switching the video output:

`vlc --vout=xcb_xv udp://@192.168.1.99:5000`

Now, I want do the same in VLCJ but there it doesn't work. Originally, I've tried to set the `--vout=xcb_xv` directly in `onGetMediaPlayerFacvtoryExtraArgs()` of an EmbeddedMediaListPlayerComponent instance. Then I found the the [options-arguments-tutorial](http://capricasoftware.co.uk/projects/vlcj-3/tutorials/options-arguments) and similar issues (#518 or #576), where they suggest to define it on the MediaPlayerFactory directly. I did a small [example project](https://github.com/ThomasPhilipp/test-vlcj/blob/master/src/main/java/com/zwickit/test/vlcj/UdpViewer.java) but the same problem remains - it simply does not change to the `xcb_vw` module:

`main window debug: using vout window module "xcb_window"` (see also [vlcj-viewer-example-log.txt](https://github.com/caprica/vlcj/files/3562373/vlcj-viewer-example-log.txt))

And with the `xcb_window` module it does not work in VLC (v3.0.7.1) and VLCJ (v3.12.1).

I hope someone can give me some hints what I've did wrong or how can I proceed?

Thanks,
Thomas

**Comment by caprica** [comment]
Well, VLC developers will tell you those flags are not supported at all in LibVLC.

But in the past I have seen it working, I guess it doesn't work anymore.

Using --vout=dummy or --vout=none is supposed to disable the video output, but that doesn't work either for me with latest VLC when I tested it just now.

LibVLC forces defaults for certain things and those command-line switches are ismply ignored - this is especially the case e.g. for audio filters.

I'm afraid there is nothing that can be done here.
