### ISSUE TITLE
Add 'Automatic-Module-Name' to MANIFEST.MF to support Java 9+ modules

### ISSUE THREAD

**Issue by wimdeblauwe** [caprica/vlcj#896]
When building my project that uses JPMS modules on Java 11 with Maven 3.6 using `maven-compiler-plugin` version 3.8.1, I get this warning:

```
[WARNING] **************************************************************************************************************************************
[WARNING] * Required filename-based automodules detected: [vlcj-4.2.0.jar]. Please don't publish this project to a public artifact repository! *
[WARNING] **************************************************************************************************************************************
```

To avoid this warning, there should be an `Automatic-Module-Name` entry in the `MANIFEST.MF` file. See also https://blog.joda.org/2017/05/java-se-9-jpms-automatic-modules.html

**Comment by caprica** [comment]
Will this cause *any* difficulties using vlcj in java7+ especially in projects that don't care about the Java Module System?

**Comment by wimdeblauwe** [comment]
No, other jars also have this entry in their manifest file (E.g. `jackson-core`) without issues. It just enables you to declare the module name that you _will_ use in the future (if you ever make this lib into an actual JPMS module). It allows users of your libary that do use the module system to have a stable module name that they can used. Otherwise, the module name is derived from the name of the jar file on the file system, which is not so good.

**Comment by caprica** [comment]
Ok, thanks. This seems trivial enough to add.

**Comment by caprica** [comment]
Is that link really still relevant now? I had a look at it, and one of the comments suggests what was in that linked article may not be optimal anymore.

I really see no benefit at the present time in investing a whole bunch of time and effort making vlcj comply with the Java Module System. But I wouldn't mind doing what you've suggested here, just so long as it's definitely the right thing to do.

**Comment by wimdeblauwe** [comment]
Not sure what comment you are talking about? 

Some info I have found on other projects that have done the same:
* Guava: https://github.com/google/guava/pull/2961/commits/cbe29778617c9845c10a849bbaa5e23b710473ff
* Gson: https://github.com/google/gson/issues/1238
* Spring framework:
> A note about modules: Spring’s framework jars allow for deployment to JDK 9’s module path ("Jigsaw"). For use in Jigsaw-enabled applications, the Spring Framework 5 jars come with "Automatic-Module-Name" manifest entries which define stable language-level module names ("spring.core", "spring.context" etc) independent from jar artifact names (the jars follow the same naming pattern with "-" instead of ".", e.g. "spring-core" and "spring-context"). Of course, Spring’s framework jars keep working fine on the classpath on both JDK 8 and 9+.

**Comment by caprica** [comment]
The last comment in the thread is what I was referring to.

I admit I skimmed it quickly. Time is sadly limited right now.

**Comment by wimdeblauwe** [comment]
I am not using `OsxFullScreenStrategy`. If I open this class in IntelliJ, I do see that `com.apple.eawt.AppEvent.FullScreenEvent` could not be found indeed.

It seems that in openJDK 11.0.2, this is moved to `com.apple.eawt.event.FullScreenEvent`
