### ISSUE TITLE
MediaList update and play order

### ISSUE THREAD

**Issue by cookieandcoke** [caprica/vlcj#898]
vlcj version: 4.0.7

I used MediaListPlayer to play a MediaList and the playback mode is LOOP. There is a welcome video added into the play list before player start playing.  After player started playing, it would add some media into the list dynamic, also each media has a media event listener, when the media event listener received played end event, media would be removed from the play list.
```
media.events().addMediaEventListener(new MediaEventAdapter() {
    @Override
    public void mediaStateChanged(Media media, State newState) {
        // when newState is ENDED, remove the media in media list by mrl
    }
});
```

After several tries, I found that the play list played order is unexpected. Such as the play list order is `Welcome - A - B - C - D`, but the actually played order may be`Welcome - A - B - D - C`. Is there any hint for this behavior?

**Comment by caprica** [comment]
If you are removing items from the list after they have finished playing you are probably changing the indices of the remaining items. So when you play C at what you think is index 2 it is actually index 1 because you deleted B already, so it plays D instead.

Do you really need to remove those things from the playlist as they finish? I would just remove them when the entire playlist is finished.

**Comment by cookieandcoke** [comment]
Thanks for replied, my usage is playing a RTSP streaming, and video will add by user behavior. All videos that user added would play only once. If no user add a new video, the streaming will play the welcome video. Do you have any suggestion for the media play list handling? Thank you!

**Comment by caprica** [comment]
Like everything, "it depends".

How are you playing the items in the playlist? Are you using next(), are you just letting the playlist play naturally without interfering with it, are you playing a particular index?

**Comment by cookieandcoke** [comment]
I let the playlist play naturally, but I updated the playlist after a video state changed to ENDED. Maybe I should change the usage, thank you.
