### ISSUE TITLE
SIGSEGV in Linux with vlcj 4.x when opening file/directory chooser

### ISSUE THREAD

**Issue by motohead99** [caprica/vlcj#899]
I'm getting a crash in Ubuntu 16.04 that's very similar to this bug:
https://github.com/caprica/vlcj/issues/664

I have a potential work around for this but I still wanted to bring this to your attention. I'm also not sure if there are any consequences to using this workaround. The work around is to pass the following to the JVM at runtime:
`-Djdk.gtk.version=2`

Since I'm building with jpackage, it can be done when creating the application image as follows:
```
$JPACKAGE_HOME/bin/jpackage $VERBOSE_OPTION --runtime-image $IMAGE \
	--java-options "-Djdk.gtk.version=2" \
	--input $TARGET --output $APPIMAGE --name $LAUNCHER --main-jar $MAINJAR
```

Ubuntu is running in a VM if it matters. I haven't tried to replicate it with a newer version of Ubuntu yet.

If I open a file chooser or directory chooser in Linux after I create a new EmbeddedMediaPlayerComponent(); then the JVM has a hard SIGSEGV crash.

If I open one before creating a new EmbeddedMediaPlayerComponent(); then I don't get a crash.

However, my gut feeling is that the fix from https://github.com/caprica/vlcj/issues/664 is no longer applicable/used. When I search the vlcj code base for jawt I get no results.

This works, then all subsequent file/directory file chooser opens also work:
```
DirectoryChooser chooser = new DirectoryChooser();
File file = chooser.showDialog(MainFrame.main_stage);
mediaPlayerComponent = new EmbeddedMediaPlayerComponent();
```

However, if I change it to the following, then I get the crash:
```
mediaPlayerComponent = new EmbeddedMediaPlayerComponent();
DirectoryChooser chooser = new DirectoryChooser();
File file = chooser.showDialog(MainFrame.main_stage);
```

The crash is as follows:
```
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f0ef47c4d44, pid=2669, tid=2686
#
# JRE version: OpenJDK Runtime Environment (14.0+1) (build 14-jpackage+1-35)
# Java VM: OpenJDK 64-Bit Server VM (14-jpackage+1-35, mixed mode, tiered, compressed oops, serial gc, linux-amd64)
# Problematic frame:
# C  [libpthread.so.0+0x9d44]  pthread_mutex_lock+0x4
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /bin/hs_err_pid2669.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Aborted
```

The stack leading up to the crash is as follows:
```
Current thread (0x00007f0eec3cd800):  JavaThread "JavaFX Application Thread" [_thread_in_native, id=2686, stack(0x00007f0ea84bb000,0x00007f0ea85bc000)]

Stack: [0x00007f0ea84bb000,0x00007f0ea85bc000],  sp=0x00007f0ea85b5060,  free space=1000k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libpthread.so.0+0x9d44]  pthread_mutex_lock+0x4

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  com.sun.glass.ui.gtk.GtkCommonDialogs._showFolderChooser(JLjava/lang/String;Ljava/lang/String;)Ljava/lang/String;+0 javafx.graphics
j  com.sun.glass.ui.gtk.GtkCommonDialogs.showFolderChooser(Lcom/sun/glass/ui/Window;Ljava/lang/String;Ljava/lang/String;)Ljava/io/File;+23 javafx.graphics
j  com.sun.glass.ui.gtk.GtkApplication.staticCommonDialogs_showFolderChooser(Lcom/sun/glass/ui/Window;Ljava/lang/String;Ljava/lang/String;)Ljava/io/File;+3 javafx.graphics
j  com.sun.glass.ui.CommonDialogs.showFolderChooser(Lcom/sun/glass/ui/Window;Ljava/io/File;Ljava/lang/String;)Ljava/io/File;+15 javafx.graphics
j  com.sun.javafx.tk.quantum.QuantumToolkit.showDirectoryChooser(Lcom/sun/javafx/tk/TKStage;Ljava/lang/String;Ljava/io/File;)Ljava/io/File;+30 javafx.graphics
j  javafx.stage.DirectoryChooser.showDialog(Ljavafx/stage/Window;)Ljava/io/File;+23 javafx.graphics

```

In fact, looking at the stack, maybe this should be raised as a javafx bug and not a vlcj bug. What are your thoughts? It's strange that the call to "new EmbeddedMediaPlayerComponent();" doesn't cause a crash, but it sets something up that causes the crash later on when a file/directory chooser is opened.

**Comment by caprica** [comment]
So obviously I did encounter a problem like this before which is why there's that workaround in vlcj 3.x to make sure various things are preinitialised.

When I made vlcj 4.x, I used a different simpler workaround - rather than force-loading the jawt native library I simple instantiated a JPanel (or Panel, or whatever). And this *did* work for me at the time I wrote it. So I'm kinda surprised there's still a problem here.

I will take another look at it, your workaround is fine but generally I eschew having to set system properties like that.

**Comment by caprica** [comment]
Actually I mis-remembered that somewhat.

Just checking the code, and the same workaround is there, I just factored it to a separate class in LinuxNativeInit.java

**Comment by caprica** [comment]
So, I dunno... needs some more investigation I suppose.

**Comment by caprica** [comment]
This sort of thing is a real mess/PITA to be honest, this might work in this particular circumstance:

    -DVLCJ_INITX=no

I never got to the root cause of the problem once I had something that worked.

**Comment by motohead99** [comment]
No idea why, but this doesn't work on Ubuntu 17.10:
`-Djdk.gtk.version=2`

However, this works on both 16.04 and 17.10 (I should try 18.x at some point as well):
`-DVLCJ_INITX=no`

**Comment by caprica** [comment]
Unfortunately there's some weirdness with:

1. vlcj not initialising X threads before invoking LibVLC
2. Java/Java/JVM not initialising X threads before invoking LibVLC

And if vlcj initialises those threads, you don't want Java trying (hence crash), and if you leave it to Java to initialise those threads you don't want vlcj trying.

Dealing with native issues like this is pretty random and ugly, and honestly not all that interesting to debug, hence the reason VLCJ_INITX exists so that application developers can take ownership of the problem. :-)
