### ISSUE TITLE
Change width/height of buffer for DirectMediaPlayer

### ISSUE THREAD

**Issue by hjohn** [caprica/vlcj#90]
When using the Canvas based solution, the output is automatically scaled to the size of the canvas.  This makes it possible to move the video screen to a different monitor (with different resolution) on the fly.

The DirectMediaPlayer forces a buffer dimension in advance, with no way to change this during playback without creating a new instance and seeking to the last known position.  If libvlc allows it it would be nice to be able to change the buffer dimensions during playback, and perhaps add these parameters to the RenderCallback as well so it knows the size changed.

Another good reason to support this would be that a (Direct)MediaPlayer is usually only created once in my application, and used to play back many different videos -- these videos might vary in size.  Having to guess that all videos will be below a certain size and use this size as the maximum width/height (just in case) is a bit wasteful as well.

**Comment by maztan** [comment]
Would it be possible for someone to show here how would one change buffer after video starts here?

**Comment by caprica** [comment]
There is an example in the vlcj "test" sources that does this, look there.

The downside with it is it allocates enough memory for a video buffer the size of your desktop, even if you resize it down to a tiny size, but that's really the best you can do.
