### ISSUE TITLE
VLCJ no decoder configuration possible for NV12 problem

### ISSUE THREAD

**Issue by emrekgn** [caprica/vlcj#900]
Hi,
We're using VLCJ and VLCJ-SWT to create an embedded video player on a SWT video surface. Media player plays the videos just fine when using the application on a HP monitor with 1920x1080 resolution. VLC media player (3.0.3) can also play the video.

But when we try to play the video on a larger monitor with a 2560x1440 resolution, the media player just shows a black screen and eventually freezes the application. I also added a native log listener to see libvlc logs:
```

No decoder configuration possible for NV12 4480x1440
No decoder configuration possible for I420_OPAQUE 4480x1440
FindVideoServiceConversion failed
No decoder configuration possible for NV12 4480x1440
No decoder configuration possible for NV12 4480x1440
No decoder configuration possible for I420_OPAQUE 4480x1440
FindVideoServiceConversion failed
SetThumbnailClip failed: 0x800706f4
```

I also tried with different VLC settings such as disabling hardware acceleration and selecting different video output options.

Here is basicly how I use the library:
```
private String[] VLC_OPTS = new String[] { "--no-snapshot-preview", "--no-osd", "--no-audio", "--no-sout-display-audio" };

SwtMediaPlayerFactory factory = new SwtMediaPlayerFactory(VLC_OPTS);
EmbeddedMediaPlayer mediaPlayer = factory.mediaPlayers().newEmbeddedMediaPlayer();
addNativeLogListener();

Composite videoSurface = new Composite(parent, SWT.EMBEDDED | SWT.NO_BACKGROUND);
videoSurface.setLayout(gridLayout);
videoSurface.setLayoutData(gridData);
videoSurface.setBackground(resourceManager.createColor(UIFactory.COLOR_HEX_1A1A1A));

CompositeVideoSurface surface = factory.swt().newCompositeVideoSurface(videoSurface);
mediaPlayer.videoSurface().set(surface);

MediaRef media = factory.media().newMediaRef(videoPath, VLC_OPTS);
mediaPlayer.media().start(media);
```

I wonder this might be some problem with resolution or screen ratio..
Thanks in advance.

**Comment by caprica** [comment]
Those problems look unrelated to vlcj.

If you check those native log messages it looks like it tries to create a decoder for a screen that's 4480x1440. Is this a multi-monitor setup? 

The only advice really is to make sure you have VLC and all its plugins installed properly.

Other than that, I don't know.

**Comment by emrekgn** [comment]
Yes, it is a multi-monitor setup. (we record both of the monitors using ffmpeg, hence the giant resolution, and then user can playback them)

I understand but, the thing is, it also works as expected with VLCJ 3.12.1 and VLCJ-PRO 1.1.0 for both of the monitors. The problem occurred when we migrated our old code base to VLCJ 4.2.0 and got rid of VLCJ-PRO.

**Comment by caprica** [comment]
Nevertheless the error message quoted is a native error message from VLC and it looks like it's trying to create a decoder for a video buffer across two monitors.

What happens if you run the native VLC application under the same setup?

Using vlcj-pro or not should be irrelevant here.

**Comment by caprica** [comment]
Maybe you have to specify a different video output, I really don't know.

**Comment by emrekgn** [comment]
> Nevertheless the error message quoted is a native error message from VLC, and it looks like it's trying to create a decoder for a video buffer across two monitors.
> 
> What happens if you run the native VLC application under the same setup?

It also runs without any problem. :)
I'm just speculating here but, since VLCJ 3.12.1 also works for both monitors, the only major change I can think of between two VLCJ releases (v3.12.1 and 4.2.0) is JNA bindings. Can this change somehow affect media player?

> Maybe you have to specify a different video output, I really don't know.

I've tried different video outputs, but none of them worked...

I'll try again with different monitor setup and resolutions on Monday. Maybe I can narrow down the possibilities and create a topic on VideoLan forums.

Thank you for your time and consideration.

**Comment by caprica** [comment]
The JNA bindings are exactly the same really.

What changed in vlcj was _how_ the bindings were created, not the API they were bound against. And there's no implementation as such, it's not like I wrote code, I simply spec'd out the interface.

Maybe try enabling native VLC logs.

And are you really using the same version of VLC with this test compared with your other test?

**Comment by caprica** [comment]
When you play in VLC is it trying to play on a video surface across both monitors!?

From some cursory reading of the VideoLAN forums it looks like this message can be reported when there is simply insufficient memory available to create a video buffer of the requested size.

**Comment by caprica** [comment]
Is there anything else to add on this? I'm not sure this a problem than can be resolved in vlcj.

**Comment by caprica** [comment]
Closed pending any further follow-up.
