### ISSUE TITLE
native.load is not working in the latest version

### ISSUE THREAD

**Issue by Abu-Abdullah** [caprica/vlcj#901]
Hi,

im facing again issues with configuring the path of vlc plugins in the latest release 4.2

```
Native.loadLibrary(RuntimeUtil.getLibVlcLibraryName(), LibVlc.class);
```
the above seems legacy and it is giving error. the replacement 
```
Native.load(RuntimeUtil.getLibVlcLibraryName(), LibVlc.class);
```
gives cannot resolve method exception 

tried also creating dummy interface
```
public interface CLibrary extends Library
	{
		CLibrary INSTANCE = Native.load(RuntimeUtil.getLibVlcLibraryName(), CLibrary.class);
	}
```
and then just call it after add the path
```
CLibrary cLibrary = CLibrary.INSTANCE;
```
still nothing works. i tried also setting the path  VLC_PLUGIN_PATH=resources/bin/vlc/plugins

no luck at all. please provide correct method to load vlc plugins folder manually

**Comment by caprica** [comment]
Here's the thing... install the correct version of VLC and install it "properly" using your regular OS tools and vlcj will find and successfully load the LibVLC native library.

I put a lot of time and effort into getting the discovery process to work, and I tested it on Linux, OSX and Windows. In each case, I installed VLC using the OS package manager, and just let vlcj do its default behaviour, and it worked.

So I need to make sure you do indeed have VLC installed properly and that is indeed the minimum version supported by vlcj. I need to know if you've copied the various DLL's around or changed the standard installation file structure in any way.

If you have done all of that, then I need to see all the console output and the command you used to run you application - including the classpath you're using, especially to make sure you don't have some old version of JNA on your classpath.

With what you've posted here, it's not nearly enough to begin to help you I'm afraid.

**Comment by caprica** [comment]
And your VLC_PLUGIN_PATH should be an absolute path if you're trying to do things that way, not a relative path like you've quoted above.

**Comment by Abu-Abdullah** [comment]
Thank you for the quick response. The installation is not in the standard
location. I'm shipping the vlc with the app itself so that there is no
external dependency. Hence i need to map it manually. It works previously
nicely (i think 3.8). Now im upgrading all libraris and i faced this. I
will try later setting the path to be absolute

**Comment by caprica** [comment]
So what you're doing in principle should be OK, but how exactly are you telling your vlcj application to find LibVLC?

The recommended way to do that is to add your own implementation of this: https://caprica.github.io/vlcj/javadoc/4.2.0/uk/co/caprica/vlcj/factory/discovery/provider/DirectoryProviderDiscoveryStrategy.html

If you do this, you only need provide the absolute directory containing your LibVLC artefacts, and vlcj will handle setting the plugin path (as long as you maintain the proper directory structure).

**Comment by Abu-Abdullah** [comment]
thank you, im looking at the code and different OS implementations for this class. I will update on this again.

**Comment by Abu-Abdullah** [comment]
ok, it is working now with specifying the absolute path to the plugins folder
```
ClassLoader cl = TestVlc.class.getClassLoader();
NativeLibrary.addSearchPath(RuntimeUtil.getLibVlcLibraryName(), new File(cl.getResource("bin/vlc").toURI()).getAbsolutePath());
```

It seems loadLibrary is not needed anymore
```
Native.loadLibrary(RuntimeUtil.getLibVlcLibraryName(), LibVlc.class);
```
