### ISSUE TITLE
"Invalid UE golumb code",error in vlcj library

### ISSUE THREAD

**Issue by PersdeepKaur** [caprica/vlcj#903]
Using vlcj 3.12.x library for the development of Video Management System. In Video Management system I display live stream coming from cctv cameras of my college.But its gives error-"invalid ue golumb code" after playing video for sometime.Videos are getting stopped automatically and VMS hang for minutes. 

Please help me because my project deadlines are close.
Screenshot of errors are attached below:
![Screenshot from 2019-09-30 11-51-19](https://user-images.githubusercontent.com/55971894/65854066-230b4580-e379-11e9-98a6-d3cf853ed95b.png)
![IMG-20190927-WA0007](https://user-images.githubusercontent.com/55971894/65854742-ff48ff00-e37a-11e9-8379-41452fa5da95.jpg)
![IMG-20190927-WA0009](https://user-images.githubusercontent.com/55971894/65854743-ff48ff00-e37a-11e9-8ea8-cf3bbb158849.jpg)

Any help will be appreciated.
Thanks in advance.

**Comment by caprica** [comment]
I am very confused, this issue appeared in Github today (12th April, 2020) but was apparently raised 30th September 2019.

Anyway,. pasting a text log would have been much more helpful that screenshots of logs.

All of the error messages in your post are coming for VLC, they are native messages hence native errors.

So I don't know how I could help you in any case.
