### ISSUE TITLE
Is it possible to play media using a java.io.FileInputStream? 

### ISSUE THREAD

**Issue by supercom32** [caprica/vlcj#906]
Hi,

Is it possible to have vlcj play media using a `java.io.FileInputStream` instead of providing a physical path on the file system? The reason I ask is because I have libraries that can deal with compressed/password protected archives, and the way applications can transparently work with it is by reading data from a FileInputStream.

If there was a way to do this, I'd be interested to learn how!

**Comment by caprica** [comment]
Yes, but it has a lot of limitations, some of those limitations may be terminal.

You need to look at "callback media".

Look at the Javadoc, or check this tutorial here http://capricasoftware.co.uk/projects/vlcj-4/tutorials/java-io

**Comment by supercom32** [comment]
I looked at the tutorial but vlcj only seems interested in opening File objects. That is, the media must exist someplace on the filesystem. If your given an InputStream (From a random source), is there a way to somehow pass that to vlcJ without first having to write all the data to a temporary file on the filesystem?

**Comment by caprica** [comment]
Extend NonSeekableInputStreamMedia.

**Comment by hasonon** [comment]
Could you please elaborate?

**Comment by caprica** [comment]
https://capricasoftware.co.uk/projects/vlcj-4/tutorials/java-io
https://caprica.github.io/vlcj/javadoc/4.7.0/uk/co/caprica/vlcj/media/callback/CallbackMedia.html

Create an instance of a class that implement CallbackMedia, or provide your own implementation of that interface, pass that media instance via playMedia().

It really isn't recommneded though, it has (often critical) limitations.
