### ISSUE TITLE
vlcj not working on 32bit JVM

### ISSUE THREAD

**Issue by yuiopt** [caprica/vlcj#909]
I have some 32-bit .so library , I have to run on 32-bit JVM, but the vlcj-player just crashed , below is the error info
<img width="728" alt="截屏2019-12-04上午10 37 21" src="https://user-images.githubusercontent.com/9608805/70108553-920c5f80-1684-11ea-967a-02c39191e21e.png">

**Comment by caprica** [comment]
Unfortunately well known error on 32bit Ubuntu related to LUA. If you search this GitHub project issues you'll find more explanation.

**Comment by caprica** [comment]
e.g. https://github.com/caprica/vlcj/search?q=_IO_File_underflow&type=Issues
