### ISSUE TITLE
LibC.INSTANCE take a long time to process when the internet is disconnected

### ISSUE THREAD

**Issue by mwd-luongmai** [caprica/vlcj#911]
With vlcj library version: 3.10.1 and 3.12.1

The java application take a long time (about 15 - 20 seconds) to process the command 
"LibC.INSTANCE" for getting an instance of VLC library.

This issue is only happened when the internet is disconnected.
With connected internet, the issue is not happened and the line of code is processed quickly.

**Comment by mwd-luongmai** [comment]
only happened on Mac OS Catalina. Mac OS Mojave work normal

**Comment by caprica** [comment]
I really don't know what I could do about that, it's probably stuck waiting for LibVLC to initialise. It that is the case then as to why LibVLC needs the internet on startup I have no idea.

**Comment by mwd-luongmai** [comment]
> I really don't know what I could do about that, it's probably stuck waiting for LibVLC to initialise. If that is the case then as to why LibVLC needs the internet on startup I have no idea.

In debugging mode, I detected that VLC library need to use native library of Mac OS (LibC). To do that, VLC library will use other libraries: JNA (Java Native Access) and JNA-Platform (Java Native Access Platform) to support for loading native libraries.
However, while initialize JNA instance, JNA stuck on finding and execute a resource inside itself package "...lib/jna-4.1.0.jar!/com/sun/jna/darwin/libjnidispatch.jnilib"
Below are dependencies inside the "libjnidispatch.jnilib" file which will be loaded and executed:

- /System/Library/Frameworks/JavaVM.framework/Versions/A/JavaVM (compatibility version 1.0.0, current version 1.0.0)
- /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 751.29.0)
- /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 125.2.0)

=> These system libs and execution files of Mac OS (Catalina)
The internet is required to bypass this stuck. Without the internet, initialize JNA instance will be take long time.

**Comment by mwd-luongmai** [comment]
In investigation process, I tried to capture all request to internet when launching the app which is using vlcj.
I detected that a request to https://api.apple-cloudkit.com (Apple Inc.) is executed.

However, my system is working on a local network (without internet), so the resolving DNS is can't completed for this domain (api.apple-cloudkit.com), IP address is not determined.
Resolving DNS will be take about (15-20 seconds) for waiting timeout to return "UnknownHost: api.apple-cloudkit.com:..."

I dont know why a request to cloudkit is executed.

**Comment by caprica** [comment]
As far as I can tell, api.apple-cloudkit.com is not referenced in the VLC sources at all, so something else on your system must be making that call.

I really have no idea though. It is very unlikely that your problem is something that can be fixed in vlcj.

**Comment by mwd-luongmai** [comment]
> As far as I can tell, api.apple-cloudkit.com is not referenced in the VLC sources at all, so something else on your system must be making that call.
> 
> I really have no idea though. It is very unlikely that your problem is something that can be fixed in vlcj.

Thanks you. Do you think this issue relate to finding and loading lib/jna-4.1.0.jar!/com/sun/jna/darwin/libjnidispatch.jnilibon Mac OS?  This is a native library inside jna-4.1.0.jar which is referring in vlcj package

**Comment by caprica** [comment]
It's possible I suppose. You could try writing a very simple application that only used JNA (not vlcj) and seeing what happens.

The JNA project has a platform.jar that maps certain OS-specific functions, there's bound to be something simple and macOS related that you could call as a test.

**Comment by caprica** [comment]
I see you're using JNA 4.1.0 so that's presumably an old version of vlcj too.

Maybe try a later version of JNA, the current vlcj version uses JNA 5.2.0.

**Comment by mwd-luongmai** [comment]
Qq

> I see you're using JNA 4.1.0 so that's presumably an old version of vlcj too.
> 
> Maybe try a later version of JNA, the current vlcj version uses JNA 5.2.0.

I also verified on JNA 5.2.0 and dependence packages of this version. However, this issue is still be happened. I continue to be stuck 15-20 seconds at step finding and loading libjnidispatch.jnilib (I turned on jna_debug to see that). Note that only happened on Mac OS Catalina after upgraded from Mojave. Thanks for your suggestions

**Comment by mwd-luongmai** [comment]
> I see you're using JNA 4.1.0 so that's presumably an old version of vlcj too.
> 
> Maybe try a later version of JNA, the current vlcj version uses JNA 5.2.0.

Yes. Im using vlcj 3.10.1. The latest version make too much changes. I'm afraid that taking more effort to update the app with the latest version.

**Comment by caprica** [comment]
I'm closing this as I don't think there's anything that could be done in vlcj to resolve this.
