### ISSUE TITLE
empty Lists after loading a video

### ISSUE THREAD

**Issue by Samuel98-f** [caprica/vlcj#914]
Hi
I am currently working on a Project and therefore i want to calculate the aspectRatio of a Video. I`ve tried to use your libary and i got this far:

public void getVideoRatio(String path) {
int width = 1;
int height = 1;
EmbeddedMediaPlayerComponent mediaPlayerComponent = new EmbeddedMediaPlayerComponent();
MediaPlayer mediaPlayer = mediaPlayerComponent.mediaPlayer();
boolean prepare = mediaPlayer.media().prepare("path");
boolean parse = mediaPlayer.media().parsing().parse();
List videoTrackInfo = mediaPlayer.media().info().videoTracks();
List titles = mediaPlayerComponent.mediaPlayer().titles().titleDescriptions();
for (VideoTrackInfo v : videoTrackInfo) {
height = v.height();
width = v.width();
System.out.println(height + "\n" + width);
}
for (TitleDescription t : titles) {
System.out.println(t.name());
}
    float ratio = (float) width / height;
    System.out.println(ratio + Boolean.toString(parse && prepare)+ titles.size()+videoTrackInfo.size());
    video.setAspectRatio(ratio);
}

The Problem i am facing at the moment is that my lists a empty although prepare and parse are true.
I am testing with a 1 sec long .mp4 with a Resolution of 342x182px
Please help

**Comment by caprica** [comment]
It's not immediately obvious as to when the track information is available, but as you've found parsing is not enough. Parsing is used only for meta data fields, like title, artist, composer etc.

The availability of track information depends on the decoder being used, and the track information is not available until after VLC is just about to start playing the media.

You must play the media before the track information is available, it's unavoidable.

Generally you could use the "mediaPlayerReady" event, or alternatively the earliest possible point I've seen valid track information is here (this is a MediaPlayerEvenListener fragment):
```
    @Override
    public void elementaryStreamSelected(MediaPlayer mediaPlayer, TrackType type, int id) {
        if (type == TrackType.VIDEO && id != -1) {
            VideoTrackInfo videoTrackInfo = mediaPlayer.media().info().videoTracks().get(0);
            log.info("videoTrackInfo={}", videoTrackInfo);
        }
    }
```
Note how I also test for the ID being something other than -1.

If you need the data before playback, then consider some other library - this is why I created the https://github.com/caprica/vlcj-info project.

**Comment by Samuel98-f** [comment]
Thank you 
with the vlcj-info Project it was much easier anf now it runs smoothly after i added System.setProperty("jna.library.path", "C:\\Program Files\\MediaInfo");
to your example as in another issue suggested
