### ISSUE TITLE
Documentation is inconsistent

### ISSUE THREAD

**Issue by Germajex** [caprica/vlcj#922]
As it can be seen from the tutorial at http://capricasoftware.co.uk/projects/vlcj-4/tutorials/my-first-media-player, the EmbeddedMediaPlayer objects should expose a play(String) method, which is not present. I am talking about version 4.1.0, but of course the method is still missing in 4.2

**Comment by caprica** [comment]
Thanks for reporting this. It will be looked at soon.

**Comment by caprica** [comment]
Was this the only problem you found?

I can see only one place where it was wrong, and I'm about to push an update now.

**Comment by caprica** [comment]
I'll close this now, if you spot anything else feel free to let me know. Thanks!
