### ISSUE TITLE
The management of macOS fullscreen events requires Apple API unavailable to Java 9+

### ISSUE THREAD

**Issue by xinyingho** [caprica/vlcj#924]
The management of macOS fullscreen events requires Apple API unavailable to Java 9+. This means that it's not possible to use VLCj with Java 9+ on macOS even if we don't use those fullscreen features.

As my own Java 11 application doesn't need those fullscreen features, I've simply created a fork removing those Apple API dependencies. But this should probably be fixed more properly.

The only impacted class is /uk/co/caprica/vlcj/player/embedded/fullscreen/osx/OsxFullScreenStrategy.java

**Comment by caprica** [comment]
Presumably adding this dependency would work for one aspect of the problem:
```
<dependency>
            <groupId>uk.co.caprica</groupId>
            <artifactId>vlcj-osx-stubs</artifactId>
            <version>1.0.0</version>
</dependency>
```
Do you know what the actual proper solution is, I mean to be able to use fullscreen etc on Java9+?

**Comment by xinyingho** [comment]
The inclusion of this dependency doesn't fix anything on Java 9+ :/

I didn't look at this further as I don't need this feature but Oracle only replaced a subset of what the old Apple API could do. See https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8048731

For the fullscreen specific capabilities, it looks like they decided it wasn't necessary to do anything as some workarounds seem to work... I'm not convinced but see https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8143914

**Comment by caprica** [comment]
Thanks for the links. I'll try and find some time to look into it.

**Comment by caprica** [comment]
Probably should be linked with #862

**Comment by caprica** [comment]
https://bugs.openjdk.java.net/browse/JDK-8228638

Supposedly setting the extended state of the frame to MAXIMIZE_BOTH is supposed to trigger the native fullscreen.

However it does not work, at least not on Java 11.

Dealing with macOSX idiosyncrasies is always fun.

**Comment by caprica** [comment]
With commit 2cd272810d9bcef4532813e9f875dcdd5a3b27c2 it now uses reflection to use the EAWT classes for fullscreen pre Java9.

Java9+ native fullscreen is not supported, but at least vlcj should run on macOS with Java9+.

I did not test this with a Java Module System application.

**Comment by caprica** [comment]
I am actually not sure about this commit in any case, at least not at the present time.

The reason being, full screen would still work on macOS Java9+ if the Java Module System is not used.

**Comment by caprica** [comment]
Perhaps related #928.

It may now be possible to revert this particular change, some testing on macOS would be required.

**Comment by caprica** [comment]
Decided to revert this change pending further testing, especially so as various Java Module System changes have been made for vlcj-5.x.

Reverted at f6643c92c9c3c79901d8f31c0234d25d38424f4c.

Should be easy enough to add back.

**Comment by caprica** [comment]
I will close this for now and punt it into the future with the hope that the recent changes for the module system make it moot (optimistic...)

**Comment by caprica** [comment]
This still needs looking at despite the recent module changes made for vlcj-5.0.0.

**Comment by caprica** [comment]
I've been experimenting a bit with this, and I have it working without any hacks, and with the Java Module System.

BUT, IntelliJ complains about either not being able to see the EAWT classes, or that they are read from BOTH java.desktop and the vlcj-osx-stubs module.

Despite the error in IntelliJ, full-screen does appear to work.

However, this is all very unsatisfactory.

There really is NO replacement for setting fullscreen in a "legit" way anymore, so it means either:

1. situation as it is now
2. change to do a reflection-based solution for pre Java 9 and the alternate maximising window solution (this is the patch I made then reverted)
3. something else, but what?!

The easiest thing to do is to remove the vlcj-osx-stubs project and declare that full-screen is not supported on macOS, and then hope that a subsequent JDK release makes it available again.

I really don't care to spend so much time on macOS issues, it just seems there's no simple solution here.

**Comment by caprica** [comment]
The more I think about this, the more appealing it iso to ditch the OSX stubs project, and basically not support full-screen on OSX.

Instead, push it to the client application to provide a solution.

At least until something in the JDK changes to make native full-screen possible.

**Comment by caprica** [comment]
The other thing that makes this moot is I expect just about all users of vlcj on macOS to be using JavaFX.

That being the case, JavaFX has its own solution for full-screen via the Stage class.

**Comment by caprica** [comment]
Removed support for full-screen on OSX in the 4.x and 5.x branches.
