### ISSUE TITLE
Unable to view stream over RTSP

### ISSUE THREAD

**Issue by mmeyers-solartech** [caprica/vlcj#954]
Doing a very simple restream process of an RTSP camera feed. The camera RTSP is the source, and the output is a new RTSP video feed. If I run identical video commands in the VLC streaming menu I can open another VLC window and view the new RTSP feed, however matching that process programatically I am unable to view the new stream. Full code below:

```
import uk.co.caprica.vlcj.factory.MediaPlayerFactory;
import uk.co.caprica.vlcj.player.base.MediaPlayer;

public class RTSPServer {
    static Boolean streaming = false;
    MediaPlayerFactory mFactory;
    MediaPlayer mPlayer;
	public void startStream() {
        mFactory = new MediaPlayerFactory("-vvv");
   	 	mPlayer = mFactory.mediaPlayers().newMediaPlayer();
   	 
   	    String sourceMRL = "rtsp://<my ip>/axis-media/media.amp?videocodec=h264";

   	    String[] vlcOptions = {
   	    		":sout=#rtp{sdp=rtsp://127.0.0.1:8554/stream}",
   	    		":sout-keep"
   	    };

   	    mPlayer.media().start(sourceMRL, vlcOptions);
		
	}
	
	
	public static void main(String[] args) {    
	    new RTSPServer().startStream();    
	} 
	
}
```

However if I stream using the normal VLC application with these commands:

:sout=#rtp{sdp=rtsp://127.0.0.1:8554/stream} :sout-keep

I can open a new window and view 127.0.0.1:8554/stream with no issues.

**Comment by caprica** [comment]
It's not clear to me what isn't working for you, is your RTSPServer class working properly and your client code is not? Or is the RTSPServer class not delivering your stream?

Also, you specified "-vvv", did you study the native logs for clues?

**Comment by caprica** [comment]
What's different here compared with #943? Presumably in #943 that stream was actually streaming something in the end.

**Comment by mmeyers-solartech** [comment]
Yeah eventually #943 worked because I pulled it out of a thread, in this case the RTSP client is just a VLC window. I'm calling an "open networks stream" to rtsp://127.0.0.1:8554/stream. The RTSPServer is not delivering the stream. I don't actually see anything output to console when I try to connect at 127.0.0.1:8554/stream. It's not a client problem since if I do all of this through the GUI the client displays the video fine.

**Comment by caprica** [comment]
If you do `vlc rtsp://<my ip>/axis-media/media.amp?videocodec=h264`, does it play the camera video?

**Comment by caprica** [comment]
You can maybe also try playing a regular file rather than the camera to work out which piece of this architecture is not working.

i.e. is it the camera part that's not working, or is it the re-streaming part.

**Comment by mmeyers-solartech** [comment]
Yes the original camera feed plays well, and I can restream it to 127.0.0.1:8554/stream via the VLC UI. It's just not restreaming from the simple class posted at the top. So In a VLC window I open a network stream to 127.0.0.1:8554/stream. If restreamed from VLC, it plays. If restreamed from the above class, it does not play.

**Comment by caprica** [comment]
But we still don't know which piece of this is not working.

If you change RTSPServer to play a local file rather than your camera, does it work?

If no, it is likely something wrong with the restreaming part, and then we can focus on that.

If yes, it means the restreaming is OK, but the MRL to the camera is not, and then we can focus on that.

Which is it?

Because I can restream RTSP from a local file just fine. I don't have any IP camera to test.

**Comment by caprica** [comment]
I will add something, I don't like this:
```
public static void main(String[] args) {    
    new RTSPServer().startStream();    
}
```
What is keeping your RTSPServer instance alive? It is implicitly allocated on the heap in your main() method, then your main method exits, the heap unwinds and nothing references your object, so it becomes eligible for garbage collection does it not?

I would expect this application to stop immediately or fatal JVM crash because your instance gets garbage collected.

**Comment by mmeyers-solartech** [comment]
I'm with you that line was terrible, I did slightly modify to start once and sit in a while(true) loop.

```
import uk.co.caprica.vlcj.factory.MediaPlayerFactory;
import uk.co.caprica.vlcj.player.base.MediaPlayer;

public class RTSPServer {
    static Boolean streaming = false;
    MediaPlayerFactory mFactory;
    MediaPlayer mPlayer;
	public void startStream() {
        mFactory = new MediaPlayerFactory("-vvv");
   	 	mPlayer = mFactory.mediaPlayers().newMediaPlayer();
   	 
   	    String sourceMRL = "rtsp://<my ip>/axis-media/media.amp?videocodec=h264";

   	    String[] vlcOptions = {
   	    		":sout=#rtp{sdp=rtsp://127.0.0.1:8554/stream}",
   	    		":sout-keep",
   	    		":no-sout-all"
   	    };
   	    mPlayer.media().start(sourceMRL, vlcOptions);
   	   // mPlayer.media().play(sourceMRL, vlcOptions);//(sourceMRL, vlcOptions);
		
	}
	
	
	public static void main(String[] args) {   
		Boolean check = false;
		RTSPServer server = new RTSPServer();
		while(true) {
			if(check == false) {
				server.startStream();  
				check = true;
			}
		}
	} 
	
} 
```

I can see in the -vvv debug output that connection to the MRL for the camera is functional and it is reading data. 

[0000019a18ffdc30] live555 demux debug: setup start: 0.000000 stop:0.000000
Sending request: PLAY rtsp://MY IP/axis-media/media.amp?videocodec=h264 RTSP/1.0

CSeq: 6

Authorization: Digest username="User", realm="AXIS_ACCC8EBF7FA1", nonce="00766f9dY017366e3672d6ea492fcf41642f3091b0d7f54", uri="rtsp://166.149.153.174:554/axis-media/media.amp/", response="a736cda7abd5ea0189d0464160ad28ed"

User-Agent: LibVLC/3.0.4 (LIVE555 Streaming Media v2016.11.28)

Session: VZIncQ4QQKclFUpL

Range: npt=0.000-




Received 266 new bytes of response data.
Received a complete PLAY response:
RTSP/1.0 200 OK

CSeq: 6

RTP-Info: url=rtsp://IP:554/axis-media/media.amp/stream=0?videocodec=h264;seq=27001;rtptime=61089518

Range: npt=now-

Server: GStreamer RTSP server

Session: VZIncQ4QQKclFUpL;timeout=60

Date: Wed, 29 Apr 2020 17:21:13 GMT




[0000019a18ffdc30] live555 demux debug: We have a timeout of 60 seconds
[0000019a18ffdc30] live555 demux debug: play start: 0.000000 stop:0.000000
[0000019a18ffdc30] main demux debug: using access_demux module "live555"
[0000019a19042110] main decoder debug: looking for packetizer module matching "any": 48 candidates
[0000019a19042110] h264 decoder debug: found NAL_SPS (sps_id=0)
[0000019a19042110] h264 decoder debug: found NAL_PPS (pps_id=0 sps_id=0)
[0000019a19042110] main decoder debug: using packetizer module "h264"
[0000019a18f90e70] main input debug: starting in async mode
[0000019a18f754f0] main demux meta debug: looking for meta reader module matching "any": 4 candidates
[0000019a18f754f0] lua demux meta debug: Trying Lua scripts in C:\Users\Mac\AppData\Roaming\vlc\lua\meta\reader
[0000019a18f754f0] lua demux meta debug: Trying Lua scripts in C:\Program Files\VideoLAN\VLC\lua\meta\reader
[0000019a18f754f0] lua demux meta debug: Trying Lua playlist script C:\Program Files\VideoLAN\VLC\lua\meta\reader\filename.luac
[0000019a18f754f0] lua demux meta debug: Trying Lua scripts in C:\Users\Mac\AppData\Roaming\vlc\lua\meta\reader
[0000019a18f754f0] lua demux meta debug: Trying Lua scripts in C:\Program Files\VideoLAN\VLC\lua\meta\reader
[0000019a18f754f0] lua demux meta debug: Trying Lua playlist script C:\Program Files\VideoLAN\VLC\lua\meta\reader\filename.luac
[0000019a18f754f0] main demux meta debug: no meta reader modules matched
[0000019a18f90e70] main input debug: `rtsp://IP/axis-media/media.amp?videocodec=h264' successfully opened
[0000019a18f90e70] main input debug: switching to sync mode

**Comment by caprica** [comment]
Instead of your busy loop, just do Thread.currentThread().join();

**Comment by mmeyers-solartech** [comment]
```
import uk.co.caprica.vlcj.factory.MediaPlayerFactory;
import uk.co.caprica.vlcj.player.base.MediaPlayer;

public class RTSPServer {
    static Boolean streaming = false;
    MediaPlayerFactory mFactory;
    MediaPlayer mPlayer;
	public void startStream() {
        mFactory = new MediaPlayerFactory("-vvv");
   	 	mPlayer = mFactory.mediaPlayers().newMediaPlayer();
   	 
   	    String sourceMRL = "rtsp://<my ip>/axis-media/media.amp?videocodec=h264";

   	    String[] vlcOptions = {
   	    		":sout=#rtp{sdp=rtsp://127.0.0.1:8554/stream}",
   	    		":sout-keep",
   	    		":no-sout-all"
   	    };
   	    mPlayer.media().start(sourceMRL, vlcOptions);
   	   // mPlayer.media().play(sourceMRL, vlcOptions);//(sourceMRL, vlcOptions);
		
	}
	
	
	public static void main(String[] args) {   
		Boolean check = false;
		RTSPServer server = new RTSPServer();
		server.startStream();
		try {
			Thread.currentThread().join();
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	} 
	
}
```

**Comment by caprica** [comment]
Here's a fragment of my log when streaming RTSP, it picks up at the same line where your log ends:
```
[00007f9dc079ad80] main input debug: switching to sync mode
[00007f9cb400c010] main stream output debug: adding a new sout input for `h264` (sout_input: 0x7f9cbc001e80)
[00007f9cb400dce0] stream_out_rtp stream out debug: maximum RTP packet size: 1400 bytes
[00007f9cb400dce0] stream_out_rtp stream out debug: we found a startcode for NAL with TYPE:7
[00007f9cb400dce0] stream_out_rtp stream out debug: we found a startcode for NAL with TYPE:8
[00007f9cb400dce0] stream_out_rtp stream out debug: RTSP: adding /demo/trackID=0
[00007f9cb400dce0] stream_out_rtp stream out debug: sdp=
v=0
o=- 16308721021881132452 16308721021881132452 IN IP4 Pris
s=Unnamed
c=IN IP4 0.0.0.0
t=0 0
a=tool:vlc 4.0.0-dev
a=recvonly
a=type:broadcast
a=charset:UTF-8
m=video 0 RTP/AVP 96
b=RR:0
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1;profile-level-id=4d4029;sprop-parameter-sets=Z01AKZNAPAET8uAtQEBAUAAA+kAAOpgImh4+oA==,aO44gA==;

[00007f9cb400c010] main stream output debug: adding a new sout input for `mp4a` (sout_input: 0x7f9cb8000ba0)
[00007f9cb400dce0] stream_out_rtp stream out debug: maximum RTP packet size: 1400 bytes
[00007f9cb400dce0] stream_out_rtp stream out debug: RTSP: adding /demo/trackID=1
[00007f9cb400dce0] stream_out_rtp stream out debug: sdp=
v=0
o=- 16308721021881744708 16308721021881744708 IN IP4 Pris
s=Unnamed
c=IN IP4 0.0.0.0
t=0 0
a=tool:vlc 4.0.0-dev
a=recvonly
a=type:broadcast
a=charset:UTF-8
m=video 0 RTP/AVP 96
b=RR:0
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1;profile-level-id=4d4029;sprop-parameter-sets=Z01AKZNAPAET8uAtQEBAUAAA+kAAOpgImh4+oA==,aO44gA==;
m=audio 0 RTP/AVP 96
b=RR:0
a=rtpmap:96 mpeg4-generic/48000/2
a=fmtp:96 streamtype=5; profile-level-id=15; mode=AAC-hbr; config=1190; SizeLength=13; IndexLength=3; IndexDeltaLength=3; Profile=1;

[00007f9dc079ad80] main input debug: Buffering 25%
[00007f9dc079ad80] main input debug: Buffering 50%
[00007f9dc079ad80] main input debug: Buffering 75%
[00007f9dc079ad80] main input debug: Buffering 100%
[00007f9dc079ad80] main input debug: Stream buffering done (1250 ms in 13 ms)
[00007f9dc079ad80] main input debug: Decoder wait done in 0 ms
```
There's nothing like that in your log?

I can only suggest having a look at the vlcj StreamRtsp class in the vlcj test sources to see exactly what the sout strings look like.

Is there a firewall on your network somewhere? Using the --rtsp-http option might help.

I do use vlc 4.0.0 (master) which is likely different to you. I also use Linux, I know RTSP has had problems on Windows historically.

**Comment by mmeyers-solartech** [comment]
Our logs end similarly:

[000002ad57269660] stream_out_rtp stream out debug: we found a startcode for NAL with TYPE:8
[000002ad57269660] stream_out_rtp stream out debug: RTSP: adding /stream/trackID=0
[000002ad57269660] stream_out_rtp stream out debug: sdp=
v=0

o=- 16308722545913342862 16308722545913342862 IN IP4 DESKTOP-T9KQ3KA

s=Unnamed

i=N/A

c=IN IP4 0.0.0.0

t=0 0

a=tool:vlc 3.0.4

a=recvonly

a=type:broadcast

a=charset:UTF-8

m=video 0 RTP/AVP 96

b=RR:0

a=rtpmap:96 H264/90000

a=fmtp:96 packetization-mode=1;profile-level-id=640029;sprop-parameter-sets=Z2QAKazFIBQBbsBbgICA0g8SIqA=,aO48sA==;


[000002ad57206e10] main input 


Mine obviously misses the buffering piece but it's a live restream so it shouldn't ever be 'completing' so to speak. 

I'm using vlcj-4.5.1.1.jar

**Comment by caprica** [comment]
I would still like to know what happens if you replace your camera MRL with a local file.

**Comment by caprica** [comment]
There's nothing like this in your log?
```
[00007f9cb400c010] main stream output debug: adding a new sout input for `mp4a` (sout_input: 0x7f9cb8000ba0)
```

**Comment by mmeyers-solartech** [comment]
Although when I run the restream from the UI and catch the SDP read when I view it from the client I see things like this: 

CSeq: 7
User-Agent: LibVLC/3.0.4 (LIVE555 Streaming Media v2016.11.28)
Session: c54cc47674aeb767

962
Range: npt=13.033871-
Session: c54cc47674aeb767;timeout=60
Content-Length: 0
Cache-Control: no-cache
Cseq: 6

T9KQ3KA
s=Unnamed
i=N/A
c=IN IP4 0.0.0.0
t=0 0
a=tool:vlc 3.0.4
a=recvonly
a=type:broadcast
a=charset:UTF-8
a=control:rtsp://127.0.0.1:8554/stream
m=video 0 RTP/AVP 96
b=RR:0
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1;profile-level-id=640029;sprop-parameter-sets=Z2QAKazFIBQBbsBbgICA0g8SIqA=,aO48sA==;
a=control:rtsp://127.0.0.1:8554/stream/trackID=0



Whereas both of our printed SDP's don't appear to ever announce that the stream exists at 127.0.0.1

I will try to get my hands on a video file long enough I can restream and view in a client window.

**Comment by mmeyers-solartech** [comment]
This command was necessary, I can now view my stream in a client window
":ttl=1"

```
import uk.co.caprica.vlcj.factory.MediaPlayerFactory;
import uk.co.caprica.vlcj.player.base.MediaPlayer;

public class RTSPServer {
    static Boolean streaming = false;
    MediaPlayerFactory mFactory;
    MediaPlayer mPlayer;
	public void startStream() {
        mFactory = new MediaPlayerFactory("-vvv");
   	 	mPlayer = mFactory.mediaPlayers().newMediaPlayer();
   	 
   	    String sourceMRL = "rtsp://[MY IP]/axis-media/media.amp?videocodec=h264";

   	    String[] vlcOptions = {
   	    		":sout=#rtp{sdp=rtsp://127.0.0.1:8554/stream}",
   	    		":sout-keep",
   	    		":no-sout-all",
   	    		":ttl=1"
   	    };
   	    mPlayer.media().start(sourceMRL, vlcOptions);
   	   // mPlayer.media().play(sourceMRL, vlcOptions);//(sourceMRL, vlcOptions);
		
	}
	
	
	public static void main(String[] args) {   
		RTSPServer server = new RTSPServer();
		server.startStream();
		try {
			Thread.currentThread().join();
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	} 
	
}
```

**Comment by mmeyers-solartech** [comment]
Although when I connect the client window to watch the stream, I don't see anything in the console output. I know "-vvv" is verbose, but is VLC not monitoring for clients or anything?

**Comment by caprica** [comment]
Interesting about the ttl option, I need to make a mental note of that.

Anyway, this is resolved now?

**Comment by mmeyers-solartech** [comment]
Yes, although knowing when a client connects will be important. Separate issue but if you have a pointer for that let me know. This is closed and as always I appreciate the support, not a lot of projects with responsiveness like this

**Comment by caprica** [comment]
On your last comment, why would VLC care about clients? Isn't RTSP basically broadcasting the stream to the network, it's playing all the time regardless of any clients. It's not like client is connecting to the VLC server is it?

This is beyond my area of expertise, but that's my understanding.

**Comment by caprica** [comment]
I am especially responsive right now because I am very bored due to the current pandemic, I have a lot of time on my hands :-)

**Comment by mmeyers-solartech** [comment]
Yeah you're totally right in the sense that VLC has no obligations to a client on a stream, it's just broadcast and VLC wouldn't care what picks it up. That's a valid answer, thanks.
