### ISSUE TITLE
VLCJ + lwjgl

### ISSUE THREAD

**Issue by anonnyj** [caprica/vlcj#957]
Sorry I know this is probably the wrong place for this / I don't understand stuff nearly well enough.

I saw a demo for using VLCJ with lwjgl ( https://github.com/caprica/vlcj-lwjgl-demo ) but it seems to need the developmental build 5.0.0+ ... which I can't find anywhere.

Or is the problem that I just need to be patient and wait for the release?

**Comment by caprica** [comment]
This project's current master branch is vlcj-5.0.0-SNAPSHOT. You should checkout the code yourself into your own IDE and build it yourself (or e.g. use Maven to get a snapshot jar).

The vlcj-5.0.0-SNAPSHOT is stable and you should be absolutely fine using it for most things.

The tricky part is that you also need VLC/LibVLC 4.0.0 - this is still in development by the VideoLAN developers and it may be a long time before that version is released. This is the version that has the OpenGL callbacks that you need.

To get LibVLC 4.0.0, you can either checkout the code from the VideoLAN git repository and build it yourself - not so bad doing this on Linux, I have no experience doing a Windows build of this but I expect it will be very difficult.

Or you could try finding VLC nightly builds for 4.0.0 from the VideoLAN web-site. These do exist, use a Google search to find them.

These builds are bleeding edge development builds and you may have no, some, or many problems using it.

The current VLC 4.0.0 git master is pretty stable for me on Linux, but there are some broken LibVLC features (e.g. audio callbacks do not work currently, but this is unlikely to affect you). Nevertheless, the OpenGL callbacks do work as evidenced by the vlcj project you've already found.
