### ISSUE TITLE
Github JavaDoc not working

### ISSUE THREAD

**Issue by xpsKING** [caprica/vlcj#962]
http://caprica.github.io/vlcj/javadoc/5.0.0/index.html results in a 404 error

**Comment by caprica** [comment]
Since vlcj 5.0.0 status is pre-release and is still in development, that link is not ready yet and is just a placeholder.

I don't have a particular date planned for when the Javadoc will be published.

**Comment by caprica** [comment]
I just now published a 5.0.0-SNAPSHOT Javadoc, that should be good enough for now.
