### ISSUE TITLE
Suggestion: Include native binaries in vlcj as an option for Windows/MacOS

### ISSUE THREAD

**Issue by Abu-Abdullah** [caprica/vlcj#964]
Hi,

this is just a suggestion, it might be worth including native binaries for vlc for Windows/MacOS as jar dependencies besides the main vlcj in the same style javafx is doing i.e. javafx-base-14.jar/javafx-base-14-win.jar/javafx-base-14-mac.jar ...

this will make it really easy for building multi-platform binaries in Windows. in addition, im facing every time an issue with linking the native binaries with the library vlcj.jar

of course it is the best if we can do this for linux but i think having static vlc for all linux flavors might be a bit headache (I do not know how javafx is doing it with gstreamer)

**Comment by caprica** [comment]
This is not in scope of this project.

Nothing prevents you from doing that in your own projects though.

Like I said in a different issue, if you use vlcj as intended the native discovery should be transparent to you and the last time I tested it it worked just fine on all three major platforms without doing anything other than creating a MediaPlayerFactory or one of the media player component classes.
