### ISSUE TITLE
Video recording produces stuttering videos.

### ISSUE THREAD

**Issue by sblantipodi** [caprica/vlcj#970]
Hi,
thanks for the great project, love VLC and VLCJ even more.

I am trying to record my screen using this example:

https://github.com/caprica/vlcj-examples/blob/master/src/main/java/uk/co/caprica/vlcj/test/screen/ScreenRecorder.java

Video is correctly recorded but the output is a stuttering video.

Is this an issue of VLCJ or simply my fault? Thanks.
If this is not the right place for questions please let me know if you have a place for "users questions".

Thanks
Davide

**Comment by caprica** [comment]
I wouldn't say it was your fault, but it's not vlcj's fault either :-)

Probably you need to tweak the transcoding options to work better on your system. Transcoding can require a lot of CPU and when recording your desktop it's transcoded and written to disk in real time, so it's possible your system simply isn't fast enough.

Just now I re-tested that ScreenRecorder example you referred to and it records perfectly smooth video for me.

You can try passing "-vvv" when you create the media player factory and see if you get spammed with log/error/warning messages which might help you troubleshoot this.

On Linux I sometimes see the desktop background flickering in the recorded video, this is fixed simply by disabling page flipping in the GPU settings, but I suppose this is not what you're asking about here.

**Comment by sblantipodi** [comment]
I'm recording in 4K but using a very low bitrate (4096), 
I have a six cores HEDT i7 5930K with DDR4 and an RTX2080Ti.
Video is written on a NVME SSD using Windows 10.

This system is not the best in the market but I would not say isn't able to handle a screen recording.

Have you tried that example in Windows 10?

**Comment by caprica** [comment]
I don't use Windows at all, sorry.

But yeah, it seems like your system should be plenty good enough.

There's really nothing that can be "fixed" in vlcj to help you here. Remember that vlcj does not record your desktop, it's VLC itself that's recording your desktop - vlcj just makes it happen.

**Comment by sblantipodi** [comment]
last question if I can, please...
do you know if there is some APIs to record the video and process it frame by frame in "real time"?

I need to capture a 30FPS video and get the color of some pixels in X,Y position, this is easy with a BufferedImage for example.
Is there something like this in VLC/VLCJ?

Thanks.

**Comment by caprica** [comment]
That would have been better posted as a separate issue :-)

Look in the vlcj test sources, or the vlcj-examples project, for DirectTestPlayer - it processes video frames in real time to apply a pseudo grey-scale effect. In principle it could play "screen://" rather than a file.

I don't know how feasible that is to write to disk in real-time, but it's your only option if you want to process the framebuffer.
