### ISSUE TITLE
Looking for SWT example. Look like no more SWT for VLCJ v4

### ISSUE THREAD

**Issue by ivanooi** [caprica/vlcj#972]
Hi,

   Do you have any example for Java SWT? Look like the SWT not in the support list anymore?

Thanks

**Comment by caprica** [comment]
The principle hasn't changed from vlcj-3 to vlcj-4 with regards to SWT though, what is it specifically that you think is missing or different?

See https://github.com/caprica/vlcj-swt

**Comment by ivanooi** [comment]
Hi,

Thanks for pointing out the site. 
I got another problem.... 
I'm not able to load the VLC lib using this : 

        System.setProperty("jna.library.path", "/Volumes/VLC-3.0.10/lib" );
        NativeLibrary.addSearchPath("vlc", "/Volumes/VLC-3.0.10/lib");

THis was work quite well with vlcj 3.x 

Thanks

**Comment by caprica** [comment]
That is a common, unrelated issue. Please search the existing issues, there is lots of information about that problem.

**Comment by ivanooi** [comment]
Hi, 

I would like to submit a patch for CompositeVideoSurface.java as well 

 Thanks for pointing the issues. 
Ya, found the solution https://github.com/caprica/vlcj/issues/602

Thanks again

[CompositeVideoSurface.java.zip](https://github.com/caprica/vlcj/files/4775246/CompositeVideoSurface.java.zip)

**Comment by caprica** [comment]
I appreciate you taking the time to make a patch, but if you want me to take a look at it please submit it as a pull request rather than asking me to download, unzip, copy to the project and so on...
