### ISSUE TITLE
live streaming in low bitrate network

### ISSUE THREAD

**Issue by lejahmal** [caprica/vlcj#983]
hi dev 
i found your library looking ``` http://capricasoftware.co.uk/projects/vlcj ``` and i'm interresting about to use it to playback audio live streaming in very extremly poor bitrate network environnement . because rtmp maintain persistant TCP connection between server and client . so my logic is to segmented an encoded 64k RTMP stream as multiples chuncks of egal size (.ts or .mp4)  let's say for example 2 secondes and then read as a dynamically playlist (.xspf or xml) so it will look like multiples VOD files but playback as live streaming. 

my question is that what is the appropriate vlcj-examples corresponding to this shema between thoses differents samples

- https://github.com/caprica/vlcj-examples/tree/master/src/main/java/uk/co/caprica/vlcj/test/directaudio
- https://github.com/caprica/vlcj-examples/blob/master/src/main/java/uk/co/caprica/vlcj/test/streaming/
- https://github.com/caprica/vlcj-radio-demo/tree/master/src/main/java/uk/co/caprica/vlcj/radio/service/listenlive

**Comment by caprica** [comment]
I'm not sure I fully understand your question.

Things I can suggest that *might* be relevant:

1. for playlists (is this what your xspf file is?), look into the MediaListPlayer and related classes
2. potentially look into "sub items" on a normal MediaPlayer when you play your playlist/stream URL - you "play" the stream URL but it doesn't play anything, it parses the result into sub items which would be for each of your chunks (maybe), and then you can iterate and play those chunks

**Comment by lejahmal** [comment]
thanks for your prompt reply dev . a millions times thanks for your support.

this is the logics
1st step - a client broadcast an rtmp stream from device to server

2nd step - the server (nginx-rtmp-module) recieved stream and transcode it to 64kbs using (ffmpeg)  and split the stream gradually to a multiples chunks (.ts) of 2 secondes  

``` -rw-r--r-- 1 www-data www-data 18988 Jul 26 09:04 0.ts
-rw-r--r-- 1 www-data www-data 19176 Jul 26 09:04 1.ts
-rw-r--r-- 1 www-data www-data 18424 Jul 26 09:04 2.ts
-rw-r--r-- 1 www-data www-data 18800 Jul 26 09:04 3.ts
-rw-r--r-- 1 www-data www-data 18800 Jul 26 09:04 4.ts
-rw-r--r-- 1 www-data www-data 18424 Jul 26 09:04 ... (more)
```
3rd - step a receiver (another client) playback the stream on device

THE ISSUE : normaly is very simple to playback the stream by reading .m3u8 file . but in extremly poor network environement , the playback will buffering all time. using differents solution event multibitrate stream or caching before loading will not work because network is very very low (between 2kbs and 25 kbs )

the only solution to have a continu stream withouth buffering by client receiver is to play radomly and dynamically all the (.ts) file as a playlist (.xspf) stored server side .  MY QUESTION i'm looking for a player able to do it. i try ConcatenedSource of EXOPLAYER is able to do the job but cannot load more than 15 files and it is very instable . i try LibVlc 3.1.12 but i have a difficultu to achiedved it by assembling correctly player option . 

So as a found your library and i take a look into i thinks it is possible to do it with VLCj . is it possimle to have a sample code to play playlist using vlcj or how can;t you think that it will possible for me to resolve my issue using vlcj 

i hope that you will understand now as i explained with more details

**Comment by caprica** [comment]
All of the samples are already in the vlcj github repository for vlcj 4.x (in the test directory), or the vlcj-examples repository for vlcj 5.x. 

There are examples showing how to play a playlist, e.g. the YouTube player, or any of the samples with "list" in their name.

There is nothing else available that is not there already.

In fact, that old vlcj-radio sample that you found shows you how to do it, but for an older version of vlcj.

**Comment by caprica** [comment]
And to be clear, the concept is when you play the playlist nothing actually plays. You will get a "finished" event, and then you can iterate the sub-items and choose which one to play.

I don't know if that is good for your use-case or not.

**Comment by lejahmal** [comment]
thanks for pointing me on the right way .when finish handle it i will come back for the solution 
A millions times thanks dev
