### ISSUE TITLE
setVolume affect other player volume

### ISSUE THREAD

**Issue by XDIYIBEIZI-XH** [caprica/vlcj#985]
I'm using multiple media players simultaneously.

But when you set the volume, all players change the volume, not the other way around.

**Comment by caprica** [comment]
Yes, that is unfortunately how LibVLC works with multiple "in-process" media players.

This is one reason why vlcj-pro exists, vlcj-pro runs each media player in its own separate JVM and the volume can be set independently.

This limitation may be removed in LibVLC 4, but that is still in development.

**Comment by zhanghai** [comment]
Is this still the case in 2022? I saw some people complaining about this in older threads, but some other people saying that it just works.

**Comment by caprica** [comment]
It depends on two things:
- the audio output plugin in use, some plugins it works, some it doesn't
- it seems to be generally better in VLC 4.x (still in pre-release)
