### ISSUE TITLE
youtube link: player in vlcj cannot play an youtube video, while vlc can play it without problem.

### ISSUE THREAD

**Issue by mikej1688** [caprica/vlcj#989]
I used vlcj 3.10.1 to play the media files for a couple years, and it worked well when playing most youtube video clips.
As you might know, Youtube kept changing the format of videos' urls, which forced people to update the lua script, youtube.luc,  once a failure occurred.
In recent weeks, it was found that a large number of Youtube video clips were not played. Thus I went find the latest youtube.lua and use it.
However, the issue remained and it seemed irrelevant of updating lua script. 
For example, an original url is, https://www.youtube.com/watch?v=S2LKywR47xk
It can be played by using VLC (version: 3.0.11Vetinari), but was not working by using vlcj 3.10.1.
In a vlcj's test class, YouTubePlayer.java, it says that the following setting is very important,
        mediaPlayer.setPlaySubItems(true);
I am not sure if the setting is responsible for finding an indirect url which eventually points to the true location where the video resides?
What does it mean? It implies that the original url is not pointing to the real location of the video. Instead it refers to a config file with the detail video info.
By reading the video config info into the lua script's function parse() again, a new url (indirect url) is constructed, and it's like,
https://r1---sn-5uaeznde.googlevideo.com/videoplayback?expire=1598146511&ei=bnNBX-CWPIu2kAPV-aaYDQ&ip=24.30.73.71&id=o-ANyUm8GG08s-w6-LM8UUcqRR73Zicek0HPc_YllX0ldR&itag=22&source=youtube&requiressl=yes&mh=zX&mm=31%2C29&mn=sn-5uaeznde%2Csn-5ualdn7z&ms=au%2Crdu&mv=m&mvi=1&pl=19&gcr=us&initcwndbps=2528750&vprv=1&mime=video%2Fmp4&ratebypass=yes&dur=399.499&lmt=1598101794233464&mt=1598124756&fvip=1&c=WEB&txp=5535432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRAIgMsJncmekCJyqhmMfhaq431yYHK14PaYsBHdyUkxlHA4CIFFypDxMG43ioAUF6h4Q2RXkZwn_KLMBmCuMbnlFpsZ4&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgVOTxWnvTP2tAT-MJszYHJrZwI2cUs1euORV6_lwX108CIQDjej1HXUo0gsTPfpFjctpkZsD4AOxOeZOdE2tuIeWRNw%3D%3D 

This is just the real url of the video! I manually used the url with YoutubePlayer.java, and it worked fine. But YoutubePlayer.java has no way to figure it out and doesn't know how to get the indirect url and play with it.
On the other hand, the VLC knows how to obtain the indirect url pointing to the right location of the video and plays it.
Is there any way in vlcj's MediaPlayer's setting to load the indirect url and play it?

**Comment by mikej1688** [comment]
Here is my note: what I used and talked about is vlcj3.10.1, not vlc3.10.1. 
I tried to set maven dependency of vlcj5.0.0 in my project, but it was not in Maven Central. If you knew where I can have it, please let me know.
Without the direct dependency of vlcj-5.0.0 available, I cloned three projects out off the github site. They are:
vlcj-natives
vlcj-5.0.0 (use vlcj-natives, since no maven dependency of vlcj-natives-5.0.0 available)
vlcj-examples (YoutubePlayer.java)

Built all of them and then tested YoutubePlayer.java (in vlcj-examples) with the youtube.lua script, it worked as you said. Thanks.
However, like what I said, the YoutubePlayer.java in the old vlcj3.10.1 still didn't work by using the same youtube.lua. You can test it if you like.

Compared two versions of YoutubePlayer.java, and found they were not same. I think the difference of the code makes the difference of the results.

Thanks a lot for the explanations.

**Comment by caprica** [comment]
vlcj-5 will not be released until VLC 4.0 is released, so it won't be in any Maven repo until then.

So anyway you're using vlcj-3.10.1, which is almost 5 years old - this is why I suppose it didn't register that you were talking about vlcj and not VLC. That version of vlcj requires VLC 2.x, not 3.x.

I'm afraid there is no chance of me doing any maintenance on vlcj-3.x.

Why not use vlcj-4..x and VLC 3.x?

**Comment by mikej1688** [comment]
That's good, understood it now. 
Thanks.
