### ISSUE TITLE
vlcj-5.0.0: DVD play is blurry

### ISSUE THREAD

**Issue by mikej1688** [caprica/vlcj#992]
When I switched to use vlcj-5.0.0, as a simple test, I ran a test class, MediaInfoTest, with an argument,
dvd:///d:#1
or 
dvdsimple:///d:#1

to play a dvd in drive d:
It was loaded and played, but the quality was too blurry to be watched.
Using the old version vlcj3.10.1 had no the similar issue.
Not sure if it's the same issue talked about in README file:
"CallbackMediaPlayerComponent does not properly render media that does not have a sample-aspect-ratio (SAR) 1:1, this mostly affects DVD ISO, you can still provide your own implementation that handles other SAR's if you need to. "

**Comment by caprica** [comment]
What happens if you use VLC 4.x to play the DVD?

The problem with SAR for DVD is usually that the DVD appears too narrow (since with DVD the pixels usually need to be rendered wider than they are tall), it would not affect the "blurriness".

The SAR issue is also only relevant for the callback player, not the "normal" embedded media player.

**Comment by mikej1688** [comment]
I tried vlc-4.0.0 player with the same DVD disc. It worked fine.
went back to the MediaInfoTest, changed the code to use embedded media player, like
        final EmbeddedMediaPlayer mediaPlayer = factory.mediaPlayers().newEmbeddedMediaPlayer();

The issue remained. 
Like what said, the SAR is not 1:1, instease they are like, sampleAspectRatio=8,sampleAspectRatioBase=9
Here is the Track Information: [VideoTrackInfo[codec=0x7667706d,codecName=mpgv,originalCodec=0x7667706d,originalCodecName=mpgv,id=224,profile=-1,level=-1,bitRate=0,language=null,description=null,trackId=null,stable=false,name=null,selected=false,codecDescription=MPEG-1/2 Video][width=720,height=480,sampleAspectRatio=8,sampleAspectRatioBase=9,frameRate=30000,frameRateBase=1001,orientation=TOP_LEFT,projection=RECTANGULAR,yaw=0.0,pitch=0.0,roll=0.0,fov=80.0,multiview=TWO_D], AudioTrackInfo[codec=0x20323561,codecName=a52,originalCodec=0x20323561,originalCodecName=a52,id=48512,profile=-1,level=-1,bitRate=0,language=en,description=null,trackId=null,stable=false,name=null,selected=false,codecDescription=A52 Audio (aka AC3)][channels=2,rate=48000]]

**Comment by caprica** [comment]
If you are using the MediaInfo test class from vlcj-examples, then by default VLC is playing your video in a window that VLC opened.

I just tested this and the DVD played looks fine to me. I don't see any blurring. I mean, DVD is only 720x480 or 720x576 which isn't all that pretty on a nice 4k monitor, but it looks "normal" to me.

![image](https://user-images.githubusercontent.com/1385879/91463277-1e9a2600-e883-11ea-8c0a-eb052e61300e.png)

The SAR issue has nothing to do with this. The SAR is only relevant when using the "callback" media players.

**Comment by mikej1688** [comment]
I am very sorry, what I said was not correct. The version of vlc I used for testing was 3.0.11. I installed this version of 3.0.11 vlc on another box, and accidentally used it for testing. 
The test result on a vlc 4.0.0 player has the same issue as played by vlcj-5.0.0.
Probably the dvd is too old? It was not an issue when playing it using vlcj3.10.1.

**Comment by caprica** [comment]
It is probably just a temporary issue with the VLC build you have, presumably it's a nightly build for Windows.

My VLC 4.0.0 build from the latest in the git repository plays DVD's fine, although at the moment chapter selection seems not to work properly, but playback is fine.

btw. the DVD I tested is nearly 20 years old, so I doubt age is an issue.

**Comment by mikej1688** [comment]
I downloaded the latest vlc4.0.0 version from this night build url,
https://artifacts.videolan.org/vlc/nightly-win32/
and clicked the chapter #1, the video was blurring.  Maybe it's the selection issue like you said? But without selecting a chapter to play, how can I play back the dvd(same question for programmatically playing back in vlcj)?
![image](https://user-images.githubusercontent.com/7915805/91469311-395ba300-e861-11ea-9d0d-4e2f45fe9096.png)

**Comment by caprica** [comment]
I just think there may be some bug in VLC preventing chapter selection from working properly at the moment. VLC 4.x is still deep in development so it's not totally unexpected for there to be bugs like this. They won't support you with nightly builds, they're very much use at your own risk. Either you have to debug it and fix it yourself, or trust the the VLC developers will sort it all out before their final release.

To be sure we're talking about the same thing, what precisely do you mean by blurring? From your screenshot I don't see anything wrong.

**Comment by mikej1688** [comment]
You are right about the night build.
What I did was: selected the chapter 1, then the player started playing. The whole screen was like this,

![image](https://user-images.githubusercontent.com/7915805/91488439-4e462f80-e87d-11ea-8749-998ccd94a257.png)

**Comment by caprica** [comment]
Ah, OK. That sort of problem is definitely down to VLC rather than vlcj. All you can do is wait and hope the VLC developers sort it out by the time VLC 4.0.0 is finally released.

**Comment by mikej1688** [comment]
I totally agree. Thanks.
